### ISSUE TITLE
Minor UI bugs

### ISSUE THREAD

**Issue by tuxology** [unstructuredstudio/zubhub#12]
- [x] When creating account on mobile phone, date of birth on android phones open calendar widget with today's date. Its a bit loooong and complex to navigate to your birth year. What can we do about it? Would this be an issue?

- [x] "Video link is optional"
![image](https://user-images.githubusercontent.com/3373857/102719155-39b0fb80-42a1-11eb-9baa-b42261955c2a.png)

- [x] When you select one image, there is no feedback as to what happened? Can we do it like materials where image upload happens on individual images? Users would generally upload images one by one and then would want to see a feedback that it has been uploaded and "how it looks". Then they may delete the ones they don't like. Is it too late to implement that? If its too late, its fine, we can do it in next round
- [x] Confirmation email seems to be coming from admin@zubhub.com. Replace it with `hello@unstructured.studio`
- [x] When a youtu.be shortlink is shared, follow redirect and get the correct link? Currently we get a firefox/chrome security issue rendered in iframe
- [x] Can we add a "Create Project" Button here whenever you are logged in?  
![image](https://user-images.githubusercontent.com/3373857/102794964-f4540300-4360-11eb-9afd-c2a419528e53.png)

**Comment by NdibeRaymond** [comment]
> * When creating account on mobile phone, date of birth on android phones open calendar widget with today's date. Its a bit loooong and complex to navigate to your birth year. What can we do about it? Would this be an issue?

I think this is the general accepted approach to this. The only date everyone can agree is is today. It won't make sense to choose an arbitrary date in the past. There is also the option of inputting the date manually. And I don't believe this is an issue since this is what users have come to expect when it comes to date input

**Comment by NdibeRaymond** [comment]
> * When you select one image, there is no feedback as to what happened? Can we do it like materials where image upload happens on individual images? Users would generally upload images one by one and then would want to see a feedback that it has been uploaded and "how it looks". Then they may delete the ones they don't like. Is it too late to implement that? If its too late, its fine, we can do it in next round

One thing we can do here right now is add a count as to how many images the user is uploading. What you are suggesting is better included as part of the project edit feature, and for this phase, users are not supposed to edit projects. Also, given that for this phase users will be mostly supervised and guided, I think this won't cause friction.  The biggest constraint of course is time. Anything can be built with time, but we are on a clock. I think this functionality to edit projects is better suited for stage 2. What do you think ?

**Comment by NdibeRaymond** [comment]
> * Can we add a "Create Project" Button here whenever you are logged in?

yeaaaa, actually scheduled this as something to do before final deployment

**Comment by tuxology** [comment]
> One thing we can do here right now is add a count as to how many images the user is uploading. What you are suggesting is better included as part of the project edit feature, and for this phase, users are not supposed to edit projects.

Ok, lets just add the count - so after the user selects images, it says "5 images selected" etc for now

**Comment by NdibeRaymond** [comment]
> > One thing we can do here right now is add a count as to how many images the user is uploading. What you are suggesting is better included as part of the project edit feature, and for this phase, users are not supposed to edit projects.
> 
> Ok, lets just add the count - so after the user selects images, it says "5 images selected" etc for now

Added this inside the button directly. it looks good that way and still conveys the message

**Comment by tuxology** [comment]
👍🏽 Closing this! 🙏🏽
