### ISSUE TITLE
User card disappears from the followers / following list when clicked

### ISSUE THREAD

**Issue by srish** [unstructuredstudio/zubhub#162]
Steps to reproduce the issue:
* Login to your account
* Visit another user’s following page: https://zubhub.unstructured.studio/creators/Ndibe_Raymond/following 
* Follow/ unfollow another user
* Notice that user card has disappeared from the list
* User card is back again upon refreshing

Ideally, user card should never disappear.

**Comment by NdibeRaymond** [comment]
Ok. This is actually by design. I thought since this page is for creators one is following, once you unfollow a creator they shouldn't be on that page anymore. I'll change this functionality
