### ISSUE TITLE
Images preview not available in the "edit project" form

### ISSUE THREAD

**Issue by srish** [unstructuredstudio/zubhub#164]
For example, in the form below, next to the image field, it says 2 images added but there is no preview of those images available: 
<img width="707" alt="Screen Shot 2021-05-25 at 5 39 17 PM" src="https://user-images.githubusercontent.com/288353/119587605-de20f780-bd83-11eb-839d-ef4d669cc94a.png">

Ideally, there are image previews shown in the edit project form.

**Comment by souad988** [comment]
Hi @srish  i want to work on this issue would you assign it to me please

**Comment by srish** [comment]
Work is ongoing in #482. Interested contributors can help in improving it and submit PRs.

**Comment by ipriyanshi1708** [comment]
Hii @srish, I would love to work on this issue. please assign it to me.

**Comment by Temabo** [comment]
Hi @srish @darechan @tuxology i'm a designer and an outreachy applicant, I'd love to create the UI for this feature. Please assign it to me

**Comment by Mara-mma** [comment]
Hi @srish @tuxology this is my idea for solving the issue, please assign it to me
![kite_unstructuredstudio](https://user-images.githubusercontent.com/105233065/224445939-a826692d-97f3-42a3-8b51-635c1cf88d2c.jpg)
![kite 2_unstructuredstudio](https://user-images.githubusercontent.com/105233065/224446027-f8bd40dc-8c52-4965-ac13-af4be72d51bd.jpg)

**Comment by Burnleydev1** [comment]
Is anyone working on this? I will love to improve it

**Comment by iamhks** [comment]
> Work is ongoing in #482. Interested contributors can help in improving it and submit PRs.

Hi @srish I improved the existing PR and added the aspect ratio for the imagePreviewContainer.
But I noticed some shrikage is still there. Now we have 2 ways to look at it. 
1) Add the images in their respective aspect ratio, the problem would arise when a user upload images with different aspect ratio's and we display the same in preview, our list of image tiles will be inconsistent and won't look aligned/appealing. Some images would be rectangle where others would be square.
2) Add the images in a standard aspect ratio and let there be some shrinkage for some images but maintain the preview of image tiles to be consistent.

Hence, I went with the 2nd approach, considering most widely used aspect ratio is 4:3 or 16:9, not every user will add a landscape photo hence, I chose 4:3. Please review my PR and let me know of any comments.

**Comment by srish** [comment]
Looks like this got fixed! Thanks to @souad988 @iamhks for your contributions!
