### ISSUE TITLE
Unable to save changes to profile

### ISSUE THREAD

**Issue by srish** [unstructuredstudio/zubhub#166]
The following error occurs when trying to save a profile:
```
api.js:30 PUT https://api.zubhub.unstructured.studio/api/creators/edit_creator/ 500
VM231:1 Uncaught (in promise) SyntaxError: Unexpected token U in JSON at position 0
    at JSON.parse (<anonymous>)
    at EditProfile.jsx:93\
```

<img width="500" alt="Screen Shot 2021-05-25 at 7 31 32 PM" src="https://user-images.githubusercontent.com/288353/119593989-d49d8c80-bd8f-11eb-9fc3-18a28a76878e.png">

**Comment by NdibeRaymond** [comment]
Ok this seems to be a problem with group profile. Thanks for flagging this @srish

**Comment by NdibeRaymond** [comment]
> Ok this seems to be a problem with group profile. Thanks for flagging this @srish

On careful error reproduction, I figured out that it happens to profiles of any kind, once the phone number field is empty. Submitting a fix this weekend
