### ISSUE TITLE
"Do not use your real name" tooltip's behavior is odd

### ISSUE THREAD

**Issue by srish** [unstructuredstudio/zubhub#167]
“Do not use your real name” tooltip keeps popping up while editing other fields on this page.

<img width="500" alt="Screen Shot 2021-05-25 at 7 33 41 PM" src="https://user-images.githubusercontent.com/288353/119594396-90f75280-bd90-11eb-87d4-009dcc317cef.png">

**Comment by NdibeRaymond** [comment]
closing this because this issue has been fixed
