### ISSUE TITLE
Nest "my profile", "followers", "following" under "my projects" or remove them completely from the user menu

### ISSUE THREAD

**Issue by srish** [unstructuredstudio/zubhub#168]
Observe how in FB/ Twitter UX, there isn't a repeat of these fields in the user menu. Something for us to revisit later..

<img width="326" alt="Screen Shot 2021-05-25 at 7 40 47 PM" src="https://user-images.githubusercontent.com/288353/119594699-21ce2e00-bd91-11eb-8b0f-f7711982ab02.png">

**Comment by alicendeh** [comment]
Can i work on this please @srish

**Comment by srish** [comment]
I am recalling based on our team discussion that this issue is no more relevant. I am closing it for now.
