### ISSUE TITLE
Delete account option shouldn't pop up easily

### ISSUE THREAD

**Issue by srish** [unstructuredstudio/zubhub#169]
It makes me nervous when the delete account pops up so easily. This option shouldn’t be made available on the profile page, and instead moved under the user menu as “Delete account”.

**Comment by Deepthi562** [comment]
@srish i think we can add a settings option along with the (my profile, followers..) section and here in this  we can add a delete account option along with edit option.

**Comment by Deepthi562** [comment]
@srish i would like to work on this, kindly give me a little insight. Thank you.

**Comment by srish** [comment]
@Deepthi562 I am assigning this task to you. Could you share 1 or 2 more examples of possible scenarios where to place the delete account setting? Try to also look into how other similar platforms are handling the UX around this feature. If possible, share rough sketches first to show what the placement would look like before working on the issue.

**Comment by Deepthi562** [comment]
In the main menu where we are displaying all the project and profile details we can add a settings option and inside that we can include log out, delete account, or any display settings like dark or light theme etc.

I am not a pro in ux , given some time i will definitely come up with the ux part, as of now i figured out where we can make changes in the code.

![pic15](https://user-images.githubusercontent.com/71760959/164625613-c27a6a63-e505-46fe-b44d-bb2129788988.png)

instead of logout option, we can use a settings option as usually logout option shouldn't pop up easily.

**Comment by srish** [comment]
@Deepthi562 If you can come with some design ideas for how the user experience related to account management and deletion might look like before attempting a PR, that will be helpful.

**Comment by ipriyanshi1708** [comment]
Hii @srish We can add settings option and in settings option we can add edit option and logout option and in edit option there can be a dropdown for Edit project, Edit Profile where user can edit his email and mobile number.

**Comment by ipriyanshi1708** [comment]
I would love to work on this issue. Please assign it to me.

**Comment by tuxology** [comment]
@ipriyanshi1708 Please come up with 1-2 possible UX approaches (Figma sketches preferably) so we can discuss/decide and then work on fixing this. I'm assigning this to you for UX work

**Comment by KramStyles** [comment]
@tuxology can I work on the codes when @ipriyanshi1708 is done with the UX?

**Comment by ipriyanshi1708** [comment]
@tuxology I have started working on Figma sketches

**Comment by ipriyanshi1708** [comment]
> @ipriyanshi1708 Please come up with 1-2 possible UX approaches (Figma sketches preferably) so we can discuss/decide and then work on fixing this. I'm assigning this to you for UX work

![image](https://user-images.githubusercontent.com/92941945/224338944-ce9e84ee-0954-443e-b5ec-8b4c74e74f1c.png)

Hi @srish @tuxology, I have created this UI to provide high level idea of what I am talking about as I am not pro in Figma for hiding the Logout under settings section and we can discuss to add more options in the settings section. If this UI works then I can start coding.

Thanks!

**Comment by KramStyles** [comment]
> > @ipriyanshi1708 Please come up with 1-2 possible UX approaches (Figma sketches preferably) so we can discuss/decide and then work on fixing this. I'm assigning this to you for UX work
> 
> ![image](https://user-images.githubusercontent.com/92941945/224338944-ce9e84ee-0954-443e-b5ec-8b4c74e74f1c.png)
> 
> Hi @srish @tuxology, I have created this UI to provide high level idea of what I am talking about as I am not pro in Figma for hiding the Logout under settings section and we can discuss to add more options in the settings section. If this UI works then I can start coding.
> 
> Thanks!

@ipriyanshi1708 can we collaborate together on this if you are given the go ahead?

**Comment by iamhks** [comment]
Hi @srish Are you sure you want to move it as shown in this image:
<img width="1440" alt="Screenshot 2023-03-14 at 13 10 06" src="https://user-images.githubusercontent.com/43777817/224929322-2104470c-17f5-4699-bcbd-ad318da8f82e.png">
My point is, a user reaches the edit profile through the user menu itself, so it becomes even more easily visible which is a contradiction to our issue. Your inputs please.

**Comment by tuxology** [comment]
I agree with @iamhks here @srish I think moving it to main menu will make it even more visible and users can accidentally click this and move to the deletion process. I feel we keep this here itself for now unless someone comes up with a better UX for "account settings" or "account management"

**Comment by srish** [comment]
This is good for now under the edit profile.
