### ISSUE TITLE
Odd space in the top border in the input fields

### ISSUE THREAD

**Issue by srish** [unstructuredstudio/zubhub#170]
Are we using the react native controls and is this their intended behavior? I'm wondering why there is too much space between the label and the input top border on the right. 

<img width="685" alt="Screen Shot 2021-05-25 at 7 47 33 PM" src="https://user-images.githubusercontent.com/288353/119595218-10d1ec80-bd92-11eb-89cd-c0d97cc4956d.png">

**Comment by untari** [comment]
Hi @srish I'm outreachy participant this year, and would like to contribute on this issues. Do I have to wait to be assigned to work in the issues ?

**Comment by Jumeb** [comment]
@tuxology can I have a try at this issue?

**Comment by Jumeb** [comment]
> @tuxology can I have a try at this issue?

Tried working on this issue but I could not replicate the problem @srish can you check again to see if this problem still occurs.

**Comment by srish** [comment]
Yes, I checked this issue no longer exists. I'm closing this one.
