### ISSUE TITLE
Tweak design to differentiate between tags, categories and materials used

### ISSUE THREAD

**Issue by srish** [unstructuredstudio/zubhub#172]
The high-level issue here is that it is hard right now to differentiate between tags, categories and materials used. 

A few other related issues:
* It is not obvious that the tags are tags. How can we make them more prominent / visible? 
* Category does not indicate that it is clickable. Probably underline it, or invert the colors? (gray chip). 

And, then there is an alignment issue:
* Tags, categories and materials are not aligned properly to the comments box and category is not aligned to its own heading. Comments box should be shortened in width.
* There isn’t any left/right padding in the comments box on smaller devices. The padding should be same as for other components on the top of the project page.

<img width="600" alt="Screen Shot 2021-05-25 at 8 22 49 PM" src="https://user-images.githubusercontent.com/288353/119598023-0108d700-bd97-11eb-815c-075d992dddeb.png">

<img width="300" alt="Screen Shot 2021-05-25 at 8 28 52 PM" src="https://user-images.githubusercontent.com/288353/119598467-d9fed500-bd97-11eb-87da-3ce409472f8d.png">

**Comment by auasante** [comment]
I am an Outreachy applicant and I would Like to work on this please.

**Comment by tuxology** [comment]
@auasante This issue is a bit complex and requires a lot of UX rework as discussed in a very similar PR submitted here: https://github.com/unstructuredstudio/zubhub/pull/395#issuecomment-1095163243 If you have suggestions how we can improve Categories and Tags apart from what is discus so far, maybe start a new discussion using Github Discussions first?

**Comment by Temabo** [comment]
Hi @srish @darechan @tuxology i'm a designer and an outreachy applicant, I'd love to create the UI for this feature. Please assign it to me

**Comment by Burnleydev1** [comment]
Hello @srish Can I work on this issue?

**Comment by darechan** [comment]
@Temabo @Burnleydev1 If you present a UI mockup for same, it would be easy for the mentors to select the person for assignment

**Comment by Burnleydev1** [comment]
@darechan @srish @tuxology 
Here is a draft design of the implementation of the functionality. 
![drafts - edit drafts - top_unstructuredstudio](https://user-images.githubusercontent.com/81782853/224819432-f95fce95-c3f7-479c-aa90-fe07b8b7615a.png)

**Comment by srish** [comment]
Closing this for now, as we have taken this into account while designing the activity view which will be re-used for the project view.
