### ISSUE TITLE
Uneven padding / spacing between icons on the video's button bar

### ISSUE THREAD

**Issue by srish** [unstructuredstudio/zubhub#173]
Uneven padding / spacing between icons on the video's button bar, more visible when the bar becomes horizontal. The horizontal bar is full width which is  not ideal as well. It should be grouped on the right with some indication that they are clickable. Before working on this, it may be important to sketch some ideas and gather feedback

<img width="587" alt="Screen Shot 2021-05-25 at 8 38 19 PM" src="https://user-images.githubusercontent.com/288353/119599103-2dbdee00-bd99-11eb-8245-cb259eff091c.png">

**Comment by godsakani** [comment]
i will like to work on this issue

**Comment by Jumeb** [comment]
I would love to work on this issue

**Comment by tuxology** [comment]
@godsakani I just assigned this to you. Let me know if you are attempting it :+1:

**Comment by godsakani** [comment]
@tuxology am ok with it

**Comment by Jumeb** [comment]
Fixed the uneven padding on video's bottom bar

![Screenshot from 2022-04-01 02-54-45](https://user-images.githubusercontent.com/38510556/161179407-7c032461-ea38-43bc-9181-c67d2d9ebdd0.png)
Horizontal view

![Screenshot from 2022-04-01 02-55-00](https://user-images.githubusercontent.com/38510556/161179441-2affbd79-5538-4fbe-8ea9-e76b6fac694b.png)
Vertical view

Problems found

- The SVG icons from _material ui_ used in **BookmarkIcon** and **VisibilityIcon** have a different height and width from the **ClapIcon**

Solution

- Write SVG files for both **BookmarkIcon** and **VisibilityIcon** to have the same width and height as that of **ClapIcon**


If solution is accepted, I would love to make a PR @tuxology

**Comment by godsakani** [comment]
Hello @tuxology this is what i came up with
![Mobile1](https://user-images.githubusercontent.com/70459251/161250517-2360dbdd-807b-4e2a-a65d-c5c985281212.png)
h

**Comment by Jumeb** [comment]
> Hello @tuxology this is what i came up with ![Mobile1](https://user-images.githubusercontent.com/70459251/161250517-2360dbdd-807b-4e2a-a65d-c5c985281212.png) h

Great work @godsakani 
I have a slight question when the break point is reached for a devices like a tablet and the video button container is very long will the three icons remain at the left position or will they be strected out ?

**Comment by godsakani** [comment]
Thank you sir.
They will be stretched out . I tested responsiveness for other devices.
 @Jumeb

**Comment by srish** [comment]
Seems to have been resolved. Closing for now!
