### ISSUE TITLE
Font sizes are non-uniform in a few elements and pages

### ISSUE THREAD

**Issue by srish** [unstructuredstudio/zubhub#176]
- [ ] Observe the font sizes in navbar buttons and in text below:
<img width="710" alt="Screen Shot 2021-05-25 at 8 54 49 PM" src="https://user-images.githubusercontent.com/288353/119600258-8abaa380-bd9b-11eb-847e-12f8237243d0.png">

- [ ] Observe how footer text is too small for the project page text:
<img width="739" alt="Screen Shot 2021-05-25 at 8 55 04 PM" src="https://user-images.githubusercontent.com/288353/119600270-90b08480-bd9b-11eb-89b4-596d1edbf92f.png">

- [ ] The text here is not matching the description size text used before and also buttons above
<img width="730" alt="Screen Shot 2021-05-25 at 8 55 09 PM" src="https://user-images.githubusercontent.com/288353/119600293-9c9c4680-bd9b-11eb-958b-36e1eaccf28d.png">

- [ ] Title is bold here, but not in all pages
<img width="734" alt="Screen Shot 2021-05-25 at 8 55 15 PM" src="https://user-images.githubusercontent.com/288353/119600304-a32abe00-bd9b-11eb-9391-9232c6bd339e.png">

- [ ] Title text is too small, other text too big, logo & navbar text looks way smaller than body text here:
<img width="734" alt="Screen Shot 2021-05-25 at 8 55 19 PM" src="https://user-images.githubusercontent.com/288353/119600322-ac1b8f80-bd9b-11eb-8f32-9339786de203.png">

**Comment by ubaxeeycabdullaahi** [comment]
I will do

**Comment by Deepthi562** [comment]
@srish can i work on this?

**Comment by srish** [comment]
@ubaxeeycabdullaahi Sorry I missed your comment earlier? Are you working on this task if not I can assign it to @Deepthi562.

@tuxology is this issue still valid and how would you advise one can approach this task?

**Comment by Ammy198488** [comment]
Hello. I am an outreachy participant, I would like to work on this.

**Comment by IvyJeptoo** [comment]
hello @srish I am an outreachy applicant and I would like to work on this issue

**Comment by tuxology** [comment]
@IvyJeptoo Please come up with a uniform font sizing system as you attempt this (for different screen sizes also) Some example guidelines for what is considered "good" is here: https://www.editorx.com/shaping-design/article/font-size

**Comment by IvyJeptoo** [comment]
@tuxology working on it, thank you

**Comment by Ammy198488** [comment]
hello @tuxology  i indicated i would be working on this. Been waiting for your response.

**Comment by ipriyanshi1708** [comment]
hello @srish @tuxology  I am an outreachy applicant and I would like to work on this issue

**Comment by Aryanryn09** [comment]
@srish  i would be glad if you assign me this issue

**Comment by Ammy198488** [comment]
@tuxology any update on this yet? and if it's available to work on.

**Comment by srish** [comment]
I am closing this task as this feels too broad and vague. It looks like some of this was addressed in recent UX improvements. If needed, smaller tasks can be created in the future to address specific font changes.
