### ISSUE TITLE
Improvements to search bar

### ISSUE THREAD

**Issue by srish** [unstructuredstudio/zubhub#177]
- [ ] Use darker colored search bar

<img width="325" alt="Screen Shot 2021-05-25 at 8 58 55 PM" src="https://user-images.githubusercontent.com/288353/119600524-13394400-bd9c-11eb-8b65-12e7a629cdaf.png">

- [ ] Center the searchbar on large screens. 
<img width="324" alt="Screen Shot 2021-05-25 at 8 59 02 PM" src="https://user-images.githubusercontent.com/288353/119600533-17656180-bd9c-11eb-951d-d0014f48443e.png">

- [ ] Search bar appears funny in mobile view
<img width="324" alt="Screen Shot 2021-05-25 at 8 59 02 PM" src="https://user-images.githubusercontent.com/288353/167981144-088626bd-393c-4483-bc1c-61e08c8606cc.PNG">

**Comment by sunnyside88** [comment]
Hi there, can I work on this issue?

**Comment by Jumeb** [comment]
@tuxology, I would love to work on this issue. Please can you assign it to me

**Comment by Jumeb** [comment]
> @tuxology, I would love to work on this issue. Please can you assign it to me

Screenshots

![Screenshot from 2022-03-31 22-33-25](https://user-images.githubusercontent.com/38510556/161153332-a07953b3-ec49-4ae5-9787-63907343d027.png)
dark theme applied

![Screenshot from 2022-03-31 22-33-15](https://user-images.githubusercontent.com/38510556/161153475-6339b546-4b69-4550-90b0-0f1a34191942.png)
Centralized search bar

![Screenshot from 2022-03-31 22-35-00](https://user-images.githubusercontent.com/38510556/161153544-87c91ee1-3733-4980-bbd2-0cf8ca9e24ed.png)
hover effect

I would love to make a pull request @srish  and @tuxology

**Comment by tuxology** [comment]
If the PR is ready, you can send it @Jumeb Can you adjust he color in 3rd screenshot to be not so dark? Maybe the selected one could be made lighter or light yellow (and icon changed to red?) Play around with it and send the PR

**Comment by Jumeb** [comment]
> If the PR is ready, you can send it @Jumeb Can you adjust he color in 3rd screenshot to be not so dark? Maybe the selected one could be made lighter or light yellow (and icon changed to red?) Play around with it and send the PR

Ok on it

**Comment by Jumeb** [comment]
> > If the PR is ready, you can send it @Jumeb Can you adjust he color in 3rd screenshot to be not so dark? Maybe the selected one could be made lighter or light yellow (and icon changed to red?) Play around with it and send the PR
> 
> Ok on it

- The Icon changes to red, is the original settings from the code, but to give it more contrast I changed it to white.
- On hover, the search bar become a little bit darker to indicate to the user that an action can occur here on click, so i further reduce the opacity to make it calmer.

**Comment by Jumeb** [comment]
@tuxology  I just  made a pull request, please review the changes.

**Comment by tuxology** [comment]
I am reopening this since it seems like changes made in https://github.com/unstructuredstudio/zubhub/pull/366 got overwritten by another refactor of code. Apologies @Jumeb :cry: Can you recreate the PR with exact changes and resend it?

**Comment by Jumeb** [comment]
> I am reopening this since it seems like changes made in #366 got overwritten by another refactor of code. Apologies @Jumeb cry Can you recreate the PR with exact changes and resend it?

Ok, I'm on it.

**Comment by srish** [comment]
I have added a third bullet item to the task description.

**Comment by Ammy198488** [comment]
hello @srish @tuxology I'm interested in working on this.

**Comment by iamatifmoin** [comment]
@srish @tuxology 
I have fixed the issue. 
Can you please review the PR?

**Comment by ipriyanshi1708** [comment]
Hii @srish @tuxology I am an outreachy applicant, I would love to work on this issue.

**Comment by srish** [comment]
Got fixed it seems.
