### ISSUE TITLE
Cover image on the mobile version appears differently

### ISSUE THREAD

**Issue by srish** [unstructuredstudio/zubhub#194]
Perhaps the activity of the month photo should appear below the buttons on the cover section

**Comment by tuxology** [comment]
I've marked this as release blocker because it leads to a confusing UX on mobile

**Comment by NdibeRaymond** [comment]
After meeting with Suchakra, I made some changes to the cover image by adding a small label that indicates what the image is all about on mobile. I am closing this for now, if the change is inadequate, then we can open this back up
