### ISSUE TITLE
Allow email address and phone number to be changed

### ISSUE THREAD

**Issue by srish** [unstructuredstudio/zubhub#198]
Currently, to edit email and password, one needs to send an email to an admin. Visit, https://zubhub.unstructured.studio/edit-profile and see email and password field. For reference, see screenshot below:

![Screen Shot 2022-05-16 at 5 09 11 PM](https://user-images.githubusercontent.com/288353/168701936-a9871617-1f20-44c2-9352-bcc933734984.png)

Ideally, user should be able to change the address and phone number themselves without having to reach out to an admin.

**Comment by kavyabhat02** [comment]
Hi @srish , could I please work on this?

**Comment by srish** [comment]
Please take a look at other platforms like scratch https://scratch.mit.edu/accounts/email_change/ to gain some ideas on how they allow changing email etc. You will have to create an account on the website to use the email change feature.

**Comment by kavyabhat02** [comment]
Alright, I'll refer to other platforms too. Thanks for the resources to help me get started!

**Comment by kavyabhat02** [comment]
The email field is disabled in the current version. I was thinking of enabling the same field, and then asking for their password to confirm changes. 
@srish mentioned that there could be privacy concerns around password requests, are there any other options or is this method okay? @tuxology

**Comment by NdibeRaymond** [comment]
> The email field is disabled in the current version. I was thinking of enabling the same field, and then asking for their password to confirm changes. @srish mentioned that there could be privacy concerns around password requests, are there any other options or is this method okay? @tuxology

I feel like we can achieve the same purpose by just asking for their username. And it's much more safer than doing passing around the passwords.

**Comment by kavyabhat02** [comment]
> I feel like we can achieve the same purpose by just asking for their username. And it's much more safer than doing passing around the passwords.

Ah okay, I'll do that. In this case, would these options to change email/phone numbers have to be on a different screen?

**Comment by tuxology** [comment]
> > The email field is disabled in the current version. I was thinking of enabling the same field, and then asking for their password to confirm changes. @srish mentioned that there could be privacy concerns around password requests, are there any other options or is this method okay? @tuxology
> 
> I feel like we can achieve the same purpose by just asking for their username. And it's much more safer than doing passing around the passwords.

@NdibeRaymond I feel we should challenge the users with their login/password. Change of email/phone number is a critical change in the account and if someone has access to a logged in machine, they can take over the account. This can also act as a secondary protection against possible future security issues for "account update" workflow. What do you think?

**Comment by Deepthi562** [comment]
> > > The email field is disabled in the current version. I was thinking of enabling the same field, and then asking for their password to confirm changes. @srish mentioned that there could be privacy concerns around password requests, are there any other options or is this method okay? @tuxology
> > 
> > 
> > I feel like we can achieve the same purpose by just asking for their username. And it's much more safer than doing passing around the passwords.
> 
> @NdibeRaymond I feel we should challenge the users with their login/password. Change of email/phone number is a critical change in the account and if someone has access to a logged in machine, they can take over the account. This can also act as a secondary protection against possible future security issues for "account update" workflow. What do you think?

@tuxology i agree with you on this. I think email /password have to be  inlcuded with the username for security. Thank you. Let me know if i can work on this.

**Comment by srish** [comment]
Removing the assignee, as there was no progress recently.

**Comment by iamhks** [comment]
Hi @srish @tuxology I would like to work on this. Can you please assign it to me?

**Comment by iamhks** [comment]
Hi @tuxology I have been trying to make this change, enabled the text box and also added a new password text box to verify whether the actual user is making the change or not. But I am stuck here:
<img width="610" alt="Screenshot 2023-03-10 at 01 43 32" src="https://user-images.githubusercontent.com/43777817/224144196-ea5fbafd-50f2-409d-b12a-51bfefcc06fe.png">
The api directly sends back 400 response. I don't see a way to edit the params as it's from rest_framework.generic and in the definition also, I don't find a way to accept email/phone. Can you pls throw some light how should I proceed further?

**Comment by tuxology** [comment]
@kamthamc If you can help @iamhks it would be nice //cc @NdibeRaymond

**Comment by iamhks** [comment]
@tuxology Thanks for the support, but I was able to do it after spending a lot of time.
Anyway, can you please review my PR?
