### ISSUE TITLE
Allow more than 1 video to be added

### ISSUE THREAD

**Issue by srish** [unstructuredstudio/zubhub#202]
Limit to be decided

**Comment by Deepthi562** [comment]
@srish, did you mean to add it in the code or write saying this is the limit? Please clarify I would like to work.
![pic14](https://user-images.githubusercontent.com/71760959/164553605-d230960c-701e-4756-9d49-1fd213b24791.png)

**Comment by srish** [comment]
@Deepthi562 This feature would require more brainstorming and discussion and is currently a less priority to us.

**Comment by srish** [comment]
Closing this, as this is no more a requirement right now.
