### ISSUE TITLE
Long usernames getting cut off from the user menu

### ISSUE THREAD

**Issue by srish** [unstructuredstudio/zubhub#203]

**Comment by souad988** [comment]
Hello @srish  i would like to work on this issue, i suggest to add a condition when displaying the name in the menu

**Comment by srish** [comment]
@souad988 I am assigning it to you :) Also, before you start working on it, make sure to double check that the issue still exists :-)

**Comment by souad988** [comment]
> @souad988 I am assigning it to you :) Also, before you start working on it, make sure to double check that the issue still exists :-)
thanks for the assignment @srish , i checked, the issue is still remaining the width of the menu increases with size of username 
![long username](https://user-images.githubusercontent.com/59707859/164322701-36d7069e-844a-4e08-8771-372e3205c136.PNG)

**Comment by souad988** [comment]
Hi @srish  
is this solution acceptable? i can add onMouseOver display the full name
![spliceLongName](https://user-images.githubusercontent.com/59707859/164489635-ba59ccf3-6e8b-4c6c-86a2-48c9f95daf4c.PNG)

**Comment by tuxology** [comment]
@souad988 I think we should allow the width of menu to be extended to a "reasonable" number of characters. Lets say around 14 characters (its reasonable for humans to keep usernames like this that they can remember). If the width becomes more than 14 characters, we will follow your solution in https://github.com/unstructuredstudio/zubhub/issues/203#issuecomment-1104454732 Does this sound good?

**Comment by souad988** [comment]
> @souad988 I think we should allow the width of menu to be extended to a "reasonable" number of characters. Lets say around 14 characters (its reasonable for humans to keep usernames like this that they can remember). If the width becomes more than 14 characters, we will follow your solution in [#203 (comment)](https://github.com/unstructuredstudio/zubhub/issues/203#issuecomment-1104454732) Does this sound good?

Hi @tuxology  thanks for your response
for names less than 14 characters we display the fullName 
![namesLessThan14](https://user-images.githubusercontent.com/59707859/164507760-24371d7f-5ba7-44aa-b417-32b58e3aed41.PNG)

**Comment by souad988** [comment]
i added bubble info so when user hover the username area they can see the full username,` {<Tooltip title={props.auth.username}  placement="top">
                          ...
                          </Tooltip> `

**Comment by souad988** [comment]
@tuxology  what do you think?

**Comment by tuxology** [comment]
@souad988 This makes sense and looks good! :+1:

**Comment by srish** [comment]
@souad988 Yeah, I like the idea of increasing the menu's width to up to certain characters. Could you also check how it looks on mobile web? 

@tuxology I am now wondering do we not have a character limit on usernames? If not, perhaps we should and there can be a separate task around it. What say?

**Comment by souad988** [comment]
> @souad988 Yeah, I like the idea of increasing the menu's width to up to certain characters. Could you also check how it looks on mobile web?
> 
> @tuxology I am now wondering do we not have a character limit on usernames? If not, perhaps we should and there can be a separate task around it. What say?

@srish thanks for accepting this approach, this is how it looks on mobile screen size
![splitedNameMobile](https://user-images.githubusercontent.com/59707859/164678458-0c531c1c-620d-4d47-bc7e-e60667a7ce3e.PNG)
