### ISSUE TITLE
Allow creation of learning activities on ZubHub web app

### ISSUE THREAD

**Issue by srish** [unstructuredstudio/zubhub#205]
Based on feedback from educators, a critical feature that we need is to allow the creation of learning activities on ZubHub web app. Currently, the learners and educators browse the activity on a different website, hosted by Unstructured Studio "http://kriti.unstructured.studio," which is based on Ghost, a blogging platform solely administered by Unstructured Studio team members. The new feature ideally allows users to engage with the activities directly on ZubHub and educators to upload/manage their ideas on the web app for free use globally. This feature will also be beneficial if educational organizations want to host a custom installation of ZubHub and build a community around their own content. Ideally, there is support for content creation in a similar format as on the "Kriti website." (e.g., https://kriti.unstructured.studio/messaging-station/).

To investigate further:
* Does ghost allow remapping of the URLs?
* Can we allow remapping of another subdomain URL?
* From design perspective, how different or similar should project creation be in comparison with activity creation? This requires brainstorming with designers, our mentors, educators and child users.

**Comment by souad988** [comment]
Hi @srish 
I will go through the resources you shared, take notes then leave my questions here

**Comment by srish** [comment]
Closing this task as this was completed via Outreachy. PR is still in review.
