### ISSUE TITLE
Add Login or Sign Up button when user clicks share a project/create project when not logged in

### ISSUE THREAD

**Issue by tuxology** [unstructuredstudio/zubhub#207]
Clicking "Share A project" button when not logged-in shows the following:

![image](https://user-images.githubusercontent.com/3373857/122860122-fe37ce00-d2d1-11eb-821f-13bb9fd0fc3f.png)

There is no “sign-in” button. The only way to reach the “login” button is by clicking the hamburger menu. We should have dedicated buttons in such cases saying “Login” and “Sign Up” and also notify user that they are not logged in - would they like to login or sing-up before they get an opportunity to share a project

**Comment by NdibeRaymond** [comment]
Thinking about something. Won't a better ux be to redirect the user to the login page without requiring them to click on a button to do that?

**Comment by NdibeRaymond** [comment]
> Thinking about something. Won't a better ux be to redirect the user to the login page without requiring them to click on a button to do that?

@tuxology ?

**Comment by Jumeb** [comment]
@NdibeRaymond this issue has been solved by means or redirecting to the login page, can it be removed from issues or indicated as done

**Comment by srish** [comment]
I think in general the page could have an improved UX. Maybe something like? "Sign up" and "login" can then be directed to https://zubhub.unstructured.studio/signup and https://zubhub.unstructured.studio/login pages. More suggestions are welcome!

![Screen Shot 2022-04-04 at 4 00 36 PM](https://user-images.githubusercontent.com/288353/161646313-35a36a68-11f7-43a6-bb16-98b51090ec85.png)

**Comment by Jumeb** [comment]
I think we could do like some sort of pop-up instead telling the user, he or she can only share a project if they are logged in or if the create an account. This could improve ux. Instead of just forcing the user to create an account we simply just give them a nudge.
Some users may only be interested in viewing the projects.

**Comment by souad988** [comment]
> I think in general the page could have an improved UX. Maybe something like? "Sign up" and "login" can then be directed to https://zubhub.unstructured.studio/signup and https://zubhub.unstructured.studio/login pages. More suggestions are welcome!
> 
> ![Screen Shot 2022-04-04 at 4 00 36 PM](https://user-images.githubusercontent.com/288353/161646313-35a36a68-11f7-43a6-bb16-98b51090ec85.png)

Hello @srish @tuxology @NdibeRaymond  I want to work on this issue as suggested would you assign it to me

**Comment by tuxology** [comment]
I think I agree with @Jumeb The login page already has a CTA for signup in case you are not a "member". So, this page can work and we don't need another page. We might want to improve the UX on login page itself. Maybe make "Welcome to Zubhub" a bit bold. 

@souad988 I am assigning this to you :+1:

**Comment by souad988** [comment]
> I think I agree with @Jumeb The login page already has a CTA for signup in case you are not a "member". So, this page can work and we don't need another page. We might want to improve the UX on login page itself. Maybe make "Welcome to Zubhub" a bit bold.
> 
> @souad988 I am assigning this to you 👍

Hi @tuxology 
what do you think is this acceptable? or you want just to make the title bolder
![login title yellow](https://user-images.githubusercontent.com/59707859/163796338-e53c33c4-b214-430c-9d92-cc100513db9f.PNG)

**Comment by tuxology** [comment]
Closing this as duplicate of #488
