### ISSUE TITLE
Scroll freezes when menu is open on mobile

### ISSUE THREAD

**Issue by tuxology** [unstructuredstudio/zubhub#208]
### Issue
Upon clicking hamburger menu on mobile (Chrome/Safari), the Menu shows up but does not go away. This is fine because the user may want to click on something. But when you begin scrolling, it still does not go away and the scroll does not work.  

![image](https://user-images.githubusercontent.com/3373857/122860462-9afa6b80-d2d2-11eb-8d95-4e91ae272fcf.png)

### Workaround
Only when tapping on any empty area of screen does it go away. 

### Expected Outcome
When scrolling begins, menu should go away and scrolling should continue

**Comment by godsakani** [comment]
Hi, I am Ngodwill an Outreachy Applicant interested in contributing to the development of Zubhubs mobile application. Can i please work on this issue?

**Comment by souad988** [comment]
hello @srish   @tuxology   @godsakani  
i'm souad an outreachy applicant if no body is working on this issue i would like to take it

**Comment by souad988** [comment]
> Hi, I am Ngodwill an Outreachy Applicant interested in contributing to the development of Zubhubs mobile application. Can i please work on this issue?

hello @godsakani  can you please let me know if you are not working on this issue

**Comment by tuxology** [comment]
@souad988 I've assigned this to you for now :+1:

**Comment by souad988** [comment]
> @souad988 I've assigned this to you for now 👍

thanks @tuxology

**Comment by godsakani** [comment]
can i work on it too @tuxology  to ?

**Comment by NdibeRaymond** [comment]
> can i work on it too @tuxology to ?

@godsakani I'm sorry you weren't assigned this but we had no idea if you were working on it already or not. Perhaps you can comment on some of the not already claimed issues and tag tuxology or me to assign them to you? you can also go through the codebase and create issues based off of any issue you find.
