### ISSUE TITLE
Error Notification on Sign Up gets hidden on mobile UX 

### ISSUE THREAD

**Issue by tuxology** [unstructuredstudio/zubhub#209]
### Issue
When signing up on mobile device, any notification (eg password mismatch etc.) shows up at top (below heading) when you tap **Sign Up**. Since the form is long, the user is unaware of what they are missing and the app just seems stuck when you tap **Sign Up**

### Expected Outcome
The error should be shown on top of screen/bottom of screen like other notifications using standard notification system we are using (such as successful creation of project etc)

**Comment by alicendeh** [comment]
Can I please work on this issue @tuxology ?

**Comment by alicendeh** [comment]
Hello @tuxology please i have a question regarding the way i should customize the toast?

This is how far I have gone

![Screenshot from 2022-04-18 15-09-03](https://user-images.githubusercontent.com/58989178/163820242-abb607d9-31b8-4568-8218-63e2cfd4f7ec.png)

**Comment by tuxology** [comment]
@alicendeh Thanks for your efforts here! Seems like you are on the right track. Since there is a clear description of the text on the fields themselves, maybe the only thing we should do is to bring up the toast (red color which denotes error) on the screen which says something like: 

"Looks like there are a few errors in the registration form. Review it before clicking Signup!"  

The reason is that the issue is mostly relevant only for mobile registrations where some error fields are hidden up or below and the user is left confused why the signup button is not working. Therefore, maybe test it on the mobile screens as well.

**Comment by alicendeh** [comment]
Done @tuxology 

here is the output
![Screenshot from 2022-04-18 16-58-28](https://user-images.githubusercontent.com/58989178/163836214-1f456754-cae9-4dd8-b479-b27c5f2fa543.png)

**Comment by tuxology** [comment]
Thanks, very close! Lets refine this in the PR :+1:

**Comment by alicendeh** [comment]
Thank you
