### ISSUE TITLE
Consistency of Modal UI elements on mobile

### ISSUE THREAD

**Issue by tuxology** [unstructuredstudio/zubhub#210]
### Issue

UI elements on a modal on mobile are a bit inconsistent:

- [ ] Title Text is small. It seems not to be a title
- [ ] There is extra vertical space between title text and content text
- [ ] Inconsistent padding in buttons. padding of buttons in relation to modal border should be same as top and left padding of title. 

![image](https://user-images.githubusercontent.com/3373857/122861191-de090e80-d2d3-11eb-9ec9-663d7112eef9.png)

**Comment by Jumeb** [comment]
@tuxology I would like to work on this issue, as my second contribution for outreachy
