### ISSUE TITLE
Buttons in Project Page on mobile need realignment

### ISSUE THREAD

**Issue by tuxology** [unstructuredstudio/zubhub#211]
### Expected Outcome

- [ ] Edit should be right aligned and placed along with Delete
- [ ] Clap, bookmark and views button should be equally spaced or left/right aligned and packed together 
- [ ] Too much vertical spacing between clab,bookmark,view button row and photos div

![image](https://user-images.githubusercontent.com/3373857/122861614-8fa83f80-d2d4-11eb-8246-78d78a88366b.png)

**Comment by alicendeh** [comment]
Hello, Am called Alice Ndeh an outreachy applicant and my initial application was selected. Can i please work on this issue?

**Comment by alicendeh** [comment]
Hi, I am Alice Ndeh an Outreachy Applicant interested in contributing to the development of Zubhubs mobile application. Can i please work on this issue?

**Comment by imranburki** [comment]
Hi, i am Outreachy 2022 applicant. can i work on this issue too?

**Comment by alicendeh** [comment]
Hey @imranburki am already working on this issue. Please get another one which hasn't been assigned to someone yet
