### ISSUE TITLE
Bug: no avatars for some

### ISSUE THREAD

**Issue by srish** [unstructuredstudio/zubhub#220]
It looks like we ran out of avatars for some:
![Screen Shot 2021-07-03 at 10 42 27 AM](https://user-images.githubusercontent.com/288353/124362701-7dd76e00-dbeb-11eb-83dd-64d2e98b8245.png)
Project links:
https://zubhub.unstructured.studio/projects/b5968b3d-4d66-42d5-822a-71ec429431c1, 
https://zubhub.unstructured.studio/projects/7a729910-86bd-419a-8fd4-8c9c268d60bd

**Comment by NdibeRaymond** [comment]
This is caused by slow network. The network is not fetching the avatar fast enough.

**Comment by NdibeRaymond** [comment]
> This is caused by slow network. The network is not fetching the avatar fast enough.

Since this doesn't have any other reply and it's clear the quoted reply is the reason this happens, I am closing this right now. We can open it later if it becomes a problem
