### ISSUE TITLE
Improve account creation's ux 

### ISSUE THREAD

**Issue by srish** [unstructuredstudio/zubhub#221]
- [x] Keep password and confirm password at the same level. Instead of confirm password, the text can say "Type password again"
- [x] Swap location with phone number field.
- [x] Keep phone number and email at the same level 
- [x] Phone number should have another field for country code which we detect programmatically based on the location entered by someone. And, this should be changeable from a drop down list of several country code.

**Comment by NdibeRaymond** [comment]
closing this because it has been fixed
