### ISSUE TITLE
Allow uploading videos to ZubHub 

### ISSUE THREAD

**Issue by srish** [unstructuredstudio/zubhub#225]
YouTube, Vimeo, Drive links are good but makes the process a lot more complicated. Allowing uploading videos to ZubHub will make the process a lot more smooth. We may have to make extra efforts to ensure child's privacy is retained and they don't upload anything with their face in it. But, efforts in this direction will be overall worth it.

**Comment by tuxology** [comment]
The upload feature does work 🙏🏽 Thanks a lot!! Here is a small suggestion on improving the UX I think @NdibeRaymond  🤔 

![image](https://user-images.githubusercontent.com/3373857/134099483-15903915-38d4-4ec4-99e1-be3c27ae0a5a.png)

**Comment by NdibeRaymond** [comment]
This  looks great! I have a question though, you are aware we don't upload media resources (images and videos) until the user have clicked on submit, so the last step seems irrelevant (?). The reason for this is so that when a user tries selecting a different image or video than the one they've already selected, we won't need to re-upload the new resource to digitalocean space or cloudinary, saving the user's data and stuffs. It also makes sense, because the whole project creating process needs to be treated like a single atomic unit, so if the user ends up closing the form without clicking submit, we won't need to start worrying about cleaning up the already partially uploaded resources

**Comment by NdibeRaymond** [comment]
Also you are suggesting I remove drag and drop?

**Comment by tuxology** [comment]
> Also you are suggesting I remove drag and drop?

Yes, lets remove drag and drop

**Comment by tuxology** [comment]
> This looks great! I have a question though, you are aware we don't upload media resources (images and videos) until the user have clicked on submit, so the last step seems irrelevant (?). The reason for this is so that when a user tries selecting a different image or video than the one they've already selected, we won't need to re-upload the new resource to digitalocean space or cloudinary, saving the user's data and stuffs. It also makes sense, because the whole project creating process needs to be treated like a single atomic unit, so if the user ends up closing the form without clicking submit, we won't need to start worrying about cleaning up the already partially uploaded resources

Yes, so in this case, the last modal I have in the diagram will change a bit. Basically, we will show the name of file and when user hits ✅ then we begin the upload. Once the upload hits 100%, we can just show thumbnail of the video below "Add Video" button to show user their video is now added. We should also change "Add Video" to "Replace Video" then maybe. How does that sound?

**Comment by NdibeRaymond** [comment]
> > Also you are suggesting I remove drag and drop?
> 
> Yes, lets remove drag and drop

ok

**Comment by NdibeRaymond** [comment]
> > This looks great! I have a question though, you are aware we don't upload media resources (images and videos) until the user have clicked on submit, so the last step seems irrelevant (?). The reason for this is so that when a user tries selecting a different image or video than the one they've already selected, we won't need to re-upload the new resource to digitalocean space or cloudinary, saving the user's data and stuffs. It also makes sense, because the whole project creating process needs to be treated like a single atomic unit, so if the user ends up closing the form without clicking submit, we won't need to start worrying about cleaning up the already partially uploaded resources
> 
> Yes, so in this case, the last modal I have in the diagram will change a bit. Basically, we will show the name of file and when user hits ✅ then we begin the upload. Once the upload hits 100%, we can just show thumbnail of the video below "Add Video" button to show user their video is now added. We should also change "Add Video" to "Replace Video" then maybe. How does that sound?

There is still the atomicity problem with this UX flow. ideally, all resources should be uploaded once the user clicks on "create project". For displaying thumbnail, images thumbnails can be displayed immediately without first uploading image to server, but videos are bit dicey. If you still think we should upload, the media resources first (then when user clicks on "create project" we now submit the form data), then it means we need to do the same for the image side as well. this also means we can potentially have up to 2 different occasions (for images and videos) where the user will see upload progress loaders, even before the actually project creation. I feel like this flow is more complicated and confusing than the current flow where all uploads are grouped into one

**Comment by tuxology** [comment]
OK, then lets keep the flow where we remove "upload" progress from the last modal and replace it with name of selected file. The ✅ can remain to just close the modal I think and acting as affirmation that the correct file is chosen. We can also add a button on left of ✅ saying "Change Video"

**Comment by NdibeRaymond** [comment]
> OK, then lets keep the flow where we remove "upload" progress from the last modal and replace it with name of selected file. The ✅ can remain to just close the modal I think and acting as affirmation that the correct file is chosen. We can also add a button on left of ✅ saying "Change Video"

Or maybe the "upload video" toggle will change to "change video"?
And what if the user decides to close the modal without adding any video? there is not clear way of doing that here

**Comment by tuxology** [comment]
> Or maybe the "upload video" toggle will change to "change video"?

While this idea does look natural, it could be confusing because the toggle button also acts kinda as 'Title' for what the modal is doing. We need a button adjacent to name to indicate you can change this specific "file". Maybe try and see what UX seems good?

**Comment by tuxology** [comment]
> And what if the user decides to close the modal without adding any video? there is not clear way of doing that here

Then we do nothing, we wait for user to proceed and we say "Either upload video, add video link or add images" in the standard places we are showing errors (or something like that?)

**Comment by NdibeRaymond** [comment]
> > And what if the user decides to close the modal without adding any video? there is not clear way of doing that here
> 
> Then we do nothing, we wait for user to proceed and we say "Either upload video, add video link or add images" in the standard places we are showing errors (or something like that?)

was trying to say that there is no obvious way to close the modal. Once you select a video, to remove it, you need to select another video file. so if a user already selected a video but doesn't want to proceed again, the only way is for them to click outside the modal and the modal will discard the selected video and close. But this is not obvious (it's like the context menu issue we had on the ui project)

**Comment by NdibeRaymond** [comment]
I've been away for a while now trying to combine all the various things I have going on. This issue has been fixed some time ago, closing now. We can open it again if it still needs fixing
