### ISSUE TITLE
Improve navigation on mobile view

### ISSUE THREAD

**Issue by srish** [unstructuredstudio/zubhub#226]
It is not immediately clear how to navigate back and forth between the home screen and a project page on mobile. It is not clear to students that clicking the ZubHub logo can take them to the home page. And, same when they are on the homepage and want to go to a project, it is not clear to them that they can click on the top-right icon from the user menu to create a project.

**Comment by yaya-usman** [comment]
@srish  can i be assigned this? i am an outreachy applicant

**Comment by souad988** [comment]
hello @srish  i'm an outreachy applicant if this issue wasn't assigned to anyone i would like to work on it as a first contribution

**Comment by srish** [comment]
Closing this for now as we have unstructuredstudio/zubhub-mobile#17 now
