### ISSUE TITLE
Fix the content in and placement of "Enter a valid username..." error

### ISSUE THREAD

**Issue by srish** [unstructuredstudio/zubhub#25]
This error is likely coming from Django. I couldn't find it on the frontend side. Ideally, we detect the exact problem in the username, and then display a short message like "Usernames can't have spaces". As far as the placement goes, we display this message right below the username input and not on the top. of the form.

![Screen Shot 2020-12-21 at 6 49 36 PM](https://user-images.githubusercontent.com/288353/102843162-796d0580-43bd-11eb-9976-348859c95d96.png)

**Comment by srish** [comment]
Similarly all the other errors coming from Django, e.g., "This field is required".. could be ideally placed below each input field if possible.

**Comment by NdibeRaymond** [comment]
> Similarly all the other errors coming from Django, e.g., "This field is required".. could be ideally placed below each input field if possible.

The problem with this is that certain errors from django come without context. I will find a way to make this happen though

**Comment by NdibeRaymond** [comment]
> This error is likely coming from Django. I couldn't find it on the frontend side. Ideally, we detect the exact problem in the username, and then display a short message like "Usernames can't have spaces". As far as the placement goes, we display this message right below the username input and not on the top. of the form.
> 
> ![Screen Shot 2020-12-21 at 6 49 36 PM](https://user-images.githubusercontent.com/288353/102843162-796d0580-43bd-11eb-9976-348859c95d96.png)

Hello @srish , I am looking at this right now and I have a few things to say. I don't think trying to detect the exact problem with the username field is a good idea as there are perhaps hundreds of characters that are unsupported and trying to detect every one of them so we can customize the error message is a bit of a nightmare. What we can do is display an error message stating the allowed characters (which is a known quantity, and this is exactly what the above error message does) under the specific field (in this case the username field)

**Comment by srish** [comment]
@NdibeRaymond Okay, I agree! Maybe we show the errors not on the top of the page but beneath the input field where we show other errors. What say?
