### ISSUE TITLE
Remove the line behind the DOB text

### ISSUE THREAD

**Issue by srish** [unstructuredstudio/zubhub#26]
Date of birth text appears on the line as shown in the first screenshot. But, when I try to enter something, the line behind the text goes away (as in the second screenshot). 

![Screen Shot 2020-12-21 at 6 18 39 PM](https://user-images.githubusercontent.com/288353/102843403-fb5d2e80-43bd-11eb-809f-0c892644ec59.png)
![Screen Shot 2020-12-21 at 6 18 44 PM](https://user-images.githubusercontent.com/288353/102843404-fd26f200-43bd-11eb-88cc-cdae54eebc6d.png)

Ideally, there is no line anytime behind the DOB text.

**Comment by NdibeRaymond** [comment]
> Date of birth text appears on the line as shown in the first screenshot. But, when I try to enter something, the line behind the text goes away (as in the second screenshot).
> 
> ![Screen Shot 2020-12-21 at 6 18 39 PM](https://user-images.githubusercontent.com/288353/102843403-fb5d2e80-43bd-11eb-809f-0c892644ec59.png)
> ![Screen Shot 2020-12-21 at 6 18 44 PM](https://user-images.githubusercontent.com/288353/102843404-fd26f200-43bd-11eb-88cc-cdae54eebc6d.png)
> 
> Ideally, there is no line anytime behind the DOB text.

This was a tough one since material dob field doesn't have functionality for adding a fixed label. and removing the label is not an option. But perhaps I can come up with a hack
