### ISSUE TITLE
All validation errors show at once as soon after exiting without entering any information in an input

### ISSUE THREAD

**Issue by srish** [unstructuredstudio/zubhub#27]
Not sure, what the best alternative to address this is though. See screenshot below:

![Screen Shot 2020-12-21 at 7 00 55 PM](https://user-images.githubusercontent.com/288353/102843867-08c6e880-43bf-11eb-80b4-ed4a7a40c793.png)

**Comment by srish** [comment]
Same for the form on https://www.zubhub.unstructured.studio/projects/create

**Comment by NdibeRaymond** [comment]
> Not sure, what the best alternative to address this is though. See screenshot below:
> 
> ![Screen Shot 2020-12-21 at 7 00 55 PM](https://user-images.githubusercontent.com/288353/102843867-08c6e880-43bf-11eb-80b4-ed4a7a40c793.png)

will look into this
