### ISSUE TITLE
Description should support basic formatting and line endings

### ISSUE THREAD

**Issue by tuxology** [unstructuredstudio/zubhub#277]
Current description does not adhere to line endings or links to external sites etc. Allow a little bit of rich text editing (Bullet points, `code formatting`, **bold text** etc). As a result, formatted text added by someone changes to just a paragraph style blob.

**Comment by ghost** [comment]
@tuxology can you please assign me this task? I am an outreachy applicant.

**Comment by tuxology** [comment]
@NdzeRegina This task is done and soon to be merged via a sub-task in PR #318. I'm marking a few more good first use issues so that you can go through them possibly!

**Comment by srish** [comment]
We have support for text formatting now in place.
