### ISSUE TITLE
Same roundness for all buttons

### ISSUE THREAD

**Issue by srish** [unstructuredstudio/zubhub#28]
Don't have best advice to share here may be @tuxology has. I think all our buttons should have same roundness (border radius).
![Screen Shot 2020-12-21 at 7 05 35 PM](https://user-images.githubusercontent.com/288353/102844394-395b5200-43c0-11eb-98c5-e8e8ce6e3b99.png)

**Comment by tuxology** [comment]
Yes, valid point. I was going to file it for later. Lets create tags with phase 2

**Comment by NdibeRaymond** [comment]
They actually do. all buttons use the same border-radius of 15px. The thing is that for UI reasons, all buttons are not of the same size. we have small, medium and large. For example, using large or medium in the "create project" button of the navbar affects responsiveness when the screen size is below something like 400px, so this is a consideration to make. I already reduced the logo at that screen size that it won't make sense to reduce it further just to accommodate a large button. I guess we will talk more about this in our next meeting

**Comment by NdibeRaymond** [comment]
Or maybe we can just use small size buttons throughout
