### ISSUE TITLE
We should make Code documentation and testing a priority

### ISSUE THREAD

**Issue by NdibeRaymond** [unstructuredstudio/zubhub#290]
## Description
Developing this codebase, it was easier to avoid regression since I know every path of the system. Now that we are onboarding new devs, It will progressively become more difficult to avoid regression as more changes are made to the system. There is a need to focus on documenting the codebase and testing testable paths of the codebase.
This will likely be an ongoing process as we can't wave a wand to get all these done. This also means that this task is going to remain open for quite sometime. 

I'm assigning this to myself too so it doesn't interfere with the work the hack4impact folks are doing.

## Todo

- Setup appropriate dev practices like linting and code styling and enforce them.
-  Document functions across the codebase to spell out clearly what they are doing
- Test the testable parts of the codebase to avoid regression.

**Comment by tuxology** [comment]
Most of this is done now, so I am closing this. If we need more specific tests, we will file them individually
