### ISSUE TITLE
Character limit for materials used is too high

### ISSUE THREAD

**Issue by srish** [unstructuredstudio/zubhub#30]
I see that we are using 10,000 as character limit for materials used. Is it for each material? Is so, it is too high. I think for each there should be a limit of 100, and then another limit on number of materials one can enter, that also we can keep as 100.

**Comment by NdibeRaymond** [comment]
> I see that we are using 10,000 as character limit for materials used. Is it for each material? Is so, it is too high. I think for each there should be a limit of 100, and then another limit on number of materials one can enter, that also we can keep as 100.

No, it is not for each material. The materials used field is actually stored as a concatenated string separated by a coma. the 10,000 is still the same as 100 x 100. But I think it is still too high still. maybe reduce it to 5000? @tuxology what do you think?
