### ISSUE TITLE
Hamburger Menu and Sidebar

### ISSUE THREAD

**Issue by ghost** [unstructuredstudio/zubhub#303]
## Description

Add the hamburger menu and sidebar for the mobile view.

Context: Currently, on the mobile view there isn't a hamburger menu and the dropdown isn't clean. This will make the UI clearer for the user. 

## Learning objectives

- CSS and JSX

## Todo

- [ ] Add Sidebar component
- [ ] Add hamburger icon/button

## Useful links

- https://www.figma.com/file/rdoLGoH5vfFBfqV11lgOyw/ZubHub-Mobile?node-id=0%3A1
  - Look at Redesign 3 - Menu

**Comment by Deepthi562** [comment]
@ajain1921, can I work on this if this isn't assigned to anyone?
