### ISSUE TITLE
Unable to create new project

### ISSUE THREAD

**Issue by abetco** [unstructuredstudio/zubhub#305]
**Describe the bug**
When trying to submit a project on my account, I'm unable to do so and there is no error message.

**To Reproduce**

1. Click "Create Project"
2. Fill out the project fields
3. Click "Create Project" at the bottom of the form
4. See a brief 0% loading screen, but no other behavior. Clicking "Create Project" again clears the forms fields. Checking the main page does not show the new project added.

**Comment by abetco** [comment]
tagging @tuxology

**Comment by NdibeRaymond** [comment]
Thanks for creating this issue @abetco . However I and I @tuxology haven't been able to reproduce this issue? 
if it works now on your machine, can you close the task?

**Comment by AndrewLester** [comment]
Here's a video displaying the behavior:
https://user-images.githubusercontent.com/23221268/155836311-546d026a-e016-4659-8d35-bf43dc86aed2.mov

Getting these errors from the network tab in console:
<img width="1440" alt="Screen Shot 2022-02-26 at 2 40 54 AM" src="https://user-images.githubusercontent.com/23221268/155836587-913ca30d-68d0-4c2c-a888-99c6377453e3.png">

**Comment by NdibeRaymond** [comment]
Maybe the best way to resolve this is through a video meeting. I'd love to see your url bar to know exactly what's going on. Can you view your profile currently?

**Comment by AndrewLester** [comment]
My profile image is not visible for some reason, I can see everyone else's though.

**Comment by AndrewLester** [comment]
This can be closed now, it turns out Albert and I were having the same issue: Our university's network blocks the digital ocean URLs.
