### ISSUE TITLE
Carousel on desktop is broken when less images are uploaded

### ISSUE THREAD

**Issue by tuxology** [unstructuredstudio/zubhub#31]
## Example Project (view on Dekstop only)

https://www.zubhub.unstructured.studio/projects/d5bb27b5-c87b-471a-a034-8245f6e067a1 

![image](https://user-images.githubusercontent.com/3373857/102848584-fe5e1c00-43c9-11eb-9cd6-213313edc1bc.png)

**Comment by NdibeRaymond** [comment]
What screen width is this @tuxology ?

**Comment by tuxology** [comment]
It was 2838x1058

**Comment by NdibeRaymond** [comment]
> It was 2838x1058

Submitting a fix for this in the next set of PRs
