### ISSUE TITLE
Draft Autosave

### ISSUE THREAD

**Issue by ghost** [unstructuredstudio/zubhub#317]
## Description

Trigger a function to autosave a draft when a user stops typing/makes a change.

## Learning objectives

- Objective

## Todo

These points are a rough guideline. **Please** feel free to discuss with others on the team about the best way to design this component!

- Todo

## Useful links

- Useful link

**Comment by yaya-usman** [comment]
@ajain1921 can i get assigned this issue?

**Comment by ghost** [comment]
@yaya-usman There's currently a draft PR open for this issue. I apologize for the confusion and I've fixed the labels on it.
