### ISSUE TITLE
Improve materials field ui

### ISSUE THREAD

**Issue by srish** [unstructuredstudio/zubhub#32]
The materials field ui needs to be made more clear, that it can be used to add several materials. I noticed in the user study today. The child got stuck and kept writing a long sentence.

**Comment by tuxology** [comment]
Maybe we can have a small line below which says enter materials you use like Papers, Cardboard, Plastic Cup etc. And be a bit smart, that is, if a uses stars adding a comma, we create a new pill automatically

**Comment by NdibeRaymond** [comment]
> Maybe we can have a small line below which says enter materials you use like Papers, Cardboard, Plastic Cup etc. And be a bit smart, that is, if a uses stars adding a comma, we create a new pill automatically

That sounds great
