### ISSUE TITLE
docker related steps in local setup guide

### ISSUE THREAD

**Issue by lalit97** [unstructuredstudio/zubhub#328]
we might want to add docker related steps in the local setup guide also like 
1. install `docker`
2. install `docker-compose` 
and can provide some related links from docker documentation in the local setup guide
https://github.com/unstructuredstudio/zubhub/#backend

**Comment by yaya-usman** [comment]
@lalit97 i am interested in this issue but i will like to be clear, you mean you want the application containerized and also want a documentation on how to run it right?

**Comment by lalit97** [comment]
Hi @yaya-usman the application is already containerized. I was suggesting having steps in the local setup guide for installing docker.

**Comment by yaya-usman** [comment]
@lalit97  ok thanks for the clarification, let me work on that now, i'll make a pull request soon.
