### ISSUE TITLE
Allow for project creation when only one media source is provided

### ISSUE THREAD

**Issue by srish** [unstructuredstudio/zubhub#33]
In the testing today, the user put the video URL but didn't want to upload any images, and the app wasn't allowing them to create the project. 

We should not allow creating projects only if both inputs are empty. If there is one media input, it should be okay; we let it pass.

**Comment by NdibeRaymond** [comment]
> In the testing today, the user put the video URL but didn't want to upload any images, and the app wasn't allowing them to create the project.
> 
> We should not allow creating projects only if both inputs are empty. If there is one media input, it should be okay; we let it pass.

Ok. I will push a fix for this
