### ISSUE TITLE
Notification Grouping

### ISSUE THREAD

**Issue by ghost** [unstructuredstudio/zubhub#333]
## Description

Based on Cindy's designs we want to group notifications that are triggered by the same event and happen in a certain time interval. 

## Learning objectives

- Frontend Design
- Django REST Framework

## Todo

- [ ] Update get endpoint to group notifications based on their type/date added
- [ ] Update frontend to support showing grouped notifications (2 profile pics)

## Useful links
- https://www.figma.com/file/jRQdwIwXdgmXEe5L0XLgno/ZubHub?node-id=0%3A1

**Comment by yaya-usman** [comment]
@ajain1921  The figma file link not working
