### ISSUE TITLE
Add edit button to draft tile

### ISSUE THREAD

**Issue by ghost** [unstructuredstudio/zubhub#335]
## Description

In order to make it easier for users to edit their drafts, we're going to add an edit button on the draft tile itself. This way they can go to the edit form without having to open up the draft first.

## Learning objectives

- React
- Material UI

## Todo

- [ ] Add edit button

## Useful links

- https://www.figma.com/file/jRQdwIwXdgmXEe5L0XLgno/ZubHub?node-id=0%3A1

**Comment by yaya-usman** [comment]
@ajain1921 can i be assigned this? i am an outreachy applicant

**Comment by ghost** [comment]
@ajain1921 please I will like to work on this.  I am an outreachy applicant.

**Comment by ghost** [comment]
@yaya-usman @NdzeRegina We have someone assigned to the issue and a PR open for it already. We will soon be adding more issues so stay tuned for that!

**Comment by ghost** [comment]
Ok, thank you @ajain1921 , patiently waiting.

**Comment by tuxology** [comment]
@ajain1921 Seems like this is linked to #338 Should we resolve commits there and merge?

**Comment by srish** [comment]
This was addressed in recent enhancements related to project creation.
