### ISSUE TITLE
3 mb size for images, is it too less?

### ISSUE THREAD

**Issue by srish** [unstructuredstudio/zubhub#34]
In the testing today also, we encountered this issue when the user tried to upload images. This made me wonder if we are being too restrictive when it comes to image size. Should we try to keep the image upload size limit a bit higher?

**Comment by NdibeRaymond** [comment]
> In the testing today also, we encountered this issue when the user tried to upload images. This made me wonder if we are being too restrictive when it comes to image size. Should we try to keep the image upload size limit a bit higher?

3mb is kind of like an average. I think this is because we never really talked about what should be reasonable image size. What do you think we should use here?
