### ISSUE TITLE
Use same border radius for Next and Prev buttons

### ISSUE THREAD

**Issue by tuxology** [unstructuredstudio/zubhub#344]
In paginated view when Prev and Next buttons are present together, their right and left border radius are zero. We need to keep consistent button styling as all other buttons. Restore the border radius for a more consistent UI experience. 

![image](https://user-images.githubusercontent.com/3373857/160296554-eeb48a8a-d454-404b-9132-c55aaaae797f.png)

**Comment by Deepanshu039** [comment]
@tuxology i would like to work on this.

**Comment by Deepanshu039** [comment]
@tuxology i am still working on the issue.

**Comment by Morai-C** [comment]
please if this is still open i would like to work on it

**Comment by Deepanshu039** [comment]
@Morai-C this issue is under process and i am about to make a PR as well in sometime so i suggest you to do look for some other issues. thank you

**Comment by Morai-C** [comment]
> @Morai-C this issue is under process and i am about to make a PR as well in sometime so i suggest you to do look for some other issues. thank you

okay thank you
