### ISSUE TITLE
Make "Tinkering Resources" footer link editable from admin backend

### ISSUE THREAD

**Issue by tuxology** [unstructuredstudio/zubhub#345]
The "Tinkering Resources" resources footer is a static link in the code to `http://kriti.unstructured.studio/` We need to make this link editable from the Django admin interface. Here is the location where you can add make this editable. Here a re few tasks that need to be done to achieve this:

- [ ] Create a Footer section in the following are in Django Admin

![image](https://user-images.githubusercontent.com/3373857/160296686-57dc4b96-a7d6-4a21-83ca-43d18e6855de.png)

- [ ] In the footer section, create a editable setting which will change the URL. It would look something like this

![image](https://user-images.githubusercontent.com/3373857/160296849-d181683a-995f-4860-a5d1-fa61758d89fd.png)

**Comment by khabdrick** [comment]
Hello @tuxology I'll like to be assigned to this issue

**Comment by tuxology** [comment]
What happened to #356 @khabdrick? Are you planning a fresh start for this?

**Comment by khabdrick** [comment]
Yes, I am starting afresh. But I am a bit confused, I was told that tinkering resources url points to Explore Ideas button in the heroes section. If so, is there any need to have tinkering resources URL separately?
Can I just fetch the data directly from explore_ideas_url? 
@tuxology

**Comment by NdibeRaymond** [comment]
> Yes, I am starting afresh. But I am a bit confused, I was told that tinkering resources url points to Explore Ideas button in the heroes section. If so, is there any need to have tinkering resources URL separately? Can I just fetch the data directly from explore_ideas_url? @tuxology

I thought about this further and this is my opinion:

I think what needs to be done is to add a `tinkering_resources_url` to the model (next to `explore_ideas_url`), then add it to the same serializer and view that handles `explore_ideas_url` on the backend. 

On the frontend, `tinkering resources` in the footer should point to the new field and if the new field is empty, it should point to `kriti.unstructured.studio` (for hint see how `explore_ideas_url` is currently being used in the hero section). 
You also need to modify how `explore_ideas_url` is used in the hero section. 
It should be `explore_ideas_url` --- `if not present` ---> `tinkering_resources_url` --- ` if not present` ----> `https://kriti.unstructured.studio`

**Comment by khabdrick** [comment]
> Yes, I am starting afresh. But I am a bit confused, I was told that tinkering resources url points to Explore Ideas button in the heroes section. If so, is there any need to have tinkering resources URL separately? Can I just fetch the data directly from explore_ideas_url? @tuxology

Never mind, this has been clarified.

**Comment by tuxology** [comment]
@NdibeRaymond Yes, your explanation in https://github.com/unstructuredstudio/zubhub/issues/345#issuecomment-1092262172 is precisely what we want!
