### ISSUE TITLE
Extra stray html <p> tags in some descriptions

### ISSUE THREAD

**Issue by tuxology** [unstructuredstudio/zubhub#346]
**Describe the bug**
There is an extra `<p>` and `</p>` tag in some of the project descriptions

**To Reproduce**

1. Go to Zubhub homepage (https://zubhub.unstructured.studio)
2. Observe the descriptions of some projects

**Expected behavior**
There should be no `<p>` tag 

**Screenshots**
![image](https://user-images.githubusercontent.com/3373857/160297032-e45a7bca-c10f-4155-8ebd-beb0154c0d00.png)

**Comment by ktric001** [comment]
It looks like the tags are written into the descriptions themselves, causing them to appear on the site. 
![image](https://user-images.githubusercontent.com/87986240/160297531-8dd32344-d4ca-4d5d-a4d8-ac27154694af.png)

**Comment by ktric001** [comment]
Removing the extra tags fixes this issue. 
![image](https://user-images.githubusercontent.com/87986240/160297758-d0045fc0-36e9-4714-ba11-86ced4aecaa5.png)

**Comment by yaya-usman** [comment]
@tuxology  can i get assigned this issue? and i'll appreciate if you can review my #342 pull request, i have made that since yesterday

**Comment by Somya-Singhal** [comment]
Hi @tuxology, I am an outreachy applicant. I would like to work on this issue. Can I be assigned this issue?

**Comment by Kavita-Dhamot** [comment]
HI @tuxology . can you assign this issue to me?

**Comment by qxprakash** [comment]
Hi @tuxology can I work this issue as an outreachy 22 applicant ? Thanks !!

**Comment by NdibeRaymond** [comment]
Hello @tuxology this particular issue is a result of the richtext editing feature that is currently live on encube. I am assigning this to myself because it's a fix already in the private_mode PR and is not as simple as removing the p tag.

**Comment by tuxology** [comment]
Makes sense @NdibeRaymond :+1:

**Comment by tuxology** [comment]
This seems fixed closing this one :+1:
