### ISSUE TITLE
Generate improved and conscise ZubHub documentation

### ISSUE THREAD

**Issue by tuxology** [unstructuredstudio/zubhub#347]
Current developer  documentation for ZubHub resides in multiple places  

- https://github.com/unstructuredstudio/zubhub/tree/master/zubhub_backend/zubhub/docs as well as 
- https://github.com/unstructuredstudio/zubhub#development
- https://github.com/unstructuredstudio/zubhub/tree/master/single_vm_deployment

We currently need a way to bring all the documentation in one place which is concise and easy to use. New documentation should make lives of developers and newcomers to the project more easy than it is now. We have decided for now to being working on the existing markdown documentation we have and integrate it into a statically generated doc using `mkdocs`. We will be using the mkdocs-material project (https://squidfunk.github.io/mkdocs-material/) to build this new documentation. The tasks involved in this work are as follows:

- [x] Consolidate all markdown files and create a proper documentation structure. Get inspired from https://beta.reactjs.org/learn and https://squidfunk.github.io/mkdocs-material/reference/ themselves
- [x] Convert all the documentation in structure the mkdocs understands and ensure that the documentation builds
- [x] Use current ERD diagram generator mechanism as part of the build
- [x] Create a Github Action to build the docs and push them to github pages
- [x] Rename github action to Documentation Deployment and ensure deployment works. 
- [x] Add scripts to copy relevant files to docs and then use them instead of maintaining two copies of files. Refer https://github.com/unstructuredstudio/zubhub/pull/392#issuecomment-1100777444

**Comment by qxprakash** [comment]
Hi @tuxology I would like to work on this issue as an Outreachy 22 applicant please assign me this issue. Thankyou!!

**Comment by Vaishnavi-Markunde** [comment]
Hi, I would like to build tutorial documentation for installation and setting up the environment on Linux OS for extreme beginners. Please assign it to me. Thank you!

**Comment by tuxology** [comment]
@Prakashh21 and @Vaishnavi-Markunde I am assigning it to you both as you requested this :smile_cat: This is a good opportunity to team up and work as well. I would suggest working on first two tasks in the beginning and see how it works out for you. We can begin by creating a `docs` directory in the top level of `zubhub` project and start adding stuff there. Please add a README.md in `docs` as well so we can see an outline of docs and how they are going to be built.

**Comment by Vaishnavi-Markunde** [comment]
Thank you sir, we'll work on it

> @Prakashh21 and @Vaishnavi-Markunde I am assigning it to you both as you requested this 😸 This is a good opportunity to team up and work as well. I would suggest working on first two tasks in the beginning and see how it works out for you. We can begin by creating a `docs` directory in the top level of `zubhub` project and start adding stuff there. Please add a README.md in `docs` as well so we can see an outline of docs and how they are going to be built.

**Comment by qxprakash** [comment]
> @Prakashh21 and @Vaishnavi-Markunde I am assigning it to you both as you requested this smile_cat This is a good opportunity to team up and work as well. I would suggest working on first two tasks in the beginning and see how it works out for you. We can begin by creating a `docs` directory in the top level of `zubhub` project and start adding stuff there. Please add a README.md in `docs` as well so we can see an outline of docs and how they are going to be built.

@tuxology Sure !! we will work on it.

**Comment by imranburki** [comment]
Hi, I am outreachy  2022 applicant. can i work on this issue?

**Comment by tuxology** [comment]
@Vaishnavi-Markunde and @Prakashh21 How are things going with this one? Remember to send smaller and manageable PRs. Are you still working together on this one still?

**Comment by Vaishnavi-Markunde** [comment]
> @Vaishnavi-Markunde and @Prakashh21 How are things going with this one? Remember to send smaller and manageable PRs. Are you still working together on this one still?

Yes we are working on this, will update soon.

**Comment by tuxology** [comment]
**Update:** This issue is to be kept open since this is still half way done. I am assigning it to myself. Currently, the `mkdoks` job (`ci.yml`) is breaking and the deployments are not working. In addition, we need to fix the documentation itself as discussed here : https://github.com/unstructuredstudio/zubhub/pull/392#issuecomment-1100777444

**Comment by NdibeRaymond** [comment]
> **Update:** This issue is to be kept open since this is still half way done. I am assigning it to myself. Currently, the `mkdoks` job (`ci.yml`) is breaking and the deployments are not working. In addition, we need to fix the documentation itself as discussed here : [#392 (comment)](https://github.com/unstructuredstudio/zubhub/pull/392#issuecomment-1100777444)

I spent sometime working on this over the weekend @tuxology. Here is the link to the deployment https://unstructuredstudio.github.io/zubhub/
