### ISSUE TITLE
Error page shown when no project is created

### ISSUE THREAD

**Issue by SIXIN-LI** [unstructuredstudio/zubhub#350]
**Describe the bug**
After setting up the backend and frontend, http://localhost:3000/ gives an error page like the below screenshot.
![image](https://user-images.githubusercontent.com/45926850/160505701-e147791b-5f7b-4624-aed0-1b59a6eed5f2.png)

**To Reproduce**

1. Follow readme.md of the project
2. Enter http://localhost:3000/ in your browser

**Expected behavior**
I am not sure of the design. Something like the screenshot in the readme.md may be shown as the default. Or, a welcome page instructing users to create an account first would help!
![image](https://user-images.githubusercontent.com/45926850/160505505-e85b6125-ee93-4414-a41f-927b568ab1ef.png)

**Screenshots**

**Comment by tuxology** [comment]
Thanks @SIXIN-LI for this very obvious and valid issue :pray: Maybe a welcome page instructing users to create a new account and set it as admin from the backend will be a good idea. Can you sketch how it will look? To keep consistent design, we should make it similar to the _Oops_ page :)

**Comment by tuxology** [comment]
@SIXIN-LI Should I assign this issue to you? Let me know!

**Comment by SIXIN-LI** [comment]
> @SIXIN-LI Should I assign this issue to you? Let me know!

I am new to React. If this is not urgent, I can take it!

**Comment by Jumeb** [comment]
@tuxology can I work on this issue.

**Comment by arushi2715** [comment]
Hey @tuxology I want to work on this issue.

**Comment by tuxology** [comment]
@SIXIN-LI Are you still working on this? If not, I can reassign this. Let me know by EOD

**Comment by Jumeb** [comment]
> @SIXIN-LI Are you still working on this? If not, I can reassign this. Let me know by EOD

I would love to help @SIXIN-LI to get his feet on this issue

**Comment by tuxology** [comment]
Hey @Jumeb I've assigned you on this one :+1:

**Comment by Jumeb** [comment]
> Hey @Jumeb I've assigned you on this one +1

Hello, @tuxology this is what I came up with for the fix. Any ideas or modifications are much welcomed. Before I make a pull request.

Screenshot
![Screenshot from 2022-04-11 13-48-26](https://user-images.githubusercontent.com/38510556/162742529-817f3f03-4d8d-4022-a18e-2be4fd5e2b0a.png)

**Comment by tuxology** [comment]
Closing this since we merged this :pray: Thank you @Jumeb
