### ISSUE TITLE
Detailed Documentation

### ISSUE THREAD

**Issue by Vaishnavi-Markunde** [unstructuredstudio/zubhub#353]
## Description
Hi @tuxology , I would like to build tutorial documentation with step by step procedure for installation and setting up the environment on Linux OS for extreme beginners. I'll keep a note of issues faced by me and other members in the group.

##  Objectives
- To help beginners to set up their developer environment

Thank You!

**Comment by tuxology** [comment]
This is a valid issue, however, this could be a subset of #347 and an upcoming PR #342 so I am closing this one. However, I would suggest working on #347 as part of this.
