### ISSUE TITLE
'Failed to load api specification' error when visiting https://localhost:8000

### ISSUE THREAD

**Issue by NdibeRaymond** [unstructuredstudio/zubhub#357]
**Describe the bug**
when you build zubhub on your localmachine and try visiting https://localhost:8000 on your browser, you get an internal server error with message "failed to load api specification". This error is coming from the `UserProfileAPIView` class `get_serializer_class` method. This happens because we decided not to pass requests object into `SchemaGenerator`  class `get_schema` method because doing so will apply permissions to the schema endpoints and this is not desirable.

One quick fix for this is to replace the `UserProfileAPIView` class `get_serializer_class` method with:

` def get_serializer_class(self):`

`    if self.request and self.kwargs.get("username") != self.request.user.username:`
`        return CreatorMinimalSerializer`
`    else:`
`        return CreatorSerializer`

and add the following to the class docstring:

`Note that this schema returns the full user profile, but the api sometimes` 
`returns a minimal version of the user profile, omitting certain fields that` 
`are not neccessary or are sensitive.`

**To Reproduce**
1. follow the readme on zubhub home page to setup zubhub on your local environment.
2. visit https://localhost:8000 and observe what happens

**Expected behavior**
You should have zubhub API documentation on your screen.

**What Happens**
You get an error page with message 'failed to load api specification'

**Comment by Somya-Singhal** [comment]
I would like to work on this issue. Can I take this issue?

**Comment by Somya-Singhal** [comment]
Hello @tuxology, I had linked a pull request. Can you please review it and do let me know if it works fine?

**Comment by Somya-Singhal** [comment]
Hello @tuxology, I had made the changes requested and linked the PR. Can you please review it and let me know if any changes are required?
