### ISSUE TITLE
Fix email address

### ISSUE THREAD

**Issue by srish** [unstructuredstudio/zubhub#36]
Replace `hello@unstrucuted.studio` with `hello@unstructured.studio`

**Comment by srish** [comment]
Also, I was able to create projects without confirming my email address. Is this an intentional behavior?

**Comment by NdibeRaymond** [comment]
> Also, I was able to create projects without confirming my email address. Is this an intentional behavior?

Yes this is intentional. Project creation is one of the basic things are user should be able to do once registered. This can be changed though. We will talk about it in our next meeting

**Comment by NdibeRaymond** [comment]
> Replace `hello@unstrucuted.studio` with `hello@unstructured.studio`

oooooh. That was a terrible mistake. fixing it asap
