### ISSUE TITLE
Search Bar Suggestions

### ISSUE THREAD

**Issue by ghost** [unstructuredstudio/zubhub#360]
## Description

As you're typing in the search bar, you should get a list of possible options to choose from. 

NOTE: This isn't a required feature but it would be nice to implement. One concern that Albert brought up is that this might eat up someone's internet quota as requests are constantly being made to the backend to search. We need to find a way to quantify how internet intensive it is and decide whether the feature is worth it. 

## Learning objectives

- Django REST Framework
- React

## Todo

- [ ] Add suggestions dropdown to search bar
- [ ] Modify backend if necessary to support suggestions

## Useful links

- https://www.figma.com/file/jRQdwIwXdgmXEe5L0XLgno/ZubHub?node-id=0%3A1

**Comment by godsakani** [comment]
hello @ajain1921  the figma file is not opening
