### ISSUE TITLE
Horizontal overflow and horizontal Scroll on smaller devices when logged in.

### ISSUE THREAD

**Issue by Morai-C** [unstructuredstudio/zubhub#364]
Describe the bug
The page does not fit to screen on smaller devices when logged in.

**To Reproduce**

1. Go to zuhub homepage
2. login
3. use the developer tools or inspect on browser. (Ctrl + shift + I)

**Expected behavior**
page is supposed to  fit to device width without any overflow

**Screenshots**
![Screenshot (107)](https://user-images.githubusercontent.com/77807331/161136492-453c7635-4925-425e-aff8-48308b51955f.png)

**Comment by tuxology** [comment]
@Morai-C I can reproduce it on the desktop using inspector, but was unable to reproduce this on an actual tiny phone I have. I use a very small phone (possibly the smallest right now) and this does not seem to be a problem there. If you can reproduce this on a real device, let me know. We'll keep this open until then

**Comment by Vaishnavi-Markunde** [comment]
> @Morai-C I can reproduce it on the desktop using inspector, but was unable to reproduce this on an actual tiny phone I have. I use a very small phone (possibly the smallest right now) and this does not seem to be a problem there. If you can reproduce this on a real device, let me know. We'll keep this open until then

Even I tried it with my real device and it works fine on my phone.
![image](https://user-images.githubusercontent.com/79241223/161544712-7cc33818-a17a-459c-9061-7360de1b3139.png)

And this in inspection mode :
<img width="959" alt="image" src="https://user-images.githubusercontent.com/79241223/161549527-ca8e0441-0009-4852-a10a-7eb5f25ada7e.png">

**Comment by AndrewLester** [comment]
This is certainly a problem on small devices, you'll just need to observe the cause of the issue. In @Morai-C 's first picture it is clear that the username extends past the edge of its parent element, and this is confirmed in a screenshot from a real phone (Samsung Galaxy S10e) shown below:
<img height="600" src="https://user-images.githubusercontent.com/23221268/162030740-ea482e75-e442-4be9-af8c-8c679b48e182.jpg" alt="ZubHub creator page overflow">

This user is on the production site if you'd like to test it yourself. Given a long enough username without breaking characters, the page will overflow on any screen.

**Comment by tuxology** [comment]
@AndrewLester Thanks for testing this. Since our intended users may use the exact phone you have, we should indeed find the root cause for this now and get a fix.Also, can you let me know which browser did you use? I can't reproduce it on safari and Firefox on all screen sizes. If this is on Chrome, this is more urgent then as almost everyone we've talked to use Zubhub on chrome on android on small screens.  

@Morai-C does your #367 PR fix this? There might be other cases as well. Check long comments in comment boxes as well while you are at it

**Comment by AndrewLester** [comment]
@tuxology yeah this is on Chrome.

**Comment by Morai-C** [comment]
@tuxology i fixed the overflow caused by the cards in which the email addresses also extended but in that case i'll go through my code to see if it addresses the issue of longer email addresses.. i'm on it. @AndrewLester  thanks for also spoting this, my email address wasn't long so in my tests it didn't cause an issue.. i used an iphone display 5 resolution and it looked great..

**Comment by Morai-C** [comment]
@tuxology please i've added a commit addressing the latest finding please review and in case more bugs are noticed you can call my attention to it i  worked on the minor ones i could find when debugging and also addressed that of @AndrewLester

**Comment by tuxology** [comment]
We are closing this since it is a very corner case for now. I wasn't able to reproduce this even on small phones like iPhone 6s
