### ISSUE TITLE
Creator text on project cards disappearing into card on smaller screen devices

### ISSUE THREAD

**Issue by Morai-C** [unstructuredstudio/zubhub#365]
**Describe the bug**
The creator text goes into the card on smaller devices

**To Reproduce**

1. Go to 'http://localhost:3000/profile'
2. Use developer tools to adjust screen width
3. Scroll down to created projects'
4. notice the text entering inside the card

**Expected behavior**
the text should wrap to a new line when the width is exhausted

**Screenshots**
![Screenshot (108)](https://user-images.githubusercontent.com/77807331/161139086-1506cb2a-7168-49f7-a901-b95556e671d8.png)

**Comment by tuxology** [comment]
Awesome @Morai-C Thanks for reporting this! :+1: Do you want to make an attempt to fix this bug? If yes, let me know and I can assign this to you.

**Comment by Morai-C** [comment]
> Awesome @Morai-C Thanks for reporting this! 👍 Do you want to make an attempt to fix this bug? If yes, let me know and I can assign this to you.

yes i would like to fix this

**Comment by ntungwe-90** [comment]
Please can i be assigned to fix this?

**Comment by ntungwe-90** [comment]
@tuxology  please can i be assigned to fix this ?

**Comment by Morai-C** [comment]
> @tuxology please can i be assigned to fix this ?

already on it

**Comment by tuxology** [comment]
This is linked to #528 now. We will focus on only fixing that first. We will keep this open to make sure we are tracking #367

**Comment by srish** [comment]
Couldn't replicate/no more applicable, closing this.
