### ISSUE TITLE
Share projects privately with another user

### ISSUE THREAD

**Issue by srish** [unstructuredstudio/zubhub#37]
In the user testing today with a 6th grader, the user shares a wish to share projects with others privately. I think this is super ambitious for us at this point. Something to consider in the future..

**Comment by tuxology** [comment]
I think this is not that ambitious. Each project can have a flag which says if its visible in gallery or not. If its not, the only way to view this is by direct link (which is already present anyways)

**Comment by NdibeRaymond** [comment]
> I think this is not that ambitious. Each project can have a flag which says if its visible in gallery or not. If its not, the only way to view this is by direct link (which is already present anyways)

This is true. We already have the functionality to publish and unpublish a project (though the default for now is "true"). We can just give the user the ability to save a project for further editing or publish it.

**Comment by srish** [comment]
There is now a feature that allows users to share their projects with another user in private mode. However, there are a couple of bugs #470 #454. In any case, this very issue can be considered as resolved.
