### ISSUE TITLE
Share to multiple social media applications

### ISSUE THREAD

**Issue by Vaishnavi-Markunde** [unstructuredstudio/zubhub#377]
Hi, @tuxology  , @NdibeRaymond 
The share button only copies the profile URL to the clipboard right now. I want to implement a share option that will enable the user to share their profile across multiple social media applications.

**Comment by NdibeRaymond** [comment]
@tuxology is this worth pursuing? for me I think the current profile sharing functionality is enough, but I might be wrong.

**Comment by tuxology** [comment]
@Vaishnavi-Markunde and @NdibeRaymond Thanks for this nice suggestion! However, this is being taken care of by #384 They've already worked on UX and other features related to sharing. Closing this one!
