### ISSUE TITLE
Add unit tests for Authentication

### ISSUE THREAD

**Issue by khabdrick** [unstructuredstudio/zubhub#394]
## Description
Writing unit tests for views for authentication of creators. The views that will be worked on are `AuthUserAPIView`, `AccountStatusAPIView`, `UserProfileAPIView`, `RegisterCreatorAPIView`.

## Learning objectives

- These unit tests will help reduce regression as we make further contributions

subset of #290

**Comment by khabdrick** [comment]
I'd like to work on this. What do you guys think, can I go ahead?
@tuxology @NdibeRaymond

**Comment by khabdrick** [comment]
Any updates on this please?

**Comment by tuxology** [comment]
Yes, @khabdrick These are stable and good targets for API tests :+1:
