### ISSUE TITLE
`AccountStatusAPIView` status code inconsistency

### ISSUE THREAD

**Issue by khabdrick** [unstructuredstudio/zubhub#401]
**Describe the bug**
The status code when the user is authenticated is the same as when the user is unauthenticated. I am thinking unauthenticated users should return 404 instead?
**Screenshots**
![2022-04-14_21-04](https://user-images.githubusercontent.com/57852546/163467481-48d0ae91-1a05-4d73-be27-bc371c183336.png)

**Comment by NdibeRaymond** [comment]
Hello @khabdrick, This should be left as it is. It can introduce unintended bugs if changed without making necessary changes to the frontend. The status code here is suitable for it's usecase on the frontend.
