### ISSUE TITLE
Add Pending changes to .gitignore file

### ISSUE THREAD

**Issue by godsakani** [unstructuredstudio/zubhub#408]
When project is clone and the various containers are initialized , it generate a lot of pending changes that need to be added.
possible solution: 
move pending changes to .gitignore file to avoid pending changes.

![chan](https://user-images.githubusercontent.com/70459251/163732574-c2604d53-19d6-42ab-8a08-1933ecec5ca5.png)

**Comment by Deepthi562** [comment]
@godsakani, I would like to work on this. Please assign and give more insights. Thank you.

**Comment by godsakani** [comment]
> @godsakani, I would like to work on this. Please assign and give more insights. Thank you.

Ok @Deepthi562

**Comment by tuxology** [comment]
@godsakani Would you like to create the gitignore and add the relevant files in it?

**Comment by godsakani** [comment]
> @godsakani Would you like to create the gitignore and add the relevant files in it?

Yes @tuxology

**Comment by godsakani** [comment]
Hello @tuxology  
Am closing this issue because I noticed @NdibeRaymond  already work on this issue some months ago. 
you can check it out here issue #7
