### ISSUE TITLE
Create Recommended Projects Endpoint

### ISSUE THREAD

**Issue by ghost** [unstructuredstudio/zubhub#417]
## Description

Create an endpoint that will return recommended projects for a certain project. 

## Learning objectives

- Django REST Framework

## Todo

- [ ] Determine the heuristic to use
- [ ] Add endpoint that will use a project ID to generate recommended projects 

## Helpful Links
- Notion Page on Recommendation Heuristic - https://www.notion.so/h4iuiuc/fa3efb7a564348e1acd98c80f621a943?v=da708e7029c04ffa8c334456ca8610e9&p=98ed7386f13c4524b21f9238127cab83

**Comment by souad988** [comment]
Hi @ajain1921  i would like to work on this issue would you please assign it to me

**Comment by tuxology** [comment]
@souad988 Please ignore issues labeled as `h41`

**Comment by souad988** [comment]
> @souad988 Please ignore issues labeled as `h41`

ah! ok thanks for letting me know @tuxology

**Comment by tuxology** [comment]
@ajain1921 Are we on track for this or should we wait more? I see that this is linked to the fronted parts #418 and #421 and is being attempted in #458. Is this ready for merging or we need more work here?

**Comment by Oluwayhemisi** [comment]
@tuxology I would like to work on this project, can you assign it to me?

**Comment by skynette** [comment]
Hi @srish @khallow7 @tuxology . I'm an outreachy applicant, and so excited to make my first contribution to this project. Could you please assign this task to me if Its still open

**Comment by tuxology** [comment]
@Oluwayhemisi I am assigning this to you. Please get back in a day and let me know if you have begin work on this. See my previous comment for more context on this

**Comment by Oluwayhemisi** [comment]
@tuxology thank you for assigning it to me. Yes I've started working on it, I should update you about my progress before the end of the day.

**Comment by iamhks** [comment]
@Oluwayhemisi Are you still working on this issue?

**Comment by Oluwayhemisi** [comment]
@iamhks Yes but I've not been able to run the backend, i need requirements.txt or dependency to install the packages for the backend because all the classes are shoeing error and is making my work slow.

**Comment by iamhks** [comment]
@Oluwayhemisi 
<img width="441" alt="Screenshot 2023-03-21 at 00 33 55" src="https://user-images.githubusercontent.com/43777817/226440599-61eccc43-2908-4f88-af86-bad762ea8254.png">
Here are available requirements.txt. But simply running the `make init` and `make start` usually does the job

**Comment by Oluwayhemisi** [comment]
@iamhks thank you

**Comment by Oluwayhemisi** [comment]
@iamhks 
![projects](https://user-images.githubusercontent.com/99804239/226466624-b70b21d0-e71e-4478-92e4-c6d730adaebe.jpg)

**Comment by Oluwayhemisi** [comment]
Still complaining about the projects, that i should install the package projects,i'm still getting error
