### ISSUE TITLE
Search autocomplete should bold query within results

### ISSUE THREAD

**Issue by AndrewLester** [unstructuredstudio/zubhub#420]
**Describe the bug**
The search autocomplete is displaying items that don't start with the query, but contain it as well. This is unintended, and is a bug that I expected the material ui autocomplete component to take care of.

**To Reproduce**

1. Go to [https://zubhub.unstructured.studio/](https://zubhub.unstructured.studio/)
2. Click on the search bar
3. Select creator searching
4. Type in "par"
5. Note the invalid autocompletes

**Expected behavior**
Only options that *start* with the search query are displayed.

**Screenshots**
<img width="719" alt="image" src="https://user-images.githubusercontent.com/23221268/163903159-96b1551c-a76c-4904-b400-3a1ae4a39742.png">

**Comment by khabdrick** [comment]
I would like to work on this. I will like it be assigned to me?

**Comment by Deepthi562** [comment]
@AndrewLester, I would like to work on this. Please assign. Thank you.

**Comment by tuxology** [comment]
@AndrewLester I'm just wondering isn't the goal of the search algorithm you used to look for n-grams in the text anywhere and not just the start? 

### Example Case
If the creator name is `dreamsinparadise` and as a user I just remember someone who had `paradise` in their name, I would just start searching for `para..` and should then find `dreamsinparadise` in the results. Hence this looks like a non-issue to me. What do you think? Are there other cases where this type of usage looks unintended?

**Comment by AndrewLester** [comment]
> @AndrewLester I'm just wondering isn't the goal of the search algorithm you used to look for n-grams in the text anywhere and not just the start?
> 
> ### Example Case
> If the creator name is `dreamsinparadise` and as a user I just remember someone who had `paradise` in their name, I would just start searching for `para..` and should then find `dreamsinparadise` in the results. Hence this looks like a non-issue to me. What do you think? Are there other cases where this type of usage looks unintended?

You bring up a good point @tuxology . The only reason I made this issue was that I think our original plan was to avoid showing results where some word didn't start with the query. The trigram searching was mainly applied because the standard Django search doesn't have that kind of "part of word" matching.

I agree having the search works for these cases is beneficial as you said, but I would support having the user's query be bolded in the results in these cases too. Since my original implementation didn't anticipate these results, they don't have bold in them. Would you support renaming this issue and focusing it on the bolding?

**Comment by tuxology** [comment]
> Would you support renaming this issue and focusing it on the bolding?

Yes, sounds good @AndrewLester Lets focus on bolding the part of word :+1:

**Comment by tuxology** [comment]
Also, lets give @khabdrick a chance to fix this in case you have not already started @AndrewLester?

**Comment by Deepthi562** [comment]
@tuxology I see that the text is already appearing in bold. Correct me if I misunderstood something. Thank you.
![pic4](https://user-images.githubusercontent.com/71760959/164508261-900e2e9a-827a-4dab-85c9-03ee65708e46.

Kindly let me know if I can work on this or any issue, I am interested in this. Thank you.

**Comment by Deepthi562** [comment]
@tuxology I see that the text is already appearing in bold. Correct me if I misunderstood something. Thank you.

![pic4](https://user-images.githubusercontent.com/71760959/164508696-a0dcfac5-aedb-42d2-b9ad-738f40eb3957.png)


Kindly let me know if I can work on this or any issue, I am interested in this. Thank you.

**Comment by khabdrick** [comment]
@AndrewLester what branch can I pull to have this autocomplete patch
Plus @Deepthi562 is right, it boldens in result (on the live web app)

**Comment by AndrewLester** [comment]
> @AndrewLester what branch can I pull to have this autocomplete patch
> Plus @Deepthi562 is right, it boldens in result (on the live web app)

You should be able to find the most recent autocomplete code on master.

Also, the specific bolding issue comes from the search query being strictly within a word of the search results main text. See the image example in my issue description.
