### ISSUE TITLE
Footer alignment error

### ISSUE THREAD

**Issue by singhavs** [unstructuredstudio/zubhub#423]
## Description
**Problem**
The alignment of Footer is not in centre

![before](https://user-images.githubusercontent.com/67657066/164244520-71529195-d93c-49e6-b462-199d388b85f3.png)

**Comment by singhavs** [comment]
Hey! @NdibeRaymond  can i work on this issue?

**Comment by tuxology** [comment]
@asaayushisingh This looks OK to me :thinking: . Are there other examples in other websites where footer text (if too much) is generally aligned to center in mobile views?  @NdibeRaymond What do you think?

**Comment by srish** [comment]
I am closing the PR and the issue for now as there is no further progress made. Further in my personal opinion concern raised in the issue is not entirely valid or urgent.
