### ISSUE TITLE
Create Unpublished Project Modal

### ISSUE THREAD

**Issue by ghost** [unstructuredstudio/zubhub#427]
## Description

Add Unpublished Project Modal

Context: When a project is unpublished, this modal will indicate that and provide reasoning for why it was unpublished. The user will then know what needs to be changed so they can republish it.  

## Learning objectives

- React
- CSS
- MUI

## Todo

- Add modal with reasons
- Trigger modal open upon project page open
- Add "Unpublished" tag that also triggers modal open

## Useful links

- https://www.figma.com/file/jRQdwIwXdgmXEe5L0XLgno/ZubHub?node-id=528%3A3528

**Comment by Deepthi562** [comment]
Hi @ajain1921, the link is not redirecting
![pic5](https://user-images.githubusercontent.com/71760959/164511431-e5242da5-7260-4a49-940c-c30c775d4b95.png)

Please let me know how to get started with this, as I am a newbie and willing to work on this.
