### ISSUE TITLE
Web Sharing Bugs

### ISSUE THREAD

**Issue by ghost** [unstructuredstudio/zubhub#434]
**Describe the bug**

- The WhatsApp and Facebook buttons should redirect to a new tab or open up a new smaller window like `react-share` does
- Copying link isn't working

**Comment by Deepthi562** [comment]
@ajain1921 I would like to work on this. Could you please assign it? Also, where are these Whatsapp and Facebook buttons you are refereeing to? I can only see the "contact us" option.
![pic10](https://user-images.githubusercontent.com/71760959/164548418-31e01076-e81b-48ed-9540-1000ea8b908c.png)
