### ISSUE TITLE
Navigation buttons on the caraousel images.

### ISSUE THREAD

**Issue by Deepanshu039** [unstructuredstudio/zubhub#435]
Left-right navigation buttons can be added in the carousel mode using which user can easily navigate between images. This functionality reduces the effort to preview images in a project and also quick navigation can be done using left-right button.

![Screenshot (88)](https://user-images.githubusercontent.com/92849065/164533537-bdf74da2-8872-4307-8c84-5cdf6d0a0a87.png)

two left-right buttons can be attached over the images itself when in PREVIEW mode so that user do not need to press back button again and select new image from there.
Using the buttons over the image next or previous image can be previewed.

**Comment by Deepanshu039** [comment]
greetings @srish  @tuxology  ,I would like to work on this feature.

**Comment by Deepthi562** [comment]
@Deepanshu039 this is a good one!

**Comment by srish** [comment]
@Deepanshu039 Thank you for filing the issue! I'm a bit wondering the navigation buttons that you are referring to work as intended. Did you try clicking on the buttons annotated in the screenshot below:

![Screen Shot 2022-04-21 at 3 13 48 PM](https://user-images.githubusercontent.com/288353/164560457-13d26b8e-2ffb-4a21-8277-41b654b1531e.png)

**Comment by Deepanshu039** [comment]
> @Deepanshu039 Thank you for filing the issue! I'm a bit wondering the navigation buttons that you are referring to work as intended. Did you try clicking on the buttons annotated in the screenshot below:
> 
> ![Screen Shot 2022-04-21 at 3 13 48 PM](https://user-images.githubusercontent.com/288353/164560457-13d26b8e-2ffb-4a21-8277-41b654b1531e.png)


@srish 
the navigation buttons you are referring works only when a image is not in preview mode.
In preview mode(refer my screenshot) you cannot click on those buttons(navigation left-right) in a single click, first you have to close the image(from preview mode) and then buttons can be clicked.

My proposal is to add the buttons itself in preview mode of images(refer my screenshot), so that navigation(prev-next image) can be possible from there itself.

**Comment by tuxology** [comment]
@Deepanshu039 This is a good one. Do you want me to assign you? we can try by using similar left-right buttons (not so big though) as we currently have on the "carousel". We also need an explicit red button with a cross (imagine :red_circle: but with a white cross) to close the image viewer as well. We can place it on corner of the image.

**Comment by alicendeh** [comment]
Can I work on this please?
@tuxology

**Comment by Ammy198488** [comment]
Hello. I am an outreachy participant, I would like to work on this.

**Comment by psalmuelle** [comment]
Hello @tuxology , I noticed this issue has not been worked upon, I will like to take it up. Kindly assign it to me

**Comment by ferindesigns** [comment]
Hello @tuxology. I would like to work on this issue. Thank you.

**Comment by psalmuelle** [comment]
My progress so far!
I realized a library was used to create the carousels, and only the image URL was provided for the preview when a user preview an image. I have been able to create a carousel for the preview. I am currently working on optimizing my code and testing what I have done

**Comment by psalmuelle** [comment]
https://user-images.githubusercontent.com/81099447/223986359-4c51d419-ceec-40ae-98a4-69714d2e9f94.mp4


This is a video of the new feature!
Users can now see all images in preview mode using the previous and next buttons. I also added a close button to improve user experience.

**Comment by psalmuelle** [comment]
I also made sure it is mobile responsive.
![Screenshot 2023-03-09 112155](https://user-images.githubusercontent.com/81099447/223995262-7be52db8-c03b-468b-95d2-b40cb24f826e.jpg)

**Comment by psalmuelle** [comment]
The UI of the preview images has been improved!
The position of the cancel button changed, the arrows are now more visible and the preview image is now bigger!
![correction](https://user-images.githubusercontent.com/81099447/224488343-c3e2837c-322b-430f-8130-cd9665b59ab5.jpg)

![323](https://user-images.githubusercontent.com/81099447/224488355-501ceacf-33ed-4c15-9104-0145e2c68232.jpg)

![22](https://user-images.githubusercontent.com/81099447/224488362-3a0bdfd0-e5c1-421c-b111-6cd86806ecce.jpg)

**Comment by yokwejuste** [comment]
@srish @tuxology , if this is still opened, I'll like to be on this while I'm familiarizing myself with the project

**Comment by srish** [comment]
Feel free to add a PR without task assignment :)

**Comment by yokwejuste** [comment]
> Feel free to add a PR without task assignment :)

Sure,

Thanks !!!

**Comment by Stephxdesigns** [comment]
Hello @srish @tuxology I came up with designs and I prototyped the interactions for this issue and I'm currently working with a developer to create a PR. 
Please let me know your thoughts so that feedback can be implemented accordingly.
Thank you 
![Screenshot_20231005-154246](https://github.com/unstructuredstudio/zubhub/assets/136924367/8bf7f0de-0cec-435b-9503-7a000f4cb9cc)
![Screenshot_20231005-154041](https://github.com/unstructuredstudio/zubhub/assets/136924367/08d70acd-ce89-4d3d-9a6e-c297282afc25)

**Comment by Stephxdesigns** [comment]
@srish @tuxology This is the prototype of the interaction. I maintained the image slider interaction already on the zubhub website and came up with a new interaction and design for previewing the images

https://github.com/unstructuredstudio/zubhub/assets/136924367/3c8beb0a-64d5-4d69-8f8f-5f72bd1500af

https://www.figma.com/proto/p41jr4nKV6pzN6drpLKqqB/Untitled?page-id=0%3A1&type=design&node-id=1-408&viewport=71%2C61%2C0.12&t=36WiPQcW7pxfzBuV-1&scaling=min-zoom&mode=design

**Comment by benndip** [comment]
Hello @tuxology and @srish , please I have opened a PR here:
[https://github.com/unstructuredstudio/zubhub/pull/833](url) that solves this issues. 
Please could you check it out ? I used the designs from @Stephxdesigns 

Thanks!!

**Comment by brrkrmn** [comment]
Hello @tuxology, @srish. I opened #842 for this issue. Can you review my pr?
