### ISSUE TITLE
missing links and broken links in readme.md

### ISSUE THREAD

**Issue by Deepthi562** [unstructuredstudio/zubhub#436]
## Description
1.  In the documentation heading i see that both web server and media server claiming that "below is the interactive documentation of web server API" but it is not mentioned.
![pic6](https://user-images.githubusercontent.com/71760959/164544397-23d97623-d1dd-4f78-905c-0c6e23526b09.png)
![pic7](https://user-images.githubusercontent.com/71760959/164544421-7a9ab825-f773-467c-ade0-692680137ea1.png)
![pic8](https://user-images.githubusercontent.com/71760959/164544780-116eca9a-03d7-49c6-b7b5-06a1f157a447.png)

2. Also the last three links: database er diagram, background-tasks, and reverse-proxy all are redirecting to the same page attached below.

![pic9](https://user-images.githubusercontent.com/71760959/164545027-9c8376f7-4b8f-4d0f-a727-9dbc301550d2.png)

## Todo

We have to attach the correct links and make sure they are redirected to the correct information.

- Todo

## Useful links

- https://github.com/unstructuredstudio/zubhub/blob/master/README.md

If this issue is reviewed, I would like to work on this. Thank you.

**Comment by Deepthi562** [comment]
@tuxology please review this.

**Comment by tuxology** [comment]
I want to create a more larger task related to documentation and will take it upon myself. Hence we are not too keen on making small fixes here and there. @NdibeRaymond Is also working on multiple things currently related to generated documentation (see #392) We'll wait for him to finish this. When that work is finished, then we will do a review of the status of docs and work on fixing them. I'm closing this one for now.
