### ISSUE TITLE
unclear logos

### ISSUE THREAD

**Issue by Deepthi562** [unstructuredstudio/zubhub#437]
## Description
images in the media seem to be camouflaged.

## Todo

I would like to make new logos. I have attached the pictures of the unclear logos.

![pic11](https://user-images.githubusercontent.com/71760959/164552664-131db342-0fc3-42c8-b45f-14c519d535ee.png)
![pic12](https://user-images.githubusercontent.com/71760959/164552673-10775899-eb14-458b-b6a9-ebf12c936fbc.png)
![pic13](https://user-images.githubusercontent.com/71760959/164552685-1e1c3417-fec5-47ac-9c96-ad0dea17b079.png)

- Todo

## Useful links

- https://zubhub.unstructured.studio/projects/create

I would like to work on this. Thank you.

**Comment by tuxology** [comment]
@Deepthi562 These are PNG/SVG images. They are intended to be like this - the camouflage look comes from a standard pattern used to show that there is transparency in images. Read more about PNG here: https://en.wikipedia.org/wiki/Portable_Network_Graphics I'm closing this since its a non-issue.
