### ISSUE TITLE
Clicking on a username in the comment box takes you to the current user's profile page

### ISSUE THREAD

**Issue by srish** [unstructuredstudio/zubhub#438]
**Describe the bug**
If you click on a username in the comment box, it will take you to the current user's profile page. Ideally, it should take you to the user's profile whose avatar or username is clicked.

**To Reproduce**

1. Visit the following project: https://zubhub.unstructured.studio/projects/61045c12-6eae-4678-abda-4f62161a2a8a
2. Scroll to the comments section
3. Click on the username or avatar in a comment box
4. Notice that you are redirected to your own profile page

**Expected behavior**
Ideally, you were redirected to the clicked user's profile page.

![Screen Shot 2022-04-21 at 3 31 55 PM](https://user-images.githubusercontent.com/288353/164562450-17440f84-029d-4262-abc9-dc8c5ce0e190.png)

**Comment by Deepthi562** [comment]
@srish I was looking into the code and found that the href statement for the person commenting is missing., only the image href is present.  Also, after clicking the commenting person's name, the page is not going back to the previous page. I am adding the relevant screenshots. Kindly correct me if I am wrong.

![pic16](https://user-images.githubusercontent.com/71760959/164649861-5a258c5e-686c-4034-9b64-9e6162422dca.png)

Thank you.

**Comment by tuxology** [comment]
Yes, that could be the issue @Deepthi562 However, you would need to make the changes in the relevant JSX files that populate the page. Do you want to work on this one?

**Comment by Deepthi562** [comment]
@tuxology, yes, I would like to work on this.

**Comment by Ammy198488** [comment]
I would like to work on this.

**Comment by cherish2003** [comment]
Hello @srish  I am an Outreachy applicant and I would love to work 
on this issue.

**Comment by ipriyanshi1708** [comment]
Hi @srish and @tuxology , I am an Outreachy applicant and I would love to solve this issue. Please assign it to me.
