### ISSUE TITLE
Text changes to "publish option" field in "create" form 

### ISSUE THREAD

**Issue by srish** [unstructuredstudio/zubhub#440]
Currently, the last option in the "create" project form has a confusing language. 

![Screen Shot 2022-04-21 at 5 44 54 PM](https://user-images.githubusercontent.com/288353/164575408-5396ba4a-ae15-44bb-be86-944ee280bafd.png)

How about we change "What publish option do you want to set for this project? " to "Ready to publish your project?"

And change the help text from  "Think about your target audience. Should this project be visible to all creators?, authenticated creators?, or do you want to provide the usernames of creators this project should be visible to?" to "Choose an option from the dropdown below".

Also change "Authenticated Creators" to "ZubHub Users"

**Comment by Francoise02** [comment]
I would like to work on this issue @srish

**Comment by godsakani** [comment]
> Currently, the last option in the "create" project form has a confusing language.
> 
> ![Screen Shot 2022-04-21 at 5 44 54 PM](https://user-images.githubusercontent.com/288353/164575408-5396ba4a-ae15-44bb-be86-944ee280bafd.png)
> 
> How about we change "What publish option do you want to set for this project? " to "Ready to publish your project?"
> 
> And change the help text from "Think about your target audience. Should this project be visible to all creators?, authenticated creators?, or do you want to provide the usernames of creators this project should be visible to?" to "Choose an option from the dropdown below".
> 
> Also change "Authenticated Creators" to "ZubHub Users"

Hello @srish  I wish to work on this issue

**Comment by srish** [comment]
Ahha, my bad. I didn't know that there is an ongoing discussion to redesigning the "publish option" field in the form. @tuxology pointed me to a related issue and PR https://github.com/unstructuredstudio/zubhub/issues/334, https://github.com/unstructuredstudio/zubhub/pull/336. So, I would say that this very issue is currently not valid.

**Comment by godsakani** [comment]
@srish @kamthamc @tuxology 

Please I need help
I Am unable to locate the HTML file. I mean the content of the front end.
I notice is rendered from the backend and have searched for it but am unable to locate it.
please can someone help me with directives I will be grateful

**Comment by kamthamc** [comment]
Is this what you are looking for?

https://github.com/unstructuredstudio/zubhub/blob/ea32962fee39aee12c2fef4e0e8f23ef71ba3c36/zubhub_frontend/zubhub/public/locales/en/translation.json#L359

**Comment by godsakani** [comment]
> Is this what you are looking for?
> 
> https://github.com/unstructuredstudio/zubhub/blob/ea32962fee39aee12c2fef4e0e8f23ef71ba3c36/zubhub_frontend/zubhub/public/locales/en/translation.json#L359

yes @kamthamc

**Comment by godsakani** [comment]
> 



> > Is this what you are looking for?
> > https://github.com/unstructuredstudio/zubhub/blob/ea32962fee39aee12c2fef4e0e8f23ef71ba3c36/zubhub_frontend/zubhub/public/locales/en/translation.json#L359
> 
> yes @kamthamc

Thank you @kamthamc
