### ISSUE TITLE
UX enhancements to "publish option" in "create" form 

### ISSUE THREAD

**Issue by srish** [unstructuredstudio/zubhub#441]
First, some text changes are needed in the "publish option" field, issue is filed here: https://github.com/unstructuredstudio/zubhub/issues/440. 

Second comes UX improvements, which have primarily to do with options in the dropdown. I think the four options are confusing and not entirely related to publishing. 

I think the dropdown should only have two options, "Public" and "ZubHub Users". "Draft" can be moved out of this dropdown, as saving the project in draft mode means the changes are still in progress and not published. So either "Draft" should be named "Private" or appear next to the "Create Project" button as "Save as draft" and "Create Project" can be changed to "Publish Project" or "Publish Changes".

Then, the "Preview" option in its current shape and form is very confusing. It doesn't convey its intended purpose, which is that it allows anyone to share their project with other users for preview. One idea - this option can be offered as soon as the project is saved below the create form itself, just like how blogging platforms like Ghost allow.

![Screen Shot 2022-04-21 at 5 44 54 PM](https://user-images.githubusercontent.com/288353/164576175-8c647802-7e15-4238-83f5-38aa696d8358.png)

**Comment by godsakani** [comment]
> First, some text changes are needed in the "publish option" field, issue is filed here: #440.
> 
> Second comes UX improvements, which have primarily to do with options in the dropdown. I think the four options are confusing and not entirely related to publishing.
> 
> I think the dropdown should only have two options, "Public" and "ZubHub Users". "Draft" can be moved out of this dropdown, as saving the project in draft mode means the changes are still in progress and not published. So either "Draft" should be named "Private" or appear next to the "Create Project" button as "Save as draft" and "Create Project" can be changed to "Publish Project" or "Publish Changes".
> 
> Then, the "Preview" option in its current shape and form is very confusing. It doesn't convey its intended purpose, which is that it allows anyone to share their project with other users for preview. One idea - this option can be offered as soon as the project is saved below the create form itself, just like how blogging platforms like Ghost allow.
> 
> ![Screen Shot 2022-04-21 at 5 44 54 PM](https://user-images.githubusercontent.com/288353/164576175-8c647802-7e15-4238-83f5-38aa696d8358.png)

Hello @srish  I wish to work on this issue

**Comment by srish** [comment]
Ahha, my bad. I didn't know that there is an ongoing discussion to redesigning the "publish option" field in the form. @tuxology pointed me to a related issue and PR https://github.com/unstructuredstudio/zubhub/issues/334, https://github.com/unstructuredstudio/zubhub/pull/336. So, I would say that this very issue is currently not valid.

**Comment by srish** [comment]
I am re-opening this issue! 

<img width="933" alt="Screen Shot 2022-05-15 at 7 44 16 PM" src="https://user-images.githubusercontent.com/288353/168511186-aba654d9-1e9a-4c6a-a327-a027ad3762f5.png">

Some categories are not immediately clear right now, for example, what is the difference between everyone and all zubhub users. I think we could use the following options and they should be in a different order: more private to less private option. 

- Only me
- With a few friends on ZubHub
- All ZubHub users
- Everyone - users and non-users of ZubHub

**Comment by godsakani** [comment]
> I am re-opening this issue!
> 
> <img alt="Screen Shot 2022-05-15 at 7 44 16 PM" width="933" src="https://user-images.githubusercontent.com/288353/168511186-aba654d9-1e9a-4c6a-a327-a027ad3762f5.png">
> 
> Some categories are not immediately clear right now, for example, what is the difference between everyone and all zubhub users. I think we could use the following options and they should be in a different order: more private to less private option.
> 
> * Only me
> * With a few friends on ZubHub
> * All ZubHub users
> * Everyone - users and non-users of ZubHub

Hello @srish  I wish to work on it

**Comment by srish** [comment]
@godsakani Okay, please feel free to submit a PR. I believe this only requires text and order changes to the options. Should be fairly easy to do :)

**Comment by godsakani** [comment]
> @godsakani Okay, please feel free to submit a PR. I believe this only requires text and order changes to the options. Should be fairly easy to do :)

Yes @srish 
I wish ask if the first changes you requested up , am I to maintain it ?

**Comment by godsakani** [comment]
> First, some text changes are needed in the "publish option" field, issue is filed here: #440.
> 
> Second comes UX improvements, which have primarily to do with options in the dropdown. I think the four options are confusing and not entirely related to publishing.
> 
> I think the dropdown should only have two options, "Public" and "ZubHub Users". "Draft" can be moved out of this dropdown, as saving the project in draft mode means the changes are still in progress and not published. So either "Draft" should be named "Private" or appear next to the "Create Project" button as "Save as draft" and "Create Project" can be changed to "Publish Project" or "Publish Changes".
> 
> Then, the "Preview" option in its current shape and form is very confusing. It doesn't convey its intended purpose, which is that it allows anyone to share their project with other users for preview. One idea - this option can be offered as soon as the project is saved below the create form itself, just like how blogging platforms like Ghost allow.
> 
> ![Screen Shot 2022-04-21 at 5 44 54 PM](https://user-images.githubusercontent.com/288353/164576175-8c647802-7e15-4238-83f5-38aa696d8358.png)

 Hello @srish 
am asking about this changes here?

**Comment by godsakani** [comment]
Hello @srish please check if these changes are fine so I can open a PR on it.
![fix](https://user-images.githubusercontent.com/70459251/168610866-78533002-da8e-4e22-9726-34a742d42fd0.png)

**Comment by tuxology** [comment]
@srish @godsakani I think we should rethink this a bit and be a bit clear about what we want before PR is worked upon. Also be aware that this option will change again when the Draft mode PR with custom Draft button is worked upon. Here is what I would comment on [this comment](https://github.com/unstructuredstudio/zubhub/issues/441#issuecomment-1127159576):

- The ordering is good. We should also have "Everyone" as default selected value
- The reason "All ZubHub Users" was chosen was because to be a "ZubHub User" the expectation is that you are going to create a project for which you will create an account and hence fulfil the criteria that you are authenticated user and not just browsing ZubHub without an account. For public mode ZubHub this is not really needed - but since we wanted this fix very quickly, we just kept it as it is. In later stages we will even remove this for public mode ZubHub.
- Current "Everyone - users and non-users of ZubHub" is confusing. We can replace it by "Everyone on the web"
- "With a few friends on ZubHub" is also not correct. The question is "Who can see your project after you create it?". The answer should be a noun. 

I propose the following:

-----  

(8) Who all can see your project after you create it?
If you are still working on the project and are unsure if you want to publish this right away, select "Only me".

- Only me
- Only a few ZubHub Users
- All ZubHub Users
- Everyone on the web

-----
 The last option above gets selected. Lets resolve this quickly because this is an interim fix -  when the Draft mode UX changes will be needed very shortly, this will be changed.

**Comment by godsakani** [comment]
> 

@tuxology 
 I should change the oder?

**Comment by tuxology** [comment]
> @tuxology 
>  I should change the oder?

See my previous comment. We should discuss this a bit more before we send a PR (for example, changing order) . Let's wait for @srish to comment. If you have something to add, please do.

**Comment by godsakani** [comment]
> > @tuxology
> > I should change the oder?
> 
> See my previous comment. We should discuss this a bit more before we send a PR (for example, changing order) . Let's wait for @srish to comment. If you have something to add, please do.

ok, sir.
thank you

was also thinking if we can use just:
All ZubHub Users
Everyone on the web

since the other ones almost sound the same

**Comment by srish** [comment]
Looks like @tuxology suggested the following options: 
> 
> * Only me
> * Only a few ZubHub Users
> * All ZubHub Users
> * Everyone on the web

I am okay with the order now. Still wondering about "Only a few ZubHub users" and "Everyone on the web." It is not immediately clear what they mean. For example, would children immediately understand what web means? Maybe internet is a better world in this context? I don't have alternative suggestions myself for "Only a few ZubHub users". So unless anyone has good ideas, we keep it:)

**Comment by tuxology** [comment]
Maybe we can say, "Registered ZubHub users" and "Everyone on the internet"? Would that be better?

**Comment by srish** [comment]
Yes, that makes a lot of sense to me.

**Comment by godsakani** [comment]
> Maybe we can say, "Registered ZubHub users" and "Everyone on the internet"? Would that be better?

So we have 
1. Only me
2. Registered ZubHub Users
3.  All ZubHub users
4. Everyone on the internet

Correct me if am wrong  @srish  @tuxology

**Comment by godsakani** [comment]
I have a question @srish  and @tuxology 

Please what is the difference between Registered ZubHub users and All ZubHub Users?

**Comment by tuxology** [comment]
@godsakani Here is the correct order and their meaning:

1. Only me
2. Only a few ZubHub users
3. All registered ZubHub users
4. Everyone on the internet

Number 1 & 4 are self explanatory. 2 means only a few of the registered users on Zubhub. This mode is meant to share your project with only a few friends/educators and not make it public to everyone. Number 3 is everyone who is currently registered on Zubhub. Distinction between 3 and 4 is more relevant if you run Zubhub in private mode (which is meant for private communities that don't want all projects to be public by default)

I think you can now go ahead and create a PR 👍

**Comment by godsakani** [comment]
> @godsakani Here is the correct order and their meaning:
> 
> 1. Only me
> 2. Only a few ZubHub users
> 3. All registered ZubHub users
> 4. Everyone on the internet
> 
> Number 1 & 4 are self explanatory. 2 means only a few of the registered users on Zubhub. This mode is meant to share your project with only a few friends/educators and not make it public to everyone. Number 3 is everyone who is currently registered on Zubhub. Distinction between 3 and 4 is more relevant if you run Zubhub in private mode (which is meant for private communities that don't want all projects to be public by default)
> 
> I think you can now go ahead and create a PR 👍

 ok, @tuxology  thanks a lot for the explanation.
One last question am I to follow the order as mentioned above like the default should be only me and the rest follow the same?

**Comment by tuxology** [comment]
Default should be "Everyone on the internet "

**Comment by godsakani** [comment]
> Default should be "Everyone on the internet "

ok Thank you sir

**Comment by godsakani** [comment]
Hello @tuxology , @srish 
Are this changes ok? so I can create the PR

![chan](https://user-images.githubusercontent.com/70459251/168838366-1a87e123-d27e-40da-b409-cbbd1cca280c.png)
