### ISSUE TITLE
Mkdocs docs generation job is broken

### ISSUE THREAD

**Issue by tuxology** [unstructuredstudio/zubhub#442]
**Describe the bug**
We created a Ci job that build docs using Mkdocs as part of #392 Looking at the recent commits, it seems the build job is broken because mkdocs.yaml is not there. We should fix this.  

**To Reproduce**

1. Go to https://github.com/unstructuredstudio/zubhub/runs/6108082194?check_suite_focus=true
2. See that this job fails

**Expected behavior**
mkdocs.yml config is missing and should be present at correct location

**Comment by Deepthi562** [comment]
@tuxology i would like to work on this. Thank you.

**Comment by NdibeRaymond** [comment]
This is a known issue @tuxology . There are many things wrong with the docs right now that I'd love to fix myself. I already have a PR in my local machine that potentially fixes this any many of the other minor problems in our docs right now. We should close this task (or edit it?) so we can more accurately describe what is wrong and whats needs to be done.

**Comment by tuxology** [comment]
Ok, I'm closing this since you already have a PR which fixes other parts.
