### ISSUE TITLE
Tag autocomplete returning inaccurate result

### ISSUE THREAD

**Issue by abetco** [unstructuredstudio/zubhub#445]
**Describe the bug**
Entering "hello" for the tags section of creating a projects gives the autocomplete result of "storytelling". It is unknown why this behavior exists and also if there is a more general issue with the tag autocomplete in the create project form. Requires more investigation.

**Screenshots**
![image](https://user-images.githubusercontent.com/40071557/164842623-84f07719-c7d6-443b-bd69-64e25beff214.png)

**Comment by camouflagedName** [comment]
Hi, I think I have a solution for this. On the backend, there is an autocomplete function that measures the similarity between the queried tag and tags already in the db. The similarity threshold seems to have been set as low as possible. Raising this seems to decrease inaccurate results.

The fix requires changing a value from 0.01 to a larger value such as 0.25 or 0.3 in projects/views.py. Django docs seem to suggest 0.3, but I haven't researched this enough to know more than that. I'm happy to make the fix or give directions on how to fix it.

**Comment by Vic-Orlands** [comment]
Hello @srish @tuxology  I went over the site and realized that this issue has not been fixed. I would like to work on it. Thank you

**Comment by camouflagedName** [comment]
I actually provided a solution several months back (see comment above) with a pull request to have it reviewed but have not seen any updates regarding this.

**Comment by tuxology** [comment]
@camouflagedName Uh oh! So sorry, I think I missed this. I've approved this, will merge it soon. I haven't tested it, but logically your approach looks correct!

**Comment by skynette** [comment]
Is this still open?
