### ISSUE TITLE
Preview and Draft Mode Visibility

### ISSUE THREAD

**Issue by ghost** [unstructuredstudio/zubhub#454]
**Describe the bug**
When a user creates a project in Preview/Draft mode, other users can still see the project by visiting the user's profile or  using the search bar.  

**To Reproduce**

The easiest way to test this is by having two accounts.
1. Create a project in Draft or Preview Mode with Account A
2. Visit Account A's profile with Account B.
3. You should be able to see Account A's projects that should not be visible to Account B
4. You should be able to use the search bar with Account B to find Account A's private projects.

**Expected behavior**
When a project is created with Draft mode it should only be visible to the author. When a project is created with Preview mode, it should only be visible to the users specified and the author. This means the project should be invisible from the search bar as well as the profile page.

**Comment by tuxology** [comment]
@NdibeRaymond I think we would need your eyes on this as well. This seems to be related to "private mode" so just wanted to keep you in the loop.
