### ISSUE TITLE
Header part is not consistently responsive to different screen sizes.

### ISSUE THREAD

**Issue by Deepanshu039** [unstructuredstudio/zubhub#463]
**Describe the bug**
When the Zubhub main page is subjected to different screen sizes the UI of the header becomes inconsistent.
Different components like create project and search bar tend to overlap each other.

**To Reproduce**

1. Go to  zubhub main page
2. Resize the screen 
3. Observe the UI in different screen sizes

**Expected behavior**
The header should behave consistently with different screen sizes for a better user experience.

**Screenshots**
![Screenshot (106)](https://user-images.githubusercontent.com/92849065/166886941-ad5b45e6-6075-4c18-bfdc-78dcd69236c4.png)

![Screenshot (105)](https://user-images.githubusercontent.com/92849065/166887056-d6f373fb-78e2-4060-bd62-dfe0e63f3719.png)

![Screenshot (104)](https://user-images.githubusercontent.com/92849065/166887149-8a1c404d-71b6-41ce-8668-44f0331ae5b7.png)

![Screenshot (103)](https://user-images.githubusercontent.com/92849065/166887233-e08bf458-5f5f-4182-acf3-4d90cc63cd2d.png)

![Screenshot (102)](https://user-images.githubusercontent.com/92849065/166887598-42811098-51b0-42a5-95f4-6b0a3b111965.png)

**Comment by Ammy198488** [comment]
Hello. I am an outreachy participant, I would like to work on this.

**Comment by IvyJeptoo** [comment]
I would like to work on this issue

**Comment by iamatifmoin** [comment]
@tuxology Please Review.

**Comment by tuxology** [comment]
@iamatifmoin This issue required more than just trivial changes. I had assigned @Ammy198488 already so we'll wait for their PR attempt for a couple of days before reviewing your work. Please take a note of prior assignments.

**Comment by iamatifmoin** [comment]
@tuxology 
Okay. I'll improve my work till then.

**Comment by Ammy198488** [comment]
@tuxology 
Task update: I am done with implementing changes but I'm having issues running my backend.

**Comment by tuxology** [comment]
@Ammy198488 Please take help on community chat and let us know in a day or so. Thanks!

**Comment by Ammy198488** [comment]
@tuxology I have made a pr for this issue.
