### ISSUE TITLE
Failing workflow

### ISSUE THREAD

**Issue by khabdrick** [unstructuredstudio/zubhub#464]
**Describe the bug**
CI workflow is failing because Config file 'mkdocs.yml' is in a different directory (`docs/`).

**Screenshots**
![2022-05-06_10-11](https://user-images.githubusercontent.com/57852546/167103547-fd97241b-9858-4a0f-83dd-34d10ccda372.png)

It wasn't a lot of work so I have already prepared a pr to solve this issue.

**Comment by tuxology** [comment]
Reopened because the PR didn't fix it. Assigning this to myself as this is related to efforts I'll put in https://github.com/unstructuredstudio/zubhub/issues/347

**Comment by tuxology** [comment]
Closing this because its fixed now!
