### ISSUE TITLE
All category options (except 'None') are missing from the dropdown

### ISSUE THREAD

**Issue by srish** [unstructuredstudio/zubhub#474]
In the project creation form, we used to show a bunch of categories from here: https://github.com/unstructuredstudio/zubhub/blob/master/zubhub_backend/zubhub/projects/management/commands/categories.txt for the question "What is the category of your project?". Now these options are gone, and we only see "None" as an option in the dropdown.

**Comment by NdibeRaymond** [comment]
closing because we were unable to reproduce this
