### ISSUE TITLE
Remove the text "Can't play video? Click here" beneath video description

### ISSUE THREAD

**Issue by srish** [unstructuredstudio/zubhub#483]
Remove the text "Can't play video? Click here" that appears beneath the video on the project description page. The reason why we were displaying the text previously was due to a backend issue that has now been resolved.

See the screenshot below.
<img width="200px" src="https://user-images.githubusercontent.com/288353/169745798-ff9acbb5-0561-4a86-a8bc-3755723e99e9.png">

**Comment by mathcodes** [comment]
I can give those button a whirl :)

**Comment by arushi2715** [comment]
Hey @srish I would like to work on this issue.
Could you please assign it to me.

**Comment by srish** [comment]
@arushi2715 done and welcome to our project:)

**Comment by arushi2715** [comment]
Hye @srish!
I wanted to know that is there a test account using which i can login and check the functionalities of the project?
Also, the delete and edit button are available just for the creator of the project? 
If so then do i need to create a project to check the sizes of button?

**Comment by srish** [comment]
@arushi2715 We do not have a test account. You can create one for your use to check the functionalities of the project. And yes creating the project seems like the right way to go about it.

**Comment by iamhks** [comment]
Hi @srish can you please review my PR for this issue?
Let me know if any changes required
