### ISSUE TITLE
Inconsistent wording of terms "sign in"/"log in" and "sign up"

### ISSUE THREAD

**Issue by BemaFisher** [unstructuredstudio/zubhub#488]
**Describe the bug**
Currently, when user needs to sign in/log in or sign up, the wording of terms for signing in or signing up  are inconsistent. For example, when user presses button to share a project, it says the user needs to press "signin" button there is no button named "signin". 

**To Reproduce**

1. Go to Homepage
2. Click on 'share a project'

**Expected behavior**
Use terms sign in/log in and sign up consistently throughout the process. 
<img width="1424" alt="Screen Shot 2022-06-01 at 7 01 44 PM" src="https://user-images.github
<img width="739" alt="Screen Shot 2022-06-01 at 7 02 23 PM" src="https://user-images.githubusercontent.com/43227071/171534361-4ab2ef74-5db0-40b9-860b-8acf417448a5.png">
usercontent.com/43227071/171534330-7dc5a832-7f75-47ec-a979-2535d7d4f78b.png">

**Comment by Krishna841** [comment]
Is this issue closed? I checked on the website and the issue still persists, Can you assign it to me?
![image](https://user-images.githubusercontent.com/65186847/220535261-db91d0e7-b03d-4d9f-af35-517d848cd9ff.png)
We can also add a link taking one to sign up page which also has the option to login in case the user has already registered.

**Comment by Ammy198488** [comment]
Hello @srish @tuxology . I am an outreachy participant, I would like to work on this.

**Comment by klaus139** [comment]
hello, i would like to work on this

**Comment by emmaz12** [comment]
Hi @BemaFisher @srish @tuxology I would be interested in working on this!

**Comment by ferindesigns** [comment]
Hi @srish @tuxology @BemaFisher I would really like to work on this

**Comment by funmbiroyal** [comment]
Hi @srish, I love to work on this. but then I am still somewhat confused about where to start. I saw like four different repository, i don't know which one to clone

**Comment by iamatifmoin** [comment]
Hi @funmbiroyal, you need to fork THIS repository and then clone the fork.

**Comment by iamatifmoin** [comment]
@srish is this issue still open?

**Comment by nourhan-ashraf** [comment]
Hi @srish , I am an outreachy participant and I'd like to work on this issue if it's still open.

**Comment by ipriyanshi1708** [comment]
Hi @srish @tuxology @BemaFisher, I am an outreachy applicant and a react developer and I think I will be able to do this. So, please assign it to me. I would really like to work on this.

Thanks!

**Comment by tuxology** [comment]
@Krishna841 Are you interested in working on this? I also like your idea of adding a (call to action) CTA button for Sign Up page in case user is not logged in and goes to `/create` endpoint (which should not happen since there is no button that takes them there I think 🤔). Let me know here within a day and I will assign this to you.

**Comment by ghost** [comment]
@srish @tuxology I will like to work on this if its open and i will also like to add a social option for the sign up page like "google" to make sign up easier and faster for users

**Comment by ComradeVedant** [comment]
Hey @srish @tuxology I'm an outreach intern applicant and I have a few ideas for this issue. I think this issue can we easily tackled by adding a <sign in> CTA at the error page which redirects the user to the auth. page. I also think the UI could be improved, i don't think we need such a large Oops text (especially on mobile) which with the unavailability of a sign in CTA, could be irritating. Also to clear up the confusion, I think we should just choose one CTA from <sign in> and <sign up> CTA, as they basically perform the same tasks and use them consistently across the entire platform. Also one nice addition would be add <hindi> CTAs as well. One thing that stuck out to me was that while a large volume of content was vernacular, the design is done with an english speaker in mind. I think that is something we could solve for as well.

**Comment by ComradeVedant** [comment]
![sign_in issue#](https://user-images.githubusercontent.com/112879302/224308075-e3e04c10-313b-4b83-b06f-fe4aa73c2a0d.PNG)
![Frame 1](https://user-images.githubusercontent.com/112879302/224308100-5a858a50-f645-4627-bc84-499e7c203727.png)
Here's my attempt to solve this particular problem. That aside I would like to discuss the UX of the landing page itself. Why put a share a project CTA there if someone not signed up can't do that? Are we setting the user for a failure? Won't it be better to have a sign In CTA on the landing page itself? Along with <Share a Project> and <Be our Ambassador>. That way we can communicate the necessity of logging in aswell as the functionalities of the platform. Would be happy this discuss this further. @srish @tuxology

**Comment by Burnleydev1** [comment]
Hello @tuxology, Please can I work  on this issue?
I think I have a good understanding on how to fix it.

**Comment by skynette** [comment]
Hi @srish @khallow7 @tuxology . I'm an outreachy applicant, and so excited to make my first contribution to this project. Could you please assign this task to me?

**Comment by khallow7** [comment]
Oh, @skynette I am an applicant just like yourself. Wait for our mentors to reply to you.
They will let you know what to do.
