### ISSUE TITLE
Disable debug mode from production backend

### ISSUE THREAD

**Issue by tuxology** [unstructuredstudio/zubhub#49]
We know that debug mode is enabled in django - this exposes a lot of internal info about backend when errors are encountered. We need to disable it

**Comment by NdibeRaymond** [comment]
> We know that debug mode is enabled in django - this exposes a lot of internal info about backend when errors are encountered. We need to disable it

This is true. Don't know how that skipped my mind. Changed it now. it only required changing a variable in  production .env file so no need for a PR. Closing now
