### ISSUE TITLE
not able to delete the repository files from my local machine.

### ISSUE THREAD

**Issue by aashimawadhwa** [unstructuredstudio/zubhub#499]
**Describe the bug**
not able to delete the repository files from my local machine , it's duplicating with some malicious files.

**To Reproduce**

1. Go to cloned repository files in your local machine
2. Click on delete
3. Scroll down 

**Expected behavior**
The files should delete with the terminal commands and manana delete option

**Screenshots**
![Screenshot from 2022-06-15 23-39-18](https://user-images.githubusercontent.com/73706697/173895738-0e2eda33-109d-4671-91fe-07b52ecf1394.png)
![Screenshot from 2022-06-15 23-38-58](https://user-images.githubusercontent.com/73706697/173895747-f6957dd9-a4cd-45e2-bbce-3a305fb0636b.png)

**Comment by AnishaSingh0118** [comment]
can i assigned

**Comment by srish** [comment]
Sounds like an issue to do with permissions on local machine not ZubHub
