### ISSUE TITLE
Create activities banner with video carousel.

### ISSUE THREAD

**Issue by souad988** [unstructuredstudio/zubhub#506]
- [x] create the video carousel.
- [x] Add state to current slide of carousel and auto play active slide video.
- [ ] Fix carousel styling for mobile size.
- [ ] Handle different video source types.
- [ ] Fix styling to stick to figma [design](https://www.figma.com/file/jEy3xfgLKa7VGaJgf4Bwmx/create-activity-button?node-id=73%3A121)
- [ ] Add Build this button to redirect the user to activity creation form.

**Comment by srish** [comment]
This task is no more relevant.
