### ISSUE TITLE
Build APIs to fetch total_views_count, total_comments_count, and total_likes_count on the user's profile.

### ISSUE THREAD

**Issue by Deepanshu039** [unstructuredstudio/zubhub#514]
Create a new api that will return total views, total comments, and total likes for all the projects of a user. 
- [ ] create an endpoint and connect it with the corresponding class view
- [ ] create a view to handle the logic
- [ ] create serializer to convert model data into dictionary

**Comment by tuxology** [comment]
Closing this since this has been done as part of #518
