### ISSUE TITLE
Create a new file to return the titles of the badges in particular categories to the user's profile.

### ISSUE THREAD

**Issue by Deepanshu039** [unstructuredstudio/zubhub#517]
Create a separate file that will assign the correct badge_title in a particular category according to the likes_count, views_count, project_count, and comments_count on the user's profile.

**Comment by Deepanshu039** [comment]
A new file has been created to identify which title is applicable in a category with the name DisplayBadges.js.

**Comment by tuxology** [comment]
This has been merged as part of #518. Closing this
