### ISSUE TITLE
Add a prompt / help text in the project description field

### ISSUE THREAD

**Issue by srish** [unstructuredstudio/zubhub#52]
In the project description field, enter a prompt / help text that explains what one can include/ share in their project description.

@srish to give text for prompt to @NdibeRaymond

**Comment by NdibeRaymond** [comment]
@srish can you give an example of what the help text should say?

**Comment by srish** [comment]
@NdibeRaymond You can add this as a the prompt "Tell us something interesting about the project! You can share what it is about, what inspired you to make it, your making process, fun and challenging moments you experienced, etc."

**Comment by srish** [comment]
Also, description field can be slightly longer..
