### ISSUE TITLE
Clap button on user's profile is not working

### ISSUE THREAD

**Issue by Deepanshu039** [unstructuredstudio/zubhub#520]
**Describe the bug**
Clap button(Like Button) on the user's profile is not incrementing the total clap value and showing an error _t.map is not a function_.

**To Reproduce**

1. Go to 'Homepage of website'
2. Click on 'any user's profile '
3. Try clicking clap button on the projects 
4. See error (in the top right corner)

**Expected behavior**
When clicked on clap button the count on clap icon should increase or decrease.

**Screenshots**

![Screenshot (212)](https://user-images.githubusercontent.com/92849065/180567838-9ba5bfa5-59ba-4022-8825-fe8041d1b50d.png)

**Comment by khabdrick** [comment]
Hello @Deepanshu039 , has this been fixed?
I'd like to take it up

**Comment by Deepanshu039** [comment]
hi @khabdrick, you can work on this. Just ask @srish or @tuxology they will assign you the issue : )

**Comment by khabdrick** [comment]
@tuxology can you assign me to this

**Comment by tuxology** [comment]
@khabdrick Sorry this slipped my notifications. Just assigned this to you!

**Comment by Krishna841** [comment]
Hiee, I would like to work on this issue can you assign it to me?

**Comment by iamhks** [comment]
Hi @srish can you please review my PR for this issue?
Let me know if any changes required

**Comment by iamhks** [comment]
> Hiee, I would like to work on this issue can you assign it to me?

Hi @Krishna841 I am so sorry I didn't check the comments before working on this issue, and saw your assignee request only when asking srish to review my PR. Hopefully you don't mind.

**Comment by tuxology** [comment]
@Krishna841 Apologies, we've just begun reviewing the incoming requests. Since @iamhks has attempted the simple fix, we can track this on his PR now
