### ISSUE TITLE
Very long usernames are pushing the tags(creator, staff etc.) from the project display card.

### ISSUE THREAD

**Issue by Deepanshu039** [unstructuredstudio/zubhub#528]
**Describe the bug**
If a user has a very long username then it can push the tag of a user outside the project display card.

**Expected behavior**
The entire tag of a user should be visible on the project card.

Like this:-
![Screenshot (329)](https://user-images.githubusercontent.com/92849065/188283189-484dc391-ecad-4ec3-bd44-f163d0551ac8.png)

**Screenshots**
what is happening right now :- 
![Screenshot (328)_LI](https://user-images.githubusercontent.com/92849065/188283201-aa4d1a8c-edf2-468b-bed0-8d3357df5258.jpg)

![Screenshot (327)_LI](https://user-images.githubusercontent.com/92849065/188283205-21bee02d-b9a6-4130-a62a-192dccf2c1ec.jpg)

**Comment by tuxology** [comment]
A partial attempt to fix this has been made on #367 If someone plans to work on this, that can be a good starting point to review

**Comment by aparna-bhatt** [comment]
I would like to suggest if we can limit the characters of the username between 3 to 25 characters.
Alternatively if we want the username of no limit then we can add  ```...``` at the end of the username while displaying.
Thanks!

**Comment by psalmuelle** [comment]
Hi @tuxology , I would like to work on this issue. I have gone through #367, and I think @aparna-bhatt suggestion is a nice one. We could add `...` to usernames that's greater than, let's say 8 characters. 
Alternatively, we could make the username just below the profile picture. Profile picture and username will be in a column.
Kindly let me know what you think about this.
Thank you!
![WIN_20230222_18_46_28_Pro (2)](https://user-images.githubusercontent.com/81099447/220712515-2063bfd0-cf71-4639-9767-9680fc839f94.jpg)

**Comment by tuxology** [comment]
@psalmuelle We would want more discussion this including more mockups of the cards before we attempt to fix this. Please bring your ideas here or on Discussion tab. We can rearrange the "creator" tag's position as well as username and try to create more high-fidelity mockups. I think that would help

**Comment by yaya-mamoudou** [comment]
Hi @tuxology, I made this figma design to highlight my idea on how we can improve the project card and also to conform with the need to change the look and feel of the zubhub website.
1- The description will be maximum 2 lines and when the content is more than 2 lines we will append some ellipses at the end
2- For the username, the same thing But it's only going to occupy 1 line. If the user hovers over the username, he/she will be able to see the rest of the hidden data on a tooltip
let me know what you think and you can also tell what to change to make it better
<img width="352" alt="image" src="https://user-images.githubusercontent.com/57509871/223213695-00be8291-421b-4ace-ad5b-f015a8460456.png">

**Comment by psalmuelle** [comment]
@tuxology, can we direct UI/UX designers to this issue? They would be helpful because they have a better understanding of user experience than developers as it is their speciality.

**Comment by yaya-mamoudou** [comment]
@tuxology I also made some propositions on the private projects. See image bellow

<img width="722" alt="image" src="https://user-images.githubusercontent.com/57509871/223417792-60949efc-d5c1-4cda-b618-5fc3eaf57abc.png">

**Comment by tuxology** [comment]
@yaya-mamoudou I like the approach in https://github.com/unstructuredstudio/zubhub/issues/528#issuecomment-1458060176 Note that if the username is too long, in addition to using ellipses, lets create a tooltip for now to show fullname. In addition, what happens of the tag is big? What takes precendence - tag chip or username? Or should the pill go to next line? Lets think a bit more about it.

**Comment by yaya-mamoudou** [comment]
> @yaya-mamoudou I like the approach in [#528 (comment)](https://github.com/unstructuredstudio/zubhub/issues/528#issuecomment-1458060176) Note that if the username is too long, in addition to using ellipses, lets create a tooltip for now to show fullname. In addition, what happens of the tag is big? What takes precendence - tag chip or username? Or should the pill go to next line? Lets think a bit more about it.

Thank you for the feedback @tuxology. I think I now see where we are going with this. The card should be flexible. Let me quickly rethink. Thank you

**Comment by darechan** [comment]
> Hi @tuxology, I made this figma design to highlight my idea on how we can improve the project card and also to conform with the need to change the look and feel of the zubhub website. 1- The description will be maximum 2 lines and when the content is more than 2 lines we will append some ellipses at the end 2- For the username, the same thing But it's only going to occupy 1 line. If the user hovers over the username, he/she will be able to see the rest of the hidden data on a tooltip let me know what you think and you can also tell what to change to make it better <img alt="image" width="352" src="https://user-images.githubusercontent.com/57509871/223213695-00be8291-421b-4ace-ad5b-f015a8460456.png">

Lovely Idea

**Comment by yaya-mamoudou** [comment]
Hi @tuxology, below is another proposal for the project card. In this proposal, I also took into consideration the fact that there can be more than one tag.

- 1st Card handles the case when the `username` is too long. In this scenario, the `tag wraps to the next line`. It also highlights how the tag section will be when there is `more than one tag`
- 2nd Card shows the case of a `very long username` and a `single tag`
- 3rd Card shows the case of a `short username` and short `tag name`
- Also, when the username is too long, an `ellipse` is added and when the user hovers over the username, a `tooltip` will appear having the complete username

## Screenshot of Figma design
<img width="1253" alt="image" src="https://user-images.githubusercontent.com/57509871/223826813-d4a4b907-b232-4547-bc40-fa7295067350.png">

**Comment by tuxology** [comment]
@yaya-mamoudou I think think this makes sense to me for now (at least for all common cases). Lets build this and merge. We will improve this in next iteration 👍
