### ISSUE TITLE
Invalid email error when the email seems to be valid

### ISSUE THREAD

**Issue by srish** [unstructuredstudio/zubhub#53]
@srish to send a DM to @NdibeRaymond and @tuxology with details.

**Comment by NdibeRaymond** [comment]
Hello @srish , I can't reproduce this bug. can you elaborate more on how to reproduce it so I can submit a fix?

**Comment by srish** [comment]
It seems like there is an issue with the signup process. I tried again today:
![Screen Shot 2021-01-10 at 8 11 10 PM](https://user-images.githubusercontent.com/288353/104125959-01707a80-5380-11eb-9af6-79bd3ab3a414.png)

**Comment by tuxology** [comment]
I can see that the user is already existing. Did you multiple times? Can you give exact steps to reproduce? i can't reproduce this as well actually..

![image](https://user-images.githubusercontent.com/3373857/104127193-8a060100-5315-11eb-9d36-3285c55b37f6.png)

**Comment by srish** [comment]
@tuxology All the above users, most probably I created accounts for. I never received any confirmation for the above users that the account got successfully created, but that the account already exists.

**Comment by NdibeRaymond** [comment]
This issue has been fixed. the container handling task queueing was down and that was the cause of this issue. closing now
