### ISSUE TITLE
Improve user onboarding experience for private mode ZubHub

### ISSUE THREAD

**Issue by srish** [unstructuredstudio/zubhub#555]
Currently, Unstructured Studio's ZubHub is running in public mode while Encube's ZubHub is running in private mode. 
The challenge right now with private mode ZubHub (used by EnCube) is getting children on the system. Right now, when children try to sign up in private mode, someone needs to validate them from the backend so they can proceed and start creating projects. They don't get any notification when they first try to sign up or are approved. So, this communication currently happens between the educator and student outside the platform. We need to improve the user experience by automating this workflow.

**Comment by Ananya2003Gupta** [comment]
For this, we can push a notification and email. 
The notification of them being approved will appear in the notification section of the ZubHub website. 
The automated email can be sent on their registered email.

![image](https://user-images.githubusercontent.com/90386813/218085155-55f110b6-1b1d-4196-989a-beb397063ab3.png)

**Comment by ferindesigns** [comment]
Automated emails should be an option when signing up to the platform and can be easily disabled from the profile or account settings

**Comment by khallow7** [comment]
@srish Can we get more details on Encube's Zubhub?
Can we go through the process to better understand the onboarding experience?

**Comment by Temabo** [comment]
Hello @srish @tuxology I think there are several ways to improve the user experience of the ZubHub platform for children trying to sign up in private mode:

1. Add a notification system: Implementing a notification system can alert children when their accounts have been validated by someone from the backend. This way, they can immediately start creating projects and using the platform without having to wait for external communication.

2. Use email verification: The children would verify their email addresses during sign up. This can help ensure that the email address belongs to the child and can serve as a form of validation, reducing the need for manual validation by the backend.

3. Add an in-app messaging system: Implementing an in-app messaging system can allow for communication between the educator and student directly on the platform. This way, they can discuss any issues related to validation and the student can be notified once their account has been approved.

We can also make sure that the instructions for signing up and the validation process are clear and easy to follow. This can help reduce confusion and frustration for children trying to use the platform. I would work on Wireframes to illustrate these ideas.

**Comment by srish** [comment]
This task is no more relevant.
