### ISSUE TITLE
Implement UX/UI for new users and grouping feature for ZubHub

### ISSUE THREAD

**Issue by srish** [unstructuredstudio/zubhub#559]
> ⚠️ For any future applicants landing here, we would encourage you to use our chat channel to introduce yourselves https://unstructured.zulipchat.com/#narrow/stream/246561-general/topic/Introductions. Let's keep the issues and discussion threads on GitHub to the topic related to a specific task.

[ZubHub](https://github.com/unstructuredstudio/zubhub) is an open-source documentation & collaboration tool for activity-based learning. It is available for custom use for schools, libraries, hackerspaces, educational organizations, etc. Imagine your own online community built around your educational activities! 

Currently, it is hard for new users to immediately get an idea of what they are supposed to do when they first land on the website. Some examples of keeping new users engaged through a guided experience would be emphasizing signing up, making the sign-up process smooth, welcoming them with a quick tour of the platform, following up with them with an email, or leaving a message on their phone with next steps if they leave without creating a project and sharing with them some activity ideas, sending them a notification if someone claps or comment on their project or when they acquire a badge, etc. 

Currently, a grouping feature on ZubHub allows organizations to create group accounts and add and remove members to them. But all this happens presently from the backend, and there is no user interface. The second part of this project would be to design a user interface to support the grouping feature for educators or organizations. They should be able to promote a group account from the backend; after that, an organization should be able to add multiple accounts under them as group members from the front end and view the list from their profile page.

For this project, you will work closely with a designer who will help generate ideas for how the UX/UI will look and develop wireframes and mockups. Your task will be to code and implement them. You will be doing full-stack development and testing on both the frontend and backend web application.

Skills required: Python, Django, React, Javascript, HTML, CSS, 
Mentors: @tuxology, @srish 
Microtasks: https://github.com/unstructuredstudio/zubhub/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22 (non-ux issues only)
Join the discussion: https://github.com/unstructuredstudio/zubhub/discussions/560

**Comment by srish** [comment]
If you have any questions, want to share ideas, or take part in the discussion, join here: https://github.com/unstructuredstudio/zubhub/discussions/560

**Comment by emteehi** [comment]
Hello developers, I'm Mercy idowu from Nigeria. I am a UI/UX designer and an Outreachy applicant. I've started contributions to implement UX/UI for new users and grouping feature for ZubHub. You can reach out to me as a developer if you need help.

**Comment by amogbe-esther** [comment]
Hello, I'm Amogbe Idowu Esther, From Nigeria a UI/UX designer looking forward to collaborate with developers on the open source project, I've started my research on the implementation of the ui/ux for new users and the grouping features.

**Comment by andreasSune** [comment]
Hello, i'm Andreas Sune UI/UX designer from Cameroon. i would like to contribute on this project.

**Comment by ComradeVedant** [comment]
Hey @srish, I'm Vedant and an Outreachy applicant. Could you assign this issue to me?

**Comment by vish3z** [comment]
hellow **@srish** 
my name is vishez and i am an outreachy applicant and ill like to make my contribution on the UX/UI for new users and grouping feature for **ZubHub**. my contribution is more on new user and how fast and smooth registration for a new account can take place.

i realized that the sign up page there isnt anything going in it and i decided to add a illustration to make it more welcoming and eye catching to new users when they are signing up and move the sign up form on the right side anc easily accessible.

Another change i applied was that i have removed the **bio** text box simply because its a long process and people are still new to the website and arent really invested yet. i suggest that users will be allowed to edit their bio on their profile instead of the signing up page.


![Screenshot (35)](https://user-images.githubusercontent.com/123076372/229386041-3a3eea5a-afa9-4cf2-be91-2186e55ea238.png)

i have also added a very quick way to sign up and also log in by using google account and Facebook, if majority of the users are kids and most of them have a little attention span and aren't patient enough to go through all the steps. then it will be easy for kids to log in and sign  up. 

log in.
![Screenshot (36)](https://user-images.githubusercontent.com/123076372/229386293-99caa1a2-786c-4dc3-9282-7b02ac714715.png)

**@srish**

**Comment by Br-Al** [comment]
Hello @srish  after doing the some research and prior design i noticed a few concerns extra:

1. despite making my project visible only to me, others could still see it.
2. the activity feature  existing , there is no prompt to add an activity and it was confusing.
3. a means to not only drag and drop images and videos in the project creation section, a way to take a live photo/video and also retake the photo/video. 

I came up with a solution for these 3 alongside the point to create organization accounts and manage them
this can be seen in the photos below:
2. Activity screen:
![activitys screen](https://user-images.githubusercontent.com/58564800/229544403-482c39b9-7b45-4e9e-92a0-9d86501fdcff.png)
3: live photo/video take and preview:
![activitys screen-1](https://user-images.githubusercontent.com/58564800/229544801-a40f2c73-77f0-4c64-8d10-f6f948971636.png)
![activitys screen-2](https://user-images.githubusercontent.com/58564800/229544813-58707de2-5585-4883-8886-ce1c9ac628d5.png)

4:Organization /individual sign up:
![Property 1=Variant2](https://user-images.githubusercontent.com/58564800/229545615-283f3feb-1086-4e51-bdff-6e558cc15f19.png)
![Property 1=Variant3](https://user-images.githubusercontent.com/58564800/229545622-92fb1fea-2ee1-49e4-b214-d741d118cda7.png)
![Property 1=Variant4](https://user-images.githubusercontent.com/58564800/229545627-e030fee9-882f-4540-9594-adfec74ca24a.png)
![sign up](https://user-images.githubusercontent.com/58564800/229545632-93440c9a-460d-4d80-817a-71f55ce6f51d.png)

Hope this helps. Thanks
link to prototype:
https://www.figma.com/proto/XgnCijjTFVMIdOJbi8JyRI/zubhub?page-id=0%3A1&node-id=22-153&viewport=1585%2C272%2C0.24&scaling=min-zoom&starting-point-node-id=22%3A153

**Comment by srish** [comment]
This project is almost complete. Any remaining bits and pieces will be promoted as tasks via next round of Outreachy.
