### ISSUE TITLE
Document Problems faced during deployment (like ssl and https issues we encountered)

### ISSUE THREAD

**Issue by NdibeRaymond** [unstructuredstudio/zubhub#56]
Before deploying and during the first few days after deployment, we faced a number of production grade problems some of which had to do with SSL and https. There is a need to document how these problems where solved. This is so as to make sure that other people who get to work on this project don't end up making the same mistake we made and solving the same problems over again

**Comment by Deepthi562** [comment]
@NdibeRaymond, I am interested in this. Could you please brief me a little more, provide some links, and assign this to me. Thank you.
