### ISSUE TITLE
Inconsistent padding and alignment in the mobile version of ZubHub's website 

### ISSUE THREAD

**Issue by darechan** [unstructuredstudio/zubhub#567]
## Bug
While going through the website of [ZubHub](https://zubhub.unstructured.studio/), I noticed a lot of inconsistency with regard to the padding and alignment of the website on the mobile browser. While the desktop website is pretty well constructed as it is meant for the desktop use however the mobile version having such small UI/UX bug ruins the professional aspect of the website. I've highlighted the issue areas. 

- Various alignment are not consistent with pattern and design of the website
- Padding between two fields in `SIGN UP` module is too long

## Screenshots
![issue 2](https://user-images.githubusercontent.com/93364240/218270583-08100264-12f9-462f-bec3-45900aa961c0.png)
![issue 3](https://user-images.githubusercontent.com/93364240/218270585-a8962c5c-00cc-43c4-afb4-b7878612f859.png)

**Comment by EbukaOkoye** [comment]
I would love to work on this issue

**Comment by Dejipot** [comment]
I would love to work on this issue

**Comment by Kingjhenny** [comment]
I would very much like to be assigned to solve this issue.

**Comment by tuxology** [comment]
@darechan Can you update the issue and remove the first point since there is already a bug filed for it #528 and folks are working on it? Rest are valid bugs and we can track them in this issue.

**Comment by ferindesigns** [comment]
@darechan for the video icon, as stated before we could use SVG instead of png and remove the shadow.
For the issue with padding, we could reduce it and make sure it follows mobile rules.
Something like this:
![Screenshot 2023-03-10 005558](https://user-images.githubusercontent.com/108564127/224187843-6b934964-759b-4476-9878-825fdbfd829b.png)
Also for the png to SVG:
![Vector](https://user-images.githubusercontent.com/108564127/224187940-a27721bc-2948-490a-95b8-230cab8486c8.svg)

**Comment by ComradeVedant** [comment]
Hey @tuxology , I took a good look at the issue and I have some ideas as to how we could solve this. Now the problem could majorly stem from two things,
1. The codebase is not optimized for a mobile based experience
2. Inconsistent design systems

Please correct me if i'm wrong, but I feel it is a mix of both of these problems. As we can see, tags and usernames are overlapping on each other. I think that our design system should work like <username (first n letters)> <padding> <Tags> and follow the same pattern throughout. Would love to discuss this further.

**Comment by nawtinerd** [comment]
> @darechan for the video icon, as stated before we could use SVG instead of png and remove the shadow. For the issue with padding, we could reduce it and make sure it follows mobile rules. Something like this: ![Screenshot 2023-03-10 005558](https://user-images.githubusercontent.com/108564127/224187843-6b934964-759b-4476-9878-825fdbfd829b.png) Also for the png to SVG: ![Vector](https://user-images.githubusercontent.com/108564127/224187940-a27721bc-2948-490a-95b8-230cab8486c8.svg)

@tuxology  @srish @ComradeVedant 
What if an icon is used like react icon for the front-end 
And add a background... I think an icon would be more responsive in the app...

**Comment by darechan** [comment]
> @darechan Can you update the issue and remove the first point since there is already a bug filed for it #528 and folks are working on it? Rest are valid bugs and we can track them in this issue.

Updated the first and the last point as it is covered in #528 and #620

**Comment by ipriyanshi1708** [comment]
Hi @srish @tuxology , I am an Outreachy applicant and a frontend developer. I would like to contribute to this issue. Can you please assign it to me?

**Comment by srish** [comment]
These improvements will be addressed via a dedicated project that will be promoted via the next round of Outreachy. Closing this task for now as it will be used as a reference for the future project.
