### ISSUE TITLE
Broken hyperlink in the about section

### ISSUE THREAD

**Issue by darechan** [unstructuredstudio/zubhub#568]
## The bug
On the [ZubHub's About Section](https://zubhub.unstructured.studio/about) I've encountered a broken link for `Build In Progress`
the current URL is `http://buildinprogress.media.mit.edu/`
This is a simple fix that can be made to a static page.

Also, a suggestion, to make `hello@unstructured.studio` a hyperlink to open mailing service or your website.

## Expected behavior
To be successfully transferred to the other page.

## Screenshots
![image](https://user-images.githubusercontent.com/93364240/218272926-3f680284-917d-471e-87b0-d3d69cc483d4.png)

**Comment by Nandani-Paliwal** [comment]
Hey @darechan 
May I work on this issue, if it is not assigned to anyone else?

**Comment by tuxology** [comment]
Assigned to you. You can link this page instead: https://www.media.mit.edu/projects/build-in-progress/overview/

**Comment by Nandani-Paliwal** [comment]
The content is not written statically, right?

**Comment by darechan** [comment]
@tuxology Alright! I'll work on it asap
