### ISSUE TITLE
Make user profile details fully editable, and allow creators to delete their accounts

### ISSUE THREAD

**Issue by NdibeRaymond** [unstructuredstudio/zubhub#57]
Currently, it is only possible to edit just the username. This needs to change to make it possible to edit other user infos

**Comment by srish** [comment]
When you address this, it might be nice to look into how we allow editing on the page itself and not open a new dialog box for it (like it is now).

**Comment by NdibeRaymond** [comment]
> When you address this, it might be nice to look into how we allow editing on the page itself and not open a new dialog box for it (like it is now).

I looked into how It is done in other platforms, and they all seem to use the option of redirecting to a new page that contains the form (this is to make it easier to handle form errors and other form related stuffs), then redirect page to the profile page after editing. Eg, is twitter and linkedin. Scratch also uses a slightly different variation but it also doesn't allow editing of username and things like location directly on the profile page (they do however allow editing of bio on the profile page)
