### ISSUE TITLE
Hindi Translation Not Complete

### ISSUE THREAD

**Issue by BabyElias** [unstructuredstudio/zubhub#570]
![image](https://user-images.githubusercontent.com/95405559/220256407-0a638809-029a-4f3e-9874-653f26635c70.png)
The Hindi Translated version of Zubhub still seems incomplete.
I would love to help if its completion is needed!

**Comment by AnishaSingh0118** [comment]
I am working on this issue as part of my Outreachy's contribution.

**Comment by tuxology** [comment]
@AnishaSingh0118 I've assigned this to you

**Comment by srish** [comment]
This will be addressed later via a bigger project around translation, coming soon.
