### ISSUE TITLE
Like/Clap button not working for user profile page

### ISSUE THREAD

**Issue by iamhks** [unstructuredstudio/zubhub#576]
**Describe the bug**
After resolving #520 the current loggedin user clap button is not working.

**To Reproduce**

    1. Go to 'Homepage of website'
    2. Click on 'my profile'
    3. Try clicking clap button on the projects
    4. See error (in the top right corner)

**Expected behavior**
When clicked on clap button the count on clap icon should increase or decrease.

**Screenshots**
<img width="1280" alt="Screenshot 2023-03-04 at 23 50 46" src="https://user-images.githubusercontent.com/43777817/222922432-6e9d265c-22b8-4d4b-b687-22376bb5a1a6.png">

**Comment by iamhks** [comment]
Hi @tuxology Can you pls review this?
Also, wanted to know is it okay if I create issues like this and solve or I can directly send a PR?

**Comment by tuxology** [comment]
@iamhks It is preferable to create issues and then subsequently submit a PR just like you did. Thanks for finding this and fixing. I'll be reviewing the PR soon 👍
