### ISSUE TITLE
Browse activity button gets merged search bar 

### ISSUE THREAD

**Issue by darechan** [unstructuredstudio/zubhub#580]
## The Bug
When you visit [Zubhub](https://zubhub.unstructured.studio/) the browse button on the toolbar next to the search bar gets overlapped by `browse activity` button depending on whichever browser you use. 

## To Reproduce

- Visit the website https://zubhub.unstructured.studio/ on any browser
- Login into the website
- Go back to the home page
- Repeat the same steps on any other browser

## Expected Behavior
The search bar and the button should not overlap and maintain their padding

### On Chrome
When the page is loading:
![image](https://user-images.githubusercontent.com/93364240/223354727-474dd1b6-411c-4b0c-bcf2-33db77330b61.png)

Once it fetches the data:
![image](https://user-images.githubusercontent.com/93364240/223354814-5e804b91-edf1-4fdb-af01-ab76fbef19f1.png)

### On FireFox
When the page is loading:
![image](https://user-images.githubusercontent.com/93364240/223355823-e853ca13-9790-4126-a678-e7f479905ad2.png)

Once it fetches the data:
![image](https://user-images.githubusercontent.com/93364240/223355054-7996dadd-42ce-4445-8324-8b15d6fcf188.png)

### On Brave Browser
When the page is loading:
![image](https://user-images.githubusercontent.com/93364240/223355279-c433d604-3dde-41b3-8c48-0afdbf9ad977.png)

Once it fetches the data:
![image](https://user-images.githubusercontent.com/93364240/223355332-e9d3f029-e054-432d-8dd2-ce81bcaabc6d.png)

### On Microsoft Edge
When the page is loading:
![image](https://user-images.githubusercontent.com/93364240/223355575-a993435c-c87f-4663-9fbc-a651a22b8a73.png)

Once it fetches the data:
![image](https://user-images.githubusercontent.com/93364240/223355679-bfcbbd3f-6dee-41af-a364-70207b1fe3f9.png)

**Comment by the-techgurl** [comment]
Adequate spacing needs to be added to the top navigation to avoid different elements overlapping.
