### ISSUE TITLE
Circled Numbers

### ISSUE THREAD

**Issue by ferindesigns** [unstructuredstudio/zubhub#582]
I noticed that some of the coloured circled numbers were not centred making the numbering seem a little bit off.

**Comment by ferindesigns** [comment]
![Screenshot 2023-03-07 142627](https://user-images.githubusercontent.com/108564127/223435440-7c34bc41-b376-4eda-9e1b-b7e42c5651f1.png)
The numbers 6 and 8 were not centred in the circle.

**Comment by cherish2003** [comment]
@srish i am outreachy applicant i want to work on this issue can you assign me

**Comment by cherish2003** [comment]
[#602](https://github.com/unstructuredstudio/zubhub/pull/602) @srish kindly review it

**Comment by ipriyanshi1708** [comment]
Hi @srish @tuxology, I am an Outreachy applicant and a frontend developer. I would like to contribute to this issue if this is still open. Can you please assign it to me?

**Comment by srish** [comment]
This task is no more applicable as we recently removed numbers from the project creation form
