### ISSUE TITLE
Create Project Form

### ISSUE THREAD

**Issue by ferindesigns** [unstructuredstudio/zubhub#583]
The whitespace between the numbers and text is too small. It could be adjusted to make it look more presentable.

As the form is, it feels a little bit clustered because there is not enough whitespace and the alignment is also off.

**Comment by darechan** [comment]
Hey @ferindesigns can you be a little more specific on the issue and provide visual samples for the same?

**Comment by ferindesigns** [comment]
okay will do

**Comment by ferindesigns** [comment]
![Screenshot 2023-03-07 142238](https://user-images.githubusercontent.com/108564127/223434790-c970a0de-680b-4960-a219-423404c6ab7b.png)
The whitespace between the coloured circled numbers and text is too small. Alignment is also off.

**Comment by ghost** [comment]
@srish please can you assign me this task?

**Comment by nourhan-ashraf** [comment]
Hi @srish , I am an outreachy participant and I'd like to work on this issue if it's still open.

**Comment by ipriyanshi1708** [comment]
Hi @srish @tuxology, I am an Outreachy applicant and a frontend developer. I would love to contribute to this issue. Please assign this to me.

**Comment by srish** [comment]
This is no more applicable, the project form has changed quite a lot in terms of its UI
