### ISSUE TITLE
Active language not showing on mobile display

### ISSUE THREAD

**Issue by yaya-mamoudou** [unstructuredstudio/zubhub#589]
**Describe the bug**
 On smaller displays, the Active language not showing the selected language gets hidden on the navbar and on the footer

**To Reproduce**

1. Go to Home page
2. If you are opening from your desktop look resize your screen to a mobile screen else go to step 3
3.  Look at the language dropdown on the navbar and on the footer
4. See errors

**Expected behavior**
The selected language should be visible by the user so he/she knows which language is on

**Screenshots**
<img width="504" alt="image" src="https://user-images.githubusercontent.com/57509871/223575270-4efa5fef-bf5c-44b7-9306-2c64f0a492d9.png">

<img width="364" alt="image" src="https://user-images.githubusercontent.com/57509871/223580264-5817b3f0-4fdf-4e3a-bd0f-bb2135bbb362.png">

**Comment by yaya-mamoudou** [comment]
Hi @tuxology , check this out. Please could you assign me to work on this issue?

**Comment by nourhan-ashraf** [comment]
Hi @srish  , I am an outreachy participant and I'd like to work on this issue if it's still open.

**Comment by tuxology** [comment]
@yaya-mamoudou In the header bar, this was intentional since the real estate is less. However, we can surely show the selected language on the footer. As you work on this, can you also also change color of dropdown triangle to white?

**Comment by yaya-mamoudou** [comment]
> @yaya-mamoudou In the header bar, this was intentional since the real estate is less. However, we can surely show the selected language on the footer. As you work on this, can you also also change color of dropdown triangle to white?

Alright. Thank you
