### ISSUE TITLE
Behavior of “for all registered Zubhub users” viewing mode is not defined correctly.

### ISSUE THREAD

**Issue by khallow7** [unstructuredstudio/zubhub#592]
### **The Bug**
When a creator sets the option to “for all registered Zubhub users” then an additional field opens to input usernames.

### **To Reproduce**

Visit: https://zubhub.unstructured.studio/
Login
Create a Project
Scroll down to the 8th option in the form.
Select “all registered zubhub users”.
An additional input field will appear.

### **Expected behavior**
The project should be visible to all the registered/authenticated users.
There shouldn't be any new input field to take in usernames.

### **Screenshots**

<img width="695" alt="223364315-c48dd707-a616-43d9-ad53-64bdd0b852b2" src="https://user-images.githubusercontent.com/107268558/223626933-f8c44493-7a9d-4bd9-af1c-c35b2c252bdd.png">

**Comment by cherish2003** [comment]
@srish @tuxology  i am outreachy applicant i want to work on this issue can you assign me

**Comment by abangmajesika** [comment]
Hello @srish @khallow7 @tuxology. I'm an outreachy applicant, and so excited to contribute to this project. Could you please assign this task to me?

**Comment by skynette** [comment]
Hi  @srish  @khallow7  @tuxology . I'm an outreachy applicant, and so excited to make my first contribution to this project. Could you please assign this task to me?

**Comment by Ammy198488** [comment]
Hy @tuxology is this still available. I would like to work on this.

**Comment by iamhks** [comment]
@tuxology Please make sure to merge both #592 and #593 together, if not, we will end up with two identical labels.

**Comment by cherish2003** [comment]
@tuxology  [#678](https://github.com/unstructuredstudio/zubhub/pull/678) this PR resolves both the issuses #592 and  #593 kindly review it

**Comment by srish** [comment]
No more applicable, as this field has been removed.
