### ISSUE TITLE
Behavior of “only a few zubhub users” viewing mode is not defined correctly.

### ISSUE THREAD

**Issue by khallow7** [unstructuredstudio/zubhub#593]
### **The Bug**
When I set the option to “only a few zubhub users” it sends the project to draft, and it's only visible to me.

### **To Reproduce**
Visit: https://zubhub.unstructured.studio/
Login
Create a Project
Scroll down to the 8th option in the form.
Select the “only a few zubhub users” option.
The created project will be shifted to drafts.

### **Expected behavior**

The project shouldn't shift to drafts. It should be visible to selected zubhub users that a creator will select.

An additional input form should open when selecting “only a few zubhub users” during the project creation process, like the image below:
![image](https://user-images.githubusercontent.com/107268558/223630000-fb85d5e6-347f-4e9f-aae3-16b2fe821c1f.png)

Screenshot of the bug
![image](https://user-images.githubusercontent.com/107268558/223629147-2cbd17d7-f2fb-418c-a0e7-a5e58851cdec.png)
![image](https://user-images.githubusercontent.com/107268558/223629215-e2da94f9-385f-4822-a51b-8bce497c9dab.png)

**Comment by tuxology** [comment]
@khallow7 This also means that we should rename this option as Draft or introduce a button called "Save as Draft" or have an autosave feature that saves projects to draft in case users leave the site. This is a valid bug. Thanks for reporting 👍

**Comment by cherish2003** [comment]
@srish @tuxology i am outreachy applicant i want to work on this issue can you assign me

**Comment by khallow7** [comment]
> @khallow7 This also means that we should rename this option as Draft or introduce a button called "Save as Draft" or have an autosave feature that saves projects to draft in case users leave the site. This is a valid bug. Thanks for reporting 👍

Yup, @tuxology a “Save as Draft” button is needed there. I was looking for the “Save as Draft” button and confused about how saving to draft works, and even left the site to check is auto-save is available. An auto-save feature of projects to drafts will be great.

**Comment by tuxology** [comment]
@khallow7 Would you like to work on this?

**Comment by khallow7** [comment]
@tuxology I am a UX designer applicant . It should be assigned to a developer applicant.

**Comment by tuxology** [comment]
@khallow7 Ok, I got it. Since these are all valid suggestions, we will leave them here and let devs work on them. For you, I would suggest align with #561 and its related tasks and develop concrete UX/mockups and share on relevant discussion groups. If there are UX ideas even for small ticket items like these, you can create new discussions and suggest them as well :)

**Comment by ahn-nath** [comment]
Hello, @tuxology.

I have checked this issue and the source of the problems and have noticed that this can easily be divided into two different issues to solve of different natures. Those two are:

1. “Drafts” need to be enabled via a different input as well as autosaving when the user leaves without submitting the project.
2.  Add the usernames input field so that the system can restrict the visibility of the project based on those records.

My suggestion is that they are treated independently. If @cherish2003 is comfortable, and you think is reasonable, I would volunteer to work on the first issue.

**Comment by blessingpeters** [comment]
> @tuxology I am a UX designer applicant . It should be assigned to a developer applicant.

Hi @tuxology I'm a developer and would love to work on this. you can assign it to me.

**Comment by cherish2003** [comment]
@blessingpeters i am currently working on this

**Comment by blessingpeters** [comment]
Ohh Great! Goodluck then

**Comment by cherish2003** [comment]
@tuxology i have renamed the option now it is working fine the projects are saving in the drafts 
<img width="561" alt="Screenshot 2023-03-14 at 12 11 52 AM" src="https://user-images.githubusercontent.com/88829894/224800469-4dcc2d3d-fd9a-4c63-a66b-4c81fb11645b.png">

### Found another Bug
<img width="559" alt="Screenshot 2023-03-14 at 12 13 42 AM" src="https://user-images.githubusercontent.com/88829894/224801181-6937a798-b181-4e1e-ad72-d297ca52ade4.png">

but when we select option  `All registered ZubHub users` it is showing for adding usernames but it is not possible to determine all the ZubHub users by taking as input and then i found that there are only four publish_types by default in the codebase so if this option is replaced by  `Only a few ZubHub users` option  it would be perfect and the bug will be solved

**Comment by cherish2003** [comment]
@tuxology the bug i mentioned about is also issue [#592](https://github.com/unstructuredstudio/zubhub/issues/592) so this needs to be rectified if approved i will fix the issue here itself because both are linked

**Comment by cherish2003** [comment]
@tuxology @srish Can you say your opinion on my mentions so that i can proceed working on it

**Comment by tuxology** [comment]
@cherish2003 Lets go with your suggestions for now. Please proceed, we will improve UX further in next iteration

**Comment by cherish2003** [comment]
@tuxology kindly check this PR [#678](https://github.com/unstructuredstudio/zubhub/pull/678) to close the issue

**Comment by khallow7** [comment]
@tuxology Is this issue fixed? I just tried creating a project, but I am getting the same issue.
