### ISSUE TITLE
Dropdown menu in mobile responsive

### ISSUE THREAD

**Issue by nourhan-ashraf** [unstructuredstudio/zubhub#596]
**The bugs:**
The hamburger menu dropdown list is not looking good in mobile responsive view and the name is not fully shown.
This issue only happens with the hamburger menu button.

**What you expected to happen:**
The hamburger menu dropdown list should be more smaller.

**Screenshots**

- Dropdown list in iPhone12 Pro resolution:
![iphone menu](https://user-images.githubusercontent.com/66208099/223886907-32fcd482-1330-42d8-b2c9-017173463f2b.png)

- Dropdown list for 512 pixels wide
![humbutton](https://user-images.githubusercontent.com/66208099/223887612-8970e3aa-170b-424e-b203-093075aa798e.png)

**Comment by nourhan-ashraf** [comment]
@srish @tuxology  could you see the issue and let me know if I can work on it for outreachy program?

**Comment by ghost** [comment]
@nourhan-ashraf  I'd love to work in this with you once it's approved

**Comment by tuxology** [comment]
@nourhan-ashraf File separate github issues for separate bugs/improvements. Please go through old issues as well. 

For this specifically: 
 - From your first point, only long username cutting off can be an issue. Please also refer #203 and see if this is valid still. Use more realistic mobile phone resolutions for testing. Apart from that, the screen size  you selected is unrealistic for modern devices.
 -  Second is a valid issue if you can reproduce on standard screen sizes (or even responsive ones). Make this a separate issue. 
 - Change title and description of this issue to only reflect the specific bug. Thanks 👍

**Comment by nourhan-ashraf** [comment]
> @nourhan-ashraf File separate github issues for separate bugs/improvements. Please go through old issues as well.
> 
> For this specifically:
> 
> * From your first point, only long username cutting off can be an issue. Please also refer [Long usernames getting cut off from the user menu #203](https://github.com/unstructuredstudio/zubhub/issues/203) and see if this is valid still. Use more realistic mobile phone resolutions for testing. Apart from that, the screen size  you selected is unrealistic for modern devices.
> * Second is a valid issue if you can reproduce on standard screen sizes (or even responsive ones). Make this a separate issue.
> * Change title and description of this issue to only reflect the specific bug. Thanks 👍

- I updated this issue with new screenshots of the bug in iPhone 12 pro resolution and more info about when the issue starts to show.
- About the issue you mentioned #203, the solution of this issue is still valid as long as the hamburger menu button doesn't show, once it shows and the avatar photo disappears the issue starts to happen.
- I created new issue for the second one, https://github.com/unstructuredstudio/zubhub/issues/612 .

**Comment by srish** [comment]
No more applicable, as the menu no longer exists
