### ISSUE TITLE
search bar in mobile responsive view

### ISSUE THREAD

**Issue by nourhan-ashraf** [unstructuredstudio/zubhub#597]
The bug:
1- The search bar is too big for the mobile view, it needs to be smaller to fit in.

**Screenshots**

![searchbar](https://user-images.githubusercontent.com/66208099/223725088-799d4aa7-e836-4ba0-bd3c-a5fb445d2e6d.png)

**Comment by nourhan-ashraf** [comment]
@srish could you see the issue and let me know if I can work on it for outreachy program?

**Comment by yaya-mamoudou** [comment]
This issue has already been fixed and approved. See https://github.com/unstructuredstudio/zubhub/pull/586
