### ISSUE TITLE
Hero Section is too clustered with 2 different information

### ISSUE THREAD

**Issue by askdenit** [unstructuredstudio/zubhub#599]
**Describe the Bug**
Hero section is too clustered and not grabbing attention. 
Share a project button and create project button are both linking to the same page
The new stuff!: Creative challenge 2023 is not meant to be on the hero section since it's clickable.. Most users might not know that it's clickable

**To Reproduce**
Visit [https://zubhub.unstructured.studio/](url)

**Expected Behaviour**
- Over-all redesign of the hero section giving it a new look n feel. And still maintaining the color pallete.
- Share a project button will be removed from the hero section

The Text on the Hero section should consist of 
1. Header text
2. Body Text
3. CTA Buttons 

Creative Challenge 2023 banner should be moved down to another page on the website

**Screeshots**
![ZH Hero](https://user-images.githubusercontent.com/81030718/223781640-d3cc308f-4263-412a-89b2-56444e8cc34d.png)

**Comment by askdenit** [comment]
@tuxology @srish Please check this out, can you please assign this to me? Thanks

**Comment by askdenit** [comment]
@tuxology can you please assign this to me. I've started working on it. Thanks

**Comment by tuxology** [comment]
@askdenit Would you like to first create some mockups? Maybe in Figma or in any other form you are comfortable with. Since this is a major rework of the major part of the UX, we would like to think this through and debate, evolve the design before we move ahead with this. I also feel much of the changes and proposals in #562 will affect this design work as well, so keep an eye on that as well. I am assigning this to you, but only for the first UX proposal for now. Feel free to collaboratively work with other folks as well if you feel like it.

**Comment by askdenit** [comment]
**Solutions to Bugs**

First, I did a research on [https://colorhunt.co/](url)
To be sure of which color to use for the project. Then I inputted tags like, kids, education. Then I got this. So I realised I'm on the right track with the current color palette of Zubhub
![Group 87](https://user-images.githubusercontent.com/81030718/224322583-e62e20a6-c56f-495f-a251-0ae2b0e3bfe0.png)

1. Navbar re-design considering the user experience.

**Current Nav-bar**
![ZH Nav](https://user-images.githubusercontent.com/81030718/224315423-540eb6dd-7ef4-4783-a93b-b162f7ca9f88.png)

**Nav-bar redesign**
![ZH Navbar](https://user-images.githubusercontent.com/81030718/224315560-8a532f75-a5da-40c9-9a7c-d1b2a23f7059.png)

- The language dropdown button is not a priority on the navbar. So it was shifted to the right side of the Navbar.
- On the search bar, the drop down menu that consist of projects, creators and tags has also been removed. Because a better UX reduces the number of steps or clicks a user as to make.. With the new design, user will only take a step to perform the search task instead of 2 steps. 

2. An engaging Hero section

**Current Hero section**
![ZH Hero](https://user-images.githubusercontent.com/81030718/224318006-3ab40807-cb43-42e0-b5ea-a09b2811c1b9.png)

**Hero section re-design**
![ZH Dektop (1)](https://user-images.githubusercontent.com/81030718/224318262-6bf8ac40-35e3-4d93-8802-2984e1a8a45d.png)

- The first thing users see when they visit Zubhub is the hero section. This area shows what Zubhub is all about with images as illustrations consisting of header text, body text and engaging CTA buttons. From the re-design, the share a project button has been removed because it's the same prompt as create project on the Nav bar.
- New Stuff: Creative challenge has been moved down to another page. since it's a vital information. 
The New Stuff text on the yellow background would be in marquee. A continuous animation.. Which would catch the attention of users

**Comment by askdenit** [comment]
@tuxology What do you think about these?

**Comment by cybraia** [comment]
hii, @askdenit and @tuxology in case you need a developer, assign me the task. Thanks!

**Comment by srish** [comment]
No more applicable, as hero image recently received a new design
