### ISSUE TITLE
Inconsistent Spacing between padding  throughout the Create a Project form

### ISSUE THREAD

**Issue by Kingjhenny** [unstructuredstudio/zubhub#601]
**Describe the bug**
While going through the website of [ZubHub](https://zubhub.unstructured.studio/), I noticed the create a project page had a lot of inconsistency with the padding and alignment on the website.  

### **Issue**

- Where the Create a Project and tell us about your project had reasonable spacing in between, the first step "Name your Project" had too much spacing in between which make the site look like it lacks uniformity,

**Screenshots**

![Frame 1](https://user-images.githubusercontent.com/117821480/223790001-a062894f-d165-486f-9e24-3959dea156e5.png)

please assign this project to me to make a mockup of a create a project form Style.

**Comment by Kingjhenny** [comment]
@srish @tuxology  i am outreachy applicant i would like work on this issue can you assign me ?

**Comment by Kingjhenny** [comment]
Description of PR here...
Inconsistent Spacing between padding throughout the Create a Project form.

### Changes 

- uniformly adjusted the vertical spacing throughout create a project form according to their respective numbering.
- Adjected unnecessary width space in the answer boxes
- Aligned most of the boxes to ensure uniformity
- Removed unnecessary excess spacing to make the form shorter.
![Zubhub create a project](https://user-images.githubusercontent.com/117821480/226204845-aca73567-28bf-4b1b-a512-9a8748536faa.png)

**Figma link:**
https://www.figma.com/file/9y72IGo5tiB2zJxX6O82M9/Zubhub-create-a-project?node-id=14%3A4&t=1Wz5jOnW4qjEHKso-1

**Comment by ahmadadejumo** [comment]
@tuxology and @srish i would love to work on the new design @Kingjhenny provided, i am also an outreachy applicant

**Comment by srish** [comment]
No longer applicable, a lot has changed in the project creation form
