### ISSUE TITLE
Removing repetitive buttons and/or Changing Content to better understandable ones

### ISSUE THREAD

**Issue by Ololad-e** [unstructuredstudio/zubhub#603]
Under this issue, I plan to scrutinize the website to remove some misleading buttons and change contents of some buttons to a better understandable ones.
Please assign this issue to me, thanks. @srish 
To start with,
While I was trying to create a project, I noticed a lot of "CREATE project buttons"  that are actually clickable, its quite **distracting and misleading** and not useful since I'm already trying to create a project. Even at first I thought the bole Create button on the top nav bar was actually for me to post my project, but it didn't when I clicked on it
so I removed it in my design I uploaded in the "Improve the UI/UX for activity and project creation features for ZubHub #557"
![Frame 35](https://user-images.githubusercontent.com/64203558/223844586-2a350ae9-0557-40a5-a1e6-5168641598c5.png)
![name project2](https://user-images.githubusercontent.com/64203558/223844631-e8186637-9879-4fdc-a61d-056c215b11ce.png)

**Comment by tuxology** [comment]
@OloladeOdus Thanks, this is very valuable 🎉 . Since this is a point of discussion and not yet something tangible we can do, I am closing this issue. Please move all this content to a new discussion here: https://github.com/unstructuredstudio/zubhub/discussions
