### ISSUE TITLE
Profile page 

### ISSUE THREAD

**Issue by amogbe-esther** [unstructuredstudio/zubhub#609]
Improvement on the profile page that gives a users a better feel and experience.

**Comment by amogbe-esther** [comment]
The user interface of the profile page can be improved on and comprise of more details
![profile page](https://user-images.githubusercontent.com/61055736/223878468-1e363d10-9cb7-4f26-b218-403466a5b5b4.PNG)
![my profile page](https://user-images.githubusercontent.com/61055736/223878486-0225983b-c473-4cc4-9e0e-6594f678d175.PNG)

**Comment by ferindesigns** [comment]
Please @srish could you assign this to me?

**Comment by tuxology** [comment]
Thanks @amogbe-esther Can you provide tangible improvement ideas? Also, lets move this to Github Discussions since there is nothing specific to do here. I am closing this.
