### ISSUE TITLE
Improved the UI/UX for the Project Creation Form

### ISSUE THREAD

**Issue by Rosietta-UIUX** [unstructuredstudio/zubhub#610]
The Problem
ZubHub allows educators and children to upload an educational activity or project via a form. This process is lengthy; many fields in both forms require lots of information. Overall, it has room for significant improvements on the user experience and design front.

The Solution
1. I made the form a step-by-step, wizard-like form rather than a single one. 
2. Added a "Back button" in case of mistakes while filling out the form.
3. Added a "Save Changes" button so creators can quickly start from where they stopped.

Figma File:
https://www.figma.com/file/znHmUthh7VmGk5W9StISSc/ZubHub-Project?node-id=0%3A1&t=mZoupSHiQ0E06VVD-1

**Comment by tuxology** [comment]
Thanks for this! This is a duplicate for #557 so we will be closing this. Since you are creating a Figma sketch and adding valuable feedback, please move this information to discussion going on at #558 Feel free to radically change the UI as well including colors/fonts.
