### ISSUE TITLE
Games feature

### ISSUE THREAD

**Issue by ferindesigns** [unstructuredstudio/zubhub#611]
Hello, @tuxology and @srish I would like to suggest a new feature/page. To add a little bit of a fun element, I was thinking we could add a games page. That was one of the first things that occurred to me when I found out that the website is targeted towards children since kids love games. Statistically, it has been proven that 90% or more children play games.
I have designed a page and would like it if you could check it out. Thank you.
[](https://www.figma.com/file/SmxXgcNYgN8y3jBSVKvzxX/Untitled?node-id=20%3A72&t=rxbJkUhzuRkrLVdY-1)

**Comment by EbukaOkoye** [comment]
@srish @tuxology  I'll love to work on this feature when @ferindesigns is done with the design

**Comment by ferindesigns** [comment]
![Desktop - 1](https://user-images.githubusercontent.com/108564127/224444456-baceb4bb-adaf-44a9-b1be-15dc31da8ab7.png)
It might take collaborating with some game owners to get it started, or we can design our own game.

**Comment by srish** [comment]
Closing this for now, as it is not on the product roadmap.
