### ISSUE TITLE
Add a Cancel button to the Edit page

### ISSUE THREAD

**Issue by Vic-Orlands** [unstructuredstudio/zubhub#614]
Motivation: When a creator clicks on Edit on a project, there should be a cancel button should the creator decide not to continue editing. As it is currently implemented, only the Edit project button is shown, and clicking on it will update the project and take the user back to their website but that shouldn't be the case.

![Screenshot from 2023-03-09 13-18-36](https://user-images.githubusercontent.com/53902215/224021553-c4a31f9e-90fa-443a-b4d1-40d4eb8de07a.png)

**Comment by Vic-Orlands** [comment]
@srish @tuxology Can I be assigned to this task?

**Comment by tuxology** [comment]
There are two issues here. One is that Edit Project should be renamed to "Save Project" and another button called cancel should be added adjacent to it, maybe in an outline format.

**Comment by tuxology** [comment]
@Vic-Orlands I can assign this to you. Can you also update the issue with what I just described above?

**Comment by Vic-Orlands** [comment]
> @Vic-Orlands I can assign this to you. Can you also update the issue with what I just described above?

Yes, I do. I will implement the changes and make a pull request

**Comment by aditramdas** [comment]
Everything going good? Need any help with this?

**Comment by Vic-Orlands** [comment]
Hi Adith,

I am almost done with it but thank you for offering.

**Comment by nawtinerd** [comment]
I am Chukwuebuka an outreachy applicant. 
I want to work on this issue

**Comment by ahmadadejumo** [comment]
Hello @srish and @tuxology has this issue been closed out ?... If yes i would love to be assigned to another one please

**Comment by ipriyanshi1708** [comment]
Hii @srish , Can I be assigned to this issue?

**Comment by Formasitchijoh** [comment]
> Motivation: When a creator clicks on Edit on a project, there should be a cancel button should the creator decide not to continue editing. As it is currently implemented, only the Edit project button is shown, and clicking on it will update the project and take the user back to their website but that shouldn't be the case.
> 
> ![Screenshot from 2023-03-09 13-18-36](https://user-images.githubusercontent.com/53902215/224021553-c4a31f9e-90fa-443a-b4d1-40d4eb8de07a.png)

@tuxology  i would like to work on this issue would you please assign me this

**Comment by Formasitchijoh** [comment]
> @Vic-Orlands I can assign this to you. Can you also update the issue with what I just described above?

And can i update the issue as you suggested with the description you provided,

**Comment by srish** [comment]
No longer applicable as UI has changed.
