### ISSUE TITLE
Image Positioning on Activities page

### ISSUE THREAD

**Issue by Vic-Orlands** [unstructuredstudio/zubhub#616]
**Describe the bug**
On the mobile screen, the “no activities created” page and image is positioned under the header.

**To Reproduce**

1. Open the mobile screen
2. Click on Browse Activities
3. See error

**Expected behavior**
There should be a margin top to show the image clearer

**Screenshots**
![D98D6239-7DBC-4ECE-9613-ED7550C601BF](https://user-images.githubusercontent.com/53902215/224024759-bd9e5d13-6845-4d8e-ab97-c05af6257018.png)

**Comment by cherish2003** [comment]
@srish @tuxology  i am outreachy applicant i would like work on this issue can you assign me ?

**Comment by Vic-Orlands** [comment]
> @srish @tuxology i am outreachy applicant i would like work on this issue can you assign me ?

Same here. I am also an Outreachy applicant and I just created this issue.

**Comment by cherish2003** [comment]
@Vic-Orlands are working on this issue ?

**Comment by Vic-Orlands** [comment]
> @Vic-Orlands are working on this issue ?

Yes, I am working on it. I am only waiting to be assigned in order to make a PR

**Comment by tuxology** [comment]
@Vic-Orlands This is similar to another issue where the activity bar/breadcrumb bar was hiding content on screen below. I can't find it :( Please make sure that work doesn't overlap :)

**Comment by Vic-Orlands** [comment]
> @

I have gone through the created issues. This is a distinct issue as the only similar ones are [this](https://github.com/unstructuredstudio/zubhub/issues/600#issue-1615650896) and [this](https://github.com/unstructuredstudio/zubhub/issues/557#issue-1573408409), and both issues are different from this bug.

**Comment by Vic-Orlands** [comment]
> @Vic-Orlands This is similar to another issue where the activity bar/breadcrumb bar was hiding content on screen below. I can't find it :( Please make sure that work doesn't overlap :)

I have gone through the created issues. This is a distinct issue as the only similar ones are https://github.com/unstructuredstudio/zubhub/issues/600#issue-1615650896 and https://github.com/unstructuredstudio/zubhub/issues/557#issue-1573408409, and both issues are different from this bug.

**Comment by tuxology** [comment]
@Vic-Orlands Ok, please go head a fix this

**Comment by iamatifmoin** [comment]
@Vic-Orlands are you working on this?

**Comment by Vic-Orlands** [comment]
> @Vic-Orlands are you working on this?

Yes, I am. Thank you.
