### ISSUE TITLE
Creating better design system for zubhub

### ISSUE THREAD

**Issue by emteehi** [unstructuredstudio/zubhub#617]
I saw on the group chat that zubhub needs a better design system. I've decided to work on the design system to make it better.
Former design system; https://www.figma.com/file/NxbX0miY30Sfd4Le2Yl1qv/ZubHub-Sample-Sketches?node-id=0-1&t=IpGc9r0R9VyPVhHO-0

Does this count @srish @tuxology?

**Comment by waju-ire** [comment]
Hi @srish @tuxology, @ferindesigns and I decided to start work on a creating a new design system. We started by analysing the current website to see how best to approach it. This way we looked at current typography, colour combinations and other details. You can view the contribution via https://www.figma.com/file/MyUgXg5QldbCgV3Ye2ANht/ZubHub.Unstructured.Studio?node-id=16%3A45&t=8NmESg9sZw0PT5MQ-1
This is still an ongoing contribution.

**Comment by Vic-Orlands** [comment]
@waju-ire Can I join as a collaborator on this task? I know my skills will be beneficial to this task

**Comment by emteehi** [comment]
Hi @waju-ire, i cant access the figma file

**Comment by waju-ire** [comment]
@Vic-Orlands how can I get a hold of you?
@emteehi, you should be able to now... sorry about that

**Comment by Vic-Orlands** [comment]
@waju-ire this is my email: chimezieinnocent@gmail.com

I am Chimezie Innocent on the community discussion group, should you want to reach me there

**Comment by waju-ire** [comment]
> Hi @srish  @tuxology, @ferindesigns and I decided to start work on a creating a new design system. We started by analysing the current website to see how best to approach it. This way we looked at current typography, colour combinations and other details. You can view the contribution via https://www.figma.com/file/MyUgXg5QldbCgV3Ye2ANht/ZubHub.Unstructured.Studio?node-id=16%3A45&t=8NmESg9sZw0PT5MQ-1 This is still an ongoing contribution.

Hi @tuxology @srish, @ferindesigns and I have reached a stage in building the component library to an extent we feel we should open it up for other designers to use in implementing their solutions. So far, we have documented decisions and tips that helped us in building the library.
click the link to see: 
https://www.figma.com/file/MyUgXg5QldbCgV3Ye2ANht/ZubHub.Unstructured.Studio?node-id=0%3A1&t=z77GtGGmg2QU9hW7-1
