### ISSUE TITLE
Quick Tour Guide Feature

### ISSUE THREAD

**Issue by Rosietta-UIUX** [unstructuredstudio/zubhub#618]
Hello @sethiastha, @srish, @tuxology

Upon signing up for Zubhub, I was redirected to the profile page and found myself unsure of what steps to take next. I recommend adding a Quick Tour Guide feature to help new users navigate the platform more efficiently. This feature could include interactive modal samples that demonstrate how to use key features and tools. By implementing this feature, not only could it help me, but could also benefit other new users who may face a similar challenge.

Here are some sample designs of the modals that I could improve on if accepted

The Welcome message modal
![Profile Page 1](https://user-images.githubusercontent.com/123890450/224064016-f8f40060-ea69-4507-b463-ac81de2855d6.png)
![Profile Page 4](https://user-images.githubusercontent.com/123890450/224064110-88ed231b-1712-428d-a0bd-c67f75094b27.png)
![Profile Page 2](https://user-images.githubusercontent.com/123890450/224064326-0d396c11-8ec5-4df2-9df5-67f1c4c36817.png)
![Profile Page 3](https://user-images.githubusercontent.com/123890450/224064423-24bf9fd9-95a1-438f-8262-c626c0789983.png)
![Profile Page 5](https://user-images.githubusercontent.com/123890450/224064550-1b3b265c-53e8-49b2-982d-b427ac326202.png)

**Comment by darechan** [comment]
Brilliant Idea! Would love to be the one to integrate this into the website!

Additional suggestions: 

- Addition of character from asset packs in the tour dialog boxes as the website is intended for young audience
- Addition of a help button on every page that would open up tour 
- Addition of a badge on the profile for completing the website tour

**Comment by Rosietta-UIUX** [comment]
@darechan Thank you for the amazing suggestions. There's so much room for improvement in the design and it can be worked on further if the mentors approve of it

**Comment by Vic-Orlands** [comment]
> @darechan Thank you for the amazing suggestions. There's so much room for improvement in the design and it can be worked on further if the mentors approve of it

@tuxology Can I work on this task with @Rosietta-UIUX. I can implement it after she is done designing it

**Comment by Rosietta-UIUX** [comment]
Hello @tuxology @srish, please assign me and @darechan to work on this task

**Comment by Rosietta-UIUX** [comment]
Hello @sethiastha, @srish, @tuxology @darechan 

Here's an improved version of the tour guide after brainstorming and considering the feedback.

![Profile Page 1 0](https://user-images.githubusercontent.com/123890450/225277653-f4cae2fc-b1eb-42d6-ba9c-59ba48f274d2.png)
![Profile Page 5 0](https://user-images.githubusercontent.com/123890450/225277843-0c9b0bbd-def5-40f4-bf1e-39b6a1f59953.png)
![Profile Page 2 0](https://user-images.githubusercontent.com/123890450/225277728-563f75e3-bec9-4ba8-89e6-c19f677c2485.png)
![Profile Page 4 0](https://user-images.githubusercontent.com/123890450/225277952-b25817c8-5b96-4d3e-bdee-75ffc91fe5c2.png)
![Profile Page 3 0](https://user-images.githubusercontent.com/123890450/225278021-73cd10b1-efb4-4448-93eb-aa01620af789.png)
![Profile Page 7 0](https://user-images.githubusercontent.com/123890450/225278143-8b49a1bc-473e-4fc1-a5f3-715f5fdb2c7d.png)
![Profile Page 8 0](https://user-images.githubusercontent.com/123890450/225278200-8bd79863-a956-4b62-98a0-48097285462a.png)
![Profile Page 9 0](https://user-images.githubusercontent.com/123890450/225278268-c66b0f8f-7a79-4ad5-b7bf-701ff37f0488.png)
![Profile Page 10 0](https://user-images.githubusercontent.com/123890450/225278339-bf7105be-9704-4e17-a3a9-4aa5cfc874f3.png)

**Prototype**
https://www.figma.com/proto/znHmUthh7VmGk5W9StISSc/ZubHub-Project?node-id=306%3A15657&scaling=scale-down-width&page-id=236%3A25&starting-point-node-id=301%3A6881&hide-ui=1

https://user-images.githubusercontent.com/123890450/225278525-51dada95-6d83-427d-8dce-0473d80f77f9.mp4

**Comment by darechan** [comment]
@Rosietta-UIUX looks great to me we can add in transition using css and it would look smoother

**Comment by Rosietta-UIUX** [comment]
@darechan Yes. thank you for the feedback

**Comment by Rosietta-UIUX** [comment]
Hello @sethiastha,@tuxology @srish I would really appreciate it if I can be assigned to this issue to further work and improve on it. Thank you.

**Comment by srish** [comment]
Very nice design ideas! The platform has changed a bit recently, so some of these designs might no longer will be applicable. We will come back to tour guide features once the platform has matured.
