### ISSUE TITLE
Use of SVG instead of PNG in play icon

### ISSUE THREAD

**Issue by darechan** [unstructuredstudio/zubhub#620]
## The bug
The png for play icon gets blurred out based on screen resolution so replacing the png to an svg for the same would be a great quick fix

## Screenshots
![image](https://user-images.githubusercontent.com/93364240/224126784-a9457003-4694-4894-a0f7-3f126bd5653e.png)

**Comment by cherish2003** [comment]
@darechan i am outreachy applicant i want to work on this issue can you assign me

**Comment by tuxology** [comment]
@darechan Thanks, this is a good small work which can improve UI a lot. Issue is not just SVG, but is related to good quality image. Should I assign this to you?

**Comment by darechan** [comment]
> @darechan Thanks, this is a good small work which can improve UI a lot. Issue is not just SVG, but is related to good quality image. Should I assign this to you? 

For sure!

**Comment by ferindesigns** [comment]
![Vector](https://user-images.githubusercontent.com/108564127/224181509-af626abd-feb4-4b0c-b597-dcf5c4846251.svg)
Yeah @darechan I think the png could be replaced with svg

**Comment by darechan** [comment]
> ![Vector](https://user-images.githubusercontent.com/108564127/224181509-af626abd-feb4-4b0c-b597-dcf5c4846251.svg)
> Yeah @darechan I think the png could be replaced with svg

Since this is the official youtube logo, I've downloaded the same from there and edited the colour to match the website! But thanks for the resource!

**Comment by ferindesigns** [comment]
You're welcome @darechan
