### ISSUE TITLE
Dark Mode Option for Mobile 

### ISSUE THREAD

**Issue by Kingjhenny** [unstructuredstudio/zubhub#622]
**Describe the the feature request**
As beautiful and colourful as the Mobile version for Zubhub is, a dark mode feature would it all the more better, it would give people an option to choose what suits there eyes better. I opened Zubhub in a dark room at night trying to come up with ideas.. but when i got into the site the colorful-ness was blinding , glaring and not easy on the eyes.

@srish @tuxology , i would like work on this issue can you assign me ?

**Comment by darechan** [comment]
Hi @Kingjhenny can you please collaborate on #590 and provide UI mock ups for the same?

**Comment by tuxology** [comment]
Closing as duplicate of #590
