### ISSUE TITLE
Play Icon on Cards should pop :onhover 

### ISSUE THREAD

**Issue by i-am-rita** [unstructuredstudio/zubhub#623]
## Description
Play Icon on each card should :onhover pop another color also the play Icon(<img/>) should be a .svg file and not .png to make the icon not look bright and prompt an action.
<img width="403" alt="Screen Shot" src="https://user-images.githubusercontent.com/69390818/224249235-5007e83f-b6b0-4ead-9eef-9908cf2d9b2d.png">

**Comment by i-am-rita** [comment]
@srish @tuxology can you assign this task to me, I'll be happy to work on it.

**Comment by Kingjhenny** [comment]
> @srish @tuxology can you assign this task to me, I'll be happy to work on it.
 @i-am-rita If you agree i would be happy to assist you in this contribution

**Comment by i-am-rita** [comment]
> > @srish @tuxology can you assign this task to me, I'll be happy to work on it.
> > @i-am-rita If you agree i would be happy to assist you in this contribution
> > @Kingjhenny Sure!

**Comment by darechan** [comment]
@tuxology shall we merge this request with #620 as the issue same ?

**Comment by tuxology** [comment]
This can be merged with #620 @darechan Please change the description of #620 as well to better reflect the requested changes. Closing this.
