### ISSUE TITLE
Number of views on the eye icon

### ISSUE THREAD

**Issue by i-am-rita** [unstructuredstudio/zubhub#624]
**Description:**
The number of views should be on the upper-left side on the eye icon not under the icon so users can understand that the number is for the amount of views the video has gotten.

**Go to:**
Click on any of the cards and on the right hand of the video, you should see it.

**Screenshot:**
<img width="136" alt="View Screen Shot " src="https://user-images.githubusercontent.com/69390818/224270631-1b66d0d7-efcc-4634-b895-6a320099e12f.png">

**Comment by i-am-rita** [comment]
@srish @tuxology can this task be assigned to me? I'll be happy to fix it.

**Comment by srish** [comment]
No longer applicable
