### ISSUE TITLE
Make Footer links change color on hover

### ISSUE THREAD

**Issue by Collins-Omariba** [unstructuredstudio/zubhub#625]
I think it will be better and also intuitive to the users if the links in the footer changed color to say #03848c on hover.

![Screenshot (84)](https://user-images.githubusercontent.com/88287473/224274842-bf1569fc-a40d-4bc5-b785-9af22d968e78.png)

**Comment by Collins-Omariba** [comment]
@srish , @tuxology kindly assign me this issue so I can work on it.

**Comment by darechan** [comment]
`tabindex` attribute and `:focus` selector to the link elements and this should work.

**Comment by skynette** [comment]
@tuxology kindly assign me this issue I have a fix for it.
