### ISSUE TITLE
Email label is getting merged inside input border when open for the first time 

### ISSUE THREAD

**Issue by cherish2003** [unstructuredstudio/zubhub#627]
**Describe the bug**
In the password reset section the email is getting merged inside input border
**To Reproduce**
Steps to reproduce the behaviour:
1. Go to [Password reset section](https://zubhub.unstructured.studio/password-reset)
2. Click on input 
3. Observe that email label getting merged inside border

**Screenshots**
<img width="674" alt="Screenshot 2023-03-10 at 7 55 39 PM" src="https://user-images.githubusercontent.com/88829894/224341374-b7beadb7-88a7-4c96-b2be-6244e6683b3f.png">

**Comment by cherish2003** [comment]
@tuxology @srish if this issue is taken i want to work on this issue

**Comment by darechan** [comment]
can be recreated even with [Login Page](https://zubhub.unstructured.studio/login) 

### To Recreate
- Visit the login page
- Click on `Username or email` once

### Screenshot
![image](https://user-images.githubusercontent.com/93364240/224373759-ee390d69-230b-4648-ba01-c117b4c9fb2c.png)

UI testing for this is required and this issue can have more tasks added

**Comment by cherish2003** [comment]
@tuxology kindly check the PR #693 to close this issue

**Comment by Marhiposa** [comment]
@srish has this issue been solved if no can you assign it to me

**Comment by Dagmawi-22** [comment]
Can I take this one?

**Comment by brrkrmn** [comment]
Hey, I just opened #745 for this issue. @srish can you check it?

**Comment by MsVick** [comment]
> Hey, I just opened #745 for this issue. @srish can you check it?

Can I take this?

**Comment by JessicaItepu** [comment]
Dear team, could this project be assigned to me?

**Comment by Boluwatifey1** [comment]
@JessicaItepu the password reset page is showing error 404, so i think till that is resolved you cannot access the page

**Comment by ChrisFeji247** [comment]
Can I please be assigned to this
