### ISSUE TITLE
Hide "Scroll back to top" button when already on top

### ISSUE THREAD

**Issue by ipriyanshi1708** [unstructuredstudio/zubhub#628]
Hi! @srish @tuxology, Scroll to top button should not be visible when user is already at the top of the website.

![image](https://user-images.githubusercontent.com/92941945/224346690-e75981f7-dc3d-456e-a07d-eaf724f4ca99.png)

Thanks!

**Comment by ipriyanshi1708** [comment]
Hi! @srish @tuxology, I am an Outreachy applicant. Please assign this issue to me, I will be very happy working on this.

**Comment by tuxology** [comment]
@ipriyanshi1708 Please also change color to the exact zubhub red as per the palette. There is a slight difference in the color of the button as well.

**Comment by coderatomy** [comment]
is this still needed @srish. I wish to take over

**Comment by Chinecherem-dot** [comment]
If this issue is still open, I would love to be assigned to this @srish

**Comment by yokwejuste** [comment]
> If this issue is still open, I would love to be assigned to this @srish

There is already an opened PR, please check the messages above and the time when the issue was assigned too

**Comment by Chinecherem-dot** [comment]
> > If this issue is still open, I would love to be assigned to this @srish
> 
> There is already an opened PR, please check the messages above and the time when the issue was assigned too

Noted and thank you!

**Comment by coderatomy** [comment]
Thanks @Chinecherem-dot for concern on this. Am actually waiting for a review from @tuxology. Feel free to checkout the conversations on this topic and the PRs and share your suggestion. You share them here or on my new PR
