### ISSUE TITLE
Make buttons hoverable

### ISSUE THREAD

**Issue by ipriyanshi1708** [unstructuredstudio/zubhub#629]
Hi! @srish @tuxology , Only "Share a Project" button has hover effect but it will be a better idea if we add hover effect to "Explore ideas" and "Be our Ambassador" buttons.

![image](https://user-images.githubusercontent.com/92941945/224375737-5e4997d1-8315-41cd-a4e7-95f42753cd39.png)

**Comment by ipriyanshi1708** [comment]
Hi! @srish @tuxology, I am Outreachy applicant. Please assign this issue to me.

Thanks!

**Comment by skynette** [comment]
@ipriyanshi1708  I believe the "Explore ideas" and "Be our Ambassador" buttons already have the hover effect

**Comment by darechan** [comment]
@tuxology looking at the code for these button 

```
  darkDangerButtonStyle: {
    borderRadius: 30,
    backgroundColor: '#9A0036',
    color: 'white',
    '&:hover': {
      color: 'white',
      backgroundColor: '#9A0036',
    },
  },
  customWarningButtonStyle: {
    borderRadius: 30,
    backgroundColor: '#FECB00',
    color: '#896e00',
    '&:hover': {
      color: '#896e00',
      backgroundColor: '#FECB00',
    },
  },
  ```

technically they should be hoverable but there seem to be some issue with that? I cannot recreate this on my local system can you confirm?

**Comment by tuxology** [comment]
@darechan They do not change on my system as well

**Comment by darechan** [comment]
> @darechan They do not change on my system as well

found the error, the colour for changing on hover is same as the button
can you please provide me with the hex code so we could close this?

**Comment by tuxology** [comment]
@darechan Try some iterations and send a PR so we can review
