### ISSUE TITLE
Projects not getting sorted according to category on click

### ISSUE THREAD

**Issue by darechan** [unstructuredstudio/zubhub#630]
## The Bug
In certain projects, when you visit a project and click on the category of that project instead of directing you to a page that has all the projects in that category it directs to `No Result Found` Page. 

Example of such categories:
1. Electronics
2. Music
3. Art
4. etc

## To Reproduce

1. Visit [Zubhub](https://zubhub.unstructured.studio/)
2. Click on any project (for example: https://zubhub.unstructured.studio/projects/0f2bf6bd-2a44-4da7-8d4d-2330070d5339)
3. Scroll to the category and click on the category (in this case `electronics`)

## Expected Behavior

Be directed to a page with all the project of that category instead of this [page](https://zubhub.unstructured.studio/search?q=Electronics)
For some categories it works fine as you visit a project (Example: https://zubhub.unstructured.studio/projects/0848243c-5381-45f3-bacb-e60c58fdda73) and click on the [category](https://zubhub.unstructured.studio/search?q=Mechanical) you land on the correct page

## Screenshots

Visit a project: 
![image](https://user-images.githubusercontent.com/93364240/224380758-0417276c-1d94-4135-9913-7f6c996e0e96.png)

Click on category:
![image](https://user-images.githubusercontent.com/93364240/224380907-431a0284-3508-4b86-898c-2dfa6eef63d6.png)

Directs to: 
![image](https://user-images.githubusercontent.com/93364240/224381161-2aea243d-c1b2-4e96-a382-051cbf09200a.png)

**Comment by darechan** [comment]
@tuxology 
If we look at the network response of the website, it is receiving data for the search but for some reason it's just not getting displayed. I think this is more of a backend than frontend bug.

![image](https://user-images.githubusercontent.com/93364240/224387823-c75eca11-0cdd-4109-9d8a-f32fcd573bfd.png)

**Comment by iamhks** [comment]
Hi @darechan thankyou for finding and reporting this bug.
Since, you're a UI/UX designer, and this is a dev issue I would like to work on it.
Hopefully you're okay with this.

**Comment by darechan** [comment]
> Hi @darechan thankyou for finding and reporting this bug.
> Since, you're a UI/UX designer, and this is a dev issue I would like to work on it.
> Hopefully you're okay with this.

No, i am not a designer I am dev as well and I have a working branch for this issue if you don't mind. Thanks.

**Comment by iamhks** [comment]
@darechan Oh cool then! All the best!

**Comment by tuxology** [comment]
Assigned to you @darechan 👍

**Comment by srish** [comment]
Closing this for now, as the category field has another critical issue right now (to be filed soon).
