### ISSUE TITLE
Login and Sign Up do not get scaled along with the entire page 

### ISSUE THREAD

**Issue by darechan** [unstructuredstudio/zubhub#631]
## The bug

If you scale the browser, all the components except the `Login` and `Sign Up` gets scaled along with the page.
If you zoom out up to 50%, the nav bar component ends at a space.

## To Reproduce

- Visit zubhub
- Zoom out from you page and then zoom in

## Expected behavior

Login and sign up button should scale along with the entire website

## Screenshots

On 100%
![image](https://user-images.githubusercontent.com/93364240/224389385-7533007e-e490-403a-8540-247faca82972.png)

On 75%
![image](https://user-images.githubusercontent.com/93364240/224389476-db564ed7-909b-4919-ab09-b246fc176154.png)

On 50%
![image](https://user-images.githubusercontent.com/93364240/224389608-ce58c002-48ff-4edd-b91a-e5c48cfbe7a2.png)

Nav bar ending

![image](https://user-images.githubusercontent.com/93364240/224390025-bfb39cbe-89f6-41fe-8eca-170400873a95.png)

**Comment by darechan** [comment]
Would love to be assigned for the same

**Comment by tuxology** [comment]
Yes, I've heard this from other users also now, so lets fix this fast @darechan Its a quick fix, I tested on my machine.

**Comment by darechan** [comment]
@tuxology the similar issue is also with browse and create project 

Zoom 100%
![image](https://user-images.githubusercontent.com/93364240/224484303-cbac2bca-3eaa-41da-880f-5e57d23db8ca.png)

Zoom 80%
![image](https://user-images.githubusercontent.com/93364240/224484334-bdd930f8-728c-47f1-aaf7-535d17b5f37e.png)

Also, can we replace `create project` button with a plus icon?

![image](https://user-images.githubusercontent.com/93364240/224484468-05dc0023-da02-4e88-bd71-4fc8892d75b7.png)

this looks a bit more professional

**Comment by Rosietta-UIUX** [comment]
@darechan instead of just the "+ icon" the create project button can be a combination of icon & text 
" + Create project "

**Comment by darechan** [comment]
@Rosietta-UIUX wouldn't that increase the button size and make the page look too packed?

**Comment by Rosietta-UIUX** [comment]
@darechan with just the + icon the users might not easily understand what it's for at first. Instead to avoid the page looking packed the browse activity button can be made into just a text button without the fill color or removed from there entirely since the main CTA is to create a project. Also the top navigation could be redesigned to fit the buttons. Don't know if you get what I'm trying to say.

![Polish_20230311_151506728.png](https://user-images.githubusercontent.com/123890450/224489617-ad2f956a-8cd7-466a-8c26-c0a4bf06d5a4.png)

**Comment by darechan** [comment]
yeah I do agree it can be confusing at first, we can have a discussion for button design based on whatever @tuxology says

**Comment by Rosietta-UIUX** [comment]
Alright @darechan
