### ISSUE TITLE
Rooms/Chat Feature 

### ISSUE THREAD

**Issue by Rosietta-UIUX** [unstructuredstudio/zubhub#633]
Hi @srish @tuxology @darechan @sethiastha

I worked on a grouping/Room User interface on ZubHub that allows users to create a group and add or remove members, making the room public or private and chat with other users.

**Figma file:** https://www.figma.com/file/znHmUthh7VmGk5W9StISSc/ZubHub-Project?node-id=236%3A25&t=N56ogQ9wscGvd3fc-0

**Prototype Link:** https://www.figma.com/proto/znHmUthh7VmGk5W9StISSc/ZubHub-Project?node-id=236%3A26&scaling=scale-down-width&page-id=236%3A25&hide-ui=1&starting-point-node-id=236%3A26

**Proposed Landing Page** 
![Landing page](https://user-images.githubusercontent.com/123890450/224290833-6c942be5-123f-43fb-ba8d-5076287930b6.png)

**After Login**
![Home page](https://user-images.githubusercontent.com/123890450/224290971-261e07a9-fbc4-44a2-be1b-ffc0e722ec5d.png)

**Find Room/Groups**
![Find room page](https://user-images.githubusercontent.com/123890450/224291117-bcc73d38-8fce-4045-8248-d2c4ee48581b.png)

**Create Room/Group**
![createroom page](https://user-images.githubusercontent.com/123890450/224291219-8934d450-2f25-4df6-9cca-3bbb66cb476e.png)

**Chat Interface**
![Room interface](https://user-images.githubusercontent.com/123890450/224291336-90a484fc-482a-45cc-b476-048c53f272cc.png)

_Originally posted by @Rosietta-UIUX in https://github.com/unstructuredstudio/zubhub/discussions/560#discussioncomment-5265934_

**Comment by psalmuelle** [comment]
Adding a Room/Chat feature to zubhub will really improve user interaction, and also improve communications among students. Weldone @Rosietta-UIUX !

**Comment by darechan** [comment]
This seems like a brilliant idea. This feature can be divided into subtasks and worked upon. 
We could add in more elements like sharing project directly to the room/chat and design a structure for public and private rooms. 
Very interesting feature and I'd love to collaborate on this with mentors @tuxology @srish and @Rosietta-UIUX  because right now this raw idea has a lot of room for improvement as we will also have to make sure that there is language sensitization as the website carters to young audience.

**Comment by Rosietta-UIUX** [comment]
Hello @tuxology @srish, please assign me and @darechan to work on this

**Comment by ipriyanshi1708** [comment]
Hi @tuxology @srish @Rosietta-UIUX , I am a Frontend developer and would love to collaborate with you on this issue.

**Comment by Rosietta-UIUX** [comment]
Hello @sethiastha,@tuxology @srish I would really appreciate it if I can be assigned to this issue to further work and improve on it. Looking forward to your response. Thank you

**Comment by srish** [comment]
@Rosietta-UIUX Thank you for contributing these fantastic designs! Building a chat room feature is not part of ZubHub's roadmap, so I will close this task for now. 

We will promote another design project via the next round of Outreachy, so you are welcome to apply again. :) 

Also, do you have a link to the source of the illustration that you have used on the cover image, and do ou mind sharing it with us at hello@unstructured.studio? We would love to consider it for the cover image design.
