### ISSUE TITLE
Screen goes blank after making mistake in the URL

### ISSUE THREAD

**Issue by psalmuelle** [unstructuredstudio/zubhub#635]
**Describe the bug**
When there is a mistake in the URL, like [https://zubhub.unstructured.studio/rres](https://zubhub.unstructured.studio/rres), the screen goes blank- doesn't display anything.
![Screenshot 2023-03-10 212542](https://user-images.githubusercontent.com/81099447/224422188-82c25e14-1af8-4471-b23c-36694f632abc.jpg)

**To Reproduce**
1. Go to [https://zubhub.unstructured.studio/rres](https://zubhub.unstructured.studio/rres),

**Expected behavior**
An error page that has a button that redirects to the homepage.

**Comment by psalmuelle** [comment]
We can work on creating a UI for the error page. It will help improve user experience.

**Comment by tuxology** [comment]
Nice, good one! Lets build an error page. Look for a standard template like we use with Oops and stuff, But replace icons and such and add button to redirect.

**Comment by Temabo** [comment]
Hello @tuxology @psalmuelle I am a designer, can I design the error page so that @psalmuelle can implement it?

**Comment by psalmuelle** [comment]
Alright, @tuxology . I'll work on it
@Temabo , Sure! We can work together on it.

**Comment by Temabo** [comment]
> Alright, @tuxology . I'll work on it
> 
> @Temabo , Sure! We can work together on it.

Great! Please send your email so we can communicate better. I'd start working on it now

**Comment by psalmuelle** [comment]
Sorry, I can't share because this is a public space.
Kindly signify on zulip chat, so I can dm you my email address. Or better still, kindly check my GitHub profile

**Comment by Temabo** [comment]
> Sorry, I can't share because this is a public space.
> 
> Kindly signify on zulip chat, so I can dm you my email address. Or better still, kindly check my GitHub profile

Trueee, I'd reach out to you on Zulip!

**Comment by Temabo** [comment]
Hi @psalmuelle @tuxology @srish 
![Desktop - 15](https://user-images.githubusercontent.com/105416140/224463301-a18c8e05-69b1-4b47-9a1c-a42ba47d3c45.png)
This is the link to the design, the mobile view is on it too, check it out and let me know your thoughts https://www.figma.com/file/A1GYQtENXSmPUzB63MTgPj/outreachy?node-id=107%3A1255&t=I94nPAhEX8sfF2BN-1

**Comment by yaya-mamoudou** [comment]
> Hi @psalmuelle ![Desktop - 15](https://user-images.githubusercontent.com/105416140/224463301-a18c8e05-69b1-4b47-9a1c-a42ba47d3c45.png) This is the link to the design, the mobile view is on it too, check it out and let me know your thoughts https://www.figma.com/file/A1GYQtENXSmPUzB63MTgPj/outreachy?node-id=107%3A1255&t=I94nPAhEX8sfF2BN-1

I love this @Temabo. Really nice

**Comment by Temabo** [comment]
Thank you @yaya-mamoudou 👍🏾

**Comment by psalmuelle** [comment]
> > Hi @psalmuelle ![Desktop - 15](https://user-images.githubusercontent.com/105416140/224463301-a18c8e05-69b1-4b47-9a1c-a42ba47d3c45.png) This is the link to the design, the mobile view is on it too, check it out and let me know your thoughts https://www.figma.com/file/A1GYQtENXSmPUzB63MTgPj/outreachy?node-id=107%3A1255&t=I94nPAhEX8sfF2BN-1
> 


The design is really nice! It's really great you were able to come up with this design within this short time.
Did you intentionally omit the breadcrumb below the header?

The design looks good. Let's wait for @tuxology to review the design before implementing it!
Thank you @Temabo

**Comment by Temabo** [comment]
@psalmuelle i wasn't show if I should include it. If it's needed I can quickly add it

**Comment by psalmuelle** [comment]
Alright, let's wait for suggestions from a mentor!

**Comment by yaya-mamoudou** [comment]
@Temabo and @psalmuelle. If I understand well you have to add a 404 page for this type of scenario.

So, I think that the message **Something went wrong** is not really good experience for the user. 
`In this case, we want to let the user know that the page they are trying to access doesn't exist`. 
Sometimes too, the page might exist but they need to be logged in to be able to access it.
In this scenario, some other websites provide messages like:
```
You might not be able to access this page for the following reasons:

1. This page doesn't exist
2. The page might require you to be authenticated before

```
So these are some examples.  Let me know what you think.

**Comment by sethiastha** [comment]
> Hi @psalmuelle @tuxology @srish ![Desktop - 15](https://user-images.githubusercontent.com/105416140/224463301-a18c8e05-69b1-4b47-9a1c-a42ba47d3c45.png) This is the link to the design, the mobile view is on it too, check it out and let me know your thoughts https://www.figma.com/file/A1GYQtENXSmPUzB63MTgPj/outreachy?node-id=107%3A1255&t=I94nPAhEX8sfF2BN-1

**Comment by sethiastha** [comment]
This is a great design. I liked the idea of displaying a CTA that redirects to the homepage.

**Comment by sethiastha** [comment]
@Temabo This is a great design. I liked the idea of displaying a CTA that redirects to the homepage.

**Comment by Temabo** [comment]
> @Temabo and @psalmuelle. If I understand well you have to add a 404 page for this type of scenario.
> 
> 
> 
> So, I think that the message **Something went wrong** is not really good experience for the user. 
> 
> `In this case, we want to let the user know that the page they are trying to access doesn't exist`. 
> 
> Sometimes too, the page might exist but they need to be logged in to be able to access it.
> 
> In this scenario, some other websites provide messages like:
> 
> ```
> 
> You might not be able to access this page for the following reasons:
> 
> 
> 
> 1. This page doesn't exist
> 
> 2. The page might require you to be authenticated before
> 
> 
> 
> ```
> 
> So these are some examples.  Let me know what you think.

Yes this is true, I get your point. I'd work on another and put it there as a copy so the mentors can decide

**Comment by Temabo** [comment]
Thank you 🙏 @sethiastha

**Comment by tuxology** [comment]
What is the source of the "frustrated robot" image? Is it self drawn? Either we use a self drawn image or we should use images licensed under creative commons license. One source to look at is https://openclipart.org

**Comment by Temabo** [comment]
@tuxology i designed it with Figma
You can view it on this link

https://www.figma.com/file/A1GYQtENXSmPUzB63MTgPj/outreachy?node-id=107%3A1255&t=I94nPAhEX8sfF2BN-1

**Comment by tuxology** [comment]
@Temabo Wow, this is so cool!! 🎉 Is this complete done in Figma or some other vector graphic tool? Lets build this @psalmuelle  🤝

**Comment by Temabo** [comment]
Thank you! @tuxology I used figma only for it. Drew it with the pen tool

**Comment by psalmuelle** [comment]
> @Temabo Wow, this is so cool!! 🎉 Is this complete done in Figma or some other vector graphic tool? Lets build this @psalmuelle 🤝

Alright! I am on it already. Thank you!

**Comment by psalmuelle** [comment]
@tuxology , I have made a PR to this issue, having implemented the design provided by @Temabo 
![localhost_3000_oo-bigScreens](https://user-images.githubusercontent.com/81099447/225002856-3530fb46-6c04-43bb-ac30-20b5dc3e8dee.png)

![localhost_3000_oo(Pixel 5)](https://user-images.githubusercontent.com/81099447/225003554-bc23108a-c367-4a4c-b7c8-1a0e4907d265.png)
