### ISSUE TITLE
Align username and type properly and resize hero font on mobile view

### ISSUE THREAD

**Issue by KramStyles** [unstructuredstudio/zubhub#638]
## Description
When you visit the homepage on your mobile device, you'd notice the write up under the `creative challenges 2023` is a bit too large. 
![Screenshot_20230310-233630](https://user-images.githubusercontent.com/21022645/224442146-e4d310ef-8f0f-466f-99b3-4b53e2bbc21f.jpg)

You'd also notice that the username and user type under the card description are not properly aligned horizontally.
![Screenshot_20230310-233659](https://user-images.githubusercontent.com/21022645/224442168-39bdddcb-1e17-4d84-804d-086cb6711084.jpg)

## Todo

- Modify the font size of the text on mobile view not to be too large.
- Ensure the username and user type in the card are well aligned horizontally and vertically

**Comment by KramStyles** [comment]
Can this please be assigned to me if approved ? @tuxology

**Comment by ipriyanshi1708** [comment]
Hi @tuxology, I would love to contribute to this issue. Please assign it to me.

**Comment by srish** [comment]
No more applicable
