### ISSUE TITLE
Improve UI for categories

### ISSUE THREAD

**Issue by skynette** [unstructuredstudio/zubhub#640]
Currently, the way categories are displayed on the website doesn't look as visually appealing as other sections, such as the "Materials Used" section. This could make it more difficult for users to quickly find the categories they are looking for, which could impact their overall user experience.

![image](https://user-images.githubusercontent.com/29153968/224455130-68e6baea-5a89-419d-91b4-09e7cab7748f.png)

To improve the UI for displaying categories, we could explore different design options that could make the categories more visually appealing and easier to navigate.

**Comment by Burnleydev1** [comment]
Hello, can I work on this

**Comment by darechan** [comment]
duplicate of #172

**Comment by skynette** [comment]
okay will close this issue
