### ISSUE TITLE
Unclear and vague descriptions in the documentation file. 

### ISSUE THREAD

**Issue by EbukaOkoye** [unstructuredstudio/zubhub#644]
I went through the documentation and i noticed some places that can improved on

for example, Some of the instructions are incomplete and assume a certain level of familiarity with the tools and technologies used in ZubHub's development. Being an open source, contributors should find the documentation very detailed in other to install and access the project fully. Citing the instructions for setting up, the backend assume that the reader is familiar with Docker and Docker Compose.

Thirdly, there are instances where some words are unclear in the documentation. An example is the the term "creator portfolios" which is used without any explanation of what it means. Also, the "Windows Specific Setup" section assumes that the reader already knows why they need to install certain tools.

I have written and worked on the documentation locally

**Comment by EbukaOkoye** [comment]
<img width="1280" alt="Screenshot 2023-03-11 at 07 03 54" src="https://user-images.githubusercontent.com/92609307/224491789-f14d2e64-6f17-4a04-855d-b9ad8fbd8945.png">

**Comment by tuxology** [comment]
Please submit a PR. Thanks 👍
