### ISSUE TITLE
No Page for user to preview Project before submission

### ISSUE THREAD

**Issue by iamexousia** [unstructuredstudio/zubhub#646]
After going through the Zubhub's platform and creating a demo project, i realized that at the project creation stage, there is no where to preview your project and make changes before submission.
![drafts - edit drafts - top_unstructuredstudio](https://user-images.githubusercontent.com/46329513/223691470-0de6ff58-eb41-423b-87dd-fe6b62de44d1.png)

_Originally posted by @iamexousia in https://github.com/unstructuredstudio/zubhub/discussions/558#discussioncomment-5240113_

**Comment by iamexousia** [comment]
i Iterated on the Preview page idea and was able to come up with further UX solutions to the project creation feature.

1. I improved the UX writing of the project creation to convey the messages in a way that would be very easy for any one to understand. I also improved the flow of the project creation feature.  broke it down into stages to reduce the information overload the user might be feeling. 
![drafts - edit drafts - top_unstructuredstudio (5)](https://user-images.githubusercontent.com/46329513/224489628-2a00f341-64c3-4655-aa4c-23e88a92c652.png)

![Group 160](https://user-images.githubusercontent.com/46329513/224489598-686fc7c9-cf40-4ee4-9f14-73cc6043d5c9.jpg)

2. Video And Photo: I improved the UX of the Photo and Video upload to a singlular secton named "Media" that allows users to upload any media file, either Video or image. The user is also able to upload from the internet by inputing the video url and uploading. Also i improved the UX of the material used. instead of the current UX and interface of adding materials in a listed format. i checked other Interface designs to get insight into modern Ui practices to make the UX easier for the user.
![drafts - edit drafts - top_unstructuredstudio (6)](https://user-images.githubusercontent.com/46329513/224490005-827778f9-7252-4bb8-a0b7-61af34b2c2e9.png)
![Group 160 (1)](https://user-images.githubusercontent.com/46329513/224490318-2a4c8b82-dfdb-42bb-95a7-c2b31e3cd204.jpg)

3. PROJECT TAGS: I Improve the UX of adding tags to the project. multiple tags are going to be added in a single field.
![drafts - edit drafts - top_unstructuredstudio (7)](https://user-images.githubusercontent.com/46329513/224490455-2385db0c-1582-42f2-8c2f-e220df1d1733.png)

4. PREVIEW PROJECT: This page is missing from the current flow of the project creation feature, I Worked on the Page using the existing Design style. This page would help the user to get a preview of all the details they have entered in the project creaton process and also make corrections to a particular information without having to go back multiple steps . The user can simply click on the "Edit" button and the field is changed to the edit state.
![drafts - edit drafts - top_unstructuredstudio (10)](https://user-images.githubusercontent.com/46329513/224491580-6d083719-c24f-4660-9820-30c262400dbf.png)
![drafts - edit drafts - top_unstructuredstudio (9)](https://user-images.githubusercontent.com/46329513/224491582-aed79b25-8af8-44c3-9367-ea3192af635b.png)
![Group 160 (2)](https://user-images.githubusercontent.com/46329513/224491606-cd5c7066-dd37-407d-a22c-c9ae6f4db70a.jpg)

I would be expecting your feedback on this wheter to raise it as an UX issue and  a developer gets to implement it. @tuxology Thanks

**Comment by tuxology** [comment]
These are all good suggestions @iamexousia 🎉  Please add them to #557 or on discussion #558 (as you have already done I believe) There is no need to create a new issue for previewing a project since the work in #557 is about overhaul of the Project/Activity creating experience. I am closing this as there is nothing actionable yet on this that we can work on.
