### ISSUE TITLE
"Challenge" page  need to be placed where it is Visible

### ISSUE THREAD

**Issue by Atinukepamper1** [unstructuredstudio/zubhub#648]
**As a user on the website, i do not think i will see where the challenge button is placed**
i have been surfing zubhub website for 2 day plus and i did not notice the challenge button that leads to an important advertisement of "zubhub science and creativity challenge 2023"
As important as this feature is as it can help promote the website to creators and educators who would want their students to be creative while competing, the placement is wrong. it will not catch users attention
it is situated at the footer under the about section, user who come to the site might not see this, to take part and tell other creators too.
![IMG_20230311_223201_755](https://user-images.githubusercontent.com/105361517/224513926-fcfb2bbd-bd41-40c9-b6a8-c3d73215b008.jpg)

I reposition it by placing it at the footer 
![Challenge](https://user-images.githubusercontent.com/105361517/224513883-b2d67820-2360-4710-9008-59d174736fed.png)

placing it here will attract users and also promote Zubhub website to the world
I will like to work on the UX if approved

**Comment by Atinukepamper1** [comment]
i will love to work on this if approved and also with a developer @tuxology

**Comment by darechan** [comment]
@Atinukepamper actually there is a button for challenges on the website 
![image](https://user-images.githubusercontent.com/93364240/224554127-8d4562ec-624e-4263-89f0-1cc487b8a38b.png)

If you click on this image you will get directed to the challenge page. 
May be we could create it a bit more prominent? @tuxology @srish

**Comment by the-techgurl** [comment]
@darechan It's more of a banner than a button and could easily be unnoticed especially by those new to the site.

**Comment by sethiastha** [comment]
That's a good observation. 'Creative Challenge 2023' can be more visible if it's a button rather than a sticker on the banner. You can explore more designs around this.

**Comment by Atinukepamper1** [comment]
You can see that I did not notice it was a CTA banner, If the creative challenge is placed as a button at the header it can never go unnoticed, this button is like an important aspect of the website that can promote the website to creators and organizations  @darechan

**Comment by ipriyanshi1708** [comment]
Hi @Atinukepamper, I am an Outreachy applicant and a frontend developer and would love to collaborate on this issue with you. @srish @Atinukepamper @tuxology Please assign this task to me.
