### ISSUE TITLE
Improving privacy policy page 

### ISSUE THREAD

**Issue by darechan** [unstructuredstudio/zubhub#650]
## Suggestion

The [Privacy Policy](https://zubhub.unstructured.studio/privacy_policy) page of Zubhub needs a lot of improvement with the styling and documentation.

### 1. Privacy Policy header is repeated twice

![image](https://user-images.githubusercontent.com/93364240/224538537-616c0b4b-b7fc-4edd-938a-9abe4b73d3db.png)

### 2. Using hyperlinks

![image](https://user-images.githubusercontent.com/93364240/224538606-520a8f02-6893-421d-9d8b-ec3df013161b.png)
![image](https://user-images.githubusercontent.com/93364240/224538728-2d92a212-7266-4297-b3df-e7f23227fd21.png)

### 3. Linking sections for ease of use

![image](https://user-images.githubusercontent.com/93364240/224538671-5d68e4d9-64f5-4430-97e2-e4eebffda18b.png)

### 4. Using justify alignment for professional look

![image](https://user-images.githubusercontent.com/93364240/224538759-f2cd39cc-86b4-441a-a3b5-bba8bbbf728a.png)

### 5. Correcting grammatical mistakes and case

`date` instead of `data of birth`
![image](https://user-images.githubusercontent.com/93364240/224539172-f8d75d81-4d12-449c-a986-9d022c0fdd3b.png)

`P` for `Phone number` is capital
![image](https://user-images.githubusercontent.com/93364240/224539251-996ecdd1-1ace-43c7-9531-676f1b1d1a03.png)

`re-enrollment` spelling error
![image](https://user-images.githubusercontent.com/93364240/224539423-04d4d572-c642-4a97-b415-b3da439fffb3.png)

**Comment by darechan** [comment]
@tuxology since this is dynamically generated it cannot be worked upon by other contributors please look at the issue.

**Comment by tuxology** [comment]
Fixed
