### ISSUE TITLE
Password reset not checking if user already has an account before validating the request.

### ISSUE THREAD

**Issue by yaya-mamoudou** [unstructuredstudio/zubhub#654]
**Describe the bug**
When we access the password [reset page ](https://zubhub.unstructured.studio/password-reset), and we add an email address that isn't tied to an existing user in the system, we get a success message from the API saying `Password reset e-mail has been sent`
This should not be the case as password reset emails should only be sent to those that had previously created an account on zubhub.

**To Reproduce**

1. Go to https://zubhub.unstructured.studio/password-reset
2. Enter a creative email that you think doesn't exist on the app 
3. Submit the form
4. See error or check the network tab to see the response of the API

**Expected behavior**
When an email doesn't exist on the platform, the API should indicate it and we can let the user know that the email they used doesn't exist on the platform. This will also help us not to send unnecessary emails to people that don't have accounts.

**Comment by yaya-mamoudou** [comment]
@tuxology this is a Full-stack work. To implement this, I will do some work on the backend to check if the user exists and provide a proper response to the frontend.

**Comment by yaya-mamoudou** [comment]
@tuxology please if the issue is valid, I'll like to be assigned this issue.

**Comment by skynette** [comment]
@tuxology can you review my fix for this issue

**Comment by yaya-mamoudou** [comment]
Hi @skynette. This issue has been assigned to me and work is still in progress
