### ISSUE TITLE
Simplified tutorial on how to create a project feature.

### ISSUE THREAD

**Issue by comfy96** [unstructuredstudio/zubhub#655]
hello @srish @tuxology 

From our feedback, we realized that a fifth-grade student may not be able to input as much information as a tenth-grade student. The goal is to design the form in a way that allows children in the 5th grade to go about their learning activities unsupervised by

1.  adding clues in a video format on step by step process to create a project
2. A feature to record their voice instead of typing.

![CREATE PROJECT SCREEN 1 (1)](https://user-images.githubusercontent.com/57982384/224665682-51e54205-60cb-404e-9480-14922cf956bd.png)
![screen 2 new (2)](https://user-images.githubusercontent.com/57982384/224665742-b784af2d-6a3b-45fd-a03a-a551c872cc1e.png)
![screen 3 (1)](https://user-images.githubusercontent.com/57982384/224665825-99153201-eca1-4fe4-863a-1dedfbf64021.png)
![Screen 4 (1)](https://user-images.githubusercontent.com/57982384/224665871-481f1025-0c89-41ed-8af0-54d4b520cae1.png)
![Screen 5 (1)](https://user-images.githubusercontent.com/57982384/224665907-c5d875af-c9cf-4163-b0ea-1261cbb73e20.png)
![Screen 6 (1)](https://user-images.githubusercontent.com/57982384/224665950-69c8ab2c-7db6-4969-9df2-6865bbf6d459.png)

View link to problem statement(solution):
[https://docs.google.com/document/d/1-kRQfhG3e8eFKF_1PdRsRVgZsKinq89XU0mtpcUCkcs/edit#heading=h.1sekce2by8gm](url)
Figma link:
[(https://www.figma.com/file/utMFy7GSxuxXrhM2kxN5nI/OUTREACHY-PROJECT-SOLUTION?node-id=120%3A603&t=ok4pvSmzUTQNaWbg-0)](url)
Prototype link:
[https://www.figma.com/proto/utMFy7GSxuxXrhM2kxN5nI/OUTREACHY-PROJECT-SOLUTION?node-id=101%3A350&scaling=scale-down&page-id=0%3A1&starting-point-node-id=101%3A350](url)

**Comment by tuxology** [comment]
Thanks @comfy96 For your inputs! 🎉  Can you please move them to #557 and/or #558. Since there is nothing actionable here in terms of feature/enhancement/bug, that we have decided on yet I am closing this issue.

**Comment by comfy96** [comment]
thank you @tuxology
