### ISSUE TITLE
Nav bar integrity broken

### ISSUE THREAD

**Issue by darechan** [unstructuredstudio/zubhub#656]
## The bug
The nav bar for [zubhub](https://zubhub.unstructured.studio/) lost its integrity to hold other components and all of them overlap and scale based on the scaling of the browser. This is most probably a regression issue that some code got reversed back for the same in a PR.

### Brave Browser 
On 100%
![image](https://user-images.githubusercontent.com/93364240/224692532-a5f7e417-f30a-42c6-8704-83d7821a9f8b.png)

On 80%
![image](https://user-images.githubusercontent.com/93364240/224692708-b6f12622-f1b2-4a37-8bd5-a3fe266cc03b.png)

### Chrome

On 100%
![image](https://user-images.githubusercontent.com/93364240/224692805-2cfc7a66-aa42-4d07-90c2-7cf14bbc54ff.png)

On 80%
![image](https://user-images.githubusercontent.com/93364240/224692864-5451575b-5993-4d06-bb28-b79f8182e341.png)

**Comment by darechan** [comment]
@tuxology @srish Please check immediately

**Comment by Burnleydev1** [comment]
hello @darechan, if this issue is approved can I work on it.

**Comment by yaya-mamoudou** [comment]
@darechan I just checked on my end and everything works fine. What browser are you using? And have you pulled the latest changes to your local? because even the [live version](https://zubhub.unstructured.studio/) of the app doesn't behave like that?
