### ISSUE TITLE
Creator/Staff image, name/email and tag not aligned

### ISSUE THREAD

**Issue by i-am-rita** [unstructuredstudio/zubhub#657]
## Description
On the list of projects and all projects cards, the creator image, name and tag are not aligned.

How it currently looks 
<img width="1184" alt="Screen Shot 2023-03-13 at 1 51 15 PM" src="https://user-images.githubusercontent.com/69390818/224712196-7561f781-7507-4d6e-9b5e-4651371ec2da.png">

How I think it should look (aligned/on a straight line): 
<img width="409" alt="Screen Shot 2023-03-13 at 1 45 03 PM" src="https://user-images.githubusercontent.com/69390818/224712977-6130a571-a8eb-4ae1-a7fc-15f272726990.png">

**Comment by i-am-rita** [comment]
@tuxology I am an Outreachy contributor and would appreciate if I am assigned to fix this issue.

**Comment by comfy96** [comment]
Hi, I'd appreciate it if I am assigned this issue. thank you.

**Comment by tuxology** [comment]
@i-am-rita Can you verify if #528 Fixes this? If yes, we keep this open, else close this. Thanks!

**Comment by i-am-rita** [comment]
@tuxology Yes, I think #528  will fix this when what was discussed there about the username and the design is implemented. Thank you.

**Comment by tuxology** [comment]
OK, we can close this for now 👍

**Comment by i-am-rita** [comment]
Great, thanks!
