### ISSUE TITLE
On the header section and body text, of the 'zubhub' website the Text written in Hindi doesn't translate to english.

### ISSUE THREAD

**Issue by comfy96** [unstructuredstudio/zubhub#658]
When I clicked on the cards under 'project from our recent creative learning workshop' I went to the card that is written in Hindi, when I tried to translate it to English, it didn't work.
 
To fix the translator setup ;

- add the function() In the website Title and body section of individual post
@tuxology

**Comment by comfy96** [comment]
@tuxology

**Comment by darechan** [comment]
can you explain with with screenshots?

**Comment by comfy96** [comment]
Yes please

**Comment by comfy96** [comment]
When I clicked on the middle card that contain the 'Hindi' text, it took me to the next screen;

![Screenshot (114)](https://user-images.githubusercontent.com/57982384/224759810-9d6eac42-5dde-4777-bf42-26bfadc17e83.png)

It brought me here;
![Screenshot (115)](https://user-images.githubusercontent.com/57982384/224760224-918c9dfb-3234-4c81-9729-dd783513f479.png)

I went further to change the translator from 'Hindi' to 'English'  But the translator didn't work as seen in the image below;

![Screenshot (116)](https://user-images.githubusercontent.com/57982384/224760462-6c62236c-cc34-4b48-92c2-b4069e972ab9.png)

I noticed the same issue with the body text on 'DESCRIPTION' and 'MATERIAL USED'

![Screenshot (117)](https://user-images.githubusercontent.com/57982384/224761092-e9a6ffda-3e0e-4299-ace0-ed13d53a42fa.png)

Lastly, on the comment section, I tried to change the translator to English so I can read the comment but it only change the 'year' and the 'REPLY' while the comment remained in 'Hindi'.

![Screenshot (118)](https://user-images.githubusercontent.com/57982384/224762966-c7a186d1-57e2-4cd8-bd97-49b8fd0591c8.png)

The translator;

![Screenshot (119)](https://user-images.githubusercontent.com/57982384/224764041-e14b6a4b-4dd5-4743-9675-5c553a7e916c.png)


I hope I made justice to this. meanwhile, I am open to more discussion and feedback. thank you. @darechan @srish @tuxology

**Comment by tuxology** [comment]
This is essentially not a bug. The goal of the translator is only to change the interface of the application and not the complete content input by user (title, description, comments etc). For example, you can use the interface of ZubHub in Hindi/English, but input content in Farsi, Arabic or whatever language and it will display that. There is larger work around translations being taken up here: #222 This requires some thinking before proceeding

**Comment by comfy96** [comment]
okay thank you @tuxology
