### ISSUE TITLE
Date of Birth Field to Allows user to enter Current Date

### ISSUE THREAD

**Issue by Burnleydev1** [unstructuredstudio/zubhub#662]
As a user of the website, I have noticed that the date of birth field allows me to enter the current date as my birth date. This is a concern as it can lead to inaccuracies 

**To Reproduce**

Navigate to the registration page of the website.
Find the "Date of Birth" field and click on it to activate it.
Enter the current date as your birth date (e.g. if today is March 13, 2023, enter "03/13/2023" or a similar format).
Submit the registration form or attempt to proceed to the next step.

**Expected behavior**
Users should not be allowed to enter the current date as their birth date, prompting the user to enter their actual date of birth.

**Comment by Burnleydev1** [comment]
@tuxology, @srish, If this is approved, I would love to work on it

**Comment by comfy96** [comment]
@srish @tuxology I'd love to work on this if approved. thank you

**Comment by tuxology** [comment]
For now, any date more than 13 years from current date can be a good starting point for verifying the date of birth.
