### ISSUE TITLE
Analysis of  Zubhub for better user experience, through user research and contribution.

### ISSUE THREAD

**Issue by amogbe-esther** [unstructuredstudio/zubhub#663]
The goal of this analysis is to help point out things that can be improved on Zubhub for better user experience and retainment. How can users maximize Zubhub and what are their challenges. redesigning the home page, creating user friendly content  and other adjustment. I mapped out a user flow to understand where users might be having difficulties and the adjustment that can be made.
![Zubhub ux 1](https://user-images.githubusercontent.com/61055736/224848805-65c712a8-129d-453a-a410-246f02488cb8.PNG)
![ZubHub ux2](https://user-images.githubusercontent.com/61055736/224848882-ef2a6d45-10ee-47c8-ae58-53c00a849a2c.PNG)

Analysis of the Zubhub Website

Zubhub Ux report as a new user

The goal of this user research was to analyze the website and see how users can navigate through the website and perform some activities with little or no help. 

To conduct the User research I came up with 10 Questions?

1. Do users understand the Purpose of Zubhub and what they do?
2. Do they explore the Home Page to fully understand Zubhub and check out the content ?
3. How is the account creation process?
4. Do they Understand the purpose of creating a project?
5. Can they create a project with no difficulty ?
6. Can they share a project and do they know how?
7. Do they know the benefit of being a Zubhub ambassador? 
8. Can they read and understand the content on Zubh
9. What do users think about the colors and the contents?
10. Do Users have a good experience using the website and improvement tips?

To achieve that, I used Zubhub for my user research and this was my process.

Describing the user flow for My process as a  new user to the website trying to figure out what the website is all about, Analyzing the user flow for a new user, (user 1)
On the landing page trying to figure out what the website was about. 
I created an Account to create a project
I clicked on the explore page to have an idea of the shared project on Zubhub
 Returned back to the Landing Page, clicked on Create Project to create my own project
Filled the details for creating a project
And my project was published as a private video due to the options I selected.  

Also, I got a 12th grader to help me proceed with my user research and this was her process.

Describing the user flow for a 12th grader new to the website trying to figure out what the website is all about, Analyzing the user flow for a new user,
She’s on the landing page trying to figure out what the website was about. 
She reads the content on the Landing page to understand the usefulness of the website
Scroll down to see the all project
She clicked on the explore page to have an idea of the shared project on Zubhub
 Returned back to the Landing Page, clicked on share Project and the response was Oops!!
She clicked on sign in to create an account, filled in the details and the account was created. 
She Created a private project for the purpose of Zubhub user testing. 

At the end of my user research i asked this questions 

Do users understand the Purpose of Zubhub and what they do?
Do they explore the Home Page to fully understand Zubhub and check out the content ?
How is the account creation process?
Do they Understand the purpose of creating a project?
Can they create a project with no difficulty ?
Can they share a project and do they know how?
Do they know the benefit of being a Zubhub ambassador? 
Can they read and understand the content on Zubhub's website?
What do users think about the colors and the contents?
Do Users have a good experience using the website and improvement tips?
And this where the feedback

USER 1

- Do users understand the Purpose of Zubhub and what they do? Yes, i do
- Can they explore the Home Page to fully understand Zubhub and check out the content ? Yes i explored the home page to check out the content
- What is the account creation process? It was quite easy
- Can they share a project and what is the process like? Yes, i can 
- Can they create a project with no difficulty ? yes i can
- Do they know the benefit of being a Zubhub ambassador? Yes i do 
- Can they read and understand the content on Zubhub's website? Not fully
- What do users think about the colors and the contents? The colors are too popping
- Do Users have a good experience using the website and improvement tips? The experience was okay.
- My improvement tips is that the colors can be worked on, the project can be sectioned into categories, and the content on the website can be more user friendly. 

USER 2

- Do users understand the Purpose of Zubhub and what they do? Not really
- Can they explore the Home Page to fully understand Zubhub and check out the content ? Yes i explored the home page to check out the content
- What is the account creation process? It was quite easy
- Can they share a project and what is the process like? Yes i can, the process is quite easy 
- Can they create a project with no difficulty ? The process is stressful 
- Do they know the benefit of being a Zubhub ambassador? Yes i do 
- Can they read and understand the content on Zubhub's website? Not fully
- What do users think about the colors and the contents? The colors are too much
- Do Users have a good experience using the website and improvement tips? The experience was okay.
- My improvement tips are:  Zubhub is too colorful, some content is not easy to read due to the language and they are not so user friendly. The projects should be easy to access for different categories. 

From the user research carried out here are some improvements that can be done  on Zubhub for better user experience. 
This is a work in progress...…
@tuxology @srish please kindly check this out, would love to make this contribution to help users get the best experience using zubhub. Thank you.

**Comment by emteehi** [comment]
Hi Esther, would you mind us collaborating? I already started work on this too.

**Comment by amogbe-esther** [comment]
that, will be great

**Comment by srish** [comment]
Closing this Outreachy specific task! thanks for your contributions, we will utilize these insights some time in the near future.
