### ISSUE TITLE
Add support for meetings and video calls 

### ISSUE THREAD

**Issue by the-techgurl** [unstructuredstudio/zubhub#665]
Hello @srish @tuxology 
After interacting with some other platforms dedicated to kids, I worked on a video feature that would encourage more engagement for the kids as they perform different actions like screen recording.

I'm open to suggestions and improvements on this feature!

Samples of the screens
![Recording](https://user-images.githubusercontent.com/115714559/224988171-0df8dbcc-e7ec-441e-9271-8ee101684c7a.jpg)
![Main video screen](https://user-images.githubusercontent.com/115714559/224988197-21e9f58f-8bf8-4e27-ba75-254d733cf57d.jpg)
![Create project (1)](https://user-images.githubusercontent.com/115714559/224988203-e134f55b-7a2e-468b-87d2-ed3fef0168d7.jpg)
![Hand raising](https://user-images.githubusercontent.com/115714559/224988210-36fb3f82-ff70-4d18-ba9e-e765a6fa51d3.jpg)

Link to prototype [https://www.figma.com/proto/swnO4zVNPnhbgeLAW6s4Dg/ZUBHUB?node-id=35%3A209&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=35%3A209](url)

**Comment by comfy96** [comment]
@the-techgurl this is a great idea. But i couldn't view the protoype.

**Comment by the-techgurl** [comment]
> @the-techgurl this is a great idea. But I couldn't view the prototype.

@comfy96  just noticed https://www.figma.com/proto/swnO4zVNPnhbgeLAW6s4Dg/ZUBHUB?node-id=35%3A209&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=35%3A209

**Comment by tuxology** [comment]
These are good points, but require a lot of work and lift. Added to that is the concern about moderation. We will keep this open and revisit this later.

**Comment by the-techgurl** [comment]
@tuxology On the issue of moderation we could have a specified number of persons who can join a video call. For example, 5 persons or a maximum of 10 and an instructor would be available to oversee that session.

Noted, thank you!

**Comment by comfy96** [comment]
@tuxology if this is approved I will like to be assigned this task.

**Comment by srish** [comment]
Not on product's roadmap
