### ISSUE TITLE
Add Model and Views tests for "activitylog" backend Django app

### ISSUE THREAD

**Issue by Collins-Omariba** [unstructuredstudio/zubhub#668]
Tests to the activitylog app in the django backend will help in knowing when there are breaking changes, hence improved user experience.
![Screenshot_20230314-193758](https://user-images.githubusercontent.com/88287473/225076872-480cbe32-abc8-4d94-95d6-c216eecb5586.png)

**Comment by Collins-Omariba** [comment]
@tuxology @srish , please assign me this issue

**Comment by Collins-Omariba** [comment]
On it

**Comment by tuxology** [comment]
Done via #685 Merged in `test` branch
