### ISSUE TITLE
Number of comments is not displayed on projects in "Featured Projects" section

### ISSUE THREAD

**Issue by skynette** [unstructuredstudio/zubhub#670]
I would like to suggest adding a feature to the project creation page. Currently, the number of views is displayed, but the number of comments is not. It would be helpful if the number of comments is also displayed initially, similar to the number of views. This will provide users with a quick overview of the engagement level of their project and encourage further participation

![image](https://user-images.githubusercontent.com/29153968/225145729-c35bdfb1-600d-4ee0-858b-f0cb0d1f3d09.png)

**Comment by darechan** [comment]
@tuxology I'd like to work on this issue!

**Comment by aqsaaqeel** [comment]
If no one is working on this, can I take up the issue? @tuxology @srish

**Comment by aqsaaqeel** [comment]
I have been analysing this for quite some time, but i am not able to get the featured projects list on my localhost, how do I go about with that?

**Comment by yokwejuste** [comment]
Hi @aqsaaqeel in case you need you help, let me know

**Comment by aqsaaqeel** [comment]
> Hi @aqsaaqeel in case you need you help, let me know

Yes, I am not able to get the featured projects

**Comment by Boluwatifey1** [comment]
Hi @aqsaaqeel is this a ux issue or it’s for the developers?

**Comment by aqsaaqeel** [comment]
> Hi @aqsaaqeel is this a ux issue or it’s for the developers?

It's for developers, the comment count is not showing up for cards under featured projects.

**Comment by Boluwatifey1** [comment]
Okay thanks @aqsaaqeel I am a ui ux designer

**Comment by JessicaItepu** [comment]
> > Hi @aqsaaqeel is this a ux issue or it’s for the developers?
> 
> It's for developers, the comment count is not showing up for cards under featured projects.

Hi @aqsaaqeel, i think the project label says "Ux"... 

@tuxology @srish , could you clarify which team this project belongs to?

I am a UI/UX designer and sould love to be assigned to this if its open. Thank you

**Comment by yokwejuste** [comment]
> > Hi @aqsaaqeel in case you need you help, let me know
> 
> Yes, I am not able to get the featured projects

give me more lights on what you faced let's work inline to get that fix

**Comment by aqsaaqeel** [comment]
I am not able to get the category of Featured Projects on my dashboard on local host. But I checked the network tab on Zubhub website. Turns out there is no "comments_count" property for projects in Featured Projects > > > Hi @aqsaaqeel in case you need you help, let me know
> 
> > 
> 
> > Yes, I am not able to get the featured projects
> 
> 
> 
> give me more lights on what you faced let's work inline to get that fix

**Comment by aqsaaqeel** [comment]
> > > Hi @aqsaaqeel in case you need you help, let me know
> > 
> > 
> > Yes, I am not able to get the featured projects
> 
> give me more lights on what you faced let's work inline to get that fix

I was not able to get the featured projects list on my local host. I had to make changes to the database manually to add staff-pick projects to get this list. 
![Screenshot from 2023-10-04 05-09-38](https://github.com/unstructuredstudio/zubhub/assets/85514520/12227980-ea85-4e54-879c-878af3779047)


Coming back to the issue at hand, The API call for All Projects has a property called comments_count as we can see here !
![Screenshot from 2023-10-04 05-12-58](https://github.com/unstructuredstudio/zubhub/assets/85514520/1efcc726-5f1c-462d-a75f-2abefbf9e3f6)


But for the API call for staff-picks which gives us the Featured Projects does not have the comments_count property as we can see here:
![Screenshot from 2023-10-04 05-16-25](https://github.com/unstructuredstudio/zubhub/assets/85514520/d7a88b28-9537-48a9-9bcf-6d6391674e08)

**Comment by Boluwatifey1** [comment]
> > > Hi @aqsaaqeel is this a ux issue or it’s for the developers?
> > 
> > 
> > It's for developers, the comment count is not showing up for cards under featured projects.
> 
> Hi @aqsaaqeel, i think the project label says "Ux"...
> 
> @tuxology @srish , could you clarify which team this project belongs to?
> 
> I am a UI/UX designer and sould love to be assigned to this if its open. Thank you

@JessicaItepu i thought so too

**Comment by yokwejuste** [comment]
This project is not the one outreachy applicants are to work on between

**Comment by coderatomy** [comment]
> > > > Hi @aqsaaqeel in case you need you help, let me know
> > > 
> > > 
> > > Yes, I am not able to get the featured projects
> > 
> > 
> > give me more lights on what you faced let's work inline to get that fix
> 
> I was not able to get the featured projects list on my local host. I had to make changes to the database manually to add staff-pick projects to get this list. ![Screenshot from 2023-10-04 05-09-38](https://user-images.githubusercontent.com/85514520/272423017-12227980-ea85-4e54-879c-878af3779047.png)
> 
> Coming back to the issue at hand, The API call for All Projects has a property called comments_count as we can see here ! ![Screenshot from 2023-10-04 05-12-58](https://user-images.githubusercontent.com/85514520/272425241-1efcc726-5f1c-462d-a75f-2abefbf9e3f6.png)
> 
> But for the API call for staff-picks which gives us the Featured Projects does not have the comments_count property as we can see here: ![Screenshot from 2023-10-04 05-16-25](https://user-images.githubusercontent.com/85514520/272424856-d7a88b28-9537-48a9-9bcf-6d6391674e08.png)

I would be happy if you share with me how you did this @aqsaaqeel. I also want to get a list of these

**Comment by aqsaaqeel** [comment]
> > > > > Hi @aqsaaqeel in case you need you help, let me know
> > > > 
> > > > 
> > > > Yes, I am not able to get the featured projects
> > > 
> > > 
> > > give me more lights on what you faced let's work inline to get that fix
> > 
> > 
> > I was not able to get the featured projects list on my local host. I had to make changes to the database manually to add staff-pick projects to get this list. ![Screenshot from 2023-10-04 05-09-38](https://user-images.githubusercontent.com/85514520/272423017-12227980-ea85-4e54-879c-878af3779047.png)
> > Coming back to the issue at hand, The API call for All Projects has a property called comments_count as we can see here ! ![Screenshot from 2023-10-04 05-12-58](https://user-images.githubusercontent.com/85514520/272425241-1efcc726-5f1c-462d-a75f-2abefbf9e3f6.png)
> > But for the API call for staff-picks which gives us the Featured Projects does not have the comments_count property as we can see here: ![Screenshot from 2023-10-04 05-16-25](https://user-images.githubusercontent.com/85514520/272424856-d7a88b28-9537-48a9-9bcf-6d6391674e08.png)
> 
> I would be happy if you share with me how you did this @aqsaaqeel. I also want to get a list of these

So the featured projects are list of projects chosen by the backend people so getting them on frontend meant adding the projects to the list of staff-picks. What I did was manually add them to the database using the postgresql using the ```insert into``` query, does this make sense? @coderatomy

**Comment by pachougu** [comment]
@srish @skynette @aqsaaqeel  I would to work on this as UI/UX designer

**Comment by pachougu** [comment]
I have designed the number of comment to display on the "featured Project" on figma file 
![drafts - edit drafts - top_unstructuredstudio](https://github.com/unstructuredstudio/zubhub/assets/146971182/e2d02603-e7ed-46d5-8f0b-c96bc512b289)

**Comment by aqsaaqeel** [comment]
> @srish @skynette @aqsaaqeel I would to work on this as UI/UX designer

@pachougu the design for this already exists, the comment count was just not showing up on UI which is fixed now

**Comment by pachougu** [comment]
@aqsaaqeel oh Okay thanks

**Comment by benndip** [comment]
@srish  @tuxology I have opened a PR here

[https://github.com/unstructuredstudio/zubhub/pull/799](url)

that fixes this issue from the frontend and according to the architecture of the backend. @aqsaaqeel  you could check it out if it makes sense
