### ISSUE TITLE
View Count on Project Details Page Not Unique to IP Addresses.

### ISSUE THREAD

**Issue by skynette** [unstructuredstudio/zubhub#671]
I have identified a bug in the project details page on the ZubHub website. I have noticed that whenever I reload the page, the number of views increases. In my opinion, these views should be unique to IP addresses, and this inconsistency may affect the accuracy of view counts.

**Steps to reproduce the issue are as follows:**

1. Go to https://zubhub.unstructured.studio/
2. Click on a project to view its details
3. Refresh the page and observe the number of views increasing despite reloading the same page.

I kindly request that this bug is addressed to ensure the accuracy of view counts for project owners and contributors.

**Expected behavior**
The expected behavior for the view count on the project details page of ZubHub website is that the number of views should be unique to each IP address. This means that when a user visits the project details page, their view should be recorded only once and subsequent page reloads should not result in additional views being counted.

By implementing this expected behavior, the accuracy of view counts for project owners and contributors will be ensured. The view count will represent the number of unique visitors to the project details page, which is a more meaningful metric for evaluating engagement and interest in the project.

**Screenshots**
![image](https://user-images.githubusercontent.com/29153968/225148838-482f73e9-f465-4bfa-b1b5-38ed16fa1775.png)

**Comment by iamhks** [comment]
@skynette As far as I know, even YouTube does this way that if you reload the same video twice or if you open your own video the view count increases.

**Comment by srish** [comment]
This is fine for now.
