### ISSUE TITLE
Create Project Button on User Profile Page

### ISSUE THREAD

**Issue by ferindesigns** [unstructuredstudio/zubhub#675]
@srish and @tuxology using the component library built in #617, I decided to work on the UX of the profile page. To make it easier to view projects and create new projects, we could add a CTA to the profile page under the project section.

![Profile2](https://user-images.githubusercontent.com/108564127/227081052-dd4b0d72-8114-4a0a-b9fa-ddf3effb2b11.png)

Also, the profile page could be rearranged to make it easier in navigating and to increase focus on one section at a time.

![Profile3](https://user-images.githubusercontent.com/108564127/227081090-4561e454-84ff-46b8-ae3a-7dba70c72abe.png)

**Comment by ferindesigns** [comment]
![Profile1](https://user-images.githubusercontent.com/108564127/226411463-4fcba82f-a8b4-4dff-972f-ab15ba391137.png)

**Comment by ferindesigns** [comment]
@srish and @tuxology what do you think?

**Comment by srish** [comment]
Thanks for your contributions. This task is no more applicable with recent updates.
