### ISSUE TITLE
Google drive error: sorry unable to open the file at this time

### ISSUE THREAD

**Issue by srish** [unstructuredstudio/zubhub#68]
At the time of project creation, I provided the following google drive link: https://drive.google.com/file/d/1HuozYMFXS4XAEL-HYdPUnf-ofcb4pSSS/view

I didn't receive an error when I tried to hit submit. But on the project page now, I see the following error: 

![Screen Shot 2021-01-10 at 9 52 26 PM](https://user-images.githubusercontent.com/288353/104128553-35eb3300-538e-11eb-9bc8-bb91806b63aa.png)

Is there something wrong about the URL I provided?

**Comment by tuxology** [comment]
Srishti added https://drive.google.com/file/d/1HuozYMFXS4XAEL-HYdPUnf-ofcb4pSSS/view as the URL, but the translated URL in the view contains 3 extra `pre` in the end: `https://drive.google.com/file/d/1HuozYMFXS4XAEL-HYdPUnf-ofcb4pSSS/preprepreprepreprepreview`
