### ISSUE TITLE
Switching language does not translate entire page

### ISSUE THREAD

**Issue by skynette** [unstructuredstudio/zubhub#683]
It seems that switching the language on the website does not translate the entire page. Specifically, some parts of the page remain in the original language instead of being translated to the selected language.

To reproduce this issue, follow these steps:

Go to the website.
Choose a language other than the default language.
Navigate to different sections of the website.
Observe that some parts of the website remain in the original language.
I expected that switching to a different language would translate the entire website into the selected language.

**Screenshots**
![image](https://user-images.githubusercontent.com/29153968/225875099-16a30d97-101f-48b4-a3da-b1e1b07988ea.png)

**Comment by darechan** [comment]
Duplicate of #570

**Comment by skynette** [comment]
okay will close
