### ISSUE TITLE
Sign up with google

### ISSUE THREAD

**Issue by skynette** [unstructuredstudio/zubhub#684]
It would be helpful to add a "Sign Up with Google" feature to the website to make it easier for users to create accounts.

Currently, users have to manually enter their information, including their email address and password, to sign up for an account. This can be a barrier to entry for some users who may not want to go through the hassle of creating a new account.

By adding a "Sign Up with Google" feature, users could use their existing Google account credentials to quickly and easily create an account on the website. This would streamline the account creation process and provide a better user experience for users.

**Comment by srish** [comment]
We don't know a lot about our users yet, if they even have Google accounts in the first place. And, as the target audience is youth, we will refrain from adding a sign-up with Google option at the moment.
