### ISSUE TITLE
Add tests for Models and Views of the 'activities' Backend.

### ISSUE THREAD

**Issue by Collins-Omariba** [unstructuredstudio/zubhub#687]
Tests for the activities backend will help notice breaking changes and thus  prevent disruption of 
the application leading to great user experience.

## screen shot 
![Screenshot_20230318-085648](https://user-images.githubusercontent.com/88287473/226088142-5fb3f7b6-52a3-46e8-b6c6-a885a199dbf6.png)

**Comment by Collins-Omariba** [comment]
@tuxology @srish please assign me this issue

**Comment by iamhks** [comment]
@Collins-Omariba I am actually already working on this issue, haven't created one in github but already have a working branch. If you don't mind can you take up any other modules? Notifications/Projects etc. I would have taken that up my myself but my current work would go in vain so... Is it okay?

**Comment by Collins-Omariba** [comment]
I'll make a closing pull request on this issue very soon. ✅

**Comment by tuxology** [comment]
Done via #705. Merged in `test` branch
