### ISSUE TITLE
Add tests for 'notifications' Backend

### ISSUE THREAD

**Issue by iamhks** [unstructuredstudio/zubhub#688]
## Description

Currently there are no tests for notifications backend, would be nice to get this added

**Comment by iamhks** [comment]
Hi all, I am already working on this issue. Please don't ask to be assigned by mentors

**Comment by Collins-Omariba** [comment]
Great. It will be good to have tests in all the backed apps Great @iamhks , for the other issue #687 , am already working on it. I'll make the pull request after being assigned.

**Comment by tuxology** [comment]
Done via #704 Tests are in `test` branch for now
