### ISSUE TITLE
Add tests for projects in backend

### ISSUE THREAD

**Issue by iamhks** [unstructuredstudio/zubhub#689]
## Description
We do not have tests for projects in backend and would be great to have
<img width="1409" alt="Screenshot 2023-03-18 at 15 43 43" src="https://user-images.githubusercontent.com/43777817/226099394-cc737050-c08e-467f-8648-452084afcc50.png">

**Comment by iamhks** [comment]
Since I am already working on #688 opening this issue to anyone interested

**Comment by darechan** [comment]
@iamhks I've never created a test case however I am open to learning can you tell me or give me a resource to start working on this?

**Comment by iamhks** [comment]
@darechan You can refer my tests branch where I have pushed some code, the authentication part is still left: https://github.com/iamhks/zubhub/commit/2860b8b7c050d031141482e93482aac30979886a
Also, you can refer to Collin's PR: https://github.com/unstructuredstudio/zubhub/pull/685

**Comment by darechan** [comment]
Thanks @iamhks

**Comment by skynette** [comment]
I started working on this

**Comment by tuxology** [comment]
Done, via #706 Tests are in `test` branch
