### ISSUE TITLE
Overflow on x-axis

### ISSUE THREAD

**Issue by Haywayaheadshot** [unstructuredstudio/zubhub#690]
**Describe the bug**
When you click on the "Unstructured Studio" logo in the footer, it leads this [webpage](https://unstructured.studio/). You will find the mobile version of this page has an over-flow on the x-axis.

**To Reproduce**

1. Go to 'Home Page' for mobile version
2. Scroll to 'Footer'
3. Click on 'Unstructured Studio' logo
4. Drag your mouse to the left like you're checking for information on the right.
5. See error

**Expected behavior**
When the user visits the page, they are supposed to able to scroll to the sides because there is no content there and it serves a bad user experience.

### **Video of bug**

https://user-images.githubusercontent.com/105272189/226146475-02fd076b-e0c1-4081-a379-4e83788ccc44.mp4

**Comment by Haywayaheadshot** [comment]
@srish @tuxology  I am an outreachy applicant. I will like to be assigned to this please.

**Comment by darechan** [comment]
@Haywayaheadshot That is the official Unstructured Studio page, I don't think you can work on that page via zubhub.

**Comment by Haywayaheadshot** [comment]
@darechan Thanks for the heads up. I’ll close the comment
