### ISSUE TITLE
Location Select option overflowing into search bar

### ISSUE THREAD

**Issue by cherish2003** [unstructuredstudio/zubhub#694]
**Describe the bug**
Location Select option in the  sign up page is overflowing into search bar
**To Reproduce**

1. Go to https://zubhub.unstructured.studio/signup
2. Click on Location 
3. See the behavior

**Expected behavior**
Location Select option should not overflow into search bar 

**Screenshots**

![Screenshot 2023-03-19 211943](https://user-images.githubusercontent.com/88829894/226210425-90af39c8-bc03-42b9-a946-eaaabfe0d29f.png)

**Comment by cherish2003** [comment]
@tuxology @srish  if this issue is approved i would like to work on this issue

**Comment by ipriyanshi1708** [comment]
Hi @srish @tuxology, I am an Outreachy applicant and a frontend developer and would like to contribute to this issue. Please assign it to me.

**Comment by cherish2003** [comment]
@tuxology kindly approved this issue so that i will start working on it

**Comment by srish** [comment]
The behavior seems okay to me, closing for now.
