### ISSUE TITLE
Number of saves on a project is not shown

### ISSUE THREAD

**Issue by skynette** [unstructuredstudio/zubhub#698]
It seems that the number of saves on a project is not displayed, unlike the number of views on a project, on the website.

To reproduce this issue, follow these steps:

Navigate to a project page on the website.
Observe that the number of views is displayed prominently on side of the page.
Look for the number of saves on the project.
Observe that the number of saves is not displayed anywhere on the page.
I expected that the number of saves on a project would be displayed like the number of views.

![image](https://user-images.githubusercontent.com/29153968/226962910-0245ee4a-71b3-4018-93cd-24a5b9f3e675.png)

**Comment by darechan** [comment]
Even other platforms like Instagram do not show the number of saves on a post expect to the author so I think that is not required also that button is for the current viewer of the project
