### ISSUE TITLE
Password reset: "failed to fetch" error

### ISSUE THREAD

**Issue by srish** [unstructuredstudio/zubhub#70]
Steps to reproduce:
* Go to https://zubhub.unstructured.studio/password-reset
* Enter email address
* Hit "Send reset link"

And, you see the following error after a while:
![Screen Shot 2021-01-10 at 10 04 24 PM](https://user-images.githubusercontent.com/288353/104128918-37b5f600-5390-11eb-808f-1201864a2f3c.png)

**Comment by NdibeRaymond** [comment]
Hello @srish , I am sorry that this took this long. It was just an issue of restarting the rabbitmq container that handles task email messaging task queueing. Won't be creating an issue for this since it is a devops problem and not dev. This issue have been fixed
