### ISSUE TITLE
Images & Text on the zubhub ambassadors page are not responsive and overflowing on mobile view

### ISSUE THREAD

**Issue by NabajitS** [unstructuredstudio/zubhub#707]
**Describe the bug**
The images and text on the zubhub ambassadors page are not responsive and overflowing on mobile view

**To Reproduce**

1. Go to [Ambassadors page](https://zubhub.unstructured.studio/ambassadors)
2. Scroll down to the ambassadors section having pictures of the kids
3. Open mobile view
4. See the images and text overflowing

**Expected behavior**
The images and text should be responsive. In case more people's details are added in this section in the future it will lead to screen overflowing and horizontal scroll.

**Screenshots**

![Screenshot 2023-03-14 215310](https://user-images.githubusercontent.com/86390740/227860947-6afe1154-66e2-4d2d-ab03-3047b1dd2cfc.png)
![Screenshot 2023-03-27 120638](https://user-images.githubusercontent.com/86390740/227860923-41179e19-16b3-4eed-96e4-c769242cd660.png)

**Comment by NabajitS** [comment]
@tuxology I would like to work in this issue if validated

**Comment by srish** [comment]
This has now been fixed
