### ISSUE TITLE
Redirected to profile page instead of intended page after logging in while performing an action as a non-logged-in user

### ISSUE THREAD

**Issue by skynette** [unstructuredstudio/zubhub#709]
It seems that when trying to take an action while not logged in, after logging in, users are redirected to the profile page instead of the page with the action they were trying to perform.

### To reproduce this issue, follow these steps:

Log out of the website (if currently logged in).
Navigate to a page where you would need to be logged in to take an action.
Attempt to take the action (e.g., add an item to a cart, post a comment, etc.).
The website should prompt you to log in. Enter your credentials and log in.
Observe that you are redirected to the profile page instead of the page with the action you were trying to perform.

### Expectation
I expected that after logging in, I would be redirected to the page with the action I was trying to perform.

**Comment by srish** [comment]
This seems okay behavior for now.
