### ISSUE TITLE
Improve the "materials" field ui

### ISSUE THREAD

**Issue by srish** [unstructuredstudio/zubhub#71]
It is not obvious from the project creation form UI how to add materials. I see now that we have a placeholder that says "add a material and click the + button". But, we could make more UI improvements to make it self-explanatory how one can add materials.

@tuxology can provide more input here on how the UI could be.

**Comment by NdibeRaymond** [comment]
This issue is a duplicate of https://github.com/unstructuredstudio/zubhub/issues/32 which have already been fixed and closed. I think we need to reopen the issue if we have more suggestions on how that field should behave

**Comment by tuxology** [comment]
@NdibeRaymond @srish before closing this, I came up with a new sketch of how create project can have a more question/task  driven UI to help kids understand what is expected in the field. We can be more descriptive in such cases I think

![image](https://user-images.githubusercontent.com/3373857/104147506-742f2500-5383-11eb-9ab1-56738d77a4f4.png)

**Comment by NdibeRaymond** [comment]
> @NdibeRaymond @srish before closing this, I came up with a new sketch of how create project can have a more question/task driven UI to help kids understand what is expected in the field. We can be more descriptive in such cases I think
> 
> ![image](https://user-images.githubusercontent.com/3373857/104147506-742f2500-5383-11eb-9ab1-56738d77a4f4.png)

Hello @tuxology , does this mean the floating placeholders should be removed? and the fields be numbered just like we have here?

**Comment by tuxology** [comment]
I think we should discuss this in some meeting and see if it makes sense to implement this
