### ISSUE TITLE
Currently, the email gets displayed on the user profile. We want to avoid that

### ISSUE THREAD

**Issue by yaya-mamoudou** [unstructuredstudio/zubhub#713]
**Describe the bug**
Currently, the email gets displayed on the user profile. This is caused because, in place of the username field in the register form, the user entered the email.

**To Reproduce**
1. Go to [this](https://zubhub.unstructured.studio/signup) link 
2. Fill out the form and in place of the username, add your email and submit the form
3. go to your profile and see that your email shows as your username

**Expected behavior**
username should be validated in order to prevent an email to be added as a username

**Screenshots**
<img width="997" alt="image" src="https://github.com/unstructuredstudio/zubhub/assets/57509871/a2208ed5-d2bc-49fe-b669-479d705bbec3">

**Comment by srish** [comment]
This got fixed via #741. Thanks @yaya-mamoudou!
