### ISSUE TITLE
Inconsistent positioning of component beneath the navbar for mobile devices

### ISSUE THREAD

**Issue by Formasitchijoh** [unstructuredstudio/zubhub#732]
This issue references #606 , but with the change of the UI more of the component have been found to be half way hiddden beneath the navbar hiding most of the  content on  mobile devices. This behavior is mostly noticed in devices of width  less than or equal to 414x926 pixels

### Here is a snippet to show the behavior .
![ps1](https://github.com/unstructuredstudio/zubhub/assets/76694292/9e5bb763-1888-4a10-b551-8eb284a9152b) ![ps2](https://github.com/unstructuredstudio/zubhub/assets/76694292/4a9d8156-fd4b-4f6c-8801-367f48aee239)

![ps3](https://github.com/unstructuredstudio/zubhub/assets/76694292/2dbe039a-87a2-4df8-aae0-1ba273cfd732)
![ps4](https://github.com/unstructuredstudio/zubhub/assets/76694292/8a255bb1-c454-4141-aea7-0f1feb90a925)

## Proposed solution:
By targeting the breakpoints that causes the error i gave a margin to this components to prevent it from being hidden under the navbar and hiding it's content, this margin corresponds to all breakpoint to prevent inconsistency in different viewport sizes.
Here is a snippet of how the changes look like

![ss2](https://github.com/unstructuredstudio/zubhub/assets/76694292/4b759d8f-2c05-4ae6-a064-b21638eec071)
![ss1](https://github.com/unstructuredstudio/zubhub/assets/76694292/ca618e9e-8a51-4fae-94fa-73fce4c5158a)

**Comment by srish** [comment]
@Formasitchijoh Thanks for filing this issue! If you have some ideas on how to fix it, let us know so we can assign it to you.

**Comment by Formasitchijoh** [comment]
@srish  yes i do have some ideas,  and i will be glad to work on it 
 I went ahead to solve it and it looks like this for devices less that or equal to 414x926
 
![image](https://github.com/unstructuredstudio/zubhub/assets/76694292/59cbf3b8-6c0b-497c-b1e1-7e3ff6125297)

i will need your feedback  if the margin and the positioning is okay so i can apply on the other pages and submit a PR

**Comment by srish** [comment]
@Formasitchijoh Yes, the margins and positioning look okay to me. How about the login and sign up dialog boxes and how do they appear?

**Comment by Formasitchijoh** [comment]
> @Formasitchijoh Yes, the margins and positioning look okay to me. How about the login and sign up dialog boxes and how do they appear?

I was waiting for your feedback on the previous one, I'll just apply the changes to the login and Signup and send

**Comment by Formasitchijoh** [comment]
@srish  i just made a PR referencing the issue , here is a video of the changes made and how it works

https://github.com/unstructuredstudio/zubhub/assets/76694292/72847975-0494-4f62-a117-509dbe0eecff

**Comment by yaya-mamoudou** [comment]
@Formasitchijoh great Job. Please pull master into your branch again and confirm it does not conflict with your work. Some changes were made on the dashboard layout component. Thanks

**Comment by Formasitchijoh** [comment]
Alright i will do that  thank you @yaya-mamoudou

**Comment by Formasitchijoh** [comment]
@srish  just want to check if you've had time to check the pull request i made on this issue
