### ISSUE TITLE
Changing the Icon for the logout button

### ISSUE THREAD

**Issue by aqsaaqeel** [unstructuredstudio/zubhub#738]
**Description**
Zubhub is using React Remix Icon (named RiLogoutBoxRFill) for the logout button in Navbar which looks like this currently. 
![Screenshot from 2023-09-26 00-49-57](https://github.com/unstructuredstudio/zubhub/assets/85514520/7af36a39-275f-4766-bea5-8302f879eae1)
It looked a bit odd to me the first time and I thought it was missing some padding on the right. But after looking into it I found that the icon is designed like that. It is taking away from the beauty of the UI.

**Suggestion**
We could use another icon from React Remix icons which will improve the UI and maintain a uniformity in the sidenav.
![Screenshot from 2023-09-26 00-54-48](https://github.com/unstructuredstudio/zubhub/assets/85514520/44954135-50bd-454e-84f6-9391facb8c92)
This is the RiLogoutBoxRLine from ReactRemix Icons which looks more uniform than the current one.

**Comment by aqsaaqeel** [comment]
@tuxology @srish can I work on this?

**Comment by srish** [comment]
@aqsaaqeel Thanks for your comment! It sounds like improvement of this sort should apply to icons all throughout the site and be taken up altogether. I'd encourage you instead to take a look at the existing tasks with a `#good-first-issue` tag.
