### ISSUE TITLE
Misaligned Login Form

### ISSUE THREAD

**Issue by mark-eke** [unstructuredstudio/zubhub#742]
Issue
When you visit the link `https://zubhub.unstructured.studio/login`, you discover the login form is too close to the top of the header. There is a lot of gap left from the login form to the bottom of the screen

To Reproduce

- Visit the login page.
- Take note of the form and it's closeness to the top both on desktop and mobile view.

Expected behavior
The login form should be well positioned and centered on the screen.

Screenshot
![image](https://github.com/unstructuredstudio/zubhub/assets/107544839/9a441419-84c4-4907-ac10-2c568d4029aa)

**Comment by brrkrmn** [comment]
hello @srish, I would like to work on this one if possible

**Comment by Dagmawi-22** [comment]
hello @srish, Let me fix this well.

**Comment by Michelle-okechi** [comment]
hello @srish please assign this to me, I can correct it

**Comment by Boluwatifey1** [comment]
Hello @srish please I will like to work on this

**Comment by Temidayo32** [comment]
@srish can this be assigned to me. It's a frontend issue.

**Comment by JessicaItepu** [comment]
Hello @srish, kindly specify if this is a Ui/ux project or a developer project. 

I would love to be assigned to it if it is a Ux project. Thank you.

**Comment by srish** [comment]
Thanks for filing! This issue has to wait till we make some improvements to our sign-up form based on designs developed by our former intern. Improvements to the sign-up form are being planned as part of the internship. I am closing this issue for now to avoid confusion.

**Comment by JulietMadu** [comment]
@srish i worked on this already but the issue has been closed
![zulip login](https://github.com/unstructuredstudio/zubhub/assets/128796937/a55f15b7-222c-489c-bc36-74eafc607bba)
