### ISSUE TITLE
Scroll to top not implemented when new projects are listed

### ISSUE THREAD

**Issue by mark-eke** [unstructuredstudio/zubhub#743]
**Describe the bug**
When you login and go to the `all projects` link, you notice a list of projects. As you scroll to the end and reach the last one on the screen with the `next` button, clicking on the next button would fetch a new list of projects. The bug here is that the page doesn't automatically scroll to the top. Instead the user has to manually scroll to the top of the screen to find the newly listed projects.

**To Reproduce**

1. Go to 'All Projects `https://zubhub.unstructured.studio/projects`'.
2. Click on `'next'` at the bottom of the screen.
3. You notice the old list disappears but you have to manually scroll to the top. 

**Expected behavior**
A scroll to top action should automatically occur when the new list is fetched successfully.

**Comment by Chinemere** [comment]
Hello @tuxology can I work on this issue?

**Comment by Dagmawi-22** [comment]
Let me implement this @tuxology.

**Comment by JulietMadu** [comment]
Can I make a prototype design for it @tuxology

**Comment by Temidayo32** [comment]
@srish I will like to work on this issue.  
@JulietMadu I think this issue is more code related than it is wiring and prototyping related since the desired design is already specified by @mark-eke

**Comment by srish** [comment]
I am not able to replicate this issue on my end. I am able to see the scroll to top button that works.

**Comment by coderatomy** [comment]
same here, @mark-eke, can you verify this and maybe close this issue

**Comment by brrkrmn** [comment]
@srish, I was able to replicate the issue and opened #888 for it.
