### ISSUE TITLE
Adding some more functionality to the User Account Icon (top right corner)

### ISSUE THREAD

**Issue by capital-e** [unstructuredstudio/zubhub#747]
From the point of view of a user who has signed in already, I noticed that clicking on the user account icon on the top right corner takes me directly to the "**My Profile**" page. I was expecting to see a small dropdown menu that lists a few options like "**My Profile, Account settings, logout, language preferences, etc.**". I suggest we add that functionality to that button to provide a more "**familiar**" user experience for users. As a young learner on the zubhub platform, I want to see and be familiar with common and modern features that will help me interact more freely with other websites.

**Comment by capital-e** [comment]
@srish @tuxology kindly consider assigning this issue to me.

**Comment by Marhiposa** [comment]
hi @tuxology is this a designers work ?

**Comment by srish** [comment]
@capital-e Thanks for creating this task. The settings you are referring to are currently accessible from other venues in the app. Language settings are on the top navbar, logout is on the left sidebar, etc. These changes were made as part of our recent UX improvement efforts, and we have no plans to adjust them anytime soon.
