### ISSUE TITLE
Making use of space

### ISSUE THREAD

**Issue by capital-e** [unstructuredstudio/zubhub#748]
I noticed how the content of the page is centered, leaving empty spaces on the left and right sides of the webpage. I suggest we spread out the icons on the navigation bar to the far ends. This means the "**zubhub**" and "**language**" icons will move further to the left side and the "**user account**" and "**notification**" icons will move further to the right side. The "**search bar**" may also be resized and moved according to how it may blend with the new adjustments. This will look more appealing.

**Comment by capital-e** [comment]
@srish @tuxology kindly consider assigning this issue to me.

**Comment by srish** [comment]
Kindly avoid submitting small UX issues like this, as they are currently part of our larger UX improvement plans. Addressing these minor concerns separately may result in further inconsistencies.
