### ISSUE TITLE
Incorporating a Hamburger menu feature for the left side panel.

### ISSUE THREAD

**Issue by capital-e** [unstructuredstudio/zubhub#749]
I noticed that incorporating a **hamburger menu button** feature may provide some key improvements to the webpage. Instead of having a static **left side panel**, we should replace it with a simple and minimal hamburger menu button which will reveal a **pop-up** side panel listing all the **main sections** of the website. This will make it possible to shift the main content of the page a little more to the left side and free up space on the right to house a **static right-side panel**. In this right-side panel, we may display the "**badges**" section. This adjustment will provide a more familiar and interactive experience for users. As a young learner on the zubhub platform, I want to see and be familiar with common and modern features that will help me interact more freely with other websites.

**Comment by teelda** [comment]
@srish @tuxology I suggest that the **side Nav panel** should be **fixed to the left on scroll**, to prevent the user from scrolling all the way to the top before switching between pages. The scroll to top button might fix this but it is however small and can easily not be noticed by the users. Having the **side Nav menu fixed** can also give a familiar experience to users, based on modern UI's they might have interacted with. 

The empty space in the attached screenshot on the left side of the screen should show a fixed side Nav Menu.

![Side Nav Menu](https://github.com/unstructuredstudio/zubhub/assets/57068192/0625665d-ec03-4597-b29b-0b1982ba4496)

**Comment by capital-e** [comment]
> @srish @tuxology I suggest that the **side Nav panel** should be **fixed to the left on scroll**, to prevent the user from scrolling all the way to the top before switching between pages. The scroll to top button might fix this but it is however small and can easily not be noticed by the users. Having the **side Nav menu fixed** can also give a familiar experience to users, based on modern UI's they might have interacted with.
> 
> The empty space in the attached screenshot on the left side of the screen should show a fixed side Nav Menu.
> 
> ![Side Nav Menu](https://user-images.githubusercontent.com/57068192/272282430-0625665d-ec03-4597-b29b-0b1982ba4496.PNG)

Nice observation, I'll be glad to work on this with you. @srish @tuxology kindly consider assigning this issue to us.

**Comment by srish** [comment]
Kindly avoid submitting small UX issues like this, as they are currently part of our larger UX improvement plans. Addressing these minor concerns separately may result in further inconsistencies
