### ISSUE TITLE
Possibly Unnecessary bar section on the create profile page

### ISSUE THREAD

**Issue by capital-e** [unstructuredstudio/zubhub#750]
When I navigated to the "**Create project**" page, I noticed a **white bar** on top of the page below the navigation bar. It has a "**back arrow**" icon which is **not functional**. It also houses the "**preview**" action button which I believe will be better off at the bottom of the page to ensure users do not need to scroll all the way back up when they have finished typing in the project details just to preview what they have done. The "**saved to draft**" button can be incorporated in the actual create project section instead of the bar so that we can eliminate the bar altogether and align the section to the top of the page.

**Comment by capital-e** [comment]
@srish @tuxology kindly consider assigning this issue to me.

**Comment by Marhiposa** [comment]
hi @capital-e i aslo noticed it can we work on it together

**Comment by capital-e** [comment]
> hi @capital-e i aslo noticed it can we work on it together

I will be glad to, and I hope to hear from the mentors soon.

**Comment by srish** [comment]
Kindly avoid submitting small UX issues like this, as they are currently part of our larger UX improvement plans. Addressing these minor concerns separately may result in further inconsistencies
