### ISSUE TITLE
Empty State page for the search bar

### ISSUE THREAD

**Issue by teelda** [unstructuredstudio/zubhub#751]
The text and illustration on the empty state for "items not found" show an overflow on the screen, which gives an unwanted horizontal scroll bar on the page and also sends the illustration behind the side Nav Bar.  When a user tries to search for a project/tag/creator, and the item is not found

**To Reproduce**

1. When a user clicks on the search bar.
2. Types in a project/tag/creator that can't be found.
3. It shows an empty state or error screen with "Oops!!! we could not find anything for your search term! Maybe try to search something else?"
4. The above text comes with an illustration that spans behind the side Nav menu and gives the page an unwanted horizontal bar, Unlike other pages with the same error message 

**Expected behavior**
The Illustration and text shouldn't be hidden behind the Nav Menu and the element should be set to "Overflow: Hidden;".

**Screenshots**
@srish @tuxology See attached screenshot. The first and second image shows the bug while the third image shows what it looks like on other pages.
![Error page 1](https://github.com/unstructuredstudio/zubhub/assets/57068192/5a22d936-002e-44c1-a349-58d058518b43)
![Error page 2](https://github.com/unstructuredstudio/zubhub/assets/57068192/fe2e0a26-abd4-4710-aebb-7580c6d4d401)
![Error page 3](https://github.com/unstructuredstudio/zubhub/assets/57068192/fa1c67cb-927c-44b4-bfa8-b616e707cb7b)

**Comment by srish** [comment]
Addressing this change is part of a larger UX overhaul so I am closing this for now to avoid further inconsistencies.
