### ISSUE TITLE
Improve Logout User Flow

### ISSUE THREAD

**Issue by teelda** [unstructuredstudio/zubhub#752]
**Issue**
When I click on the Log out text link in the side Nav Menu, I am logged out and taken directly to the Landing page. The entry and exit touchpoint of a user experience matters, which cause a UX lapse in the flow. 

**To Reproduce**

1. Click the Log out Nav Menu link on the left panel in your dashboard.
2. Redirects to homepage.

**Expected behavior**
There is a lapse in the process which is a confirmation to let the users know the action they are about to take (In scenarios where they click on the link by mistake) and also an acknowledgement or alert to let them know they have successfully logged out of their account.

**Comment by teelda** [comment]
@srish @tuxology Can I be assigned to work on this flow?

**Comment by srish** [comment]
Addressing this change is part of a larger UX overhaul so I am closing this for now to avoid further inconsistencies.
