### ISSUE TITLE
Zubhub Home Page Small Screens Issues

### ISSUE THREAD

**Issue by OmaJuliet** [unstructuredstudio/zubhub#753]
There are some issues I encountered while navigating the homepage on the mobile screen.

- When I click the notification icon on a small screen(not logged in yet), the UI doesn't look so great. The background content is scrollable and the notification modal takes up the whole width of the page. I don't know if this error is peculiar to users who aren't logged in yet. Here's a screenshot of this bug:
![Zubhub 3](https://github.com/unstructuredstudio/zubhub/assets/77335123/2ddb32b5-d1bd-4b7d-92c5-7a1d108b6e3c)

- Give the navbar a background color as it is currently transparent and doesn't look good while on smaller screens or desktop screens.
- Also, I noticed that there is no close icon to close the menu. There should be an icon for users to be able to use to close the hamburger menu on small devices.
- The search bar feature on mobile screen sizes isn't exactly good looking. It kinda overlaps the hero section.
- The texts are very large on smaller screens

These issues are bad for user experience and can lead to increase in bounce rate.
@srish @tuxology Can I be assigned to work on these?

**Comment by srish** [comment]
Addressing this change is part of a larger UX overhaul so I am closing this for now to avoid further inconsistencies.
