### ISSUE TITLE
Header Opacity 

### ISSUE THREAD

**Issue by outcast-02** [unstructuredstudio/zubhub#754]
**Header has no opacity **
Upon visiting our website, it has come to our attention that there is no header opacity effect when the website initially loads. This absence of a header opacity transition may impact the website's visual appeal and user experience, as it can result in a sudden and jarring transition from the background to the header content.

**To Reproduce**

1. Go to https://zubhub.unstructured.studio/'

**Expected behavior**
The header will have a background.

**Screenshots**
![image](https://github.com/unstructuredstudio/zubhub/assets/75933388/4e1f2448-b831-4fd7-b8b8-0404f3f459dc)

**Comment by OmaJuliet** [comment]
@srish @tuxology Can I be assigned to work on this?
It's also part of the issue I raised

**Comment by srish** [comment]
Addressing this change is part of a larger UX overhaul, so I am closing this for now to avoid further inconsistencies.
