### ISSUE TITLE
Signup Page Issues

### ISSUE THREAD

**Issue by OmaJuliet** [unstructuredstudio/zubhub#755]
**Border invisible when users click the input fields**
While trying to sign up, I clicked on the input fields of each of the entries and the border became invisible. 
In the image attached below, the large white space is the input field for "Bio". It's not supposed to be that blank.

Also, the sign-up button at the bottom of the form is blank. This can also be seen in the first screenshot attached below. 
This blank button also applies to the login page. There is no text on the login page button.

There's also the issue of "Location" dropdown being blank. There are no options in the "Location" dropdown when signing up. And without inputting a location, I can't submit the form. It throws an error(as shown in the 2nd screenshot attached).

**To Reproduce**

1. Go to '[the ZubHub website](https://zubhub.unstructured.studio/signup)'
2. Click on any of the input fields like you want to sign up to the website
3. You'll notice the border disappearance bug, the blank location dropdown, and the blank sign-up button.

**Expected behavior**
When users click on each input field, the border shouldn't disappear and there should be a text on the sign-up button.

**Screenshots**
![zubhub](https://github.com/unstructuredstudio/zubhub/assets/77335123/85b74da1-5542-4efa-ba74-379f3fd328f4)

![Zubhub 2](https://github.com/unstructuredstudio/zubhub/assets/77335123/9f7b1757-895a-48f6-8d32-d30bb61b01b1)

@srish @tuxology Can I work on fixing these issues?

**Comment by srish** [comment]
Addressing this change is part of a larger UX overhaul, so I am closing this for now to avoid further inconsistencies.
