### ISSUE TITLE
Sign up hovering issue

### ISSUE THREAD

**Issue by outcast-02** [unstructuredstudio/zubhub#756]
A significant issue has been identified concerning the sign-up button on our website. When users hover their cursors over the sign-up button, it mysteriously disappears from view. This unexpected behavior disrupts the user experience and prevents potential users from accessing the registration process.
![2](https://github.com/unstructuredstudio/zubhub/assets/75933388/32309b98-03bb-4a13-8fb1-d1a0b65d8ddc)
![1](https://github.com/unstructuredstudio/zubhub/assets/75933388/368f669b-20c2-4e3f-aea5-a14970536d45)

**Comment by OmaJuliet** [comment]
@srish @tuxology Can I be assigned to fix this bug?

**Comment by srish** [comment]
Addressing this change is part of a larger UX overhaul, so I am closing this to avoid further inconsistencies.
