### ISSUE TITLE
Search Feature on Country Codes and Error Message/ Loading screen on Sign Up page

### ISSUE THREAD

**Issue by Quinterlozi** [unstructuredstudio/zubhub#757]
On the sign up form, where one is required to input his/her phone there is no search bar where one can easily search for his/her country using the country's initial letters. One has to scroll down until one finds his/her country which is tiresome and leads to a unpleasant user experience.
On the same sign up form, when one attempts to sign in after inputting his/her credentials, the page does not load and an error message is not displayed. This makes it confusing for the user.

Below is the visual explanation on the issue
![ZUBHUB issue 1](https://github.com/unstructuredstudio/zubhub/assets/106597099/9c36fbd1-98fb-436b-8c1a-8f6efa759d4c)

@srish @tuxology  Permit me to work on this??

**Comment by srish** [comment]
Addressing this change is part of a larger UX overhaul, so I am closing this to avoid further inconsistencies.
