### ISSUE TITLE
 signup hovering issue

### ISSUE THREAD

**Issue by outcast-02** [unstructuredstudio/zubhub#758]
A significant issue has been identified concerning the sign-up button on our website. When users hover their cursors over the sign-up button, it mysteriously disappears from view. This unexpected behavior disrupts the user experience and prevents potential users from accessing the registration process.
![2](https://github.com/unstructuredstudio/zubhub/assets/75933388/4489e610-c270-4934-a479-1524ba507a5e)
![1](https://github.com/unstructuredstudio/zubhub/assets/75933388/09dfd034-4371-4a88-8895-6c82e233c5b0)

**Comment by srish** [comment]
Addressing this change is part of a larger UX overhaul, so I am closing this to avoid further inconsistencies.
