### ISSUE TITLE
Introduce a social authentication feature as a Sign up and Login option

### ISSUE THREAD

**Issue by Michelle-okechi** [unstructuredstudio/zubhub#759]
A social authentication feature easily helps users sign up to a platform using their social accounts such as Google, Facebook, GitHub account, etc. This helps to reduce drop-off rates of users at initial signup. In the picture below, there's an option to either use social authentication or sign up with email manually. This would enhance the user experience of Zubhub

![Studio Display Front View Mockup](https://github.com/unstructuredstudio/zubhub/assets/146777024/08f63149-c815-4bf5-adfc-a64bb2f77130)

@srish @tuxology please assign this task to me to work on

**Comment by Michelle-okechi** [comment]
@srish @tuxology I'll like to work on this feature to improve the user experience of Zubhub's authentication process

**Comment by srish** [comment]
Addressing this change is part of a larger UX overhaul, so I am closing this to avoid further inconsistencies.
