### ISSUE TITLE
Redesigning Hero Section Page and Introducing top navigation bar

### ISSUE THREAD

**Issue by PascalAnuche** [unstructuredstudio/zubhub#761]
I'm proposing a redesign of the hero page section. As the website targets Children and teachers, I suggest The hero page section needs improvement so that the targetted users can know the most critical information on the text hierarchy, making it more visually appealing and user friendly.

The Notification icon on the landing page as a first-time user doesn't notify users of any specific activities going on the landing page. I'd suggest that the notification icon be removed and have a CTA button that leads the users either to sign up or log in.

I'm also suggesting a top navigation bar to be included for easy navigation on the landing page so users can easily scroll on the landing page and reduce bounce-off rate

@tuxology @srish

**Comment by PascalAnuche** [comment]
@srish @tuxology Please, can you assign to  it

**Comment by srish** [comment]
Addressing this change is part of a larger UX overhaul, so I am closing this to avoid further inconsistencies.
