### ISSUE TITLE
Page components overlapped with navbar

### ISSUE THREAD

**Issue by Dagmawi-22** [unstructuredstudio/zubhub#762]
![image](https://github.com/unstructuredstudio/zubhub/assets/109204719/da622cee-ef15-49e1-a8af-d2701be71f13)
When the home page is scrolled upwards, part of it becomes overlapped with the Navbar components and somehow disturbs the user.

**Comment by Dagmawi-22** [comment]
hi @srish, I can fix this in two ways i.e. adjusting z-indices or making the navbar disappear when scrolling to top.

**Comment by srish** [comment]
Addressing this change is part of a larger UX overhaul, so I am closing this to avoid further inconsistencies.
