### ISSUE TITLE
Webapp top navigation bar overlapping with other elements when scrolling

### ISSUE THREAD

**Issue by chudivictor** [unstructuredstudio/zubhub#763]
## Learning objectives: for good UX, the top nav bar should stick to the top when scrolling so it doesn't overlap with other element on the dashboard/webapp

##Link: https://zubhub.unstructured.studio/projects

**Comment by srish** [comment]
Addressing this change is part of a larger UX overhaul, so I am closing this to avoid further inconsistencies.
