### ISSUE TITLE
Scroll to bottm

### ISSUE THREAD

**Issue by Dagmawi-22** [unstructuredstudio/zubhub#764]
![image](https://github.com/unstructuredstudio/zubhub/assets/109204719/889327de-02b1-4dd1-8fc9-505fb35b8a91)
It will be better if the scroll to top button can be converted to scroll to bottom when the scroll position is on the top

**Comment by Dagmawi-22** [comment]
hi @srish, I can apply conditional scrolling to top/bottom considering the current scroll position.

**Comment by srish** [comment]
Addressing this change is part of a larger UX overhaul, so I am closing this to avoid further inconsistencies.
