### ISSUE TITLE
Low Contrast on the Call to action button

### ISSUE THREAD

**Issue by chudivictor** [unstructuredstudio/zubhub#765]
The Primary CTA has a low contrast that users are unable to see, I am proposing the contrast should be balanced thus, using the primary color for the CTA so users can easily see and click thus increasing the conversion

[##Link](https://zubhub.unstructured.studio/edit-profile)
![issues](https://github.com/unstructuredstudio/zubhub/assets/81053657/322fdecf-7941-4aec-aaad-f4516fd5b54c)

cc @srish

**Comment by srish** [comment]
Addressing this change is part of a larger UX overhaul, so I am closing this to avoid further inconsistencies.
