### ISSUE TITLE
Date of Birth validation

### ISSUE THREAD

**Issue by Dagmawi-22** [unstructuredstudio/zubhub#766]
![image](https://github.com/unstructuredstudio/zubhub/assets/109204719/8e91818a-f6fc-435d-9300-8e4767a99105)

Rather than saying "You must be older than 13 years old", we can specify the min date for the text input so that the user can not pick an earlier date.

**Comment by srish** [comment]
Addressing this change is part of a larger UX overhaul, so I am closing this to avoid further inconsistencies.
