### ISSUE TITLE
Search Bar Width and Border radius

### ISSUE THREAD

**Issue by Aishatt** [unstructuredstudio/zubhub#769]
**Describe the bug**
 On Desktop screen search bar corners are not uniform, as a designer I believe it is visually ideal to go with either round  or square corner edges on both sides Width 

**To Reproduce**

1. Go to '(https://zubhub.unstructured.studio/signup)'

**Expected behavior**
Equal border-radius on both sides of the search bar or no border-radius to keep as square

**Screenshot**

<img width="1440" alt="Screenshot 2023-10-03 at 21 16 47" src="https://github.com/unstructuredstudio/zubhub/assets/82312567/1930258e-160e-46f4-93c1-f52a405da6f9">
search bar or no border-radius to keep as square

@srish @tuxology Can I work on fixing these issues?

**Comment by srish** [comment]
Kindly avoid submitting small UX issues like this, as they are currently part of our larger UX improvement plans. Addressing these minor concerns separately may result in further inconsistencies.
