### ISSUE TITLE
Low contrast on the edit profile button

### ISSUE THREAD

**Issue by Marhiposa** [unstructuredstudio/zubhub#771]
**Issue**
When i try to edit my profile, its just an empty button ( font is not visible).

**Expected behaviour**
The button should have a text in it that says EDIT, so people can edit their profiles.

**Screenshots**
<img width="1390" alt="Screenshot 2023-10-03 at 11 14 12 PM" src="https://github.com/unstructuredstudio/zubhub/assets/146780247/477d23c4-ddcb-4f9c-91c2-4616bc735d15">

**Comment by srish** [comment]
No more reproducible. ZubHub went through deployment recently which may have caused this issue.

**Comment by Marhiposa** [comment]
@srish Alright sorry about that
