### ISSUE TITLE
Improve the matching algorithm for materials field

### ISSUE THREAD

**Issue by Dagmawi-22** [unstructuredstudio/zubhub#776]
![image](https://github.com/unstructuredstudio/zubhub/assets/109204719/c38d7395-e847-4ef8-afbf-c84ef71cd519)

When typing and hitting enter, it adds the typed material but the input value stays same and not cleared.

**Comment by Dagmawi-22** [comment]
This may result in unnecessary duplication of items.

**Comment by akankshat05** [comment]
can i work on this?

**Comment by Dagmawi-22** [comment]
@srish, I kindly ask you to fix this as I'm familiar with such a situation.

**Comment by srish** [comment]
Feel free to submit a PR. This task can have multiple PRs. :)

**Comment by Dagmawi-22** [comment]
hello @srish, can I get access to push to the repo so that I can make a pr?
