### ISSUE TITLE
Add pagination for projects & activities page

### ISSUE THREAD

**Issue by Temabo** [unstructuredstudio/zubhub#781]
The navigation will be difficult when there will be too many items on the [projects](https://zubhub.unstructured.studio/projects) and [activities](https://zubhub.unstructured.studio/activities) page (which only users with staff credentials have access to). Right now it is possible to navigate by clicking on the "Next" and "Previous" buttons. Adding a pagination feature with numbered pages will significantly improve user experience, making it much easier for users to move around and find the projects and activities they want. This small change will enhance the user-friendliness and efficiency of ZubHub.

**Comment by aqsaaqeel** [comment]
Nice idea! I'd like to work with @Temabo to implement this feature @srish @tuxology

**Comment by srish** [comment]
@Temabo, feel free to go ahead and create a design. Once it's ready, you can post it here so that we can gather input from others, and then @aqsaaqeel can put it into action. This aligns perfectly with our vision for how the designer and developer will work together on Outreachy microtasks. :-)

**Comment by Temabo** [comment]
Great! @srish I will start working on it and tag @aqsaaqeel to the figma link when I am done

**Comment by Temabo** [comment]
Hello @aqsaaqeel This is the link to the figma file that contains the pagination design.
https://www.figma.com/file/A1GYQtENXSmPUzB63MTgPj/outreachy?type=design&node-id=506%3A7405&mode=design&t=xdOBknDLPUnlp7LB-1
![Pagination](https://github.com/unstructuredstudio/zubhub/assets/105416140/926501e3-cd19-4dfd-84d3-d1cfe6d02715)

**Comment by PascalAnuche** [comment]
With the pagination concept, @Temabo  came up with, I also came up with an idea of how the layout can be when users are navigating through the featured projects and All Projects. The pagination will help the users to navigate through the featured projects easily by seeing 6 All projects horizontally decreasing the length of the page which helps in a seamless user experience and saves time too.

Here is the figma link https://www.figma.com/file/zWHBhu5EnsNJbMi26j1NKb/Outreachy-Zubhub-intern?type=design&node-id=0%3A1&mode=design&t=BPYegXaKZF0212Vm-1

@srish @Temabo 
<img width="1622" alt="Frame 427321225" src="https://github.com/unstructuredstudio/zubhub/assets/101313594/b2ae9d38-be54-44be-86b6-159b76702cf9">

**Comment by chudivictor** [comment]
I also came up with another pagination style for this issue which is the **DROPDOWN PAGINATION STYLE** this is most effective when there are a significant number of pages to navigate, and users benefit from the ability to jump to specific pages

Here is the figma Link: [https://www.figma.com/file/CyU8aydZVGJvFtb5FF4Sq5/outreachy?type=design&node-id=0%3A1&mode=design&t=iiP4yxpgxtmdgnav-1](url)
![outreachy](https://github.com/unstructuredstudio/zubhub/assets/81053657/8c3615eb-9376-47bc-b5ec-c777de2a5baa)

**Comment by brrkrmn** [comment]
@Temabo 

The design looks great! I would love to help with the implementation if you need it

**Comment by Temabo** [comment]
Thank you! @brrkrmn I believe @aqsaaqeel has been assigned to implement it

**Comment by aqsaaqeel** [comment]
> Hello @aqsaaqeel This is the link to the figma file that contains the pagination design. https://www.figma.com/file/A1GYQtENXSmPUzB63MTgPj/outreachy?type=design&node-id=506%3A7405&mode=design&t=xdOBknDLPUnlp7LB-1 ![Pagination](https://user-images.githubusercontent.com/105416140/272743490-926501e3-cd19-4dfd-84d3-d1cfe6d02715.png)

I like this design, it is consistent with the current style of Zubhub too imo, can I start implementing this @srish ?

**Comment by Mbeute23** [comment]
I came up with a pagination an i use one of Zubhub design to show how the pagination is been use through the feature projects. Pagination will help users navigate through other pages projects easily by either clicking to next or to each numbers which will enhance the user-friendliness and efficiency of ZubHub.

Here is the link to the figma file: https://www.figma.com/file/ByALA1tM5mTZCfLz5Kr3Ko/Outreachy-Zubhub-Design-(Contribution-to-issues)?type=design&node-id=1%3A1344&mode=design&t=gVeqFKvNWKvuYr6x-1

![Pagination](https://github.com/unstructuredstudio/zubhub/assets/146943654/7159c074-9e3a-4a60-8f85-205684623387)

![Example of Pagination on Zubhub website](https://github.com/unstructuredstudio/zubhub/assets/146943654/f45bc76d-6fa5-4e7b-996f-cf29b2f8b452)
 
 @srish How is the design?

**Comment by Michelle-okechi** [comment]
Nice work!! @Temabo @chudivictor @PascalFrost

**Comment by Michelle-okechi** [comment]
@srish @tuxology I also designed a pagination style that would enable users to navigate the project page with ease. I chose this style because of I wanted a minimalistic approach and also its ease of use, by placing the previous and next buttons close to each other. I chose this colour theme because of its colour balance with the existing yellow background colour of the "Projects" page. 

![Pagination_unstructuredstudio](https://github.com/unstructuredstudio/zubhub/assets/146777024/7901dc8f-9f13-4df0-bed5-5616a6904987)

I also tried it in black colour as an option

![pagination black](https://github.com/unstructuredstudio/zubhub/assets/146777024/f3a82d68-240f-4008-8d9c-4e0e8c081668)


Up close image of the white colour option

![Pagination white](https://github.com/unstructuredstudio/zubhub/assets/146777024/d52470c3-1be7-4499-9ed1-8b441c07d764)

**Comment by yokwejuste** [comment]
@srish @tuxology please can we have a conclusion onto this, so we can start working on it

**Comment by aqsaaqeel** [comment]
@yokwejuste this is already being looked into by me I'll finish it off as soon as the design gets the green flag

**Comment by coderatomy** [comment]
Excellent job, @Temabo, @Michelle-okechi, and @Mbeute23. I have a constructive suggestion to enhance our user experience.

Consider implementing an infinite scrolling mechanism and incorporate @Prescopella's recommendation from issue #808 for efficient filtering. Additionally, create a user-friendly section featuring various tags. Users can click on these tags to initiate filtration. Infinite scrolling eliminates the need for manual pagination, simplifying the navigation process significantly. This approach is particularly advantageous when dealing with an extensive database of projects, mitigating the challenges associated with traditional pagination, especially when managing a large volume of data. Imagine having 1000 projects under pagination!

**Comment by Temabo** [comment]
@coderatomy 

Thank you for suggesting the implementation of an infinite scrolling mechanism. While it offers advantages in managing large datasets, it's important to consider potential user experience challenges. One concern is that users might find it harder to navigate back to a specific project that caught their interest, as they would have to scroll through a potentially extensive list again.

In contrast, pagination allows users to easily navigate from one screen to another, providing a clear structure. We can discuss it further so we find a middle ground and the best solution. Additionally, implementing a user-friendly section featuring various tags for efficient filtration as suggested by @prescopella in issue #808 is an excellent idea and complements both navigation methods.

**Comment by Michelle-okechi** [comment]
> Excellent job, @Temabo, @Michelle-okechi, and @Mbeute23. I have a constructive suggestion to enhance our user experience.
> 
> Consider implementing an infinite scrolling mechanism and incorporate @Prescopella's recommendation from issue #808 for efficient filtering. Additionally, create a user-friendly section featuring various tags. Users can click on these tags to initiate filtration. Infinite scrolling eliminates the need for manual pagination, simplifying the navigation process significantly. This approach is particularly advantageous when dealing with an extensive database of projects, mitigating the challenges associated with traditional pagination, especially when managing a large volume of data. Imagine having 1000 projects under pagination!

Thank you @coderatomy for suggesting an infinite scrolling mechanism. However, I agree with @Temabo 's on this and i'd like to further buttress her point with an example. 
Say a user navigates through the pages of the project list and sees a project he likes on the second page but decides to keep scrolling for more options. He later decides that he has seen enough and wants to return to the project he declared interest in. Now with the navigations designed above, he can quickly click on page 2 to find his project instead of scrolling infinitely to find it

**Comment by Temabo** [comment]
> > Excellent job, @Temabo, @Michelle-okechi, and @Mbeute23. I have a constructive suggestion to enhance our user experience.
> > Consider implementing an infinite scrolling mechanism and incorporate @Prescopella's recommendation from issue #808 for efficient filtering. Additionally, create a user-friendly section featuring various tags. Users can click on these tags to initiate filtration. Infinite scrolling eliminates the need for manual pagination, simplifying the navigation process significantly. This approach is particularly advantageous when dealing with an extensive database of projects, mitigating the challenges associated with traditional pagination, especially when managing a large volume of data. Imagine having 1000 projects under pagination!
> 
> Thank you @coderatomy for suggesting an infinite scrolling mechanism. However, I agree with @Temabo 's on this and i'd like to further buttress her point with an example. Say a user navigates through the pages of the project list and sees a project he likes on the second page but decides to keep scrolling for more options. He later decides that he has seen enough and wants to return to the project he declared interest in. Now with the navigations designed above, he can quickly click on page 2 to find his project instead of scrolling infinitely to find it

Exactly! @Michelle-okechi This use case explains it perfectly!

**Comment by coderatomy** [comment]
It seems like every scenario has it's fit 🙂. Developer wise, that was my suggestion. Feel free to ping me with a final work around. Otherwise, thanks for the outstanding work you doing guys 🙏

**Comment by yokwejuste** [comment]
> It seems like every scenario has it's fit 🙂. Developer wise, that was my suggestion. Feel free to ping me with a final work around. Otherwise, thanks for the outstanding work you doing guys 🙏

@coderatomy I really like these ideas, but what I'll suggest will require a lot of calculations and also a good communication with the backend. But a benefit will be an infinite scroll mechanism for the paginations.

Here are some examples: 
- [Oss Cameroon Projects](https://osscameroon.com/projects)
![image](https://github.com/unstructuredstudio/zubhub/assets/71908316/05dfedb7-bfd6-4c38-9b94-0cb8e50f9ee9)
- [Oss Cameroon Miniyotas](https://miniyotas.osscameroon.com/issues?page=11)
![image](https://github.com/unstructuredstudio/zubhub/assets/71908316/df8f3377-7ad9-46bc-827e-577d15e227ba)

Please keep in mind I'm not a designer reason why I couldn't design it to showcase here, but a designer can use it as a reference.

**Comment by Dumzy006** [comment]
Hello @srish 
I also came up with a pagination based on the advantages  @yokwejuste mention ( good communication with the backend and also an infinite scroll mechanism for the paginations)
Find screenshot and figma link below
https://www.figma.com/file/POs8v906c2IFSa7QqDONR6/ZUBHUB-CONTRIBUTION?type=design&node-id=8-17679&mode=design&t=eZZsvTM9ucjzO3PM-0
![image](https://github.com/unstructuredstudio/zubhub/assets/136137889/2550c58e-671c-4ec4-a8f9-322220633c8a)
![image](https://github.com/unstructuredstudio/zubhub/assets/136137889/35d8f8e7-ec57-4624-ad8b-2dce4af2835c)

**Comment by aqsaaqeel** [comment]
@coderatomy @Temabo I think pagination serves the purpose of our current use case, it helps easier navigation back and forth. We do not have any create project button so chances are the user will scroll all the way down and won't know where to go from there. 

And since we already have a previous and next functionality, pagination will be an added advantage to that. Whereas infinite scrolling will require lots of redesigning.

**Comment by yokwejuste** [comment]
> Hello @srish 
> I also came up with a pagination based on what @yokwejuste mention
> Find screenshot and figma link below
> https://www.figma.com/file/POs8v906c2IFSa7QqDONR6/ZUBHUB-CONTRIBUTION?type=design&node-id=8-17679&mode=design&t=eZZsvTM9ucjzO3PM-0
> ![image](https://github.com/unstructuredstudio/zubhub/assets/136137889/2550c58e-671c-4ec4-a8f9-322220633c8a)
> ![image](https://github.com/unstructuredstudio/zubhub/assets/136137889/35d8f8e7-ec57-4624-ad8b-2dce4af2835c)
> 
> 

Great job,

@coderatomy try to have a look at this

**Comment by Temabo** [comment]
> @coderatomy @Temabo I think pagination serves the purpose of our current use case, it helps easier navigation back and forth. We do not have any create project button so chances are the user will scroll all the way down and won't know where to go from there.
> 
> And since we already have a previous and next functionality, pagination will be an added advantage to that. Whereas infinite scrolling will require lots of redesigning.

Yes, this would work.

**Comment by Temabo** [comment]
> Hello @aqsaaqeel This is the link to the figma file that contains the pagination design. https://www.figma.com/file/A1GYQtENXSmPUzB63MTgPj/outreachy?type=design&node-id=506%3A7405&mode=design&t=xdOBknDLPUnlp7LB-1 ![Pagination](https://user-images.githubusercontent.com/105416140/272743490-926501e3-cd19-4dfd-84d3-d1cfe6d02715.png)

Hello @srish , @aqsaaqeel and I are still awaiting review and feedback on this. Thank you.

**Comment by coderatomy** [comment]
Nice.  Am sure we also have to integrate @Prescopella's, do you still have that in mind @Temabo?

**Comment by rak16** [comment]
@coderatomy I see that @srish redirected to https://github.com/unstructuredstudio/zubhub/issues/777 in terms of what's to be done with the filters - there are already approved designs for the same. So we could implement pagination + filter.

**Comment by Temabo** [comment]
> @coderatomy I see that @srish redirected to #777 in terms of what's to be done with the filters - there are already approved designs for the same. So we could implement pagination + filter.

Yes, I think this combines both ideas effectively @coderatomy

**Comment by srish** [comment]
@aqsaaqeel I hope you followed the design here https://github.com/unstructuredstudio/zubhub/issues/781#issuecomment-1755731060 that received 8 votes ? :-)

**Comment by aqsaaqeel** [comment]
> @aqsaaqeel I hope you followed the design here [#781 (comment)](https://github.com/unstructuredstudio/zubhub/issues/781#issuecomment-1755731060) that received 8 votes ? :-)

Yes, i have followed this one
