### ISSUE TITLE
Cursor not turning into pointer on hover on notification and profile icons

### ISSUE THREAD

**Issue by aqsaaqeel** [unstructuredstudio/zubhub#782]
**Describe the bug**
In the Navbar section, when I hover over the icons for Notification and Profile, it does not change the cursor into a pointer. For new users, this can be confusing and they might not how to access the profile section. 
This becomes especially confusing because there is a part on the navbar that shows the username. This part is not clickable and so the cursor being default is right. 
A new user might get confused and can keep clicking on the username to access the profile section. Only after some trials can they click on the profile icon and navigate to the profile section. This is a small issue but disrupting the UX

**To Reproduce**
Go to Zubhub page and hover over the profile and notification icons on the Navbar

**Expected behavior**
When we hover over the language icon or the search bar the cursor changes into a pointer indicating that some action can be performed. This is expected of the profile and notification icon too.

**Screenshots**
![Screenshot from 2023-10-05 01-26-16](https://github.com/unstructuredstudio/zubhub/assets/85514520/f16f32d3-3883-4b3d-baa6-b18f47ae8914)
In the screenshot, the cursor is not visible but we can try hovering on all the clickable icons and see the bug.

**Comment by aqsaaqeel** [comment]
@tuxology @srish I'd like to be assigned to work on this issue!

**Comment by srish** [comment]
@aqsaaqeel Thank you for documenting this! Please feel free to submit a pull request (PR) for it. Make sure that the hover cursor is consistent with the ones used elsewhere in ZubHub.

**Comment by aqsaaqeel** [comment]
Sounds good. I'll start working on this! Could you make me an assignee on this as well @srish
