### ISSUE TITLE
Adding Project Category to Project Page for Easier Navigation.

### ISSUE THREAD

**Issue by Stephxdesigns** [unstructuredstudio/zubhub#783]
I suggest that project categories be added to the existing project page.
Categories like Science Art Craft etc would make it easier for users interested in a particular topic find projects they are interested in quickly rather than going through the entire project listing.

This would greatly improve the user's experience while navigating the projects page

**Comment by Stephxdesigns** [comment]
@tuxology @srish 
If this is approved I would like to work on it.

**Comment by srish** [comment]
Closing this as it might make sense to wait and see how https://github.com/unstructuredstudio/zubhub/issues/777 evolves.
