### ISSUE TITLE
Clicking on items in the left sidebar doesn't give any visual feedback.

### ISSUE THREAD

**Issue by PascalAnuche** [unstructuredstudio/zubhub#790]
When a user Clicks on items in the left sidebar, it doesn't give any active state that shows the page they're on. Adding active state effects would make the interactive areas more obvious.
![Screenshot (40)](https://github.com/unstructuredstudio/zubhub/assets/101313594/5a64ba33-ae3c-4d27-9865-e855b4d3f088)

@srish Can I work on it so that a developer can implement it won't take much time

**Comment by srish** [comment]
It does give feedback unless ZubHub is broken. It is supposed to give a blue hover and text in links appear with an underline. I think that is good for now.
