### ISSUE TITLE
Add a save and a discard button on the edit profile page

### ISSUE THREAD

**Issue by chudivictor** [unstructuredstudio/zubhub#791]
<img width="1438" alt="Screenshot 2023-10-05 at 11 25 20" src="https://github.com/unstructuredstudio/zubhub/assets/81053657/c6ce87fd-29aa-4bb1-a03c-755bb0d7cffd">
**This features/button can help with 1. data confirmation**- When a user edits their profile information, they might make multiple changes. The "Save" button allows users to confirm that they want to update their profile with the changes they've made. It prevents accidental changes from being applied.
2. **Confirmation and Feedback:** After clicking the "Save" button, users typically receive confirmation that their changes have been successfully saved. This provides positive feedback and reassures users that their updates have been recorded.
3. **User Expectation:** Users have become accustomed to the presence of these buttons in various applications and websites. Not having them can confuse users and make them uncertain about how to apply or discard changes.

**Comment by Temabo** [comment]
@chudivictor I agree with this idea of adding "Save" and "Discard" buttons on the Profile page while users edit there profile information. These buttons enhance user experience by providing clear data confirmation.

**Comment by chudivictor** [comment]
**Proposed Solution**
Save and discard buttons are important elements in an edit profile page because they provide control, confirmation, error handling, and a familiar user experience, ultimately improving the usability and reliability of the profile-editing process.

![proposed solution](https://github.com/unstructuredstudio/zubhub/assets/81053657/d6ac11c6-04c4-4f47-8455-96910c31793c)

**Comment by srish** [comment]
@chudivictor @Temabo You meant having a save button and discard changes for the edit profile page here: https://zubhub.unstructured.studio/edit-profile?

**Comment by Ali-Ahmed-Mohammed** [comment]
@srish I want to work this, I create  as  UI or I write code

**Comment by chudivictor** [comment]
Yes, the save button can also stay there too @srish

**Comment by Ali-Ahmed-Mohammed** [comment]
@srish could you assign me this

**Comment by coderatomy** [comment]
For the `/edit-profile` page. I believe everything looks good now @chudivictor  @Ali-Ahmed-Mohammed @Temabo. Unless we want an update. 

![image](https://github.com/unstructuredstudio/zubhub/assets/141822315/420cd229-3953-4706-bbe1-fbc29c7a3741)

**Comment by Temabo** [comment]
@srish @coderatomy I feel like  "Save Changes" would work better than "Edit Profile" for the CTA in terms a user experience. when I tried to edit my profile, after typing in the changes I wanted to make, The "Edit Profile" button threw me off because it felt like if I click it my changes would clear. If the button said "Save changes", the function would be clearer and a "Discard" button would be effective in cases where the user wants to cancel the edit they have made and stick to their previous profile details.

![Frame 837](https://github.com/unstructuredstudio/zubhub/assets/105416140/3b116a37-9463-4e93-9572-80c6e7f9203f)

**Comment by srish** [comment]
@Temabo Thanks for the design! Ready for a dev to take this up.

**Comment by Temabo** [comment]
Alright! @srish 
I will put this up on Zulip so a dev can implement it.

Figma link; https://www.figma.com/file/A1GYQtENXSmPUzB63MTgPj/outreachy?type=design&node-id=604%3A13468&mode=design&t=FK8j4StLBFEOciEY-1

**Comment by brrkrmn** [comment]
@srish 
hey,  #836 handles this ☺️
