### ISSUE TITLE
Homepage redesign suggestions, Improving the ZubHub homepage layout, to be more visually appealing, informative and user-friendly.  and some part of the website

### ISSUE THREAD

**Issue by ladyami** [unstructuredstudio/zubhub#793]
**Re-design of Zubhub homepage**
Issues: 
1. Visually appealing
2. Informative
3. User-friendly

Visual appeal:

-According to a study by HubSpot, 82% of users say that visual appeal is an important factor in their decision to trust a website. To improve the visual appeal of the ZubHub homepage, I would suggest using a more vibrant color palette, using high-quality images and videos, and using a more modern design.

-For example, the current homepage uses a muted color palette of blue, red and white. I would suggest using a more vibrant color palette, in the same shade of the brand color to make the homepage more visually appealing.

-The current homepage also uses low-resolution images and videos. I would suggest using high-resolution images and videos to make the homepage more visually appealing and to showcase the creative projects on ZubHub in the best possible light.

-Finally, the current homepage uses a dated design. I would suggest using a more modern and minimalist design to make the homepage more visually appealing and to appeal to a wider range of users.

Informativeness:

-According to a study by Nielsen Norman Group, 70% of users want to know what a website is about within the first 10 seconds of visiting it. To make the ZubHub homepage more informative, I would suggest adding a brief overview of what ZubHub is and what it can be used for. 
-Highlight featured projects. This could be done by showcasing a few of the most popular or interesting projects on the homepage.

User-friendliness:

-According to a study by Forrester Research, 52% of users will abandon a website if it takes longer than 3 seconds to load. To make the ZubHub homepage more user-friendly, I would suggest optimizing the page for speed and using a more organized layout.

-For example, the current homepage takes a bit of time to load. I would suggest optimizing the page for speed by using a content delivery network (CDN) and by compressing images and videos.

-Use more white space. The current design is a bit cluttered and could be improved with the use of more white space. This would make it easier for users to scan the page and find the information they are looking for.

-Use a more organized layout. The current layout is a bit scattered and could be improved by grouping related elements together. This would make it easier for users to navigate the page and find what they are looking for.

Benefits of redesigning the ZubHub homepage:

-Improved user experience: A redesigned website can be more visually appealing, informative, and user-friendly, which can lead to a better user experience.

-Increased informativeness: This would help potential users to understand the value of ZubHub and how it can benefit them.

-Attract more users: A more visually appealing, informative, and user-friendly homepage is more likely to attract new users to the platform.

-Boost brand awareness: A redesigned homepage can help to boost brand awareness by showcasing ZubHub's unique value proposition and visual identity.

-Increase conversions: A well-designed homepage can help to increase conversions by making it easier for users to take desired actions, such as signing up for an account, creating a project, or browsing projects.

@srish @tuxology This task can be divided into smaller sub-tasks and assigned to designers who want to contribute to ZubHub.

**Comment by N-TITIAN** [comment]
i will love to collaborate in the design process

**Comment by ladyami** [comment]
okay let get it approved first

**Comment by srish** [comment]
@ladyami Thanks for creating this task! The homepage was recently designed, so we have no plans for another overhaul anytime soon. However, some remaining issues, such as  https://github.com/unstructuredstudio/zubhub/issues/792 are remaining and are now a work in progress. With that said, I will close this one out.
