### ISSUE TITLE
A confirmation Modal when the logout button is clicked

### ISSUE THREAD

**Issue by chudivictor** [unstructuredstudio/zubhub#794]
This feature is important because it prevents 
1. Accidental Logouts
2. User Experience: It enhances the overall user experience by giving users a clear opportunity to confirm or cancel their actions.
3. Avoid Data Loss

**Comment by Temabo** [comment]
Yea @chudivictor same thing happens when you click "Delete my account"

**Comment by chudivictor** [comment]
**Proposed Solution**

In this example, the title clearly indicates the purpose of the modal, which is to confirm the logout action. The modal content asks the user if they are sure they want to log out and provides two options: "Cancel" and "Logout." Users can choose to cancel the action if they clicked the logout button by mistake, or they can proceed with the logout by clicking the "Logout" button.

![confirmation modal](https://github.com/unstructuredstudio/zubhub/assets/81053657/2e625275-46cc-4cfd-8c2f-4087117fb843)

![auto flow](https://github.com/unstructuredstudio/zubhub/assets/81053657/d538095d-8b70-4926-9ac5-2bb35b9d1d88)

**Comment by JulietMadu** [comment]
i will create a design for this @srish

**Comment by chudivictor** [comment]
here is the figma link to the design [https://www.figma.com/file/SWnF3FnPCXd4rkI7Bwi4ZW/Untitled?type=design&node-id=1%3A15&mode=design&t=LODj0FW7gfmi14zb-1](url)

@srish

**Comment by srish** [comment]
I don't see an issue with the logout option without a dialog. Also, we have something in the works for the delete feature.
