### ISSUE TITLE
Fix project preview bug & improve design

### ISSUE THREAD

**Issue by Temabo** [unstructuredstudio/zubhub#795]
Issue Description:
When creating a project, at the 3rd and final stage, there's a "Preview" button provided. However, upon clicking this button, the preview page appears to be empty, not displaying any content related to the project being created. 
The expected behavior is that the preview page should accurately reflect the details and content entered during the project creation process. Another UX issue is that the project preview shows up within multiple rounded boxes. The design needs to be improved.

Steps to Reproduce:
1. Log into the platform.
2. Navigate to the project creation section.
3. Progress through the stages of project creation.
4. At the final stage, click on the "Preview" button.

Expected Behavior:
Upon clicking the "Preview" button, the preview page should display the content and details of the project being created, allowing the creator to verify how the project will appear to users.

Hello @srish I am not entirely sure if this is a design or development problem, but I would like to design the preview page so it can be implemented.

**Comment by Temabo** [comment]
I also noticed a typo in the input field to where you add tags during project creation

typo; "start typing to marterials"
<img width="341" alt="image" src="https://github.com/unstructuredstudio/zubhub/assets/105416140/4c719f36-7f56-4a94-8929-e3046c1f8caa">

**Comment by d-arkangel** [comment]
Is this requiring a UIUX fix or a developer fix, please?

**Comment by Mitchell377** [comment]
@srish can i work on this?

**Comment by Temabo** [comment]
Hello @srish 
I have designed the preview page; 
On this page the users can easily look through their project for errors and correct them.
![Preview Project](https://github.com/unstructuredstudio/zubhub/assets/105416140/52dfeb0d-76fc-4ea2-a185-f187be805568)
Link to figma file; https://www.figma.com/file/A1GYQtENXSmPUzB63MTgPj/outreachy?type=design&node-id=565%3A11431&mode=design&t=apIltWVttx97Nt2g-1

Kindly review and share your thoughts.

I would also like to suggest that the progress bar in the project creation flow should include a 4th step for the "Preview" because the current preview button is not very noticeable. This would also improve the user experience as Users would always crosscheck their project before publishing it. Below is a mockup to illustrate this idea;
![Frame 811](https://github.com/unstructuredstudio/zubhub/assets/105416140/ae2e1a52-972c-4ee3-893b-a6386561d13e)

**Comment by Temabo** [comment]
> Is this requiring a UIUX fix or a developer fix, please?

I think It requires both

**Comment by khallow7** [comment]
@Temabo I don't think the design for this page is needed as there's already design made by the previous intern. 
The previous design needs to be implemented properly by the devs.
Here's the link to the design: https://www.figma.com/file/hidnBfP4kNWl7RDxy3aUZI/ZubHub?type=design&node-id=8-649&mode=design&t=g9C88DcIIDf4AL4d-4

**Comment by Stephxdesigns** [comment]
@srish @tuxology 
I came up with an improved design for the preview page. I maintained the existing design layout in the website. I think this would show the creators exactly how the project will be viewed by other users.

I included an edit button that takes the user back to the project creation page which has all the details inputed and they can edit accordingly.

The creator can also publish immediately if satisfied with how the project looks.

I'd like to suggest that the option to preview be added at the last step of the project creation.

![Screenshot_20231006-113315_1](https://github.com/unstructuredstudio/zubhub/assets/136924367/67171ae9-6a40-49ac-af8b-29d9cc3b64fa)

**Comment by Stephxdesigns** [comment]
@srish @tuxology 
I also came up with a mobile view for this page.

![Screenshot_20231006-114737_1](https://github.com/unstructuredstudio/zubhub/assets/136924367/63e3c6a7-57d3-4b4e-a26e-6236b7dc77d1)

I would also like to suggest that this design should be adopted for the button placements in the draft details and project details screens in mobile. Instead of the buttons to be stacked on one another it can be designed this way.

stacked button design on the mobile web app

![Screenshot_20231006-114920_1](https://github.com/unstructuredstudio/zubhub/assets/136924367/d70436e3-43cb-424b-bb6a-3af5a80aebf4)

Please let me know your thoughts 

https://www.figma.com/file/pRcuzEI0Qf76Q6JIkBukM5/Issue-795-improve-input-design?type=design&node-id=0%3A1&mode=design&t=Tr8cOvJOXgn5RBEw-1

**Comment by Temabo** [comment]
> @Temabo I don't think the design for this page is needed as there's already design made by the previous intern. The previous design needs to be implemented properly by the devs. Here's the link to the design: https://www.figma.com/file/hidnBfP4kNWl7RDxy3aUZI/ZubHub?type=design&node-id=8-649&mode=design&t=g9C88DcIIDf4AL4d-4

Alright, Thank you! @khallow7

**Comment by Temabo** [comment]
> I also noticed a typo in the input field to where you add tags during project creation
> 
> typo; "start typing to marterials" <img alt="image" width="341" src="https://user-images.githubusercontent.com/105416140/272896705-4c719f36-7f56-4a94-8929-e3046c1f8caa.png">

I believe a developer can correct this typo...

**Comment by jumokeadeoyo** [comment]
Hi @khallow7, I went through the previous design for the preview page and I believe it needs some iteration. I've reviewed and made the following adjustments: 

- Ensured consistency in the 8-point grid system across the page.
- Reduced emphasis on the "Browse Activities" button to simplify CTAs.
- Removed the redundant "Create Project" button as we're already on the project creation page.
- Maintained consistent colors, including the bell icon, throughout the design.
- Eliminated the blue color to prevent color blocking issues.
- Aligned the search bar with previous designs on the website.
- Enhanced the boldness of the "Create Project" page title.
- Ensured consistent icon sizes across the page.
- Reduced emphasis on the auto-save icon to prevent confusion with clickable buttons.

Here's the link to the revised design: https://www.figma.com/file/7AXxymS00ebzGvqsqFmhbu/project-preview?type=design&node-id=0%3A1&mode=design&t=tHoa6zarwcfphM6h-1
I would appreciate your feedback on these changes. @srish  @tuxology

**Comment by Stephxdesigns** [comment]
![Screenshot_20231011-022144_1](https://github.com/unstructuredstudio/zubhub/assets/136924367/20f90ef9-c56f-49be-b86a-bd0dda04e11b)



@srish 
Here's a design improvement for the previous preview page design. In this design instead of several edit buttons on the page I suggested one edit button that simply takes that user back to the project creation pages to make the necessary edits

**Comment by srish** [comment]
Can we stick to the original design developed by @faridah-ux, implement all changes related to the white box, and not do any changes to the navbar? Thanks all for your suggestions!

**Comment by Stephxdesigns** [comment]
Alright 👍

**Comment by yokwejuste** [comment]
> I also noticed a typo in the input field to where you add tags during project creation
> 
> typo; "start typing to marterials" <img alt="image" width="341" src="https://user-images.githubusercontent.com/105416140/272896705-4c719f36-7f56-4a94-8929-e3046c1f8caa.png">

I fixed this part in an issue related to the tag section

**Comment by yokwejuste** [comment]
> Hello @srish I have designed the preview page; On this page the users can easily look through their project for errors and correct them. ![Preview Project](https://user-images.githubusercontent.com/105416140/273074368-52dfeb0d-76fc-4ea2-a185-f187be805568.png) Link to figma file; https://www.figma.com/file/A1GYQtENXSmPUzB63MTgPj/outreachy?type=design&node-id=565%3A11431&mode=design&t=apIltWVttx97Nt2g-1
> 
> Kindly review and share your thoughts.
> 
> I would also like to suggest that the progress bar in the project creation flow should include a 4th step for the "Preview" because the current preview button is not very noticeable. This would also improve the user experience as Users would always crosscheck their project before publishing it. Below is a mockup to illustrate this idea; ![Frame 811](https://user-images.githubusercontent.com/105416140/273075425-ae2e1a52-972c-4ee3-893b-a6386561d13e.png)

This work is incredible 😃 , love it

**Comment by rak16** [comment]
> Can we stick to the original design developed by @Faridah-ux, implement all changes related to the white box, and not do any changes to the navbar? Thanks all for your suggestions!

Hi @srish, 

i) when you say leave the navbar intact, do you mean this navbar? 
<img width="918" alt="Screenshot 2023-10-12 at 1 30 44 AM" 
src="https://github.com/unstructuredstudio/zubhub/assets/22426390/aaab6388-3bcb-4c85-8f4c-f1f27beb7dbb">

ii) in the design revamp, the steps to create a project have been made vertical – is that to be incorporated in the new design? 
<img width="508" alt="Screenshot 2023-10-12 at 1 29 02 AM" src="https://github.com/unstructuredstudio/zubhub/assets/22426390/1a2f1d95-5fa5-4f03-a4c3-74e936242ee8">


cc: @tuxology @iamhks

**Comment by srish** [comment]
I meant the top most menu on the page with the search bar. And let's stick to @faridah-ux's design unless there are any concerns.

**Comment by yokwejuste** [comment]
> Can we stick to the original design developed by @Faridah-ux, implement all changes related to the white box, and not do any changes to the navbar? Thanks all for your suggestions!

please can you reference the design file here?

I tried looking for it in this chat but nothing to find

**Comment by Temabo** [comment]
> > Can we stick to the original design developed by @Faridah-ux, implement all changes related to the white box, and not do any changes to the navbar? Thanks all for your suggestions!
> 
> 
> 
> please can you reference the design file here?
> 
> 
> 
> I tried looking for it in this chat but nothing to find

https://www.figma.com/file/hidnBfP4kNWl7RDxy3aUZI?locale=en&type=design

**Comment by yokwejuste** [comment]
> > > Can we stick to the original design developed by @Faridah-ux, implement all changes related to the white box, and not do any changes to the navbar? Thanks all for your suggestions!
> > 
> > 
> > please can you reference the design file here?
> > I tried looking for it in this chat but nothing to find
> 
> https://www.figma.com/file/hidnBfP4kNWl7RDxy3aUZI?locale=en&type=design

thanks :smile:

**Comment by aqsaaqeel** [comment]
hey @yokwejuste I have already started working on it. But since this is an overhaul of the whole project preview and a bigger task, we can work to collaborate on this

**Comment by yokwejuste** [comment]
> hey @yokwejuste I have already started working on it. But since this is an overhaul of the whole project preview and a bigger task, we can work to collaborate on this

I agree, this will be good collaboration.

**Comment by aqsaaqeel** [comment]
> > hey @yokwejuste I have already started working on it. But since this is an overhaul of the whole project preview and a bigger task, we can work to collaborate on this
> 
> I agree, this will be good collaboration.

Can you raise a draft PR with whatever you have done till now so that we can divide tasks?

**Comment by gargmonika** [comment]
> hey @yokwejuste I have already started working on it. But since this is an overhaul of the whole project preview and a bigger task, we can work to collaborate on this

Hey @aqsaaqeel  can i collaborate on this with you as well.

**Comment by yokwejuste** [comment]
> > > hey @yokwejuste I have already started working on it. But since this is an overhaul of the whole project preview and a bigger task, we can work to collaborate on this
> > 
> > I agree, this will be good collaboration.
> 
> Can you raise a draft PR with whatever you have done till now so that we can divide tasks?

I've not yet done anything on this, still studying the reusability of some existing components

**Comment by Mbeute23** [comment]
I came up with a design that show the creator an overview of the project he wants to publish after clicking in the preview button.

On the design the creator can directly edit if he sees an error by clicking on the edit button

figma link: https://www.figma.com/file/BncycON1owtkxMZK1BUo4q/Fix-project-preview-bug-%26-improve-design?type=design&node-id=0%3A1&mode=design&t=di3JmQ6bLHCuGYwA-1

![Fix project preview bug   improve design #795](https://github.com/unstructuredstudio/zubhub/assets/146943654/fbb17b38-63ff-4a45-8efd-531511468690)

@srish Pls what do you think about this design

**Comment by yokwejuste** [comment]
Hey @aqsaaqeel any progress so far? any pending draft?

**Comment by srish** [comment]
After talking to @tuxology today, we think it might make sense to first fix the bug in this feature, which is that the preview doesn't load project content. Later, we can focus on design as part of a separate task.

**Comment by aqsaaqeel** [comment]
> Hey @aqsaaqeel any progress so far? any pending draft?

Working on it, yet to raise a PR

**Comment by aqsaaqeel** [comment]
> After talking to @tuxology today, we think it might make sense to first fix the bug in this feature, which is that the preview doesn't load project content. Later, we can focus on design as part of a separate task.

Is the design that is to be followed, [Frame 872 on this?](https://www.figma.com/file/hidnBfP4kNWl7RDxy3aUZI/ZubHub?type=design&node-id=156-856&mode=design&t=hLRzvWu1j0A20DD7-0)

**Comment by yokwejuste** [comment]
> After talking to @tuxology today, we think it might make sense to first fix the bug in this feature, which is that the preview doesn't load project content. Later, we can focus on design as part of a separate task. 

@aqsaaqeel we are focusing on fixing the bug first, the design comes in later

**Comment by aqsaaqeel** [comment]
Hey @yokwejuste we were going to collaborate on this but the bug fixing was a very small issue so I have raised a PR for that. We can work together on the design task for this!

**Comment by yokwejuste** [comment]
> Hey @yokwejuste we were going to collaborate on this but the bug fixing was a very small issue so I have raised a PR for that. We can work together on the design task for this!

Sure, we can do that too as well

**Comment by aqsaaqeel** [comment]
@srish The bug is fixed now, should we start working on the redesign?
