### ISSUE TITLE
Publish without tags button not responding when clicked

### ISSUE THREAD

**Issue by chudivictor** [unstructuredstudio/zubhub#796]
<img width="1440" alt="Screenshot 2023-10-05 at 12 53 01" src="https://github.com/unstructuredstudio/zubhub/assets/81053657/c6e840b2-2718-43e0-9ad7-a7f2476a6de3">

## Description: there is an edge case here, when the primary button "publish without tag" is clicked, it should take the user to a new page, maybe a success page. But on the current design, when the button is clicked, the page still remains the same

[https://zubhub.unstructured.studio/projects/313da9af-f6d9-45a0-b663-5708a2dd7e6e/edit](url)

**Comment by Mutombe** [comment]
Can you assign this issue to me please.

**Comment by srish** [comment]
The publish without tags button works. There is another bug that causes it. I will let you investigate that :)

**Comment by Mutombe** [comment]
> The publish without tags button works. There is another bug that causes it. I will let you investigate that :)

So are you saying that the publish without tag button should not publish ? Because I am seeing no bug from my side. I do not understand the bug you are talking about.
