### ISSUE TITLE
Project does not publish without adding image or video 

### ISSUE THREAD

**Issue by Stephxdesigns** [unstructuredstudio/zubhub#797]
Users who do not add images or videos cannot publish their projects.

This leaves a bad experience for users who do not intend to add images or videos. 
It leaves them confused because adding images or videos is not indicated as a requirement and there is no error message redirecting users to add the image.
 
This leaves users unaware of what the problem is

**Comment by Stephxdesigns** [comment]
@srish @tuxology I'd like to contribute to this.

**Comment by srish** [comment]
Thanks for adding this! It is slightly related to #340 so I am going to close this one out.
