### ISSUE TITLE
Clicking on "My Project Card" Redirects to "My Profile"

### ISSUE THREAD

**Issue by Stephxdesigns** [unstructuredstudio/zubhub#798]
**Describe the bug**
Clicking on my project card opens up my profile page.

**To Reproduce**

1. Go to 'my projects'
2. Click on 'any project card'
4. See error (Opens my profile)

**Expected behavior**
Go to My project
Click any project card
Opens project details page.

**Comment by brrkrmn** [comment]
Hey @Stephxdesigns, I do not have this problem. Do you get this error when clicking on any space in the project card, or the area around the creator's username? It is true that clicking below the project description text redirects the user to the creator's profile. 
I do not think that is a problem. However, maybe the area that redirects to creator's profile should be restricted to the username text so as not to confuse anyone.

**Comment by Stephxdesigns** [comment]
@brrkrmn when I click on any area below the thumbnail.
I think clicking on any space in the project card should redirect to project details page that is the general behavior for cards. 
The only place that should redirect to profile should be the profile image or the username text like you said.
It's not a good experience for users to keep thinking about where they should or shouldn't click.

**Comment by Stephxdesigns** [comment]
@brrkrmn it also leaves an initial confusion until you probably figure it out ( I still haven't). 
It shouldn't be that way.

**Comment by brrkrmn** [comment]
@Stephxdesigns I get it, going to the creator's profile accidentally is not an ideal thing. I will get to it as soon as possible.

**Comment by Stephxdesigns** [comment]
https://github.com/unstructuredstudio/zubhub/assets/136924367/2ed4f473-c7f5-48e2-8f0d-714edd14b050

@brrkrmn for better understanding here's a video of my experience. I think you'd have to see if @srish  or @tuxology makes it an issue to work.

**Comment by srish** [comment]
It is not a problem. Thanks for attempting this.
