### ISSUE TITLE
Improve UX of header in mobile screen

### ISSUE THREAD

**Issue by N-TITIAN** [unstructuredstudio/zubhub#801]
I was going through the site and saw the contents of the header section is not properly aligned causing some inconsistency 

![image](https://github.com/unstructuredstudio/zubhub/assets/81820848/892230b7-ea1a-4671-8ab5-47c739c94373)
So i came up with design as a designer .  @srish @tuxology 
![Android Small - 1](https://github.com/unstructuredstudio/zubhub/assets/81820848/ef74b956-5ed6-4fb0-9e4e-0a8f11cbb71e)

**Comment by srish** [comment]
@N-TITIAN I am not able to replicate this issue on my end. Could you please share which OS version and device you are seeing this issue with? Also, how is your design better than the existing one? I see no big difference here.

**Comment by N-TITIAN** [comment]
Thank you @srish I saw the issue while using a smaller screen size (307x604) but viewing with a bigger mobile screen now ,the  alignments looks okay. I think its a minor issue with the sites responsiveness to smaller screens.

**Comment by coderatomy** [comment]
Nice catch @N-TITIAN. Noticed the strange alignment of the Zubhub header and the internationalization icon. @srish, I believe we need a change for this for a better look on mobiles.

@N-TITIAN, it looked nice when they're all in-line. Maybe we reduce the font-sizes. What  are your suggestions?
![image](https://github.com/unstructuredstudio/zubhub/assets/141822315/c1c13d3f-1f87-4564-9f14-131de04a7295)

**Comment by N-TITIAN** [comment]
@coderatomy I think maintaining them all in -line is a nice idea 
![Android Small - 2](https://github.com/unstructuredstudio/zubhub/assets/81820848/6cac02c1-8b49-4b03-8d2f-e3bfaf3d7500)

**Comment by coderatomy** [comment]
Still too  much populated! How about we move the profile icon to the side nav only on mobile? Then we remain with only the notification and search icons. I think that's a better solution

**Comment by Stephxdesigns** [comment]
@coderatomy here's something I came up with
![Screenshot_20231008-044659_1](https://github.com/unstructuredstudio/zubhub/assets/136924367/58a0e501-9834-451e-acd3-8277be32e454)
All the elements are aligned properly and it's not populated 

cc @srish @tuxology

**Comment by N-TITIAN** [comment]
@coderatomy I looked into your suggestion and came up with this.
@srish @tuxology 
![Android Small - 5](https://github.com/unstructuredstudio/zubhub/assets/81820848/0457d9e6-4b04-4974-b357-aa34b500ec86)
![Android Small - 6](https://github.com/unstructuredstudio/zubhub/assets/81820848/8505882c-e4bf-4c03-9927-bc0a0b1f8f39)

**Comment by yokwejuste** [comment]
Great great,

For this issue we'll be waiting on @aqsaaqeel to work on #792 and the PR #815 review will hopefully soon be done.

**Comment by coderatomy** [comment]
Can't @aqsaaqeel just merge this into her work too? It's a very minor issue.

**Comment by aqsaaqeel** [comment]
> Can't @aqsaaqeel just merge this into her work too? It's a very minor issue.

Yes, but the design hasn't been approved yet.

**Comment by aqsaaqeel** [comment]
There is a design for mobile screen in [this figma](https://www.figma.com/file/hidnBfP4kNWl7RDxy3aUZI/ZubHub?type=design&node-id=0-1&mode=design&t=OcdAjDiVmzgurocx-0) file but it does not have the hamburger menu for navigation. Is it to be removed completely? @srish

**Comment by coderatomy** [comment]
Absolutely not. Unless otherwise, like integrating a `pull-in` side-nav on mobile, I don't think we should remove the hamburger

**Comment by aqsaaqeel** [comment]
Now that I think about it, the hamburger should be removed. 

It contains these 3 options, which will lead the user to the landing page, error page, and an external link respectively. All of these can be accessed using the other buttons on the landing page. So, I think the Sidenav is unnecessary here! However, it should appear after login on the dashboard indeed!

![Screenshot from 2023-10-16 10-48-43](https://github.com/unstructuredstudio/zubhub/assets/85514520/adb64b66-d15b-4948-af2d-dc56c3408311)

**Comment by coderatomy** [comment]
Ahh! Nice catch @aqsaaqeel

**Comment by coderatomy** [comment]
I think then this will be solved, right @aqsaaqeel?

**Comment by Susan367760** [comment]
Came up with this artwork
![Mobile device artwork](https://github.com/unstructuredstudio/zubhub/assets/123363183/f2b08069-37ed-4088-b9cf-4b76a0e0f01d)

**Comment by N-TITIAN** [comment]
> Contributor

The sidnav isn't static ,it comes up when the humburger  is opened. I added it because i profile icon. 
This is how the menu section looks before the humburger is opened 
![Android Small - 6](https://github.com/unstructuredstudio/zubhub/assets/81820848/94e47d07-eebe-4317-ad4c-87f8aee84ad6)

And this is when its open 
![Android Small - 5](https://github.com/unstructuredstudio/zubhub/assets/81820848/0e50b547-1a0a-43e2-bc14-a97d9d6f5bc1)
 
With this the header is simplified and well aligned
