### ISSUE TITLE
Absence of the back arrow icon on the password reset modal leads to increase in cognitive load

### ISSUE THREAD

**Issue by chudivictor** [unstructuredstudio/zubhub#803]
The presence of the back icon helps provide users with a means to return to the previous state or screen within the application. It enhances the navigation experience by providing a clear exit point should in case the users don't want to continue with such an action.
<img width="1439" alt="Screenshot 2023-10-05 at 18 45 53" src="https://github.com/unstructuredstudio/zubhub/assets/81053657/0a5df35a-b0a4-4116-8716-3004825e2fba">

**Comment by chudivictor** [comment]
**Proposed Solution**
With the presence of the back arrow navigation, 

1. users don't need to think about how to exit the modal or where they might be taken if they dismiss it. The presence of a back icon simplifies this process.

2. When a modal includes a back icon, users can easily understand that they can return to the previous screen or dismiss the modal. It enhances the navigation experience by providing a clear exit point.


![back arrow navigation](https://github.com/unstructuredstudio/zubhub/assets/81053657/035b3d15-58a0-4941-bd56-ecac709eef81)

**Comment by aqsaaqeel** [comment]
I agree. In case of password reset, we tend to remember the password after some time. So it helps to go back. Would love to implement this

**Comment by chudivictor** [comment]
Yeah, you are right also.

**Comment by d-arkangel** [comment]
This is a good idea for improvement. I would like to be assigned this task, if you do not mind @tuxology

**Comment by srish** [comment]
Ideally, a task like this is associated with a bigger task. We cannot just add an arrow on one of the modals. This needs to be thought out carefully. For example, should there be a back arrow on one of the dialogs or all or some of them, and if so, which ones and why? And, as this is not trivial, I am closing this for now. I would encourage you to pick a task from the existing list, the ones with good first task tag.
