### ISSUE TITLE
Bug: 404 page - during project addition for unlogged user

### ISSUE THREAD

**Issue by yokwejuste** [unstructuredstudio/zubhub#807]
**Describe the bug**
When project is run successfully, we encounter an issue/404 page when we try to add a project when user is not logged in.

**To Reproduce**

1. Run the backend using the make file as described in the README
2. Run the frontend, get to [localhost:3000](http://localhost:3000)
3. Try adding a project and you will have a 400 page

**Expected behavior**
As of normal behavior, we should have a text displayed saying "logging to create a project" and not a 404 page.

**Screenshots**
![image](https://github.com/unstructuredstudio/zubhub/assets/71908316/73fe6ea8-d7f4-4673-a4dc-c04805196e70)

**Comment by srish** [comment]
Hmm! I don't think we have a button that takes user to create project page when not logged in. Closing this for now.

**Comment by yokwejuste** [comment]
> Hmm! I don't think we have a button that takes user to create project page when not logged in. Closing this for now.

here is the option showing when user is not logged-in @srish, Here is what I propose: either we disable the button or we redirect to signup/login before creating a project, because now it is clearly going to a 404 page as shown above
![image](https://github.com/unstructuredstudio/zubhub/assets/71908316/a973c5af-e089-40a0-9672-02e162452b4a)
