### ISSUE TITLE
Improving "All project" tab

### ISSUE THREAD

**Issue by Adaking-slack** [unstructuredstudio/zubhub#809]
**Describe the the feature request**
A clear and concise description of the feature.

Problem statement:
When going through the list of projects in the _All projects tab_, I realized that I was unconciously clicking on images thinking they were videos. 

Soluution:
In order to remove this confusion, i am suggesting that we add a category tab close to the feature tab with the default option being _All_, and then an _image_ and _video_ option  in order to improve user experience.

**Comment by srish** [comment]
There are multiple issues in open and close mode right now that are about this.
