### ISSUE TITLE
Adding a "Create Activity Feature" in the Activity Page

### ISSUE THREAD

**Issue by Stephxdesigns** [unstructuredstudio/zubhub#812]
Currently in the activity page there is no feature or guideline on how users can create or add new activities to the page.

I'd like to suggest that a feature to enable users create activity be added to the activity page including a guide on how new activities can be added

**Comment by coderatomy** [comment]
@srish, I recall someone is working on this? Maybe @yaya-mamoudou

**Comment by srish** [comment]
Activity creation needs a lot of improvements, only then we can have a guide around it or decide if we really need it. Closing for now.
