### ISSUE TITLE
I am not able to log in even though I signed up

### ISSUE THREAD

**Issue by rak16** [unstructuredstudio/zubhub#814]
**Describe the bug**
I signed up with Zubhub and was able to use the UI - browse projects, create projects, etc. - but all of a sudden my requests started getting throttled and I was logged out quite a few times. Now when I try logging in, the UI says "Unable to login with provided credentials"

**To Reproduce**
1. Sign up
2. Use UI
3. Get signed out automatically?
4. Can't log back in

**Expected behavior**
I should be able to login if I have signed up with Zubhub

**Screenshots**
<img width="1768" alt="Screenshot 2023-10-06 at 2 25 07 PM" src="https://github.com/unstructuredstudio/zubhub/assets/22426390/e5f44feb-729b-41ef-a947-15804d1a7119">

**Comment by khallow7** [comment]
Just tried logging in and I can log in pretty fine. Try refreshing the site or restarting the browser?

**Comment by srish** [comment]
I cannot reproduce this issue; it may have been caused due to deployment changes.

**Comment by rak16** [comment]
Okay, but if I am not able to access my account now, we must be doing something wrong somewhere - which caused my account to somehow get deleted from the system. This might be an isolated incident but it could happen to other users too. 

Moreover, how do I gain back the access to my account?

@srish @tuxology

**Comment by rak16** [comment]
I tried signing up again and now it's not even letting me do that. Screenshot below:

<img width="869" alt="Screenshot 2023-10-10 at 3 45 40 AM" src="https://github.com/unstructuredstudio/zubhub/assets/22426390/f534ffb8-26a4-4e3e-948f-66b5125ba20e">
