### ISSUE TITLE
Creating a two-account-based sign-up system for ZubHub can be a useful feature to differentiate between creators and students,

### ISSUE THREAD

**Issue by Prescopella** [unstructuredstudio/zubhub#818]
**Describe the the feature request**
A clear and concise description of the feature.
By distinguishing between educators and students at the account level, ZubHub can tailor the user interface, features, and functionalities to cater to the specific needs and expectations of each group. Educators may require administrative tools and features to manage workshops and curate content, while students may need a simplified interface focused on learning and project participation.

Proposed solution
![Account based](https://github.com/unstructuredstudio/zubhub/assets/101396117/8066afb1-b1da-4eed-a375-acaeb58b6f7e)

**Comment by coderatomy** [comment]
@Prescopella this is a nice idea. I would like to inquire from @srish @tuxology if the the `STUDENTS` feature is not supported yet.
If not, this is a great project

**Comment by Prescopella** [comment]
> @Prescopella this is a nice idea. I would like to inquire from @srish @tuxology if the the `STUDENTS` feature is not supported yet. If not, this is a great project

Thank you

**Comment by srish** [comment]
This is planned as part of Outreachy internship project.
