### ISSUE TITLE
Create Project video upload section does not display error message for invalid file formats

### ISSUE THREAD

**Issue by ladyami** [unstructuredstudio/zubhub#820]
**Describe the bug**
Create a project video upload section, allowing users to upload pictures instead of videos without throwing an Error. This is a bug because the video upload section is designed specifically for videos, and pictures are not a valid video format.

**To Reproduce**

1. Go to 'dashboard'
2. Click on 'Create project add the details and click next '
3. Scroll down to ' Add a video section, upload picture and click the next button'

**Expected behavior**
The Create project video upload section should display an error message or prevent the user from uploading the picture.

**Actual results:**

In the Create Project video upload section, the picture uploads but when click on the next button it keeps loading without displaying an error.

**Screenshots**
![Screenshot (307)](https://github.com/unstructuredstudio/zubhub/assets/99187115/b186daa8-b78a-4c21-b89c-302fc5d12430)

**Comment by srish** [comment]
Duplicate task of 340
