### ISSUE TITLE
Vertical scroll is not functional past creator review section on landing page on mobile

### ISSUE THREAD

**Issue by Stephxdesigns** [unstructuredstudio/zubhub#822]
**Describe the bug**
On mobile, the landing page is difficult to scroll past the creators' review section. It keeps scrolling horizontally.

**To Reproduce**
1 Go to mobile landing page or click on all projects (for users not logged in)
2 Scroll down to creator reviews
3 See error 

Expected behavior
Users should be able to scroll down/up the creator review with ease to see other content in the landing page.

**Comment by Marhiposa** [comment]
@Stephxdesigns  can a designer work on this issue?

**Comment by Stephxdesigns** [comment]
Yeah a designer can. 
I'm a designer so any designer can work on this. If you're available to work on it we can collaborate

**Comment by jumokeadeoyo** [comment]
Hi @Stephxdesigns, I would love to collaborate with you. i would drop my design soon

**Comment by Stephxdesigns** [comment]
That would be great. I worked on something too so let me know what you think

**Comment by Stephxdesigns** [comment]
@srish @tuxology
Here are some designs and prototype interactions that could solve this issue.
In the design I made adjustments to the alignment, visual hierarchy and graphics of the landing page to give it a more visually consistent and appealing look.
Here's a photo of the design

![Screenshot_20231007-140029_1](https://github.com/unstructuredstudio/zubhub/assets/136924367/52549715-95a1-496b-b39e-c1cda86156ec)

![Screenshot_20231007-135923_1](https://github.com/unstructuredstudio/zubhub/assets/136924367/4ebcd0c0-6636-456d-b4b4-cedacc4c3583)


https://www.figma.com/file/Miey9IxcUmAtiflup10FVq?type=design

**Comment by Stephxdesigns** [comment]
The interaction here works well for both the vertical and horizontal scrolling in the page.

https://github.com/unstructuredstudio/zubhub/assets/136924367/fa01b92f-e2b3-4a75-ae66-9d54dc7e9777

https://www.figma.com/proto/Miey9IxcUmAtiflup10FVq?node-id=0%3A1

If these are okay with you I'd like to go ahead and work with a dev to implement.

cc @srish @tuxology

**Comment by mehreeee** [comment]
Hi, @srish @tuxology  @coderatomy I have made a design to fix the scrolling issue on the Creator reviews section on the mobile landing page. Also made the featured projects section a carousel where users can easily swipe and see more projects. I would appreciate feedback, thank you.

Link to figma file
https://www.figma.com/file/yz3GGN7LWgdmNvbnlhhqEw/Zubhub-Landing-page-(Copy)?type=design&node-id=0%3A1&mode=design&t=RwSwx0j1hgj5vPbm-1

https://github.com/unstructuredstudio/zubhub/assets/105458062/306d44b5-3644-483d-9693-10720c85c57d

**Comment by coderatomy** [comment]
Nice work everyone! I just can't reproduce the issue. I can scroll past the creators review section. The design improvement is still needed though. I see how the font-size is too large on mobile. Thanks designers, everything LGTM 
[Screencast from 2023-10-08 08-08-37.webm](https://github.com/unstructuredstudio/zubhub/assets/141822315/21bfac26-3246-4b22-8c85-c60921e3dde9)

**Comment by Stephxdesigns** [comment]
@coderatomy oh really I still can't scroll past. It only scrolls past if you scroll from the white space above the review cards. Try clicking on the reviews itself and then try to scroll past after.

**Comment by coderatomy** [comment]
Can you attach a screen cast showing how you reproduce this @Stephxdesigns. Maybe that can help

**Comment by Stephxdesigns** [comment]
https://github.com/unstructuredstudio/zubhub/assets/136924367/c08ff71f-e506-4e77-a800-caffb9423983

@coderatomy I can only scroll from the whites space but once I'm in the review section and interact with by scrolling horizontally to read other reviews I can't scroll back up or down from that section

**Comment by mehreeee** [comment]
@coderatomy you have to actually click on the reviews to notice it. Once you do, you can’t scroll back to the rest of the website, you get stuck.

**Comment by DonPresh** [comment]
I made a video on the iteration for the vertical scroll animation:

### Mobile screen

![Zubhub homescreen](https://github.com/unstructuredstudio/zubhub/assets/100778015/c199fab2-9956-42a0-9c7c-200ce603e022)
### Mobile scroll video iteration

https://github.com/unstructuredstudio/zubhub/assets/100778015/b58ab28c-c2d6-45a5-836c-2871bf33ab49

@srish @coderatomy @Stephxdesigns  Feedback is appreciated!

**Comment by Stephxdesigns** [comment]
Hi @srish I'd appreciate your feedback on these design solutions for this issue. Does it work or does it need further reiteration?

https://github.com/unstructuredstudio/zubhub/assets/136924367/8ea991f9-6e40-4cad-bc90-b7bc63e3a524

![Screenshot_20231007-140029_1](https://github.com/unstructuredstudio/zubhub/assets/136924367/b905c464-01fc-4da4-86cb-2c9518923f4e)

![Screenshot_20231007-135923_1](https://github.com/unstructuredstudio/zubhub/assets/136924367/3b7c51bd-d82b-4769-beed-58f8a57351d3)

**Comment by Adaking-slack** [comment]
I think making alignment adjustments like @Stephxdesigns and the other designers did will fix the issue

**Comment by JulietMadu** [comment]
> The interaction here works well for both the vertical and horizontal scrolling in the page.
> 
>  VID_20231007_140237.2.1.1.1.mp4 
> https://www.figma.com/proto/Miey9IxcUmAtiflup10FVq?node-id=0%3A1
> 
> If these are okay with you I'd like to go ahead and work with a dev to implement.
> 
> cc @srish @tuxology

For this, When the user scrolls down and wants to go bac up faster, how will he do that

**Comment by mehreeee** [comment]
> Hi, @srish @tuxology @coderatomy I have made a design to fix the scrolling issue on the Creator reviews section on the mobile landing page. Also made the featured projects section a carousel where users can easily swipe and see more projects. I would appreciate feedback, thank you.
> 
> Link to figma file https://www.figma.com/file/yz3GGN7LWgdmNvbnlhhqEw/Zubhub-Landing-page-(Copy)?type=design&node-id=0%3A1&mode=design&t=RwSwx0j1hgj5vPbm-1
> 
>  Page.1.-.Zubhub.Landing.page.-.Figma.2023-10-07.14-50-56.mp4

@srish please review this

**Comment by srish** [comment]
I like the iteration by @DonPresh on @Stephxdesigns and other designers' work. Maybe a developer can try to match the design shown in https://github.com/unstructuredstudio/zubhub/issues/822#issuecomment-1752693908?

**Comment by DonPresh** [comment]
Any developer looking to Implement this issue? So I can share my figma file and collaborate with them?
@brrkrmn or @coderatomy  you up to work on this?

### Figma link
https://www.figma.com/file/2twyPjNSSzNEzlMO0doTCb/Outreachy?type=design&node-id=20%3A175&mode=design&t=jv5hPZByazFmw4yy-1

**Comment by yokwejuste** [comment]
> Any developer looking to Implement this issue? So I can share my figma file and collaborate with them? @brrkrmn or @coderatomy you up to work on this?
> 
> ### Figma link
> https://www.figma.com/file/2twyPjNSSzNEzlMO0doTCb/Outreachy?type=design&node-id=20%3A175&mode=design&t=jv5hPZByazFmw4yy-1

Working on it now, together with @DonPresh
