### ISSUE TITLE
Header nav links not directing me to any page.

### ISSUE THREAD

**Issue by rich-peace** [unstructuredstudio/zubhub#826]
The nav links in the header section of the website doesn't take the user anywhere, when i clicked on each of the link i was hoping that it would direct me to another page but it didn't, I see this as a bad user experience and i don't know if @srish could assign this issue to me.

**Comment by Temabo** [comment]
@rich-peace I do not experience this, could you please attach a screenshot?

**Comment by rich-peace** [comment]
<img width="960" alt="header 1" src="https://github.com/unstructuredstudio/zubhub/assets/133676458/28dc2fa9-e536-4050-9e50-287629436f16">
<img width="960" alt="header 2" src="https://github.com/unstructuredstudio/zubhub/assets/133676458/bb895c32-18f4-4498-aa8a-15ce35f4eff5">
<img width="960" alt="header 3" src="https://github.com/unstructuredstudio/zubhub/assets/133676458/ee9ca409-240f-4839-bac9-d45361b21f39">

**Comment by rich-peace** [comment]
@Temabo if you take a look at this three screen shot you would observe that when i clicked on project, creators and Tags it only shows featured projects.

**Comment by N-TITIAN** [comment]
@rich-peace I do not experience that too

**Comment by Temabo** [comment]
@rich-peace I understand you now, you are referring to the dropdown but the search bar right? The dropdown that contains "Projects", "Creators" and "Tags" right? It is supposed to filter the projects by these categories but it is now. Good job noticing this!

**Comment by srish** [comment]
Closing as a duplicate of another issue `#802`.
