### ISSUE TITLE
UX issue to be able to share your profile

### ISSUE THREAD

**Issue by Prescopella** [unstructuredstudio/zubhub#831]
Present design
![image](https://github.com/unstructuredstudio/zubhub/assets/101396117/0d206074-9489-42ad-af97-6d7e6557b6a4)
I noticed that there is no share profile link to share your profile with users and people who would love to connect with you also the creator tag looks like a button

Proposed solution
![Profile](https://github.com/unstructuredstudio/zubhub/assets/101396117/c37c8eb8-6ba8-4150-a170-1b50b220bb2d)
I added a share icon and also worked on the creator tag and the whole UI

**Comment by srish** [comment]
Closing as this issue seems trivial and we are missing a parent task here.
