### ISSUE TITLE
Design different card/carousel style to differentiate "projects" and "activities"

### ISSUE THREAD

**Issue by Michelle-okechi** [unstructuredstudio/zubhub#832]
Firstly, Having the same card design for projects and activities would be confusing to users. Having a different card style for "activities" would distinguish them from "projects" and show users that they have different purposes.
For example, on YouTube, the designs for full videos are different from that of "YouTube shorts". This would tell a user that they represent different things.

Secondly, I noticed that when the "explore activities button is clicked, it redirects you to another page.

Expected behaviour: 
1. sign in to your profile
2. Click "Explore activities"
3. View all activities on the current page, with no redirecting

Please @srish @tuxology please assign this task to me

**Comment by Michelle-okechi** [comment]
Please @srish @tuxology, i would love to work on this task, as this would enhance a user's experience

**Comment by srish** [comment]
@Michelle-okechi Activities feature is not fully functional as of right now so we don't know what content will go in an activity. Once that is ready, only then we should be able make a better judgement on the design. Closing for now.
