### ISSUE TITLE
Create a more detailed activity log page

### ISSUE THREAD

**Issue by Adaking-slack** [unstructuredstudio/zubhub#834]
**Describe the the feature request**
A clear and concise description of the feature.

I noticed that there is an activity log feature on the user's dashboard, and i think that it can be more detailed.
First, an activity log section should be added to the navigation bar.
Secondly, we can divide the activity log into different sections.
1) currently/continue watching: a list of video/s that is user has started watching but left halfway
2)history: a list of all content the user has engaged with
3)watch later: a list of content the user saved (bookmark)to engage with 
4)likes,comments and reaction can be grouped into their respective category

**Comment by srish** [comment]
@Adaking-slack Activities feature is not fully functional as of right now so we don't know what content will go in an activity. Once that is ready, only then we should be able to make a better judgment on the design. Closing for now.
