### ISSUE TITLE
Improve UX of project card icons to have variations 

### ISSUE THREAD

**Issue by N-TITIAN** [unstructuredstudio/zubhub#835]
The project card already has a bookmark or save icon. From my observations after bookmarking a project, it doesn't indicate any change from the icon appearance though reflected in my account profile.
project after saving : no change on icon
![image](https://github.com/unstructuredstudio/zubhub/assets/81820848/f1568c91-f1ce-4607-99dd-6f5458787bb5)

project after saving in my account
![image](https://github.com/unstructuredstudio/zubhub/assets/81820848/67206fe2-a4bf-45f9-ae14-64e243307ae9)
 
Proposition : 
if we can redesign the card icons to have variations , users won't get confuse on which projects they have saved before and that which have not been saved.
I came up with two propositions 
![image](https://github.com/unstructuredstudio/zubhub/assets/81820848/3330d603-2514-4cb0-91ee-388ac5470b7e)
![image](https://github.com/unstructuredstudio/zubhub/assets/81820848/a4383006-ded7-4d54-b7c5-644a4944dd1f)

Same goes for the like icon.
This is just to demonstrate, @srish if you grant me the permission to go ahead with the design , i'll bring it to perfection

**Comment by aqsaaqeel** [comment]
Hey @N-TITIAN there might be some network issue but when you visit the official website, you will notice that before bookmarking the project, the icon is outlined and after doing that it becomes filled, thus fulfilling its purpose of indication. Here is how it looks on the website.
Before bookmarking:
![Screenshot from 2023-10-09 18-39-34](https://github.com/unstructuredstudio/zubhub/assets/85514520/7c3da4da-120f-430f-b819-ee617006e110)
After Bookmarking:
![Screenshot from 2023-10-09 18-39-42](https://github.com/unstructuredstudio/zubhub/assets/85514520/4449ae2b-2d84-4fb3-be89-cdd1ae2a77ff)

**Comment by srish** [comment]
Yes, the bookmark icon works fine!
