### ISSUE TITLE
Make text link on the footer look more Responsive

### ISSUE THREAD

**Issue by Boluwatifey1** [unstructuredstudio/zubhub#840]
Good day @srish @tuxology **Going through the footer of the website, I noticed that the text links and the dormant texts have the same color and this could confuse new users **
how it looks on the website now:
![3](https://github.com/unstructuredstudio/zubhub/assets/127180289/e890662d-6f91-4d43-959f-28c725647e58)

I carried out user research and about 3 people said the same thing about the footer text links so I came up with another idea to enhance user satisfaction
**OPTION 1**
Give the text link a different color(I picked the color from the current color styles) this way users would be able to differentiate between the links and the inoperative texts.
**OPTION 2** 
Give the text link a different color (I picked the color from the current color styles) and underline it, this way it looks more appealing to the eyes
**OPTION 3**
Maintain the color but underline it. This is a mockup of how it would look
![Edit footer](https://github.com/unstructuredstudio/zubhub/assets/127180289/15ce0dda-dfb8-4f71-a786-75de2901cdfb)

**Comment by LOGESH-B** [comment]
Hii @Boluwatifey1 
I am intrested to work on this.Can i get assigned?

**Comment by Boluwatifey1** [comment]
> Hii @Boluwatifey1
> I am intrested to work on this.Can i get assigned?

Am I to do that or @srish

**Comment by Boluwatifey1** [comment]
> Hii @Boluwatifey1
> I am intrested to work on this.Can i get assigned?

I don’t think there’s any thing to work on

**Comment by aqsaaqeel** [comment]
hey @Boluwatifey1 I liked your 3rd options so i have made the changes accordingly in https://github.com/unstructuredstudio/zubhub/pull/853 The first two options make it a bit illegible to read so I chose 3rd. 

Waiting for your opinions @srish @tuxology

**Comment by srish** [comment]
This might be a part of a bigger issue at some point. See the open issue about accessibility.
