### ISSUE TITLE
Improve the Visual design and UX on the search results page on mobile

### ISSUE THREAD

**Issue by mehreeee** [unstructuredstudio/zubhub#841]
Click on the search bar and type in a creators name

1. The search results page has an alignment and margin problem.
2. I also noticed that my preferred language option is set to English. But some texts are still written in Hindi.

![3AA70F92-DCFB-4EBD-A931-2073C3F8C05D](https://github.com/unstructuredstudio/zubhub/assets/105458062/bb658931-9291-4c02-96ab-381e8497cafc)
![8E6EA051-8D3A-4F24-947E-A3B5C709F0A8](https://github.com/unstructuredstudio/zubhub/assets/105458062/531cdbb9-614c-4ed8-b18e-37209a680560)
![59BAAB1E-AF10-4C01-8420-8338140F70D9](https://github.com/unstructuredstudio/zubhub/assets/105458062/ca09d910-b6d8-419b-a44e-fa928f8d6c24)

**Comment by fiddyhamma** [comment]
hey @mehreeee if this is a design issue we can work on it together

**Comment by mehreeee** [comment]
> hey @mehreeee if this is a design issue we can work on it together

Sure, no problem.

**Comment by srish** [comment]
Too broad and generic, closing for now
