### ISSUE TITLE
Create a saved collection

### ISSUE THREAD

**Issue by Prescopella** [unstructuredstudio/zubhub#847]
**Describe the the feature request**
A clear and concise description of the feature.
This saved collection allows students to save the same project from different creators in the same category. For example, there are different creators on how to create weaving looms, this saved collection makes it easier for you to organize your saved projects. 
![Saved collection](https://github.com/unstructuredstudio/zubhub/assets/101396117/513bd5ed-0c78-4d3c-a1fc-a75c0ccf41a1)
![Create](https://github.com/unstructuredstudio/zubhub/assets/101396117/4dd4c09f-07a6-4c45-a712-7166760738ee)
![collection](https://github.com/unstructuredstudio/zubhub/assets/101396117/24ae013c-a466-4ce0-bd91-0fc0a9525a4e)

**Comment by aqsaaqeel** [comment]
I like the idea, this allows for easy navigation to similar projects too. Where do you suggest we can access the saved projects from?

**Comment by Prescopella** [comment]
> I like the idea, this allows for easy navigation to similar projects too. Where do you suggest we can access the saved projects from?

You find it in the bookmark

**Comment by Prescopella** [comment]
> I like the idea, this allows for easy navigation to similar projects too. Where do you suggest we can access the saved projects from?

![Screenshot_20231009-131243](https://github.com/unstructuredstudio/zubhub/assets/101396117/bd87bccf-4600-4a04-9c56-b32e505e77d2)
![Screenshot_20231009-131238](https://github.com/unstructuredstudio/zubhub/assets/101396117/fa2bba1a-5814-417e-ad41-d1bb884eb807)
That area there is bookmark that's where you will find it, so instead of saved project it will now be saved collection

**Comment by srish** [comment]
Sounds interesting! But this is not our priority right now as we don't have many projects on the platform.
