### ISSUE TITLE
Improve buttons on Mobile landing page

### ISSUE THREAD

**Issue by DonPresh** [unstructuredstudio/zubhub#848]
**Button Review**
I've spotted a couple of issues with the mobile landing screen buttons.
 Firstly, some buttons look more like tags, and the button text could be improved. 
Second observation is that some of the buttons do not adhere to the rule of thumb and may not accomodate for users with big thumb.

I raised this issue because I understand the role buttons play in improving the overall user experience like acting as a gateway for users to navigate and properly interact with an app or a website 
 
###  These are some of the button issues I identified
![IMG_6545](https://github.com/unstructuredstudio/zubhub/assets/100778015/da9fc267-0fca-4e75-92e0-a0e5a32b4c59)
![IMG_6547](https://github.com/unstructuredstudio/zubhub/assets/100778015/ac3e8675-c9bb-4ae7-9141-dc073223de5a)

**Comment by DonPresh** [comment]
### Here are some of my iterations for my buttons size and text:
![IMG_6548](https://github.com/unstructuredstudio/zubhub/assets/100778015/e7866b9b-56f5-4099-8224-41c69e642337)
![IMG_6549](https://github.com/unstructuredstudio/zubhub/assets/100778015/d826bea4-0b8f-4192-b7fe-703326de6266)
![IMG_6550](https://github.com/unstructuredstudio/zubhub/assets/100778015/58066786-d52d-46ce-a957-4bb4d5c12bd5)

**Comment by Olushayo** [comment]
Hi Precious, if this is a design issue,we can work on it together?

**Comment by DonPresh** [comment]
Sure!

**Comment by srish** [comment]
I don't understand the issue with the design of buttons.
