### ISSUE TITLE
Improve the ui of the about us page

### ISSUE THREAD

**Issue by Adaking-slack** [unstructuredstudio/zubhub#854]
**Describe the the feature request**
A clear and concise description of the feature.
The about us page of an organization is a very important part of a web page. It provides key information about the organization and the value it provides. I noticed that while Zubhub's about us page provides important information to the users, the UI of the page may make it difficult for the user to aaces those information at a glance(cause nobody wants to spend so much time trying to figure out what value the organization offers). So i made a little redesign, highlighting the principles of the organization, and features of the app 

![Capture bef](https://github.com/unstructuredstudio/zubhub/assets/85881234/35a53286-1945-46dd-b14e-ad10e873812e)

![About page design](https://github.com/unstructuredstudio/zubhub/assets/85881234/e0e43629-88ad-4c8e-affa-4fd752cb0031)

**Comment by srish** [comment]
Closing this as this needs to be a part of a larger task (to be filed soon). Thanks for your suggestions!
