### ISSUE TITLE
Add automatic sliding animation and right arrow button to view next review on the creator review section 

### ISSUE THREAD

**Issue by Kub-kub** [unstructuredstudio/zubhub#856]
**Describe the the feature request**
A simple sliding animation will allow users automatically view the reviews by creators without having to click on the carousel indicator . The left & right button will help users view next or previous Review. The Creator review section is static and it may take users a longer period to find out that they can go to the next review slide by clicking on the carousel Indicator. 
![Creator Review](https://github.com/unstructuredstudio/zubhub/assets/61984894/fdab3731-c0c7-4d9c-9a17-b2e2ed88500e)

https://www.figma.com/proto/ZxcomONMktap2fQ0Ex57yb/Forgot-Password?page-id=0%3A1&type=design&node-id=23-395&viewport=798%2C2633%2C0.13&t=uzh8V5msSOpxIF7a-1&scaling=scale-down-width&mode=design

**Comment by srish** [comment]
It is very trivial and of low priority right now. Please read tips and comments in Zulip. Thanks for your suggestions.
