### ISSUE TITLE
Staff should be able to delete an activity

### ISSUE THREAD

**Issue by srish** [unstructuredstudio/zubhub#863]
**Describe the bug**
Deleting an activity doesn't work

**To Reproduce**

1. Go to 'https://zubhub.unstructured.studio/'
2. Click on 'Create Activity' from sidebar
3. Try to create an activity: 'https://zubhub.unstructured.studio/activities/create'
4. Only users with staff privileges are able to see activities here https://zubhub.unstructured.studio/activities
5. Click an activity. You will see an option to edit, and delete by clicking on three dots from the top right.
6. Click on the delete option

**Expected behavior**
When you click on delete, the activity should be deleted

**Comment by gargmonika** [comment]
Hello @srish  Can i work on this issue?

**Comment by gargmonika** [comment]
Hey @srish I replicated the step as you described to reproduce the behaviour. As described in point 4, only "users with staff privileges" are able to see activities, can u plz guide me how a user can access staff privileges?

**Comment by rak16** [comment]
> Hey @srish I replicated the step as you described to reproduce the behaviour. As described in point 4, only "users with staff privileges" are able to see activities, can u plz guide me how a user can access staff privileges?

@gargmonika Are you unable to see activities on: https://zubhub.unstructured.studio/activities ?

**Comment by rak16** [comment]
I don't think I am a staff member. But I am still able to view activities under https://zubhub.unstructured.studio/activities, as can be seen in the following ss:

<img width="1296" alt="Screenshot 2023-10-11 at 12 27 43 PM" src="https://github.com/unstructuredstudio/zubhub/assets/22426390/612ad20b-267e-4c81-ba04-29b227aa3154">


@srish @tuxology @iamhks Is this expected behaviour?

**Comment by yokwejuste** [comment]
@srish  it works on my side, on deleting we have a rerouting to `activities` 

I performed some local testing and works well

**Comment by yokwejuste** [comment]
> Hey @srish I replicated the step as you described to reproduce the behaviour. As described in point 4, only "users with staff privileges" are able to see activities, can u plz guide me how a user can access staff privileges?

That is done at the [backend](https://github.com/unstructuredstudio/zubhub/blob/31e821b196fd3eb87be65e54cfb800d4435990e5/zubhub_backend/zubhub/activities/views.py#L35C52-L35C52)

```python
# part of the code
permission_classes = [IsAuthenticated, IsOwner]
# continuation
```

I'm a little bit questioning myself,  because the backend conditions saying "Only a user who is an owner `and` authenticated can view activities", looks like something when wrong, I was not supposed to be seeing the activities on [here](https://zubhub.unstructured.studio/activities), maybe we should make this a separate issue to look after it.

What do you think @tuxology ?
cc: @srish

**Comment by coderatomy** [comment]
Same here. 
Before any effort, what are `Activities` in relation with Zubhub and what does that feature do @srish? It's better if we dive into work with a prior knowledge of what's expected @yokwejuste. 
I think later we shall have a detailed documentation with all this type of information adding up on the swagger documentation

**Comment by coderatomy** [comment]
I think we are seeing those that are published and I thin we shouldn't be able to delete. Yeah, that's the intended way
![image](https://github.com/unstructuredstudio/zubhub/assets/141822315/0c5927d3-176e-4860-8b71-81c9caa5fb09)

**Comment by coderatomy** [comment]
Can you try this @yokwejuste 
Create an Activity and then try deleting that very activity you created. It worked on my side.

**Comment by coderatomy** [comment]
the data is actually deleted. Just a rework on the frontend can fix. Let me push a quick fix @yokwejuste
I think those actions shouldn't be seen for `unprivileged` users i.e the `edit` and `delete`. We shouldn't want anyone to edit someone's Activity. That's what I think

**Comment by yokwejuste** [comment]
> the data is actually deleted. Just a rework on the frontend can fix. Let me push a quick fix @yokwejuste I think those actions shouldn't be seen for `unprivileged` users i.e the `edit` and `delete`. We shouldn't want anyone to edit someone's Activity. That's what I think

so I should make those restrictions on the backednd?

Can we do a co-authored PR for that?

**Comment by coderatomy** [comment]
[Screencast from 2023-10-11 15-03-41.webm](https://github.com/unstructuredstudio/zubhub/assets/141822315/0eb71a09-9e8b-4c22-90e8-b4a2068a4ca8)

**Comment by coderatomy** [comment]
> > the data is actually deleted. Just a rework on the frontend can fix. Let me push a quick fix @yokwejuste I think those actions shouldn't be seen for `unprivileged` users i.e the `edit` and `delete`. We shouldn't want anyone to edit someone's Activity. That's what I think
> 
> so I should make those restrictions on the backednd?
> 
> Can we do a co-authored PR for that?

ok, how are you planning to that though? I mean the backend restrictions. Because I see everything is as it should. One can't actually edit or delete an activity where  one has no privileges. THe only thing left is to remove those options in the UI

**Comment by yokwejuste** [comment]
> > > the data is actually deleted. Just a rework on the frontend can fix. Let me push a quick fix @yokwejuste I think those actions shouldn't be seen for `unprivileged` users i.e the `edit` and `delete`. We shouldn't want anyone to edit someone's Activity. That's what I think
> > 
> > so I should make those restrictions on the backednd?
> > 
> > Can we do a co-authored PR for that?
> 
> ok, how are you planning to that though?

You do the changes at the front end, I get to your branch and update the content with the backend restrictions

**Comment by coderatomy** [comment]
Note my comment up. Unless am missing something out

**Comment by yokwejuste** [comment]
> > > the data is actually deleted. Just a rework on the frontend can fix. Let me push a quick fix @yokwejuste I think those actions shouldn't be seen for `unprivileged` users i.e the `edit` and `delete`. We shouldn't want anyone to edit someone's Activity. That's what I think
> > 
> > so I should make those restrictions on the backednd?
> > 
> > Can we do a co-authored PR for that?
> 
> ok, how are you planning to that though? I mean the backend restrictions. Because I see everything is as it should. One can't actually edit or delete an activity where  one has no privileges. THe only thing left is to remove those options in the UI 

If you check the code snippet above you'll see, we were not to be seeing those activities first. Then the edit button should not be shown if the user is not the owner of the activity. 

I've questions concerning the permissions implemented, there is something fishy with that.

**Comment by coderatomy** [comment]
Those `Activities` were published. Anyone can view them 
Check here 
https://api.zubhub.unstructured.studio/api/activities/

**Comment by coderatomy** [comment]
There like to categories. `Published` and `Unpublished`. Let me hope this makes sense now

**Comment by yokwejuste** [comment]
> There like to categories. `Published` and `Unpublished`. Let me hope this makes sense now

The publish makes it public ? 

Coz without the publish being `true` we can't even see the publication on the on the `/activities/`. So if I make the publish true I get my activity visible by all authenticated users right ?

**Comment by coderatomy** [comment]
Exactly. This happens from the second page of `/activities/create` after clicking publish button. Before, it is just drafted

**Comment by yokwejuste** [comment]
> Exactly. This happens from the second page of `/activities/create` after clicking publish button. Before, it is just drafted

So why was that permission implemented at the backend ? It sounds confusing

**Comment by coderatomy** [comment]
The `publish` boolean is just a property that is just posted onto the database. There is nothing complex there

**Comment by yokwejuste** [comment]
> The `publish` boolean is just a property that is just posted onto the database. There is nothing complex there

Will check all this again.

**Comment by gargmonika** [comment]
> https://zubhub.unstructured.studio/activities

No i am able to see activities but not the one i have created

**Comment by gargmonika** [comment]
@coderatomy @yokwejuste  did u guys able to see the activities after publishing it ?

**Comment by coderatomy** [comment]
> > https://zubhub.unstructured.studio/activities
> 
> No i am able to see activities but not the one i have created

Not really. Check [here](https://github.com/unstructuredstudio/zubhub/blob/master/zubhub_frontend/zubhub/src/api/api.js#L1099C1-L1166C2) for the activities endpoints @yokwejuste. 

We can't actually see it but the backend returns everything as expected. The frontend UIs need a change

[Screencast from 2023-10-12 08-14-16.webm](https://github.com/unstructuredstudio/zubhub/assets/141822315/904fe903-c58d-4f0e-bb43-7bbb2575928c)

**Comment by yokwejuste** [comment]
> > > https://zubhub.unstructured.studio/activities
> > 
> > 
> > No i am able to see activities but not the one i have created
> 
> Not really. Check [here](https://github.com/unstructuredstudio/zubhub/blob/master/zubhub_frontend/zubhub/src/api/api.js#L1099C1-L1166C2) for the activities endpoints @yokwejuste.
> 
> We can't actually see it but the backend returns everything as expected. The frontend UIs need a change
> 
>  Screencast.from.2023-10-12.08-14-16.webm

ohhh I see this now, will you handle this or I can go on with the corrections?

**Comment by gargmonika** [comment]
Hello @yokwejuste @coderatomy can i collaborate with you guys on this issue?

**Comment by coderatomy** [comment]
I think I have more context for this one @yokwejuste and @gargmonika. Will ping here for further assistance

**Comment by yokwejuste** [comment]
> I think I have more context for this one @yokwejuste and @gargmonika. Will ping here for further assistance

😄 this time around you'll do it and I'll review your code, will be waiting :)

**Comment by JulietMadu** [comment]
is this a designer or developer issue?

**Comment by coderatomy** [comment]
Yeah sure. Am pushing a fix @JulietMadu
