### ISSUE TITLE
Disabled state of create project button is unclear

### ISSUE THREAD

**Issue by brrkrmn** [unstructuredstudio/zubhub#865]
Recently I opened #845 for the creat project flow. Normally, the submit button is disabled until the user selects the project kind. I suggested that showing an error message would be more explanatory. However, a designer's input on this issue would be better. What do you think the design flow should look like?

### To Recreate
You can visit this page only when the team mode is enabled
1. In your local, go to zubhub/zubhub_frontend/zubhub/src/utils.js/index.js and change TEAM_ENABLED to `true`
2. Run the server and log in to Zubhub
3. Visit http://localhost:3000/projects/create

### Current Flow
The submit button is disabled since no option is selected

<img width="679" alt="image" src="https://github.com/unstructuredstudio/zubhub/assets/92817363/8ad08aa2-a92f-45d6-bfc8-75278f9b57bf">

**Comment by mehreeee** [comment]
@brrkrmn can you give more details on this? What are the steps to recreate to find this issue?

**Comment by productguyyy** [comment]
@srish can I jump on this as well?

**Comment by Dumzy006** [comment]
Hello @brrkrmn @srish I have two suggestions for this 
first suggestion
 I feel the button should be taken out entirely because an information is stated there for you to select the project you want to create.....so once you click on a particular project it takes you to the page to create that project
 
 Second suggestion
If we want to still keep the button there should an indication some thing like a check box on each mode that was selected to help the user know that they have made a choice before clicking the create project button 

![image](https://github.com/unstructuredstudio/zubhub/assets/136137889/b61f0578-e417-499d-a26a-c4c3862af972)
![image](https://github.com/unstructuredstudio/zubhub/assets/136137889/149e5615-4416-40d3-99a5-3bd4dbe51dc4)

**Comment by Dumzy006** [comment]
![image](https://github.com/unstructuredstudio/zubhub/assets/136137889/a3ebe239-92a5-4fbf-9e5d-a7d858ef00d9)

**Comment by brrkrmn** [comment]
> @brrkrmn can you give more details on this? What are the steps to recreate to find this issue?

I edited the PR, you can see the steps to recreate. Thanks for reminding

**Comment by Adaking-slack** [comment]
I go with @Dumzy006 second suggestion, the button should be there, but there should be a check box or anything to show an active mode on the option that is selected, then the button becomes active and the user can procced

**Comment by brrkrmn** [comment]
@Adaking-slack I agree, the second option sounds good. I think the current design of the two options may not look like they are buttons and need to be selected. Maybe a little design trick can make it more clear.
@Dumzy006 can you provide a design for your second solution? I am not sure where to put the checkboxes

**Comment by Dumzy006** [comment]
Alright @brrkrmn

**Comment by DonPresh** [comment]
These are my design suggestions for this issue.

### Disabled state
![Disabled state](https://github.com/unstructuredstudio/zubhub/assets/100778015/7c047bbf-a853-48fc-aa29-2dd11dfa3a60)

### Error state
![Error state](https://github.com/unstructuredstudio/zubhub/assets/100778015/03a06518-d17d-4e26-b7b8-9da3ba5732f9)


### Active state
![Filled state](https://github.com/unstructuredstudio/zubhub/assets/100778015/b07d2ccc-7518-4373-8c8d-a98430ff649e)


### Interaction video to show the flow will be like


https://github.com/unstructuredstudio/zubhub/assets/100778015/7ce95f2a-5ef3-4174-b68d-641d89a8b11a




@srish @brrkrmn please review.
@brrkrmn kindly check the updated corrections.

**Comment by mehreeee** [comment]
Hi @brrkrmn I think the disabled button should be there to show users that they need to click on a card. Clicking on the disabled button should show an error. I have made a design and interaction for this.
![Sign Up option1](https://github.com/unstructuredstudio/zubhub/assets/105458062/6bb0ad6d-eb77-415b-ab02-c2dda3a317e9)
![Sign Up option2](https://github.com/unstructuredstudio/zubhub/assets/105458062/c17bb30b-e751-460f-9abe-17e7e62db54b)
![Sign Up option3](https://github.com/unstructuredstudio/zubhub/assets/105458062/fe8dd97d-a238-4b2d-a096-24a60c450766)
![Sign Up option4](https://github.com/unstructuredstudio/zubhub/assets/105458062/e56c43eb-6b61-4ac5-a7d3-fef772343329)

**Comment by brrkrmn** [comment]
Thank you guys for your designs! ❤️ 
@DonPresh, The current flow functions the same as your suggestions, we are looking for alternatives for disabling the submit button. It could be showing a checkbox or an error as discussed in the comments. 
@mehreeee, your suggestion was also @coderatomy's idea. I will try to implement this but let's see what @srish thinks.

**Comment by DonPresh** [comment]
> Thank you guys for your designs! ❤️ @DonPresh, The current flow functions the same as your suggestions, we are looking for alternatives for disabling the submit button. It could be showing a checkbox or an error as discussed in the comments. @mehreeee, your suggestion was also @coderatomy's idea. I will try to implement this but let's see what @srish thinks.

Okay okay. I just saw the part you added. I already worked on it before the edit and steps

**Comment by mehreeee** [comment]
> Thank you guys for your designs! ❤️ @DonPresh, The current flow functions the same as your suggestions, we are looking for alternatives for disabling the submit button. It could be showing a checkbox or an error as discussed in the comments. @mehreeee, your suggestion was also @coderatomy's idea. I will try to implement this but let's see what @srish thinks.




https://github.com/unstructuredstudio/zubhub/assets/105458062/d457a72d-ff2d-41be-ae2d-74455233bc60




I think this interaction is not bad. What do you think?

**Comment by Dumzy006** [comment]
Hello @brrkrmn @Adaking-slack and @srish  what do you think
This is when a particular mode has been selected
so the user can go on to click the button and can now create a project
![image](https://github.com/unstructuredstudio/zubhub/assets/136137889/01cdaf75-a478-45e1-aa4d-4efc9935213d)

**Comment by Stephxdesigns** [comment]
By button state standards, the button on the current flow does not look like a disabled button. Disabled buttons either have a gray color or the opacity on the color is reduced by 50%.
The current design of the disabled button may not really let the user know that the button is disabled.

Another thing we can do is indicate to the users that picking a project is a requirement to move forward. 

Bearing these two solutions in mind I came up with the following designs

Disabled button state
![Screenshot_20231012-054812_1](https://github.com/unstructuredstudio/zubhub/assets/136924367/869ef160-ad7c-40cf-a58f-02ddd4fd3ffe)

Enabled button state
![Screenshot_20231012-054824_1](https://github.com/unstructuredstudio/zubhub/assets/136924367/5edfa76d-5746-4699-a365-f037881297fe)

Prototyped Interaction for this
[screen-capture (7).webm](https://github.com/unstructuredstudio/zubhub/assets/136924367/7d8069a4-dda2-44bd-9091-01d404cda3c3)

@srish @brrkrmn 
Let me know what you think

**Comment by Dumzy006** [comment]
I think we should stick to the kind of disabled button been used in the figma file for consistency sake
There is already a type of disabled button been used except we want to raise an issue for it to be changed @Stephxdesigns 
![image](https://github.com/unstructuredstudio/zubhub/assets/136137889/20b9050b-7891-433c-9956-a593799b5669)

**Comment by ladyami** [comment]
@brrkrmn the error can't be reproduced for designers because is on localhost I will go with @DonPresh and @Dumzy006  design
because it will be easy for users to understand

**Comment by brrkrmn** [comment]
Thank you guys for cooperating. I really like the interaction @mehreeee  suggested [#865 (comment)](https://github.com/unstructuredstudio/zubhub/issues/865#issuecomment-1759208276) as well as the checklist @Dumzy006 shared [#865 (comment)](https://github.com/unstructuredstudio/zubhub/issues/865#issuecomment-1759216443). 
Do you think combining these would be too much? What do you think about showing the empty checkbox in the first place and checking it once the user selects an option. 
In this case, if an option is not selected:
1. The submit button is disabled
2. An error message is shown under the submit button
3. The checkboxes in the options are not checked

When the user selects an option:
1. Submit button is enabled
2. Error disappears
3. The selected option's checkbox is checked

What do you think?

**Comment by mehreeee** [comment]
> Thank you guys for cooperating. I really like the interaction @mehreeee suggested [#865 (comment)](https://github.com/unstructuredstudio/zubhub/issues/865#issuecomment-1759208276) as well as the checklist @Dumzy006 shared [#865 (comment)](https://github.com/unstructuredstudio/zubhub/issues/865#issuecomment-1759216443). Do you think combining these would be too much? What do you think about showing the empty checkbox in the first place and checking it once the user selects an option. In this case, if an option is not selected:
> 
> 1. The submit button is disabled
> 2. An error message is shown under the submit button
> 3. The checkboxes in the options are not checked
> 
> When the user selects an option:
> 
> 1. Submit button is enabled
> 2. Error disappears
> 3. The selected option's checkbox is checked
> 
> What do you think?

I think this works. I'll add the checkbox to the interaction share a sample of how it looks

**Comment by brrkrmn** [comment]
thanks, @mehreeee. I'll wait for @srish's review to start on this

**Comment by ladyami** [comment]
> Thank you guys for cooperating. I really like the interaction @mehreeee suggested [#865 (comment)](https://github.com/unstructuredstudio/zubhub/issues/865#issuecomment-1759208276) as well as the checklist @Dumzy006 shared [#865 (comment)](https://github.com/unstructuredstudio/zubhub/issues/865#issuecomment-1759216443). Do you think combining these would be too much? What do you think about showing the empty checkbox in the first place and checking it once the user selects an option. In this case, if an option is not selected:
> 
> 1. The submit button is disabled
> 2. An error message is shown under the submit button
> 3. The checkboxes in the options are not checked
> 
> When the user selects an option:
> 
> 1. Submit button is enabled
> 2. Error disappears
> 3. The selected option's checkbox is checked
> 
> What do you think?

this make sense

**Comment by Dumzy006** [comment]
This works at @brrkrmn 
Here is a screenshot of when nothing is selected with the button disabled and I also used a different icon to represent team
![image](https://github.com/unstructuredstudio/zubhub/assets/136137889/0d10e6ef-01ea-40f9-bfe7-c9ee78ca73ad)
Then here is when a mode is selected with the button enabled
![image](https://github.com/unstructuredstudio/zubhub/assets/136137889/b9f5a04a-638f-47c4-93a1-91a77682b00b)

**Comment by Dumzy006** [comment]
I feel when a button is disabled it means it's not clickable based on research so there shouldn't be an error message on that screen

**Comment by mehreeee** [comment]
> I feel when a button is disabled it means it's not clickable based on research so there shouldn't be an error message on that screen

I agree. There's no need for an error message if we have an inactive button

**Comment by owunmiv** [comment]
Hi @brrkrmn 

> Thank you guys for cooperating. I really like the interaction @mehreeee suggested [#865 (comment)](https://github.com/unstructuredstudio/zubhub/issues/865#issuecomment-1759208276) as well as the checklist @Dumzy006 shared [#865 (comment)](https://github.com/unstructuredstudio/zubhub/issues/865#issuecomment-1759216443). Do you think combining these would be too much? What do you think about showing the empty checkbox in the first place and checking it once the user selects an option. In this case, if an option is not selected:
> 
> 1. The submit button is disabled
> 2. An error message is shown under the submit button
> 3. The checkboxes in the options are not checked
> 
> When the user selects an option:
> 
> 1. Submit button is enabled
> 2. Error disappears
> 3. The selected option's checkbox is checked
> 
> What do you think?

This is great. I still think the error state should not have a red button. For when a selection is made @Dumzy006 suggestion here https://github.com/unstructuredstudio/zubhub/issues/865#issuecomment-1759387571 works but for when nothing is selected, I recommend we have the error message and a non-red button. The disabled button remains.

This for the error state when the disabled button is selected 
![image](https://github.com/unstructuredstudio/zubhub/assets/96887160/93009467-a12f-4d3a-9f1e-36858748f125)

This for a selection has been made 
![image](https://github.com/unstructuredstudio/zubhub/assets/96887160/3a8ead22-0fa7-4de2-8494-7c3ef68a6c95)

What do you think? @brrkrmn @srish

**Comment by owunmiv** [comment]
> > I feel when a button is disabled it means it's not clickable based on research so there shouldn't be an error message on that screen
> 
> I agree. There's no need for an error message if we have an inactive button

We can still have an error message. In our everyday sign up forms, if a field is not filled and the user attempts to proceed, error message shows up prompting the user to fill that field...this happens despite the button being disabled. Disabled means the user is not 'able' to perform the next action, the system can still tell when a user attempts to proceed on a disabled button, hence, the need for an error message

This is my thought regarding the error message and a disabled button, I will still like to know what you think

**Comment by Dumzy006** [comment]
@omowunmio at what point do you get an error message since a disabled button is not clickable ( not interactive)?

For this other scenerio you are talking about, if you check well the button is enabled not disabled that is why you get error message but if the button is disabled you can't interact with it

**Comment by brrkrmn** [comment]
Oh I love this design @Dumzy006 [#865 (comment)](https://github.com/unstructuredstudio/zubhub/issues/865#issuecomment-1759387571). I still think that an error message may be necessary because the user may not be able to understand why they cannot click the button. Like in @Omowunmio's design [#865 (comment)](https://github.com/unstructuredstudio/zubhub/issues/865#issuecomment-1759400889).

With the checkboxes, I think it is much more clear for the user to understand that they need to make a selection. I say let's wait for @srish to comment on this and we can decide whether to include an error message or not.

**Comment by owunmiv** [comment]
> @Omowunmio at what point do you get an error message since a disabled button is not clickable ( not interactive)?
> 
> For this other scenerio you are talking about, if you check well the button is enabled that is why you get error message but if the button is disabled you can't interact with it

Some the button may look enabled or disabled (different designs for them) but they are still both disabled because the user can not proceed without filling all required fields

**Comment by Dumzy006** [comment]
Alright at @brrkrmn

**Comment by Temabo** [comment]
> I feel when a button is disabled it means it's not clickable based on research so there shouldn't be an error message on that screen

The error message would make the users understand clearly why they cannot proceed and the button is disabled.
I am also leaning towards @Dumzy006 iteration with the checkbox, it would be easier to understand.

**Comment by mehreeee** [comment]
@brrkrmn @srish  Check this interaction out
What do you think? Any need for the error message?

The checkbox only shows when it is clicked and disappears when unclicked

https://github.com/unstructuredstudio/zubhub/assets/105458062/9bbe26d4-8b68-46f9-b484-518559175225

**Comment by DonPresh** [comment]
> Oh I love this design @Dumzy006 [#865 (comment)](https://github.com/unstructuredstudio/zubhub/issues/865#issuecomment-1759387571). I still think that an error message may be necessary because the user may not be able to understand why they cannot click the button. Like in @Omowunmio's design [#865 (comment)](https://github.com/unstructuredstudio/zubhub/issues/865#issuecomment-1759400889).
> 
> With the checkboxes, I think it is much more clear for the user to understand that they need to make a selection. I say let's wait for @srish to comment on this and we can decide whether to include an error message or not.

I agree with you. Leveraging a user research I carried out for a product I worked on earlier this year, I think the error message is actually very important. Using only colors to represent that there's a problem might not be very inclusive considering there are users who are color blind and are unable to see the red alert showing that an action has not been performed hence their inability to move forward.

Also, I think the checkbox @Dumzy006 added also caters to this issue especially from an accessibility standpoint.

**Comment by mehreeee** [comment]
> Thank you guys for cooperating. I really like the interaction @mehreeee suggested [#865 (comment)](https://github.com/unstructuredstudio/zubhub/issues/865#issuecomment-1759208276) as well as the checklist @Dumzy006 shared [#865 (comment)](https://github.com/unstructuredstudio/zubhub/issues/865#issuecomment-1759216443). Do you think combining these would be too much? What do you think about showing the empty checkbox in the first place and checking it once the user selects an option. In this case, if an option is not selected:
> 
> 1. The submit button is disabled
> 2. An error message is shown under the submit button
> 3. The checkboxes in the options are not checked
> 
> When the user selects an option:
> 
> 1. Submit button is enabled
> 2. Error disappears
> 3. The selected option's checkbox is checked
> 
> What do you think?


https://github.com/unstructuredstudio/zubhub/assets/105458062/02f8e7e8-78a7-435c-9e69-ef2a5d8caecb

@srish @brrkrmn @Dumzy006 I think this final iteration pretty much solves the problem. 
When the user selects an option:
> 
> 1. Submit button is enabled
> 2. Error disappears
> 3. The selected option's checkbox is checked

When an option is not selected
1. The submit button is disabled
> 2. An error message is shown under the submit button
> 3. The checkboxes in the options are not checked

**Comment by brrkrmn** [comment]
@mehreeee regarding this design, [#865 (comment)](https://github.com/unstructuredstudio/zubhub/issues/865#issuecomment-1759439593) I believe if we are going to use checkboxes, it is important to show them before the user selects the option since in our case, their purpose is to push user to select an option, thus, seeing the not-selected checkbox works better for this view.

@DonPresh regarding this [#865 (comment)](https://github.com/unstructuredstudio/zubhub/issues/865#issuecomment-1759472324), you are certainly right about the accessibility part. That is why I think an error message is a must for people using voiceover, otherwise they would have absolutely no idea why they cannot click submit.

I think this [#865 (comment)](https://github.com/unstructuredstudio/zubhub/issues/865#issuecomment-1759511925) is what we are looking for, both visually and functionally, i like it.

**Comment by mehreeee** [comment]
> @mehreeee regarding this design, [#865 (comment)](https://github.com/unstructuredstudio/zubhub/issues/865#issuecomment-1759439593) I believe if we are going to use checkboxes, it is important to show them before the user selects the option since in our case, their purpose is to push user to select an option, thus, seeing the not-selected checkbox works better for this view.
> 
> @DonPresh regarding this [#865 (comment)](https://github.com/unstructuredstudio/zubhub/issues/865#issuecomment-1759472324), you are certainly right about the accessibility part. That is why I think an error message is a must for people using voiceover, otherwise they would have absolutely no idea why they cannot click submit.
> 
> I think this [#865 (comment)](https://github.com/unstructuredstudio/zubhub/issues/865#issuecomment-1759511925) is what we are looking for, both visually and functionally, i like it.

Thank you @brrkrmn if there's anything you'd like me to add, let me know

**Comment by Dumzy006** [comment]
Hello @brrkrmn @mehreeee @srish 

If the error message is going to be included, the error message should be under the mode
See screenshot below 

![image](https://github.com/unstructuredstudio/zubhub/assets/136137889/da928341-af9b-4a96-af3e-174412eecb4b)
![image](https://github.com/unstructuredstudio/zubhub/assets/136137889/46bbbce6-cc27-4fa6-b341-ee7f9126185c)

**Comment by srish** [comment]
Thanks for your work on this, everyone! I discussed with @tuxology, and we conclude that this design would work well: https://github.com/unstructuredstudio/zubhub/issues/865#issuecomment-1759387571. It looks different from the previous design as it has the following:
* A clear and explicit disabled button
* Personal and team cards with a circle on the top right giving users a sense that they are available as two options and they should click on them
* Different icon for the team, which distinguishes it from personal
We don't need to show a red error-like text on this page. 

@brrkrmn, you may proceed now with making the necessary changes to the PR.

**Comment by yokwejuste** [comment]
> This works at @brrkrmn Here is a screenshot of when nothing is selected with the button disabled and I also used a different icon to represent team ![image](https://user-images.githubusercontent.com/136137889/274577808-0d10e6ef-01ea-40f9-bfe7-c9ee78ca73ad.png) Then here is when a mode is selected with the button enabled ![image](https://user-images.githubusercontent.com/136137889/274578001-b9f5a04a-638f-47c4-93a1-91a77682b00b.png)

working on this one

**Comment by brrkrmn** [comment]
> Thanks for your work on this, everyone! I discussed with @tuxology, and we conclude that this design would work well: https://github.com/unstructuredstudio/zubhub/issues/865#issuecomment-1759387571. It looks different from the previous design as it has the following:
> 
> * A clear and explicit disabled button
> 
> * Personal and team cards with a circle on the top right giving users a sense that they are available as two options and they should click on them
> 
> * Different icon for the team, which distinguishes it from personal
> 
> We don't need to show a red error-like text on this page. 
> 
> 
> 
> @brrkrmn, you may proceed now with making the necessary changes to the PR.

sure, on it

**Comment by brrkrmn** [comment]
@Dumzy006 can you share the link to the final version?

**Comment by Dumzy006** [comment]
Alright @brrkrmn 

Here is the link below
https://www.figma.com/file/POs8v906c2IFSa7QqDONR6/ZUBHUB-CONTRIBUTION?type=design&node-id=42-854&mode=design&t=lUWSDl1Q8w3y0FQI-0

**Comment by yokwejuste** [comment]
> Alright @brrkrmn
> 
> Here is the link below https://www.figma.com/file/POs8v906c2IFSa7QqDONR6/ZUBHUB-CONTRIBUTION?type=design&node-id=42-854&mode=design&t=lUWSDl1Q8w3y0FQI-0

thanks, pushing in few mins

**Comment by brrkrmn** [comment]
Hey @srish, opened #894 for this, waiting for reviews.

**Comment by yokwejuste** [comment]
> Hey @srish, opened #894 for this, waiting for reviews.

Ohh, I quoted above I was on this already. I opened a PR for it at #892.

Maybe we need to assign issues now 🤔

**Comment by brrkrmn** [comment]
@yokwejuste I do not think we need to be assigned to work on an issue, mentors encourage us to open PRs even if there are existing PRs on issues. Maybe we can check our code, review and learn from each other since we have different implementations ☺️

**Comment by yokwejuste** [comment]
> @yokwejuste I do not think we need to be assigned to work on an issue, mentors encourage us to open PRs even if there are existing PRs on issues. Maybe we can check our code, review and learn from each other since we have different implementations ☺️

definitely, that is why we are present here.
