### ISSUE TITLE
No horizontal spacing between cards on search results page

### ISSUE THREAD

**Issue by Kub-kub** [unstructuredstudio/zubhub#866]
**Describe the bug**
Search result for logged in users is not adequately spaced

**To Reproduce**

1. Visit 'Zubhub website'
2. Click on 'Log in and make sure you are logged in'
3. Search for project 'light'

**Expected behavior**
adequate spacing between cards

**Screenshots**
![space](https://github.com/unstructuredstudio/zubhub/assets/61984894/0874b4ed-2e8c-4bb7-a1c1-41290680d991)

**Comment by manoahLinks** [comment]
Hi, i want to work on this buug, can it be assigned to me ?

**Comment by gargmonika** [comment]
Hello , I saw there is already pull request made for this issue. Can i still work on it?

**Comment by productguyyy** [comment]
@srish  on the mobile screen I noticed a bug, I was trying to navigate through to the create project page but an error message popped up below is a pictorial representation

![IMG_20231012_220130](https://github.com/unstructuredstudio/zubhub/assets/146936942/5ef92b2e-4ece-4d33-bfd4-815fc011f7df)

I await your reply and feedback so that it can be worked on @srish @tuxology

**Comment by yokwejuste** [comment]
> @srish on the mobile screen I noticed a bug, I was trying to navigate through to the create project page but an error message popped up below is a pictorial representation
> 
> ![IMG_20231012_220130](https://user-images.githubusercontent.com/146936942/274731848-5ef92b2e-4ece-4d33-bfd4-815fc011f7df.jpg)
> 
> I await your reply and feedback so that it can be worked on @srish @tuxology

login first

**Comment by JulietMadu** [comment]
i was able to work on this, i created equal spacing between cards and also made sure there is proper alignment. @srish 
![search result](https://github.com/unstructuredstudio/zubhub/assets/128796937/fd70ee4d-2006-457f-9c7e-9ec749893576)

**Comment by JulietMadu** [comment]
![Uploading search result.png…]()

**Comment by srish** [comment]
This task doesn't need a design change. Developer picking it up make sure that the spacing between cards is the same as used on other venues.

**Comment by brrkrmn** [comment]
@srish @tuxology, hello, opened #914 for this issue, waiting for reviews ☺️

**Comment by yokwejuste** [comment]
> @srish @tuxology, hello, opened #914 for this issue, waiting for reviews ☺️

Hey @brrkrmn there was already a PR for this issue at #873 and it is still under review. This can cause conflicts, 

please try to watch out that before opening a PR next time.

**Comment by brrkrmn** [comment]
Hey @yokwejuste, 👋🏻  Today Srish tagged this issue as ready for devs in Zulip, so I thought that meant we could work on it. Once again, it is okay to open PRs for any issues regardless of the existing ones. You can check [this message](https://unstructured.zulipchat.com/#narrow/stream/246561-ZubHub/topic/Welcome.20.26.20introductions/near/396395699) from Srish

**Comment by yokwejuste** [comment]
> Hey @yokwejuste, 👋🏻 Today Srish tagged this issue as ready for devs in Zulip, so I thought that meant we could work on it. Once again, it is okay to open PRs for any issues regardless of the existing ones. You can check [this message](https://unstructured.zulipchat.com/#narrow/stream/246561-ZubHub/topic/Welcome.20.26.20introductions/near/396395699) from Srish

Great, this is fine, so we can get different approaches to solve the issues. Thanks!

**Comment by brrkrmn** [comment]
Hello @yokwejuste, I could not help but notice that the latest commit of #873 is the same implementation in #914. I believe the reason for having multiple PRs is to see different approaches. I think we should go with our own ways for solving the issues so that mentors can compare these approaches 🙏🏻 Thanks

**Comment by tuxology** [comment]
As @brrkrmn points our reason for having different PRs is to experiment with different implementations and give everyone an opportunity to experiment as well as collaborate. However, it would also make sense to help each other once in a while on their PRs as well in the spirit of collaboration (esp if fixes are small). My recommendation for folks taking inspiration from other folks work is to ALWAYS acknowledge the original work and cite from where you took the inspiration.
