### ISSUE TITLE
Improve UX writing for my projects empty state

### ISSUE THREAD

**Issue by Kub-kub** [unstructuredstudio/zubhub#867]
**Describe the the feature request**
A better copy that let's the user know that they have not created a project and motivates them to create on. The "Oops!!
User has not created any projects yet. Check back later!" is generic and a user can check back later and still not create a project. 
A better copy will be  "No projects here!  Time to work your magic and create some projects to view. Let's get started! " or  "Uh-oh! No projects yet? Time to get those creative gears turning and start a project to view.". These suggestions are more personalised, fun and motivates users to create a project. UX writing is very important, it can either encourage or discourage a user from taking an action.

![my project](https://github.com/unstructuredstudio/zubhub/assets/61984894/c804e535-47ca-4b2d-bbcc-0dc3b37afe70)

**Comment by Kub-kub** [comment]
@srish What do you think about this?

**Comment by Stephxdesigns** [comment]
Hi @Kub-kub this issue is already being handled in issue #789 So you can start contributing to it with your ideas

**Comment by Kub-kub** [comment]
Thank you

**Comment by Kub-kub** [comment]
@srish @Stephxdesigns Just noticed that issue #789 is different. That is for when there's no result for the search made and this is for the empty state for when users click on "my projects" I came up with these. What do you think?
![my projects 1](https://github.com/unstructuredstudio/zubhub/assets/61984894/5ca72f08-ec2a-4156-831b-1373c7d36d47)
![My projects 2](https://github.com/unstructuredstudio/zubhub/assets/61984894/62006f75-887b-4170-ad2e-0f0a837ec0f9)

**Comment by Stephxdesigns** [comment]
@Kub-kub If you read through you'd see that a suggestion on the UX writing for the no project page was also made which prompted @srish to ask designers to collaborate on documenting all the error pages that need improvement and come up with a design solution for them. 

The No project page is also one of those pages but if you insist you can still wait for feedback. I just thought to say something so there wouldn't be duplicate issues being handled in various places.

**Comment by Kub-kub** [comment]
Oh!,I see. I'll make my contributions there.

**Comment by Kub-kub** [comment]
Thank you
