### ISSUE TITLE
To improve the navigation menu  and align it with modern design patterns

### ISSUE THREAD

**Issue by Mitchell377** [unstructuredstudio/zubhub#869]
**Describe the the feature request**
1, i noticed here that auto layout was not used, auto layout actually helps for consistent spacing,
2, the yellow icon was not grouped together to its frame, which is why when i dragged out the icon it moved without the frame it was in .
those are my two observations.
****
![Rectangle 34](https://github.com/unstructuredstudio/zubhub/assets/102149002/62672998-f3ba-46c4-862e-154acfa51298)

A clear and concise description of the feature
below is the correction i made, i did not tamper with the design but i did the following
1, i designed it using auto layout
2, i grouped the yellow icon with its frame
3, i named the auto layout and group so it can be located easily

![Group 92](https://github.com/unstructuredstudio/zubhub/assets/102149002/48e2adbb-2934-470e-9168-3ba6b911ad78)

@srish @tuxology  please i need your feedback on this

**Comment by srish** [comment]
I don't understand the exact problem with the design, and the expected change is trivial and barely noticeable.

**Comment by productguyyy** [comment]
I was able to noticed all the errors because I'm a designer and I looked intently 

The changes I made are very important in design
