### ISSUE TITLE
responsiveness issues when we make a search on projects that don't exist

### ISSUE THREAD

**Issue by yokwejuste** [unstructuredstudio/zubhub#872]
**Describe the bug**
The search for insexisting project leads to responsiveness issue desktop screen.

**To Reproduce**

1. Go to zubhub website 
2. Click on search and make a search without clicking the options suggested in the search
3. And here we are, see the error

**Expected behavior**
On normal circumstances, we were to have the same result except for the responsiveness issue encountered

**Screenshots**
![image](https://github.com/unstructuredstudio/zubhub/assets/71908316/8341f5fe-5997-489b-b015-3b7c331dddb0)
![image](https://github.com/unstructuredstudio/zubhub/assets/71908316/34971411-7599-4b1f-8360-abb84c1aaecf)

**Comment by DonPresh** [comment]
This is a developer issue yeah?

**Comment by yokwejuste** [comment]
> This is a developer issue yeah?

both developer and designer, I think os

**Comment by DonPresh** [comment]
I worked on a screen for something like this for an issue raised. Let me find the issue.

I also think designing with a grid system will help this issue but let's get feedback from the mentor

**Comment by yokwejuste** [comment]
> I worked on a screen for something like this for an issue raised. Let me find the issue.

Alright, please get it and paste it here, if there is need to be closed this will be closed

**Comment by DonPresh** [comment]
It's not exactly the same thing but sure.

**Comment by ladyami** [comment]
This is developer bug, can be correct on the CSS file

**Comment by brrkrmn** [comment]
Hey guys, I opened #887 for this, can you take a look?

**Comment by yokwejuste** [comment]
> Hey guys, I opened #887 for this, can you take a look?

Great job

**Comment by brrkrmn** [comment]
@yokwejuste thank you
