### ISSUE TITLE
Unable to proceed to publish a project in draft mode after selecting add tags

### ISSUE THREAD

**Issue by Dumzy006** [unstructuredstudio/zubhub#874]
Describe the bug
Unable to publish a project in draft after completing all the steps

To Reproduce

Visit 'Zubhub website'
Click on 'Log in and make sure you are logged in'
select  on a draft project in my draft 
After completing all steps click on add tags
Then select hashtag that describe your project
Then click publish

See error
Expected behavior
unable to publish and I am not getting any error message to know why I can't publish with a tag

![Screenshot 2023-10-12 062437](https://github.com/unstructuredstudio/zubhub/assets/136137889/6a84726b-ca6d-4a4d-98a3-aaadaedb50ee)

**Comment by Dumzy006** [comment]
@srish I also suggest that the publish button should be disabled when a tag has not been selected
as it is currently active.. see screenshot below

![Screenshot 2023-10-12 070049](https://github.com/unstructuredstudio/zubhub/assets/136137889/02a3e377-abb8-4278-84fd-c205ce86c97e)

**Comment by Dumzy006** [comment]
@srish I made an improvement for the publish( Disabled) when no hashtag has been selected
See screenshot below
![Uploading image.png…]()

**Comment by Dumzy006** [comment]
@srish I made an improvement for the publish button ( Disabled) when no hashtag has been selected
See screenshot below
![image](https://github.com/unstructuredstudio/zubhub/assets/136137889/d074b1ee-0745-4d5e-b2db-aab0781ca0cd)

**Comment by Temabo** [comment]
I just noticed this too, the "publish without tags" button did not work and I was unable to publish a project after selecting tags, I think this is a developer's issue. 
@Dumzy006 I agree with you on disactivating the "Publish" button on the tag selection pop up until users have selected at least one tag.

**Comment by coderatomy** [comment]
Since no one is working these. Let me wrap them into one PR @Temabo @Dumzy006

**Comment by Dumzy006** [comment]
Alright @coderatomy

**Comment by srish** [comment]
Closing as a duplicate
