### ISSUE TITLE
None option is not available in creating a project and activity

### ISSUE THREAD

**Issue by Dumzy006** [unstructuredstudio/zubhub#875]
Recently, I tried to create a project then when I got to the last step which is Step 3  I was asked to select none if I am unsure of the category.

Looking at this I suggest that a none  checkbox which disables all other checkbox when selected should be provided as an error prevention feature and to also provide easy understanding and navigation for the user
See screenshot below  and please can I work on this issue as a designer @srish 

![Screenshot 2023-10-12 064537](https://github.com/unstructuredstudio/zubhub/assets/136137889/c94393e5-11bc-4160-adf5-ea6b185bb470)

**Comment by srish** [comment]
Let's remove the line "Select none if you are unsure about". Developer implementing this, please make the same change for activity creation form.

**Comment by Dumzy006** [comment]
Hello @srish 
Here is the improved design of the none option
I have taken out the sentence you mentioned above
See screenshot below
![image](https://github.com/unstructuredstudio/zubhub/assets/136137889/639ab08b-00af-432c-9592-64082ec089e1)

**Comment by Dumzy006** [comment]
Based on the screenshot provided above I suggest the category title and subtitle should be centered align reason been that ''create project'' and subtitle is centered align. So I feel the design should be consistent all through... What do you think? @srish 

See screenshot below

![image](https://github.com/unstructuredstudio/zubhub/assets/136137889/d7b5e146-a029-488e-8372-3f57e9b0921b)

**Comment by Urmilasc** [comment]
Hello @srish , to solve this issue we need to create a None checkbox , and implement the behaviour that when someone click on this None checkbox , all other checkbox should be disable 

Or just we need to remove the line "Select none if you are unsure about" from project or activity section , 
Let me know Please !!
