### ISSUE TITLE
Ripple effect on Project cards

### ISSUE THREAD

**Issue by mehreeee** [unstructuredstudio/zubhub#877]
**Describe the bug**
When you clap or bookmark a project, the ripple effect extends to the whole card as if the whole card has been selected.

**To Reproduce**

1. On the ‘Home page'
2. Clap on ‘ any project on the featured project’s list'
3. Bookmark 'any project on the featured projects list

https://github.com/unstructuredstudio/zubhub/assets/105458062/dc969b11-fef4-480f-94a0-eb79c31388b1

'

**Comment by yokwejuste** [comment]
Can you please give more context on the issue?
I think this is an effect, what are your thoughts on the effect?

**Comment by mehreeee** [comment]
> Can you please give more context on the issue?
> I think this is an effect, what are your thoughts on the effect?

The animation after clapping on or bookmarking a project is not supposed to affect the whole card. It’s like clicking on the card itself. This can be confusing to some users

**Comment by mehreeee** [comment]
@srish Please your opinion on this

**Comment by brrkrmn** [comment]
This happens on many other places as well. If you go to profile>edit and click on anywhere on the form, the same effect is seen in a lighter version. I believe many other forms also have it. Not sure how much of it is intentional

**Comment by ladyami** [comment]
Can be fit by developer in the CSS file

**Comment by yokwejuste** [comment]
> This happens on many other places as well. If you go to profile>edit and click on anywhere on the form, the same effect is seen in a lighter version. I believe many other forms also have it. Not sure how much of it is intentional

exactly what I think too, it's too repetitive to be a bug, it is a **feature** :)

**Comment by srish** [comment]
Do not see a strong reason behind the intended change :)
