### ISSUE TITLE
The carousel cards on creator profile is, the animation effect is slow and shaky. Could be smoother

### ISSUE THREAD

**Issue by OnolexTim** [unstructuredstudio/zubhub#880]
On mobile view, the carousel cards on creator profile, the animation effect is slow and shaky. Could be smoother.

see what I mean 
[This is from a creator’s profile](https://zubhub.unstructured.studio/projects/0848243c-5381-45f3-bacb-e60c58fdda73) 

@srish

**Comment by srish** [comment]
This is trivial and I don't see a strong reasoning behind intended change
