### ISSUE TITLE
Improve UI of the user (creator) profile 

### ISSUE THREAD

**Issue by OnolexTim** [unstructuredstudio/zubhub#881]
1. There’s a section on the UI where first time users can comment on their profile. About Me section should be enough for users to talk about themselves and interest. 

Don’t see the need for users being able to write a comment on their profiles unless they’re replying to a visitor’s comments made on their profile.

2. Padding and margin needs to be adjusted 
[See here  ](https://zubhub.unstructured.studio/profile) 

See screenshot here

[1…](https://drive.google.com/file/d/1ykvifCsXTwuZFrDrAjd_U9ZsMbhPz4en/view?usp=drivesdk) 

[2…](https://drive.google.com/file/d/1baU3_vGx_nShkxP7T9lSteE-K-__MzuM/view?usp=drivesdk)

**Comment by OnolexTim** [comment]
@srish pls can I get a go-ahead to work on this issue?

**Comment by d-arkangel** [comment]
I'd probably say you should go through some of the closed issues so as to ensure that this issue has not been handled previously. Nevertheless, you may want to just go ahead and work on it.

I would also like to offer some UI/UX assistance if needed.

**Comment by srish** [comment]
Don't see a strong reasoning for intended change
