### ISSUE TITLE
The homepage of Zubhub needs an "About Us" section. 

### ISSUE THREAD

**Issue by ladyami** [unstructuredstudio/zubhub#884]
**Describe the the feature request**

The homepage of Zubhub needs an "About Us" section added to it. 

I conducted a user experience survey on the ZubHub website. I gave 10 users the website link and asked them to visit and tell me what the website is all about and how long it takes them to find out.

1 person came back and said it is an ideas-sharing website and it took just 30 seconds.
3 said it is a content-sharing website, and it took them 40 seconds.
6 said they didn't understand it, this set spent 20 / 25 seconds on the website.

none of the participants can give a simple description of  Zubhub that is "ZubHub is an open-source, documentation & collaboration tool for activity-based learning. "

Then I asked all the participants if they saw the About Us section in the footer and they replied they didn't scroll down to the footer to see it. This shows that users don't have patience.

This survey shows us the importance of having a clear and concise explanation of what ZubHub is on the home page. And also tells us that the ZubHub home page is not clear and concise enough about what the website is all about. As a result, it takes users too long to understand what ZubHub is and what they can do on the website.

Even though there is an About us section in the footer, users are not scrolling down to the footer to see it. This shows that users do not have the patience to look for information that is not immediately visible on the home page.

Recommendation:

I recommend adding a short section to the home page right under the hero section that clearly explains what ZubHub is and what users can do on the website. This section should be titled something like "What is ZubHub?" or "Get started with ZubHub."

if you check the website like Sakai Project ( is also a learning management system) they have a section dedicated for users to get to know them

![Screenshot (323)](https://github.com/unstructuredstudio/zubhub/assets/99187115/0ff191a8-4207-4149-aa4d-60b04852f84d)

website like Open LMS
![Screenshot (324)](https://github.com/unstructuredstudio/zubhub/assets/99187115/3be2c452-0bf8-464c-9190-4383b0adc5e8)

website like OpenOLAT
![Screenshot (328)](https://github.com/unstructuredstudio/zubhub/assets/99187115/12622f39-4355-43fb-b493-41d36cb8fce0)

![Screenshot (329)](https://github.com/unstructuredstudio/zubhub/assets/99187115/a05cf902-162a-4897-852e-a1a9a474e2aa)

![Screenshot (330)](https://github.com/unstructuredstudio/zubhub/assets/99187115/566abff9-ed40-4598-b703-633844ea1dc5)

Why it is important to include such sections on the home page:

The home page is the most important page on a website. It is the first page that most visitors will see, and it is the page that is most likely to influence their decision about whether or not to use the website.

A clear and concise explanation of what ZubHub is on the home page is important for the following reasons:

It can help new visitors to understand what ZubHub is and what they can do on the website.
It can make it easier for users to find the information they are looking for.
It can help to improve the overall user experience of the website.

**Comment by aqsaaqeel** [comment]
@ladyami Great observation and appreciate your efforts! In order to indulge new users, we definitely need an About Us section that shows clearly what is Zubhub and what it does

**Comment by ladyami** [comment]
> @ladyami Great observation and appreciate your efforts! In order to indulge new users, we definitely need an About Us section that shows clearly what is Zubhub and what it does

Thank you @aqsaaqeel  zubhub project is important and an "About Us" section will help new users understand its purpose.

**Comment by srish** [comment]
Thanks for your suggestions! Please see my comment here: https://github.com/unstructuredstudio/zubhub/issues/854#issuecomment-1756494516
