### ISSUE TITLE
Misc UX Improvement Suggestions

### ISSUE THREAD

**Issue by tuxology** [unstructuredstudio/zubhub#9]
I've been trying to fix here and there and not getting it completely right so, I am sending you some ideas to improve the UX. Its already looking very amazing!

- [x] Use "Raleway" font in whole app. Make sure all titles are `font-weight:900`. Increase font sized of other headings like DEscription, Comments etc (2.2em)

![image](https://user-images.githubusercontent.com/3373857/102566823-229dbe00-4095-11eb-8a8a-03eae726abbb.png)

 - [x] Experiment with following background colors (#FFCC00)

![image](https://user-images.githubusercontent.com/3373857/102566894-44974080-4095-11eb-8a9e-a9900bb8f7fc.png)

 - [x] Change App name from Create React App to Zubhub. Also change favicon. Take favicon from  https://zubhub.unstructured.studio/ Also modify README.md to reflect ZubHub name

 - [x] The right buttons next to video/image could be probably more like "buttons". maybe use this style with button shadow on the whole "pill" and white text/icons. If this does not look good, use red color background (same as title bar) with yellow icons and text and see if that is good. Otherwise, use the vertical pill and put same styled buttons as the Clap and like buttons you have on cards in gallery view for visual consistency. Also buttons here have a "ghost layer" on hover. We should remove it or restrict it to width of container.

![image](https://user-images.githubusercontent.com/3373857/102567223-ea4aaf80-4095-11eb-98ca-40c42b351712.png)

 - [x]  Increase comment box with to 100% of its container. Its also not looking that prominent. Maybe put the whole thing in another "box" to show that its separate from the other sections? In current ZubHub we have put it in a gray box to show that its a separate interaction from main page. 

![image](https://user-images.githubusercontent.com/3373857/102567498-79f05e00-4096-11eb-94e1-c62216956ea0.png)

 - [x] Use larger font (same size) and same Raleway font in the comment box as well for visual consistency

 - [x] Maybe try to use following card styling. Note that the buttons need to have yellow icons/text. Also see if we can replace these icons with "solid icons" rather than "line icons".  
![image](https://user-images.githubusercontent.com/3373857/102568042-99d45180-4097-11eb-9862-5222aa8a76f8.png)

 - [x] If there is no video in card, show the first image 

 - [x] Increase height of carousel so shadow is not cut suddenly. 

![image](https://user-images.githubusercontent.com/3373857/102568332-1d8e3e00-4098-11eb-9200-95280a12e0cc.png)

 - [x] Maybe remove the robohash background from signups for now and replace with previous gradient on pages? Other things to experiment are https://svgeez.com/ (snowball dots or sprinkles styles with our yellow/red/cyan styled palette may work)
 - [x] Replace left/right arrows in following with something more elegant - maybe buttons (same as Signup style), same height as carousel with some more minimal arrows? (like we have on unstructured impact page?)  
![image](https://user-images.githubusercontent.com/3373857/102569630-a8703800-409a-11eb-824b-ee97c18b35aa.png)

**Comment by NdibeRaymond** [comment]
"If there is no video in card, show the first image"
I have done this already

**Comment by NdibeRaymond** [comment]
Though I am not a designer, my only concern with the changes especially the color part is that we might have a color riot. Where we have many deep primary colors interacting at once. But will go ahead and make the changes

**Comment by NdibeRaymond** [comment]
> "Also see if we can replace these icons with "solid icons" rather than "line icons"

The difference in solid vs line icons is the visual indicator a user uses to know whether they have liked a project or not. "Solid for liked", "line for not yet liked".
When a user claps for a project, the line clap icon changes to solid

**Comment by NdibeRaymond** [comment]
I also think it is worth mentioning that using large fonts for titles especially on the list view is not that great. Titles are meant to be displayed in full anywhere they appear. The card above has a title of just 50 characters, If we have too large fonts for titles and a user uses a title that has 100 characters, the title will be occupying approximately 6 lines of the card

**Comment by tuxology** [comment]
> especially the color part is that we might have a color riot.

yes, you are right. I also thought about it. Lets see how it looks in its entirety. We have still not defined a color palette, so we are still experimenting :)

**Comment by tuxology** [comment]
> The difference in solid vs line icons is the visual indicator a user uses to know whether they have liked a project or not. "Solid for liked", "line for not yet liked".
> When a user claps for a project, the line clap icon changes to solid

Ok yes, you are right! this makes sense, don't change the icon style then. The only thing I feel is that the width is too less so it does not really signify that there is something worth interacting there..Can we try to adjust line-icon width?

**Comment by tuxology** [comment]
> I also think it is worth mentioning that using large fonts for titles especially on the list view is not that great. Titles are meant to be displayed in full anywhere they appear. The card above has a title of just 50 characters, If we have too large fonts for titles and a user uses a title that has 100 characters, the title will be occupying approximately 6 lines of the card

Ok, this is also a valid point. Maybe we need some way to distinguish the title from other sections. Right now, it looks very squished vertically. Maybe we use 900 weight for title and keep same size?

**Comment by NdibeRaymond** [comment]
> > I also think it is worth mentioning that using large fonts for titles especially on the list view is not that great. Titles are meant to be displayed in full anywhere they appear. The card above has a title of just 50 characters, If we have too large fonts for titles and a user uses a title that has 100 characters, the title will be occupying approximately 6 lines of the card
> 
> Ok, this is also a valid point. Maybe we need some way to distinguish the title from other sections. Right now, it looks very squished vertically. Maybe we use 900 weight for title and keep same size?

okk, yeaa. this sounds like something we can

**Comment by NdibeRaymond** [comment]
> > The difference in solid vs line icons is the visual indicator a user uses to know whether they have liked a project or not. "Solid for liked", "line for not yet liked".
> > When a user claps for a project, the line clap icon changes to solid
> 
> Ok yes, you are right! this makes sense, don't change the icon style then. The only thing I feel is that the width is too less so it does not really signify that there is something worth interacting there..Can we try to adjust line-icon width?

will look into it

**Comment by NdibeRaymond** [comment]
> > especially the color part is that we might have a color riot.
> 
> yes, you are right. I also thought about it. Lets see how it looks in its entirety. We have still not defined a color palette, so we are still experimenting :)

yeaaa, that's true. let's see how it looks then

**Comment by tuxology** [comment]
Closing this as this is done mostly!
