### ISSUE TITLE
Creator review section on homepage is not visible properly

### ISSUE THREAD

**Issue by lakshay451** [unstructuredstudio/zubhub#901]
## Description

The Creator review section on homepage is not visible properly, we can choose proper color combination and can add multiple review in the form of carousel.

![Screenshot (884)](https://github.com/unstructuredstudio/zubhub/assets/89472581/f3cf7aec-b2b8-4553-9ec1-b4226a94b6dc)

I am willing to work on this issue. Please assign it to me.

**Comment by brrkrmn** [comment]
This screenshot is from your local app, right? In the production, this section looks fine: https://zubhub.unstructured.studio/

I think your local looks different than the prod because of the failed fetching of theme. You can look for our chat history to solve this problem 🙂

**Comment by aqsaaqeel** [comment]
[Here's the conversation](https://unstructured.zulipchat.com/#narrow/stream/246561-ZubHub/topic/Welcome.20.26.20introductions/near/395239367) you can refer to fix this error @lakshay451

**Comment by srish** [comment]
This is not an issue in production.
