### ISSUE TITLE
Need help regarding local setup

### ISSUE THREAD

**Issue by lakshay451** [unstructuredstudio/zubhub#903]
Can anyone please help me setting up the project locally...I am a Windows user and I am stuck at installing 'make' in windows. Can anyone please help me get through this so that I can contribute in the project.

**Comment by brrkrmn** [comment]
Hello @lakshay451, please join our Zulip channel https://unstructured.zulipchat.com/#narrow/stream/246561-ZubHub/topic/Welcome.20.26.20introductions and you can get help there regarding your problem. You can use that chat to seek help for any problem you face. ☺️

**Comment by lakshay451** [comment]
Thanks
