### ISSUE TITLE
hi i would like redesign these components

### ISSUE THREAD

**Issue by ozoilo** [unstructuredstudio/zubhub#905]
## Learning objectives

- Objective

## Todo

These points are a rough guideline. **Please** feel free to discuss with others on the team about the best way to design this component!

- Todo

## Useful links

- Useful link

**Comment by mehreeee** [comment]
Hi ozoilo you do not need to create an issue for this. If you need help on how to contribute to issues please reach out to me on the Zulip chat and I’d put you through.
