### ISSUE TITLE
Users should be instantly redirected to the login page once their  `auth token` expires

### ISSUE THREAD

**Issue by coderatomy** [unstructuredstudio/zubhub#906]
**Describe the the feature request**
Rather than seeing a `404` error page, It's ideal to redirect the user to login page once there session expires since we are sure now  that they have to login to continue.
This should happen instantly as possible. I actually had to first see a few failing requests. Then did some actions on the site until I saw the 404. 

We could show some notifiers like `Your session has expired. Redirecting to login`. What do you say about this @Temabo @srish 

![image](https://github.com/unstructuredstudio/zubhub/assets/141822315/7ab07a1d-e8df-497d-b341-0bf95a558a28)

[Screencast from 2023-10-15 08-58-19.webm](https://github.com/unstructuredstudio/zubhub/assets/141822315/fb1b3587-93b4-4091-a67c-8fe78187c7d6)

![Screenshot from 2023-10-15 08-57-35](https://github.com/unstructuredstudio/zubhub/assets/141822315/42bdb371-a039-450e-8417-8bdf9c83ee22)

**Comment by yokwejuste** [comment]
This is interesting @coderatomy, we can use a refresh token here instead which is much easier to generate and as well as resource use effective too.

Picture this out, we will have less efforts getting the access token, so the user logs in once and the token is stored.
![image](https://github.com/unstructuredstudio/zubhub/assets/71908316/8a687bf8-865d-47f5-88ed-d0fe08549434)

what do you think? 

@coderatomy @tuxology

**Comment by coderatomy** [comment]
Great suggestion, @yokwejuste. However, I think this is already implemented. The server effectively handles the expiration of authentication tokens and generates new ones seamlessly. Our task is to promptly capture and respond to this update on our frontend. 
To achieve instant responsiveness, we can integrate this redirection mechanism within the `pageWrapper`. Given that it encompasses every page, redirection processes can occur significantly faster in this context.

**Comment by srish** [comment]
As per @tuxology, whenever the token expires, the user should see an error at the top first that says "Your session has expired, redirecting you to the login page" and be redirected to the login page.

**Comment by yokwejuste** [comment]
> Great suggestion, @yokwejuste. However, I think this is already implemented. The server effectively handles the expiration of authentication tokens and generates new ones seamlessly. Our task is to promptly capture and respond to this update on our frontend. 
> To achieve instant responsiveness, we can integrate this redirection mechanism within the `pageWrapper`. Given that it encompasses every page, redirection processes can occur significantly faster in this context.

I think this issue is made for me 😅

**Comment by coderatomy** [comment]
Go on then  @yokwejuste. Though, I would first request some help from the UI/UX team on how the redirection text should look
Will we just have a spinner with those texts
cc @Temabo ...

**Comment by mehreeee** [comment]
https://github.com/unstructuredstudio/zubhub/assets/105458062/43e9d3e0-fcc0-4f18-99c7-0d99aba42b37

Hi @yokwejuste @coderatomy This is what I think the redirection screen should look like. The redirection should happen automatically and redirect to the login screen.

**Comment by yokwejuste** [comment]
> 
> https://github.com/unstructuredstudio/zubhub/assets/105458062/43e9d3e0-fcc0-4f18-99c7-0d99aba42b37
> 
> Hi @yokwejuste @coderatomy This is what I think the redirection screen should look like. The redirection should happen automatically and redirect to the login screen. 

Can you send me links to prototype and to the figma file?

**Comment by mehreeee** [comment]
> > Page.1.-.Create.-.Figma.2023-10-17.00-14-05.mp4
> >     
> >   
> > 
> >   
> > 
> >   
> > 
> > 
> > Hi @yokwejuste @coderatomy This is what I think the redirection screen should look like. The redirection should happen automatically and redirect to the login screen.
> 
> Can you send me links to prototype and to the figma file?

sure here is the link to the figma file
https://www.figma.com/file/uw9ZqAJtIRK83oHGYKnJi1/redirection?type=design&node-id=1%3A5&mode=design&t=0hKSDD4pLqaunOGU-1

**Comment by yokwejuste** [comment]
> > > Page.1.-.Create.-.Figma.2023-10-17.00-14-05.mp4
> > >     
> > >   
> > > 
> > >   
> > > 
> > >   
> > > 
> > > 
> > > Hi @yokwejuste @coderatomy This is what I think the redirection screen should look like. The redirection should happen automatically and redirect to the login screen.
> > 
> > Can you send me links to prototype and to the figma file?
> 
> sure here is the link to the figma file
> https://www.figma.com/file/uw9ZqAJtIRK83oHGYKnJi1/redirection?type=design&node-id=1%3A5&mode=design&t=0hKSDD4pLqaunOGU-1

Amazing  🎉

**Comment by mehreeee** [comment]
> > > > Page.1.-.Create.-.Figma.2023-10-17.00-14-05.mp4
> > > > Hi @yokwejuste @coderatomy This is what I think the redirection screen should look like. The redirection should happen automatically and redirect to the login screen.
> > > 
> > > 
> > > Can you send me links to prototype and to the figma file?
> > 
> > 
> > sure here is the link to the figma file
> > https://www.figma.com/file/uw9ZqAJtIRK83oHGYKnJi1/redirection?type=design&node-id=1%3A5&mode=design&t=0hKSDD4pLqaunOGU-1
> 
> Amazing 🎉

Thank you

**Comment by coderatomy** [comment]
Nice work @mehreeee. Though I was expecting some sort of a modal and we just blur stuff in the background. But it's okay if that will take a while. This is already good

**Comment by mehreeee** [comment]
> Nice work @mehreeee. Though I was expecting some sort of a modal and we just blur stuff in the background. But it's okay if that will take a while. This is already good

I can fix that. Let me do a few changes

**Comment by yokwejuste** [comment]
> Nice work @mehreeee. Though I was expecting a modal, and we just blur stuff in the background

I guess we will link it up to the issue #802 with the design on [this comment](https://github.com/unstructuredstudio/zubhub/issues/802#issuecomment-1750927049)

**Comment by coderatomy** [comment]
@mehreeee, I meant something like a loading spinner, not directly popping the login modal. Something like below but in the context of our design. Again, if this complicates stuff, we can go on with the first mock-up
![image](https://github.com/unstructuredstudio/zubhub/assets/141822315/51691d18-0d11-41a9-adc0-a5a4c7fd4f56)

**Comment by mehreeee** [comment]
> @mehreeee, I meant something like a loading spinner, not directly popping the login modal. Something like below but in the context of our design. Again, if this complicates stuff, we can go on with the first mock-up ![image](https://user-images.githubusercontent.com/141822315/275755839-51691d18-0d11-41a9-adc0-a5a4c7fd4f56.png)

I'm not sure I understand. You want a modal to pop up on the page with a loading spinner?

**Comment by coderatomy** [comment]
Ahh alright.  Let's go on with that one you've designed for now. We can modify later

**Comment by mehreeee** [comment]
> Nice work @mehreeee. Though I was expecting some sort of a modal and we just blur stuff in the background. But it's okay if that will take a while. This is already good


https://github.com/unstructuredstudio/zubhub/assets/105458062/3ba66191-18ad-438d-9b85-6b1e433d4b26

I designed a modal with a loading spinner, I'm not sure if this is what you wanted. Anytime the modal pops up, the previous background blurs or darkens. Let me know the specific changes you want to implement and I'll work on it.

**Comment by Temabo** [comment]
@mehreeee Solid work! Regarding the pop-up design, I think it's a great start! To enhance the user experience, how about incorporating a timer within the pop-up? This way, users will have a clear idea of when they will be redirected to the login page after seeing the 'Your session has expired. Redirecting to login.' message. It's a subtle addition that can improve the overall usability and transparency of the process. @coderatomy

**Comment by mehreeee** [comment]
> @mehreeee Solid work! Regarding the pop-up design, I think it's a great start! To enhance the user experience, how about incorporating a timer within the pop-up? This way, users will have a clear idea of when they will be redirected to the login page after seeing the 'Your session has expired. Redirecting to login.' message. It's a subtle addition that can improve the overall usability and transparency of the process. @coderatomy

Thank you @Temabo. If it wouldn't be too much work for the devs we could incorporate that. Still waiting for feedback

**Comment by mehreeee** [comment]
> @mehreeee Solid work! Regarding the pop-up design, I think it's a great start! To enhance the user experience, how about incorporating a timer within the pop-up? This way, users will have a clear idea of when they will be redirected to the login page after seeing the 'Your session has expired. Redirecting to login.' message. It's a subtle addition that can improve the overall usability and transparency of the process. @coderatomy

I'm not sure I like the timer though, but let me know what you guys think.


https://github.com/unstructuredstudio/zubhub/assets/105458062/18e543d2-afd8-4ea7-8832-8a3e29218e3c

**Comment by DonPresh** [comment]
> @mehreeee Solid work! Regarding the pop-up design, I think it's a great start! To enhance the user experience, how about incorporating a timer within the pop-up? This way, users will have a clear idea of when they will be redirected to the login page after seeing the 'Your session has expired. Redirecting to login.' message. It's a subtle addition that can improve the overall usability and transparency of the process. @coderatomy

@Temabo Nice suggestion. I have a slightly different opinion, the timer might be a bit 

> > @mehreeee Solid work! Regarding the pop-up design, I think it's a great start! To enhance the user experience, how about incorporating a timer within the pop-up? This way, users will have a clear idea of when they will be redirected to the login page after seeing the 'Your session has expired. Redirecting to login.' message. It's a subtle addition that can improve the overall usability and transparency of the process. @coderatomy
> 
> I'm not sure I like the timer though, but let me know what you guys think.
> 
>  Page.1.-.redirection.-.Figma.2023-10-17.04-03-22.mp4

I think it looks better without the timer. For me, it feels alien having a timer there.

**Comment by mehreeee** [comment]
> > @mehreeee Solid work! Regarding the pop-up design, I think it's a great start! To enhance the user experience, how about incorporating a timer within the pop-up? This way, users will have a clear idea of when they will be redirected to the login page after seeing the 'Your session has expired. Redirecting to login.' message. It's a subtle addition that can improve the overall usability and transparency of the process. @coderatomy
> 
> @Temabo Nice suggestion. I have a slightly different opinion, the timer might be a bit
> 
> > > @mehreeee Solid work! Regarding the pop-up design, I think it's a great start! To enhance the user experience, how about incorporating a timer within the pop-up? This way, users will have a clear idea of when they will be redirected to the login page after seeing the 'Your session has expired. Redirecting to login.' message. It's a subtle addition that can improve the overall usability and transparency of the process. @coderatomy
> > 
> > 
> > I'm not sure I like the timer though, but let me know what you guys think.
> > Page.1.-.redirection.-.Figma.2023-10-17.04-03-22.mp4
> 
> I think it looks better without the timer. For me, it feels alien having a timer there.

Thank you @DonPresh. I agree. The redirection should happen almost immediately and not having to wait for a countdown.

**Comment by DonPresh** [comment]
My suggestion for this issue:
![Session expired](https://github.com/unstructuredstudio/zubhub/assets/100778015/d6baf7af-6cd2-413e-9930-38756ffa68bc)

The users are not immediately carted off to the login page. They click on the "ok" button before the redirection happens.
@coderatomy @mehreeee @srish what do you think?

**Comment by maureen-oz** [comment]
> > @mehreeee Solid work! Regarding the pop-up design, I think it's a great start! To enhance the user experience, how about incorporating a timer within the pop-up? This way, users will have a clear idea of when they will be redirected to the login page after seeing the 'Your session has expired. Redirecting to login.' message. It's a subtle addition that can improve the overall usability and transparency of the process. @coderatomy
> 
> @Temabo Nice suggestion. I have a slightly different opinion, the timer might be a bit
> 
> > > @mehreeee Solid work! Regarding the pop-up design, I think it's a great start! To enhance the user experience, how about incorporating a timer within the pop-up? This way, users will have a clear idea of when they will be redirected to the login page after seeing the 'Your session has expired. Redirecting to login.' message. It's a subtle addition that can improve the overall usability and transparency of the process. @coderatomy
> > 
> > 
> > I'm not sure I like the timer though, but let me know what you guys think.
> > Page.1.-.redirection.-.Figma.2023-10-17.04-03-22.mp4
> 
> I think it looks better without the timer. For me, it feels alien having a timer there.

Totally agree

**Comment by maureen-oz** [comment]
UI-UX team to the rescue. Great job @mehreeee @DonPresh @Temabo @yokwejuste 🥳

**Comment by coderatomy** [comment]
Agreed! No countdowns. Auth redirections should be made as instant as possible.

**Comment by yokwejuste** [comment]
> Agreed! No countdowns. Auth redirections should be made as instant as possible.

So what is our design here @coderatomy @srish

**Comment by srish** [comment]
@DonPresh's design here is nice: https://github.com/unstructuredstudio/zubhub/issues/906#issuecomment-1766791494 :) When a dev takes it up, can you make sure to use MUI for implementing the components?

**Comment by coderatomy** [comment]
Nice work @DonPresh, can you share the figma link for this mock-up please

**Comment by DonPresh** [comment]
@coderatomy Here's the link
https://www.figma.com/file/2twyPjNSSzNEzlMO0doTCb/Outreachy?type=design&node-id=204%3A786&mode=design&t=trxYXXuxEAaEgShk-1

**Comment by yokwejuste** [comment]
> @coderatomy Here's the link https://www.figma.com/file/2twyPjNSSzNEzlMO0doTCb/Outreachy?type=design&node-id=204%3A786&mode=design&t=trxYXXuxEAaEgShk-1

nice nice, 

Working on this now

**Comment by yokwejuste** [comment]
Hi!

I opened a PR for this issue
