### ISSUE TITLE
Fix lag around drafts & projects count and improve design

### ISSUE THREAD

**Issue by yokwejuste** [unstructuredstudio/zubhub#912]
**Describe the bug**
Creation of project and activities has a draft number lag.
**To Reproduce**
Follow the steps below:

1. Go to zubhub 
2. Login
3. Go to activities creation or project creation and you see the `Saved to draft` when you have not yet started using.
4. See error, drafts are not in sync, keeps lagging

**Expected behavior**
Normally it was to show saved to draft after step one is complete. And on step 2 we were to see the draft incrementing

**Screenshots**
![image](https://github.com/unstructuredstudio/zubhub/assets/71908316/08c66076-921a-4568-8a7a-49993dab2f62)
![image](https://github.com/unstructuredstudio/zubhub/assets/71908316/6978a522-61ae-4898-9df9-c0274bf879f3)
![image](https://github.com/unstructuredstudio/zubhub/assets/71908316/144aebd3-2f06-4f48-94b6-6f09a76fa696)

**Comment by srish** [comment]
It would be good to get this fixed! Also, if you could come up with better UI/UX design suggestions for the "My Drafts" and "My Projects" labels, that would be helpful. The number in the bracket looks very odd. You can ask around on Zulip for help with this from designers. :)

**Comment by yokwejuste** [comment]
> It would be good to get this fixed! Also, if you could come up with better UI/UX design suggestions for the "My Drafts" and "My Projects" labels, that would be helpful. The number in the bracket looks very odd. You can ask around on Zulip for help with this from designers. :)

Thanks, doing that now.

**Comment by maureen-oz** [comment]
> > It would be good to get this fixed! Also, if you could come up with better UI/UX design suggestions for the "My Drafts" and "My Projects" labels, that would be helpful. The number in the bracket looks very odd. You can ask around on Zulip for help with this from designers. :)
> 
> Thanks, doing that now.



> It would be good to get this fixed! Also, if you could come up with better UI/UX design suggestions for the "My Drafts" and "My Projects" labels, that would be helpful. The number in the bracket looks very odd. You can ask around on Zulip for help with this from designers. :)

Hi @srish and @yokwejuste  I have started working on the designs ASAP

**Comment by yokwejuste** [comment]
> It would be good to get this fixed! Also, if you could come up with better UI/UX design suggestions for the "My Drafts" and "My Projects" labels, that would be helpful. The number in the bracket looks very odd. You can ask around on Zulip for help with this from designers. :)

So what will be best for now? I want to work on this, so will this be a refactor/redesign or a bug fix?

**Comment by Stephxdesigns** [comment]
Here's what I came up with for the UX/UI

1 I thought that we could completely remove the (0) when there's no draft or project but I think the 0 should be designed to have a disabled state and positioned as seen in the design below

![Screenshot_20231018-090218_1](https://github.com/unstructuredstudio/zubhub/assets/136924367/79619f14-3a9b-4f3c-88c9-c618f75be950)

2 when a user gets a new project or draft, the labels should have an active state which indicates  that a new project have been added to either my drafts or my project.

![Screenshot_20231018-081709_1](https://github.com/unstructuredstudio/zubhub/assets/136924367/f8314476-e06c-42de-aa6e-3dfb7a255bea)


3 When the user has clicked on either my project or my drafts to see the new project added, it goes back to a disabled state with the number of projects displayed. As seen in the design here.

![Screenshot_20231018-090235_1](https://github.com/unstructuredstudio/zubhub/assets/136924367/8b6f86df-4eb7-49bc-be48-41bbf4b35ecb)


@yokwejuste @srish @tuxology 

Let me know what you think.

**Comment by Temabo** [comment]
Hi @srish @tuxology @yokwejuste This is my suggestions for the "My Drafts" and "My Projects" labels;
I made the shape of the number tag look similar to the tags we on zubhub because this can contain more digits and I feel it should be inside the same frame as the "My Drafts" and "My Projects" when either is selected so they don't look disjointed.
![No Projects (3)](https://github.com/unstructuredstudio/zubhub/assets/105416140/2a60e5ab-0e2e-45a6-bdc0-6600526ab1fa)

I also came up with a second iteration with the number in a square
![No Projects (4)](https://github.com/unstructuredstudio/zubhub/assets/105416140/8af34508-2d2b-43d3-8f62-cbd4c4ad79ac)

**Comment by mehreeee** [comment]
Hi @srish @yokwejuste these are my design suggestions.

I also feel the icons used on the side navigation panel should be the same as the icons on the project cards, both for the Drafts and projects to maintain consistency.


![Draft](https://github.com/unstructuredstudio/zubhub/assets/105458062/fa983e74-6a04-449d-a1b4-aeb404448693)

![Draft 2](https://github.com/unstructuredstudio/zubhub/assets/105458062/cb45915f-bfdc-40d6-af5a-eb95adbf00c5)

**Comment by yokwejuste** [comment]
> Hi @srish @yokwejuste these are my design suggestions.
> 
> I also feel the icons used on the side navigation panel should be the same as the icons on the project cards, both for the Drafts and projects to maintain consistency.
> 
> 
> ![Draft](https://github.com/unstructuredstudio/zubhub/assets/105458062/fa983e74-6a04-449d-a1b4-aeb404448693)
> 
> ![Draft 2](https://github.com/unstructuredstudio/zubhub/assets/105458062/cb45915f-bfdc-40d6-af5a-eb95adbf00c5)
> 
> 

Great job, but still to make some things clear on my side, try prototyping with a 4 digits projects/draft number

**Comment by Temabo** [comment]
@yokwejuste Do you mean this?
![Frame 879 (2)](https://github.com/unstructuredstudio/zubhub/assets/105416140/f8603e3f-d356-4d5c-aaf2-ea5181cec403)

**Comment by mehreeee** [comment]
> > Hi @srish @yokwejuste these are my design suggestions.
> > I also feel the icons used on the side navigation panel should be the same as the icons on the project cards, both for the Drafts and projects to maintain consistency.
> > ![Draft](https://github.com/unstructuredstudio/zubhub/assets/105458062/fa983e74-6a04-449d-a1b4-aeb404448693)
> > ![Draft 2](https://github.com/unstructuredstudio/zubhub/assets/105458062/cb45915f-bfdc-40d6-af5a-eb95adbf00c5)
> 
> Great job, but still to make some things clear on my side, try prototyping with a 4 digits projects/draft number

![Draft](https://github.com/unstructuredstudio/zubhub/assets/105458062/b2e47d43-676a-4afd-b386-f6ce1dd7d7b0)

**Comment by mehreeee** [comment]
Here's another exploration. @srish @yokwejuste 

![Draft 3](https://github.com/unstructuredstudio/zubhub/assets/105458062/822fc1da-2699-49aa-a894-004418509b6f)

Instead of using "0" to show that a user has no projects or drafts, the side nav remains the same with no notification alerts. This will reduce cluttering.
 
![Draft 4](https://github.com/unstructuredstudio/zubhub/assets/105458062/bdf65bdc-26ac-45e3-be58-65e4a4ca26d7)

**Comment by DonPresh** [comment]
well done @Stephxdesigns  @Temabo and @mehreeee

**Comment by mehreeee** [comment]
> well done @Stephxdesigns @Temabo and @mehreeee

Thank you!!

**Comment by Temabo** [comment]
Thanks! @DonPresh

**Comment by srish** [comment]
@mehreeee Thank you! Let's go with the third screenshot in here https://github.com/unstructuredstudio/zubhub/issues/912#issuecomment-1767911941

![Screenshot 2023-10-18 at 6 51 51 PM](https://github.com/unstructuredstudio/zubhub/assets/288353/a40fcfe2-62b9-4a4f-833f-a5a872f7f89d)

**Comment by yokwejuste** [comment]
> @mehreeee Thank you! Let's go with the third screenshot in here https://github.com/unstructuredstudio/zubhub/issues/912#issuecomment-1767911941
> 
> ![Screenshot 2023-10-18 at 6 51 51 PM](https://github.com/unstructuredstudio/zubhub/assets/288353/a40fcfe2-62b9-4a4f-833f-a5a872f7f89d)
> 

Great!

Working on that now.

**Comment by mehreeee** [comment]
> Here's another exploration. @srish @yokwejuste
> 
> ![Draft 3](https://user-images.githubusercontent.com/105458062/276171124-822fc1da-2699-49aa-a894-004418509b6f.png)
> 
> Instead of using "0" to show that a user has no projects or drafts, the side nav remains the same with no notification alerts. This will reduce cluttering.
> 
> ![Draft 4](https://user-images.githubusercontent.com/105458062/276212397-bdf65bdc-26ac-45e3-be58-65e4a4ca26d7.png)

@yokwejuste

**Comment by yokwejuste** [comment]
> > Here's another exploration. @srish @yokwejuste
> > ![Draft 3](https://user-images.githubusercontent.com/105458062/276171124-822fc1da-2699-49aa-a894-004418509b6f.png)
> > Instead of using "0" to show that a user has no projects or drafts, the side nav remains the same with no notification alerts. This will reduce cluttering.
> > ![Draft 4](https://user-images.githubusercontent.com/105458062/276212397-bdf65bdc-26ac-45e3-be58-65e4a4ca26d7.png)
> 
> @yokwejuste

Got it!!!

I updated the PR
