### ISSUE TITLE
 Improve login error message visibility and specificity

### ISSUE THREAD

**Issue by ladyami** [unstructuredstudio/zubhub#919]
**Describe the bug**
Currently, when a user attempts to log in with an incorrect username or password or non-signup user credentials, the error message displayed is "Unable to login with provided credentials."

Issues:

Poor Visibility: The yellow text on the light pink background makes the error message difficult to read.

Non-Specific Message: The generic message doesn't pinpoint the error source (username, password or no such user).

**To Reproduce**

1. Go to 'zubhub'
2. Click on the 'login button'
3. Login with wrong credentials 

**Expected behavior**
The error message should be clearly visible, easily readable, and provide specific information to help users identify and rectify the login error.

Solutions:

Improve Visibility:

-Use a contrasting color for the error message text (red background).
-Increase the error message text size.
 -Using a bold font weight for the error message text.

Enhance Specificity:

-Replace the generic error message with a more specific one indicating the type of error 

**Screenshots**

![Screenshot (338)](https://github.com/unstructuredstudio/zubhub/assets/99187115/ae171e74-21f4-4d75-a5ce-af82f2a9eb92)

**Comment by brrkrmn** [comment]
great catch @ladyami! The same structure is also seen in edit profile's delete dialog. I can fix the specificity issue and redesign the message box. I think we can go with the existing red color from our theme

**Comment by ladyami** [comment]
@brrkrmn i was  about to message in the chat room, No Need for UI redesign right?

**Comment by brrkrmn** [comment]
@ladyami I think you can create one because I do not know what will it look like with the current width. In the edit profile/delete dialog, the width of the box is too much. 
If we agree that the only changes will be 
- bold and white text,
- red background
- text content

it may not be necessary but I still, I think it would be great to see the design, it's your call ☺️

**Comment by ladyami** [comment]
@brrkrmn I am talking about the login error message ui, 
the profile dialog I think a lot of designers had provided a UI design for it right?

**Comment by brrkrmn** [comment]
@ladyami oh okay I thought the delete profile dialog does not have one. Okay then I can start implementing no problem

**Comment by ladyami** [comment]
@brrkrmn The error ui can be fixed with  bold text, red background / maybe white text, the message specification will be code logic thank you for your cooperation

**Comment by ladyami** [comment]
And i went to see delete profile this is what it look like
![Screenshot (345)](https://github.com/unstructuredstudio/zubhub/assets/99187115/8d7737bc-5955-466a-8f94-1aee0b9338c2)

**Comment by brrkrmn** [comment]
@ladyami yes and when you empty the fields and click on delete, you'll see the error

**Comment by brrkrmn** [comment]
@ladyami which one do you think looks better?

![Screenshot 2023-10-18 at 17 44 16](https://github.com/unstructuredstudio/zubhub/assets/92817363/bd335039-dd2b-4c92-9b48-64ff0a3418eb)

![Screenshot 2023-10-18 at 17 46 46](https://github.com/unstructuredstudio/zubhub/assets/92817363/9353b0ce-80b1-493a-92c5-30d6838775b5)

I think applying the red from theme makes the error-box too strong in the first one 🤔 Should we make some changes to the style?

**Comment by ladyami** [comment]
@brrkrmn The first one looks too strong & like a button the second one doesn't look like an error 
It should look like a label
![Slide 4_3 - 5](https://github.com/unstructuredstudio/zubhub/assets/99187115/ca9242d3-72d3-47b7-bb37-c491712b316c)

how about Something like this

**Comment by Temabo** [comment]
@brrkrmn @ladyami 
You can also add an info or alert icon to communicate the information better. Something like this
![image](https://github.com/unstructuredstudio/zubhub/assets/105416140/08ecd705-91f0-4dd8-a8f2-8b3cf8804801)

**Comment by ladyami** [comment]
@Temabo nice suggestions okay which of the UI is better ?

**Comment by Temabo** [comment]
> @Temabo nice suggestions okay which of the UI is better ?

I'm leaning towards the second one @brrkrmn suggested (outline),if an icon is added I think it'd look like an error message, what do you think? We may need to design it to see it clearly @ladyami

**Comment by d-arkangel** [comment]
> @ladyami which one do you think looks better?
> 
> ![Screenshot 2023-10-18 at 17 44 16](https://user-images.githubusercontent.com/92817363/276297327-bd335039-dd2b-4c92-9b48-64ff0a3418eb.png)
> 
> ![Screenshot 2023-10-18 at 17 46 46](https://user-images.githubusercontent.com/92817363/276297333-9353b0ce-80b1-493a-92c5-30d6838775b5.png)
> 
> I think applying the red from theme makes the error-box too strong in the first one 🤔 Should we make some changes to the style?

I would suggest the second option. It looks better and easily readable. The contrast between the text and background is high enough to let the user spot and focus more on the error message. Adding the caution icon beside it as suggested by @Temabo, in red colour too, should complete it.

My two cents.

**Comment by d-arkangel** [comment]
And I think all error messages should carry the same format across board - Red text, red outline, red icon.

**Comment by ladyami** [comment]
Something like this right @Temabo & @d-arkangle 

![Slide 4_3 - 5 (1)](https://github.com/unstructuredstudio/zubhub/assets/99187115/439567aa-d351-447f-9622-34b01aaa74f9)

**Comment by d-arkangel** [comment]
> Something like this right @Temabo & @d-arkangle
> 
> ![Slide 4_3 - 5 (1)](https://user-images.githubusercontent.com/99187115/276319559-439567aa-d351-447f-9622-34b01aaa74f9.png)

Yeah, but more like with a red text too. Can you make the text red as well?

**Comment by ladyami** [comment]
> And I think all error messages should carry the same format across board - Red text, red outline, red icon.

that means we have to test error to see what they look like

**Comment by ladyami** [comment]
> > Something like this right @Temabo & @d-arkangle
> > ![Slide 4_3 - 5 (1)](https://user-images.githubusercontent.com/99187115/276319559-439567aa-d351-447f-9622-34b01aaa74f9.png)
> 
> Yeah, but more like with a red text too. Can you make the text red as well?

![Slide 4_3 - 5 (2)](https://github.com/unstructuredstudio/zubhub/assets/99187115/107e5e59-d220-4066-bb9e-461f1e27bace)

I think This look good

**Comment by d-arkangel** [comment]
Yeah. Currently, this is what errors look like:
![image](https://github.com/unstructuredstudio/zubhub/assets/146884658/4cea3a75-fdb8-4748-88fe-135efe50b785)

**Comment by d-arkangel** [comment]
You could use this as a guide for consistency. Light stroke, maybe 1 unit, add the icon too with 1 unit stroke as well, and the text Raleway typeface (regular)

That's from my observation, though.

**Comment by ladyami** [comment]
This should work 
![Slide 4_3 - 5 (3)](https://github.com/unstructuredstudio/zubhub/assets/99187115/17004162-9cc0-40d5-ad13-5774bd335057)

**Comment by d-arkangel** [comment]
> This should work ![Slide 4_3 - 5 (3)](https://user-images.githubusercontent.com/99187115/276322193-17004162-9cc0-40d5-ad13-5774bd335057.png)

Looks better. What are your thoughts @Temabo?

**Comment by ladyami** [comment]
@brrkrmn what do you think

**Comment by DonPresh** [comment]
I think I raised this issue here #816

**Comment by brrkrmn** [comment]
> This should work 
> 
> ![Slide 4_3 - 5 (3)](https://github.com/unstructuredstudio/zubhub/assets/99187115/17004162-9cc0-40d5-ad13-5774bd335057)
> 
> 

Oh I really like this one

**Comment by ladyami** [comment]
> I think I raised this issue here #816

Is not 100% similar yours is a collection of UI accessibility improvements while this needs this contain an error message specification which can only be fixed in the code base, I got this error when I was trying to log in and the error message is not clear what went wrong

**Comment by ladyami** [comment]
> > This should work
> > ![Slide 4_3 - 5 (3)](https://github.com/unstructuredstudio/zubhub/assets/99187115/17004162-9cc0-40d5-ad13-5774bd335057)
> 
> Oh I really like this one

okay when you make a pull request it will close this and solve one of issue mentioned in the issue raised by @DonPresh

**Comment by Temabo** [comment]
> This should work ![Slide 4_3 - 5 (3)](https://user-images.githubusercontent.com/99187115/276322193-17004162-9cc0-40d5-ad13-5774bd335057.png)

This looks good to me! @ladyami

**Comment by aqsaaqeel** [comment]
> @ladyami which one do you think looks better?
> 
> ![Screenshot 2023-10-18 at 17 44 16](https://user-images.githubusercontent.com/92817363/276297327-bd335039-dd2b-4c92-9b48-64ff0a3418eb.png)
> 
> ![Screenshot 2023-10-18 at 17 46 46](https://user-images.githubusercontent.com/92817363/276297333-9353b0ce-80b1-493a-92c5-30d6838775b5.png)
> 
> I think applying the red from theme makes the error-box too strong in the first one 🤔 Should we make some changes to the style?

imo, the second one looks better

**Comment by srish** [comment]
I think this should wait till we decide on error page design #789. We might want to have some consistency with error messages similar to error pages.

**Comment by brrkrmn** [comment]
@srish sure!

**Comment by Boluwatifey1** [comment]
Certainly, here's your feedback rephrased for clarity:

"Hello @srish and @tuxology,

I understand that we're still in the process of deciding on the error page design, but I'd like to point out an observation. When a user forgets their password and attempts to reset it by inputting an invalid email and pressing enter, two error messages appear simultaneously. The first message reads 'umm, the email seems invalid,' and the second one is 'Enter a valid email.'
I would recommend sticking with a single error message. Having two simultaneous messages might potentially confuse our users."
this is what it looks like  on the website
![invalid email](https://github.com/unstructuredstudio/zubhub/assets/127180289/9763b324-5cc1-43d9-bffe-b1bf9d1c430d)
 this is what I proposed 
![Password reset (1)](https://github.com/unstructuredstudio/zubhub/assets/127180289/828a7a88-1e0d-4c56-8b91-82bec3dbde33)

I don't know how to screen record, I would have shown you the behavior when you put an invalid mail

**Comment by srish** [comment]
To be revisited as part of larger error design improvements. Thanks for all your suggestions on this task!
