### ISSUE TITLE
Redesign User profile

### ISSUE THREAD

**Issue by Boluwatifey1** [unstructuredstudio/zubhub#923]
Enhancing the Appeal of Other User Profiles

Accessing Zubhub's User Profiles:
Begin by visiting the Zubhub website and logging into your account.

Exploring User Profiles:
Next, navigate to the user profiles section by selecting any user profile card that piques your interest.

Viewing User Profiles:
When you click on a user profile card, the respective user profile will be displayed, offering you the opportunity to evaluate and improve its design.

Identifying the Issues:

Upon closer examination, several issues with the user profile design become apparent:

Inadequate Button Responsiveness:
The responsive buttons on the profile do not effectively communicate their interactive nature. This makes it difficult for users to recognize and utilize them for various actions.

Text Elements Misleading as Buttons:
Some text elements on the user profile mimic the appearance of buttons, which can be confusing for users. It's essential to differentiate these text elements from actual interactive buttons.

Misleading Badges:
Additionally, the badges on the profile exhibit the appearance of interactive elements, potentially causing user confusion. These badges need to be transformed to convey information more effectively.

Implementing Solutions:

To address these issues and enhance the user profile experience, the following solutions have been implemented:

Revamped Responsive Buttons:

Responsive buttons have been given colors to make them stand out prominently on the user profile.
Adequate padding has been introduced to enhance their touch-friendliness, ensuring users can easily click on them.
The responsive buttons are now designed in a manner that clearly indicates their interactive functionality. For example, the "Follow" button is now visually prominent and easily recognizable.

Clear Differentiation for Text Elements:

Text elements that are non-interactive have been modified to eliminate any button-like appearance. This involves changing buttons to plain text to distinguish them clearly from interactive buttons. For example, the **Creator/ Staff button**
Badge Transformation:

To rectify the misleading nature of badges, an interim solution has been implemented. Badges have been replaced with a list format, which serves to convey information effectively. This will remain in place until icons can be integrated to enhance the user profile design further.

This is how it looks on the website:
![new zubhub](https://github.com/unstructuredstudio/zubhub/assets/127180289/158bafe0-1307-4c14-84b2-f2a481f2d1b3)

 Also in the comment section, I added a feature that allows you to like people's comments,  which I believe has the potential to significantly increase user interactions and engagement. I have also taken the initiative to remove an icon from the comment field that was causing confusion due to its lack of clarity regarding its purpose.

This is what it looks like on the website:
![new zub](https://github.com/unstructuredstudio/zubhub/assets/127180289/bd6f5bc4-5014-4387-8ac7-46ba2a2f8119)
@srish @tuxology This is my proposed design

** Proposed Design**
![user profile (3)](https://github.com/unstructuredstudio/zubhub/assets/127180289/33a6560d-a3c2-46a8-8fdf-49e64800f5e1)

I look forward to your valuable insights and feedback on this proposed design. Your expertise and guidance are essential as we strive to create a more interactive and user-friendly platform for our community. Thank you in advance for your time and input

**Comment by aqsaaqeel** [comment]
hey @Boluwatifey1 have you taken a look at #917 We can make the tags similar to that!

**Comment by Boluwatifey1** [comment]
> hey @Boluwatifey1 have you taken a look at #917 We can make the tags similar to that!

You mean for the badges right? Instead of being in a bulleted list?

**Comment by Boluwatifey1** [comment]
hi @aqsaaqeel do you mean this way?:
![user profile (4)](https://github.com/unstructuredstudio/zubhub/assets/127180289/4df76fe2-559f-492a-961e-331bddc0a2dd)
 I have made the labels a tag

**Comment by aqsaaqeel** [comment]
> hi @aqsaaqeel do you mean this way?:
> 
> ![user profile (4)](https://github.com/unstructuredstudio/zubhub/assets/127180289/4df76fe2-559f-492a-961e-331bddc0a2dd)
> 
>  I have made the labels a tag

Similar to this, but placed horizontally because they take up a lot of space when stacked in a list

**Comment by Boluwatifey1** [comment]
this way then? @aqsaaqeel 
![user profile (5)](https://github.com/unstructuredstudio/zubhub/assets/127180289/e39d018d-6445-46dc-8932-0cfdc9b2ccb9)

**Comment by d-arkangel** [comment]
If I may, rather than use texts for the badges, why don't we substitute texts for icons instead? That way, there will be more optimization of real estate and space. For instance, this is an idea:
![image](https://github.com/unstructuredstudio/zubhub/assets/146884658/0b91557c-c5d7-47aa-b472-cfa5d6081ccf)

The icons could be set to reveal the title of the badge when hovered over like this:

https://github.com/unstructuredstudio/zubhub/assets/146884658/371f144a-afa5-40fc-9f4c-70f7a15179f2

What are your thoughts on this? @Boluwatifey1 @srish @tuxology

**Comment by Boluwatifey1** [comment]
> If I may, rather than use texts for the badges, why don't we substitute texts for icons instead? That way, there will be more optimization of real estate and space. For instance, this is an idea: ![image](https://user-images.githubusercontent.com/146884658/276893326-0b91557c-c5d7-47aa-b472-cfa5d6081ccf.png)
> 
> The icons could be set to reveal the title of the badge when hovered over like this:
> 
>  Page.44.-.ZubHub.Copy.-.Figma.2023-10-20.11-08-26.mp4 
> 
> What are your thoughts on this? @Boluwatifey1 @srish @tuxology

Yes check #642 for this ideas, I just made them labels pending the time that dev would work on the badges

**Comment by srish** [comment]
@Boluwatifey1 Thanks for your valuable suggestions! Right now, our focus is to attain the basic features complete stage. Even though these are all nice suggestions, they seem too broad and have to do with improving the design & user experience of existing features. We are far from the stage with ZubHub that we can think about enhancements right now.
