### ISSUE TITLE
Redirecting to login page when trying to view or edit a project

### ISSUE THREAD

**Issue by aqsaaqeel** [unstructuredstudio/zubhub#929]
**Description**
When I tried to view one of the public projects it redirected me to login page.

https://github.com/unstructuredstudio/zubhub/assets/85514520/44752f29-7601-4bd3-a87a-8ea4dd5da5d1

The same happened when I was creating a project. My projects got created but when I try to edit or delete them, I am getting redirected. 
And now my test project is on the main dashboard. And I am not allowed to delete it. This isn't just an issue with user flow but barring users from accessing anything on the website.
We should fix it on high priority.

![Screenshot from 2023-10-20 04-03-22](https://github.com/unstructuredstudio/zubhub/assets/85514520/f5855189-4fad-4889-a963-e4dd12a222f5)

**To Reproduce**

1. Go to ['zubhub.unstructured.studio/projects'](https://zubhub.unstructured.studio/projects)
2. Click on any project card.
3. It will show the login page even if a user is signed in.
4. Even after login, access is restricted.

**Expected behavior**
I want to be able to view and comment on public projects. As well as being able to edit/delete the projects I created.

**Comment by coderatomy** [comment]
Nice. When this is approved. Take in use of the `ProtectedRoute` component. Example [here](https://github.com/unstructuredstudio/zubhub/pull/885/files#diff-6e7ce2e46d1a671027f9a73a7d3218193ddd84d454f2d1c921746ac69248731aR453)

**Comment by aqsaaqeel** [comment]
Fixed by #927

**Comment by coderatomy** [comment]
Ohh! I think I read stuff my way at first 😂. I was wondering why you closed this. Now I see. Thanks @aqsaaqeel
