### ISSUE TITLE
Usabilty and UX improvement

### ISSUE THREAD

**Issue by Mitchell377** [unstructuredstudio/zubhub#930]
### **Describe** the the feature request**
going through the home page of the website i noticed that right above the footer theres no button with a text link that will take the user all the way to the top of the page, as a user you will have to scroll all the way to the to the top which does not make it seamless, 

![Screenshot 2023-10-20 at 02-55-40 Zubhub](https://github.com/unstructuredstudio/zubhub/assets/102149002/a26df7e9-9611-4f0d-8d5d-1d293e42e1d4)

**MY PROPOSITION**
1, A button with a text link feature should be added which will the user the stress of scrolling all the way up which could be tiring 

**THE IMPROVEMENT I DID**
i designed a text element as a button 
below is the screenshoot of the UX improvement i made on the design

![home - with notifications_unstructuredstudio](https://github.com/unstructuredstudio/zubhub/assets/102149002/c74506ce-6723-4628-b98f-2a91c77da743)

i also prototyped it as well here is the video, it shows how it will look like once it has been implemented

https://www.figma.com/proto/AhdeEFRzmqJVHJgbboHrtt/ADORABLE-DESIGNS?page-id=1578%3A2&type=design&node-id=1610-207&viewport=-579%2C-2271%2C0.41&t=CmpBXQh2BIEpB2rB-1&scaling=min-zoom&starting-point-node-id=1610%3A207&mode=design

design ideals and suggestions are higly welcome on this issue

@srish @tuxology  i will love to get your feedback on this please

**Comment by Boluwatifey1** [comment]
> ### **Describe** the the feature request**
> going through the home page of the website i noticed that right above the footer theres no button with a text link that will take the user all the way to the top of the page, as a user you will have to scroll all the way to the to the top which does not make it seamless,
> 
> ![Screenshot 2023-10-20 at 02-55-40 Zubhub](https://user-images.githubusercontent.com/102149002/276812816-a26df7e9-9611-4f0d-8d5d-1d293e42e1d4.png)
> 
> **MY PROPOSITION** 1, A button with a text link feature should be added which will the user the stress of scrolling all the way up which could be tiring
> 
> **THE IMPROVEMENT I DID** i designed a text element as a button below is the screenshoot of the UX improvement i made on the design
> 
> ![home - with notifications_unstructuredstudio](https://user-images.githubusercontent.com/102149002/276817330-c74506ce-6723-4628-b98f-2a91c77da743.png)
> 
> i also prototyped it as well here is the video, it shows how it will look like once it has been implemented
> 
> https://www.figma.com/proto/AhdeEFRzmqJVHJgbboHrtt/ADORABLE-DESIGNS?page-id=1578%3A2&type=design&node-id=1610-207&viewport=-579%2C-2271%2C0.41&t=CmpBXQh2BIEpB2rB-1&scaling=min-zoom&starting-point-node-id=1610%3A207&mode=design
> 
> design ideals and suggestions are higly welcome on this issue
> 
> @srish @tuxology i will love to get your feedback on this please

Hi Michelle I think that’s what’s the small red arrow icon is for,even though it’s not functioning properly, I think the developers are working on it.you can ask @aqsaaqeel

**Comment by aqsaaqeel** [comment]
Yup, the 'back to top' button already exists. like @Boluwatifey1  mentioned

**Comment by srish** [comment]
Too broad and not needed right now! Thanks for taking the time to create this.
