### ISSUE TITLE
Miscellaneous issues introduced via header and navbar changes

### ISSUE THREAD

**Issue by aqsaaqeel** [unstructuredstudio/zubhub#934]
After recent merges and changes to the navbar and hero elements via https://github.com/unstructuredstudio/zubhub/pull/883 and #946  (which we overlooked), we have an alignment issue with the navbar and main hero element in addition to various other issues (button size, font size. avatar color etc)

<img width="1451" alt="image" src="https://github.com/unstructuredstudio/zubhub/assets/3373857/125ee455-df3a-442d-a4c9-41e5d538cbe9"> 

Following sub-tasks are identified to be fixed:

- [x] The navbar root should not be 100% width - it should be in centre as it was before
- [x] Hero elements should be contained in a container which should follow navbar width and elements inside it should follow consistent responsiveness
- [x] Header does not show image on mobile screen. 
- [x] Heights of Featured Projects heading does not match other headings
- [x] Varied Buttons sizes (particular "login to view more" should be fixed and made uniform)
- [x] Avatar color in non logged-in navbar should be reverted back to what it was before

**Comment by d-arkangel** [comment]
> **Description**
> 
> 1. Header does not show image on mobile screen.
> 2. Heights of Featured Projects heading does not match other headings
> 3. Varied Buttons sizes

Hello. On which section are you referring to? The landing page or some other section? @aqsaaqeel

**Comment by aqsaaqeel** [comment]
> > **Description**
> > 
> > 1. Header does not show image on mobile screen.
> > 2. Heights of Featured Projects heading does not match other headings
> > 3. Varied Buttons sizes
> 
> Hello. On which section are you referring to? The landing page or some other section? @aqsaaqeel

This is for the landing page. And it's fixed now

**Comment by aqsaaqeel** [comment]
@srish I think we mistakenly closed PR #936 thinking it to be a duplicate issue for this ☝🏾 one. Can you re-open it as I am working on the additional tasks here?

**Comment by tuxology** [comment]
@aqsaaqeel One more task has been added to this which introduces a new issue after merging #946 - in non logged in mode, the   default avatar should be as it was before: 
<img width="246" alt="image" src="https://github.com/unstructuredstudio/zubhub/assets/3373857/d08a479b-4623-41e4-a962-6535d102a787">
