### ISSUE TITLE
Missing an "Other" button/description for an element not listed

### ISSUE THREAD

**Issue by d-arkangel** [unstructuredstudio/zubhub#950]
**Describe the the feature request**
In certain sections of the site when creating a project, it is possible that the correct description/feature of the new project is not available on the list of descriptions provided. This poses an issue where the user has to randomly select what is available or close enough. For instance, in the screenshot below, it is required to tag what category a project belongs to.
![image](https://github.com/unstructuredstudio/zubhub/assets/146884658/102d23e6-1d51-4459-8ceb-69edf949614f)
What then happens if none of these listed categories best describe the project? The user may be forced to select **"None"** or any of the listed ones. Selecting **"None"** may look like a solution now but when sorting list of projects by categories, I do not think it would be wise to have an instance where we sort the list of projects by selecting **"None".** Also, **"None"** should probably not be added to a list of available categories because you cannot make a project and say it does not belong to any category. At least, there should be a category it belongs to if it really is a thing.

The same issue goes for the _**"What hashtag best describes your project?"**_ section when creating a project.

Suggestion:
An **"Other"** description could be added to the list so the user can select that and specify the unique description instead of selecting "None" or a wrong description. For example, this is a flow of the suggestion:
![image](https://github.com/unstructuredstudio/zubhub/assets/146884658/ffe79825-4892-452b-a4b0-36ce8bc21ff6)
![image](https://github.com/unstructuredstudio/zubhub/assets/146884658/5650a828-a549-4c1c-b2df-0ba2a7840439)
 Then, the next flow could either register this unique description as **"Other"**, just like this:
![image](https://github.com/unstructuredstudio/zubhub/assets/146884658/339305da-95fd-4634-9238-fd72a516c366)
or simply create a new category using the unique description like this:
![image](https://github.com/unstructuredstudio/zubhub/assets/146884658/a7ac1eb4-fdc3-4e23-bf1c-4f0178d44b8d)

**Comment by mehreeee** [comment]
Nice suggestion

**Comment by d-arkangel** [comment]
> Nice suggestion

Thanks, @mehreeee

**Comment by srish** [comment]
We talked about this in another issue and decided to not have that option for now.
