### ISSUE TITLE
Misaligned notification/sign-in bubbles for creators and visitors alike

### ISSUE THREAD

**Issue by d-arkangel** [unstructuredstudio/zubhub#951]
**The bug**
When a visitor/creator clicks on the notification icon, the bubble is completely misaligned and even shoots out of the page. 
Here is a screenshot showing the issue for visitors not logged in:
![image](https://github.com/unstructuredstudio/zubhub/assets/146884658/867e2403-646d-4b52-957e-4e5991db2bc0)

![image](https://github.com/unstructuredstudio/zubhub/assets/146884658/a78cfdc9-9d36-457b-9752-d27508067438)

And for the creators logged in:

https://github.com/unstructuredstudio/zubhub/assets/146884658/f3c551ab-44ef-4121-ab17-a2639c26382e

**A suggested solution**
The tip of the bubbles should be adjusted so that it appears directly under the icon itself. Here is an example:
![image](https://github.com/unstructuredstudio/zubhub/assets/146884658/2138588c-8eb4-4956-a0fb-eae9a6566a10)

I believe this is a minor issue, though.

**Comment by srish** [comment]
It is really minor closing for now as can be part of a major design overhaul

**Comment by d-arkangel** [comment]
> It is really minor closing for now as can be part of a major design overhaul

You are right. Thank you, @srish.
