### ISSUE TITLE
Project image is stretched out of proportion

### ISSUE THREAD

**Issue by d-arkangel** [unstructuredstudio/zubhub#952]
**Describe the bug**
The project cover image gets stretched out of the correct proportion, distorting the image dimensions. This can give a bad impression.

**To Reproduce**

1. Login
2. Click on any of your created project.
3. See error

![image](https://github.com/unstructuredstudio/zubhub/assets/146884658/b62dc027-a18e-45c8-b16b-a6f835c3d388)

**Expected behavior**
The cover image should not be stretched . A suggested solution would be to set the cover image to "cover" or "contain" rather than "fill". This should maintain the correct aspect ratio while filling the space provided for the image

**Screenshots**
When set to "contain":
![image](https://github.com/unstructuredstudio/zubhub/assets/146884658/79358132-da99-4387-a009-0b89ade7db39)

When set to "fill":
![image](https://github.com/unstructuredstudio/zubhub/assets/146884658/b071aee9-0269-4321-bd4c-da611a269b3e)

I believe that with this, the display of projects will be rather appealing and maintain the dignity of the project.

**Comment by mehreeee** [comment]
I think this is a dev issue. They can correct it from their codes @yokwejuste

**Comment by d-arkangel** [comment]
> I think this is a dev issue. They can correct it from their codes @yokwejuste

Yes, I think so. A developer can probably adjust it.
I call on @aqsaaqeel 🙂

**Comment by brrkrmn** [comment]
Hey @d-arkangel @mehreeee , I have changed the styles for this issue. In the final version, here are different image sizes according to your suggestions, what do you think?
![Screenshot 2023-10-25 at 13 25 49](https://github.com/unstructuredstudio/zubhub/assets/92817363/9f4f2a9b-4de0-46ad-bb19-6f27e8d85b00)
![Screenshot 2023-10-25 at 13 25 59](https://github.com/unstructuredstudio/zubhub/assets/92817363/b89ca67e-bd1b-4da9-b70c-58cfced2baac)
![Screenshot 2023-10-25 at 13 26 55](https://github.com/unstructuredstudio/zubhub/assets/92817363/d8f78799-529f-4305-bf24-aa206c0323fa)
![Screenshot 2023-10-25 at 13 27 08](https://github.com/unstructuredstudio/zubhub/assets/92817363/6990f8b4-e8d1-420b-80ef-720f16be67c2)

**Comment by maureen-oz** [comment]
@brrkrmn Great job 👏 .
What about giving the user the ability to position the image the way they want?  I believe this will give them more control and a sense of ownership over their projects. 
You can check this addition I designed.

The user can select from the options fill, fit, and crop.
<img width="410" alt="fill" src="https://github.com/unstructuredstudio/zubhub/assets/106209979/d180ec35-5873-4dfa-8ed6-822a4550bc67">

If the user selects crop, the image can be dragged to the desired size.
<img width="410" alt="crop" src="https://github.com/unstructuredstudio/zubhub/assets/106209979/53449c3d-ff92-4f6d-b4b6-ce9d3d5abe86">

@srish what do you think too?

**Comment by mehreeee** [comment]
> Hey @d-arkangel @mehreeee , I have changed the styles for this issue. In the final version, here are different image sizes according to your suggestions, what do you think?
> ![Screenshot 2023-10-25 at 13 25 49](https://user-images.githubusercontent.com/92817363/277965436-9f4f2a9b-4de0-46ad-bb19-6f27e8d85b00.png)
> ![Screenshot 2023-10-25 at 13 25 59](https://user-images.githubusercontent.com/92817363/277965430-b89ca67e-bd1b-4da9-b70c-58cfced2baac.png)
> ![Screenshot 2023-10-25 at 13 26 55](https://user-images.githubusercontent.com/92817363/277965420-d8f78799-529f-4305-bf24-aa206c0323fa.png)
> ![Screenshot 2023-10-25 at 13 27 08](https://user-images.githubusercontent.com/92817363/277965446-6990f8b4-e8d1-420b-80ef-720f16be67c2.png)

I think the object fit property should be set to cover. That should take care of it. If you set it to fill, some images might still be stretched.

**Comment by d-arkangel** [comment]
> > Hey @d-arkangel @mehreeee , I have changed the styles for this issue. In the final version, here are different image sizes according to your suggestions, what do you think?
> > ![Screenshot 2023-10-25 at 13 25 49](https://user-images.githubusercontent.com/92817363/277965436-9f4f2a9b-4de0-46ad-bb19-6f27e8d85b00.png)
> > ![Screenshot 2023-10-25 at 13 25 59](https://user-images.githubusercontent.com/92817363/277965430-b89ca67e-bd1b-4da9-b70c-58cfced2baac.png)
> > ![Screenshot 2023-10-25 at 13 26 55](https://user-images.githubusercontent.com/92817363/277965420-d8f78799-529f-4305-bf24-aa206c0323fa.png)
> > ![Screenshot 2023-10-25 at 13 27 08](https://user-images.githubusercontent.com/92817363/277965446-6990f8b4-e8d1-420b-80ef-720f16be67c2.png)
> 
> I think the object fit property should be set to cover. That should take care of it. If you set it to fill, some images might still be stretched.

Yes, "Contain" looks like a better option. Also, I think all project creators will probably have to try making the cover photo of their projects something close to the aspect ratio of the container on Zubhub. It should make things easier.

**Comment by mehreeee** [comment]
> > > Hey @d-arkangel @mehreeee , I have changed the styles for this issue. In the final version, here are different image sizes according to your suggestions, what do you think?
> > > ![Screenshot 2023-10-25 at 13 25 49](https://user-images.githubusercontent.com/92817363/277965436-9f4f2a9b-4de0-46ad-bb19-6f27e8d85b00.png)
> > > ![Screenshot 2023-10-25 at 13 25 59](https://user-images.githubusercontent.com/92817363/277965430-b89ca67e-bd1b-4da9-b70c-58cfced2baac.png)
> > > ![Screenshot 2023-10-25 at 13 26 55](https://user-images.githubusercontent.com/92817363/277965420-d8f78799-529f-4305-bf24-aa206c0323fa.png)
> > > ![Screenshot 2023-10-25 at 13 27 08](https://user-images.githubusercontent.com/92817363/277965446-6990f8b4-e8d1-420b-80ef-720f16be67c2.png)
> > 
> > 
> > I think the object fit property should be set to cover. That should take care of it. If you set it to fill, some images might still be stretched.
> 
> Yes, "Contain" looks like a better option. Also, I think all project creators will probably have to try making the cover photo of their projects something close to the aspect ratio of the container on Zubhub. It should make things easier.

Nah creators shouldn’t concern themselves with the aspect ratio, the dev should take care of that and make the object fit property of all images fixed so that images uploaded  be scaled according to the website’s image property.

**Comment by d-arkangel** [comment]
> > > > Hey @d-arkangel @mehreeee , I have changed the styles for this issue. In the final version, here are different image sizes according to your suggestions, what do you think?
> > > > ![Screenshot 2023-10-25 at 13 25 49](https://user-images.githubusercontent.com/92817363/277965436-9f4f2a9b-4de0-46ad-bb19-6f27e8d85b00.png)
> > > > ![Screenshot 2023-10-25 at 13 25 59](https://user-images.githubusercontent.com/92817363/277965430-b89ca67e-bd1b-4da9-b70c-58cfced2baac.png)
> > > > ![Screenshot 2023-10-25 at 13 26 55](https://user-images.githubusercontent.com/92817363/277965420-d8f78799-529f-4305-bf24-aa206c0323fa.png)
> > > > ![Screenshot 2023-10-25 at 13 27 08](https://user-images.githubusercontent.com/92817363/277965446-6990f8b4-e8d1-420b-80ef-720f16be67c2.png)
> > > 
> > > 
> > > I think the object fit property should be set to cover. That should take care of it. If you set it to fill, some images might still be stretched.
> > 
> > 
> > Yes, "Contain" looks like a better option. Also, I think all project creators will probably have to try making the cover photo of their projects something close to the aspect ratio of the container on Zubhub. It should make things easier.
> 
> Nah creators shouldn’t concern themselves with the aspect ratio, the dev should take care of that and make the object fit property of all images fixed so that images uploaded be scaled according to the website’s image property.

Yeah I get what you're saying. Maybe I should explain better what I meant by the previous statement, using an image like this: 
![image](https://github.com/unstructuredstudio/zubhub/assets/146884658/4226404d-5699-40d8-ae7a-0d03e37fec6e)
It is almost panoramic in dimension. That might not turn out looking suitable when used as a cover image once its fitting is set to "cover" in the container. A lot of useful part of the picture might be cropped out of view and no one would know except the creator, of course.

So, maybe the creators knowing in advance what kind of image would be very suitable could be a useful information.

**Comment by maureen-oz** [comment]
Yeah that's why I proposed this @d-arkangel https://github.com/unstructuredstudio/zubhub/issues/952#issuecomment-1779198054
It would help the creators to preview the images and make adjustments as they see fit.

**Comment by d-arkangel** [comment]
> Yeah that's why I proposed this @d-arkangel [#952 (comment)](https://github.com/unstructuredstudio/zubhub/issues/952#issuecomment-1779198054) It would help the creators to preview the images and make adjustments as they see fit.
It is a fine thing too although, I do not know if this wouldn't make it a bit cumbersome. I may be wrong, though.

**Comment by brrkrmn** [comment]
@maureen-oz, regarding [your comment](https://github.com/unstructuredstudio/zubhub/issues/952#issuecomment-1779198054), I like the idea of allowing the user to select the mode, but let's get @srish's comments on this one 

@mehreeee about [this comment](https://github.com/unstructuredstudio/zubhub/issues/952#issuecomment-1779216996), right now it is set to cover, some images that I provided may look stretchy but it's their original appearance, maybe they look a bit distorted 😅

thank you all for your contributions. I do not think the users would upload an almost panoramic image like the one I shared. I believe they will mostly use the images they took on their phones, which would fit in the container that we currently have. However, accounting for each image size and applying styles accordingly would be the safe way to ensure better user experience

**Comment by maureen-oz** [comment]
Awesome.
Forgot to include this with what I sent earlier. The creators only need to click this edit button to edit the image.
![crop (1)](https://github.com/unstructuredstudio/zubhub/assets/106209979/0f758cac-a29a-45c1-b7e2-7200681c8218)

**Comment by mehreeee** [comment]
> Awesome.
> Forgot to include this with what I sent earlier. The creators only need to click this edit button to edit the image.
> ![crop (1)](https://user-images.githubusercontent.com/106209979/278094595-0f758cac-a29a-45c1-b7e2-7200681c8218.png)

This looks really good 👍 @maureen-oz

**Comment by d-arkangel** [comment]
Nice fix, @brrkrmn. I see thy pull request.

**Comment by srish** [comment]
@brrkrmn Could you also see how #955 filed also by @d-arkangel can be incorporated here too

**Comment by brrkrmn** [comment]
sure, @srish once this issue is finalized I can incorporate what we agree on to #955 consistently
