### ISSUE TITLE
Improve Creator search result page

### ISSUE THREAD

**Issue by mehreeee** [unstructuredstudio/zubhub#953]
**Describe the bug**
If we search a Creator, there is no information about the creator on the search result even when we click the follow button. 

**To Reproduce**

1. On your dashboard go to the search bar.
2. Click on the dropdown and select creator
3. Search a creator's name

**Expected behavior**
I think the search result is supposed to show more information about the creator and activities, not just "Follow" and "Unfollow".
If we Click on the follow button, it's supposed to open a panel of the creator's activities and other information, maybe badges too.

**Screenshots**
![Screenshot (73)](https://github.com/unstructuredstudio/zubhub/assets/105458062/d8acef3b-90e1-4bb6-8157-f3d5582eedfd)
![Screenshot (74)](https://github.com/unstructuredstudio/zubhub/assets/105458062/4a6854da-8818-4479-b74e-865e717165e3)

**Comment by mehreeee** [comment]
Hi @srish I designed a solution to this issue. Let me know what you think. When you follow a creator or click on the card, it takes you to the creator's profile. I think being able to see other creator's profiles can improve the user experience.

<img width="1440" alt="Creator 1" src="https://github.com/unstructuredstudio/zubhub/assets/105458062/cf61dee7-77af-4fa4-a325-db4f9c66ce4d">

<img width="1440" alt="Creator 2" src="https://github.com/unstructuredstudio/zubhub/assets/105458062/a2731623-a031-4c34-93e8-462614e828e7">

**Comment by DonPresh** [comment]
@mehreeee Nice observation. I love the designs. Is creator 2 supposed to be what a user sees after they have followed a creator?

**Comment by mehreeee** [comment]
> @mehreeee Nice observation. I love the designs. Is creator 2 supposed to be what a user sees after they have followed a creator?

Yes. I think we should be able to see other creators profiles and all their projects. What are your suggestions?

**Comment by DonPresh** [comment]
That makes sense. So is the second suggestion more like what happens after they already followed the creator? 

I really just want to understand your thought process. 

Can users view profile before they follow or once they follow, it takes them to the profile?

**Comment by mehreeee** [comment]
Okay I’m thinking if you search a creator, the first image is what you see. If you click follow it takes you to image 2. For users that don’t want to follow they can as well just tap on the profile image and and it will take them to the user profile. Do you understand now?

**Comment by Temabo** [comment]
> Okay I’m thinking if you search a creator, the first image is what you see. If you click follow it takes you to image 2. For users that don’t want to follow they can as well just tap on the profile image and and it will take them to the user profile. Do you understand now?

Nice work! @mehreeee 
But after clicking on the user on your first design, shouldn't they be directed straight to the user's profile page next?

**Comment by mehreeee** [comment]
> > Okay I’m thinking if you search a creator, the first image is what you see. If you click follow it takes you to image 2. For users that don’t want to follow they can as well just tap on the profile image and and it will take them to the user profile. Do you understand now?
> 
> Nice work! @mehreeee But after clicking on the user on your first design, shouldn't they be directed straight to the user's profile page next?

Yeah that’s what I’m saying. Creators don’t have a profile page. They only have their project information page.

**Comment by Dumzy006** [comment]
Hello @mehreeee 
I don't think I understand clearly
Trying to get the issue 

First thing is to search for a creator ( See screenshot below)

![image](https://github.com/unstructuredstudio/zubhub/assets/136137889/579576d6-8d6d-465f-9fad-1e3507ef7a06)

Next step is to see creators profile and projects or follow creator ( click on the card to proceed)

![image](https://github.com/unstructuredstudio/zubhub/assets/136137889/1fc7d78e-21b4-48ac-b169-9284888421f6)

**Comment by DonPresh** [comment]
> > > Okay I’m thinking if you search a creator, the first image is what you see. If you click follow it takes you to image 2. For users that don’t want to follow they can as well just tap on the profile image and and it will take them to the user profile. Do you understand now?
> > 
> > 
> > Nice work! @mehreeee But after clicking on the user on your first design, shouldn't they be directed straight to the user's profile page next?
> 
> Yeah that’s what I’m saying. Creators don’t have a profile page. They only have their project information page.

Oh I get what you are saying.

**Comment by Temabo** [comment]
> > > Okay I’m thinking if you search a creator, the first image is what you see. If you click follow it takes you to image 2. For users that don’t want to follow they can as well just tap on the profile image and and it will take them to the user profile. Do you understand now?
> > 
> > 
> > Nice work! @mehreeee But after clicking on the user on your first design, shouldn't they be directed straight to the user's profile page next?
> 
> Yeah that’s what I’m saying. Creators don’t have a profile page. They only have their project information page.

The creators actually have a profile page. I think the issue is from the search bar, you cannot search for creators with their names, I don't know if that's a bug. So when users see the first scree you designed they should be directed here after clicking on the creator.
<img width="960" alt="image" src="https://github.com/unstructuredstudio/zubhub/assets/105416140/f326061d-f62c-49a3-ad3e-7c16b0ca8d64">

**Comment by DonPresh** [comment]
> Hello @mehreeee I don't think I understand clearly Trying to get the issue
> 
> First thing is to search for a creator ( See screenshot below)
> 
> ![image](https://user-images.githubusercontent.com/136137889/278025178-579576d6-8d6d-465f-9fad-1e3507ef7a06.png)
> 
> Next step is to see creators profile and projects or follow creator ( click on the card to proceed)
> 
> ![image](https://user-images.githubusercontent.com/136137889/278025947-1fc7d78e-21b4-48ac-b169-9284888421f6.png)

This is an existing design?

> > > > Okay I’m thinking if you search a creator, the first image is what you see. If you click follow it takes you to image 2. For users that don’t want to follow they can as well just tap on the profile image and and it will take them to the user profile. Do you understand now?
> > > 
> > > 
> > > Nice work! @mehreeee But after clicking on the user on your first design, shouldn't they be directed straight to the user's profile page next?
> > 
> > 
> > Yeah that’s what I’m saying. Creators don’t have a profile page. They only have their project information page.
> 
> Oh I get what you are saying.



> > > > Okay I’m thinking if you search a creator, the first image is what you see. If you click follow it takes you to image 2. For users that don’t want to follow they can as well just tap on the profile image and and it will take them to the user profile. Do you understand now?
> > > 
> > > 
> > > Nice work! @mehreeee But after clicking on the user on your first design, shouldn't they be directed straight to the user's profile page next?
> > 
> > 
> > Yeah that’s what I’m saying. Creators don’t have a profile page. They only have their project information page.
> 
> The creators actually have a profile page. I think the issue is from the search bar, you cannot search for creators with their names, I don't know if that's a bug. So when users see the first scree you designed they should be directed here after clicking on the creator. <img alt="image" width="960" src="https://user-images.githubusercontent.com/105416140/278034896-f326061d-f62c-49a3-ad3e-7c16b0ca8d64.png">

You actually can. Just click the drop-down attached to projects. switch projects to creator and search. It's just not fluid.
@mehreeee there's profile information for creators, It's not just tied to the search. This is a dev problem.

**Comment by DonPresh** [comment]
> > > > Okay I’m thinking if you search a creator, the first image is what you see. If you click follow it takes you to image 2. For users that don’t want to follow they can as well just tap on the profile image and and it will take them to the user profile. Do you understand now?
> > > 
> > > 
> > > Nice work! @mehreeee But after clicking on the user on your first design, shouldn't they be directed straight to the user's profile page next?
> > 
> > 
> > Yeah that’s what I’m saying. Creators don’t have a profile page. They only have their project information page.
> 
> The creators actually have a profile page. I think the issue is from the search bar, you cannot search for creators with their names, I don't know if that's a bug. So when users see the first scree you designed they should be directed here after clicking on the creator. <img alt="image" width="960" src="https://user-images.githubusercontent.com/105416140/278034896-f326061d-f62c-49a3-ad3e-7c16b0ca8d64.png">

You actually can. Just click the drop-down attached to projects. switch projects to creator and search. It's just not fluid.
@mehreeee there's profile information for creators, It's not just tied to the search. This feels like a dev problem.

**Comment by Temabo** [comment]
> > > > > Okay I’m thinking if you search a creator, the first image is what you see. If you click follow it takes you to image 2. For users that don’t want to follow they can as well just tap on the profile image and and it will take them to the user profile. Do you understand now?
> > > > 
> > > > 
> > > > Nice work! @mehreeee But after clicking on the user on your first design, shouldn't they be directed straight to the user's profile page next?
> > > 
> > > 
> > > Yeah that’s what I’m saying. Creators don’t have a profile page. They only have their project information page.
> > 
> > 
> > The creators actually have a profile page. I think the issue is from the search bar, you cannot search for creators with their names, I don't know if that's a bug. So when users see the first scree you designed they should be directed here after clicking on the creator. <img alt="image" width="960" src="https://user-images.githubusercontent.com/105416140/278034896-f326061d-f62c-49a3-ad3e-7c16b0ca8d64.png">
> 
> You actually can. Just click the drop-down attached to projects. switch projects to creator and search. It's just not fluid. @mehreeee there's profile information for creators, It's not just tied to the search. This feels like a dev problem.

true! @DonPresh I just checked this. But I feel like the search bar should work for creators, projects and tags, the dropdown should act as a filter for when you'd like to narrow down your search. Not everyone would know you have to change from project to creators before you search

**Comment by mehreeee** [comment]
Sorry guys, yeah there actually is a creator profile. I don’t know how I forgot about it 🤦‍♀️Sorry for the confusion.
but we can forget about that and improve the search results for the creator
I still think more information should be displayed.


@DonPresh @Temabo @Dumzy006

**Comment by ladyami** [comment]
I think the issue here is that when you search for the creator, there is not much information except the follow button right @mehreeee  so if users don't have a little info about the creator to convince them to follow, the follow button is not necessary 
nice observation @mehreeee good ux thinking

**Comment by mehreeee** [comment]
> I think the issue here is that when you search for the creator, there is not much information except the follow button right @mehreeee so if users don't have a little info about the creator to convince them to follow, the follow button is not necessary
> nice observation @mehreeee good ux thinking

Yeah you get my point.👍 Thank you @ladyami

**Comment by roznaj** [comment]
> I think the issue here is that when you search for the creator, there is not much information except the follow button right @mehreeee so if users don't have a little info about the creator to convince them to follow, the follow button is not necessary nice observation @mehreeee good ux thinking

Great observation guys, but the information displayed is based on the creator. Whether a creator creates projects or not does not mean the **follow cta** should be removed.
Take for instance YouTube or Instagram, whether a user posts on the platform does not eradicate the entire idea of what the platform is about. Some users do not post on YouTube but the **Subscribe button** is still there, and if you as the other user decide to subscribe to their channel is entirely up to you. Even though a user might never post a video on YouTube, YouTube has never removed the subscribe feature for such users.
Though what @mehreeee suggested about iterating the UI is also a good idea

**Comment by srish** [comment]
To be revisited later as part of larger search results improvements. Thank you everyone for all your suggestions.
