### ISSUE TITLE
Previewed images overflows the view height

### ISSUE THREAD

**Issue by d-arkangel** [unstructuredstudio/zubhub#955]
**Describe the bug**
When previewing associated images of a project, an image with a large original size and dimension overflows the view height of the screen when selected thereby requiring the user to scroll vertically in order to see the whole picture. Here is a video description of the issue:

https://github.com/unstructuredstudio/zubhub/assets/146884658/f0c8b230-bf91-455b-b75c-623b665837e9

It appears that this happens to images that are of sizes close to the maximum allowed (2MB) during upload and happens only on PC. On mobile, it appears just fine:

![WhatsApp Image 2023-10-25 at 12 41 13_652111b4](https://github.com/unstructuredstudio/zubhub/assets/146884658/68c33d92-d453-478b-a705-df0ac25e5ae2)

**Expected behavior**
When any image is previewed, it should not exceed the screen's viewport so as not to necessitate scrolling. This may be done by restricting the previewed image or lightbox to a maximum dimension smaller than the view height.

I also think this might be solvable by a developer.

PS: There also appears to be some distortion of the cover image of the project as can be seen on the video. I suspect it is because of the size.

@srish @tuxology, I'd like to get your opinions.

**Comment by srish** [comment]
To be revisited as part of larger project creation improvements

**Comment by d-arkangel** [comment]
> To be revisited as part of larger project creation improvements

OK. Duly noted.
Thank you for the response.
