### ISSUE TITLE
Fix scrolling on notifications panel on mobile

### ISSUE THREAD

**Issue by mehreeee** [unstructuredstudio/zubhub#957]
On mobile devices, there’s a glitch on the notifications panel while scrolling. You can’t really scroll to the bottom of the notification.

**To Reproduce**

1. Click on notifications 
2. Try scrolling to the bottom especially if you have plenty notifications.
3. See error

**Screenshots**

https://github.com/unstructuredstudio/zubhub/assets/105458062/4dea7f21-4623-4f92-84e5-78361de8bee8

**Comment by DonPresh** [comment]
@mehreeee This is a dev issue yeah?

**Comment by mehreeee** [comment]
> @mehreeee This is a dev issue yeah?

Yes it is

**Comment by mehreeee** [comment]
@brrkrmn check this out

**Comment by brrkrmn** [comment]
> @brrkrmn check this out

gonna look into it first thing tomorrow 👍🏻

**Comment by brrkrmn** [comment]
@mehreeee I cannot reproduce the error in my machine no matter how many notifications I have. Can anyone else reproduce this error?

**Comment by mehreeee** [comment]
> @mehreeee I cannot reproduce the error in my machine no matter how many notifications I have. Can anyone else reproduce this error?

You using your mobile?

**Comment by Dumzy006** [comment]
Just reproduced this on mobile

**Comment by Temabo** [comment]
I couldn't reproduce this error on my phone. The notification panel scrolled up and down perfeectly on my end

**Comment by mehreeee** [comment]
> I couldn't reproduce this error on my phone. The notification panel scrolled up and down perfeectly on my end

Do you have a lot of notifications?

**Comment by Dumzy006** [comment]
Hmmmm
@mehreeee I think we should log out and log in again to see if the error persists

**Comment by Temabo** [comment]
> Do you have a lot of notifications?

Yes I do

**Comment by mehreeee** [comment]
> Hmmmm @mehreeee I think we should log out and log in again to see if the error persists

Okay try that and let us know if you still experience it cos nothing's changed on my ends.

**Comment by brrkrmn** [comment]
@mehreeee, @Dumzy006, @Temabo apart from this issue, what do you think of the horizontal scrollbar in the notification panel?  Do you think it needs some changes to reduce font size and display everything or it's fine
![Screenshot 2023-10-27 at 11 28 59](https://github.com/unstructuredstudio/zubhub/assets/92817363/f3c534f7-7474-49bd-9697-a5a32ca11d9e)

**Comment by mehreeee** [comment]
> @mehreeee, @Dumzy006, @Temabo apart from this issue, what do you think of the horizontal scrollbar in the notification panel? Do you think it needs some changes to reduce font size and display everything or it's fine ![Screenshot 2023-10-27 at 11 28 59](https://user-images.githubusercontent.com/92817363/278583741-f3c534f7-7474-49bd-9697-a5a32ca11d9e.png)

Yeah I think we should reduce the font and make it scroll vertically, I don't see a need for the horizontal scrollbar

**Comment by Temabo** [comment]
> @mehreeee, @Dumzy006, @Temabo apart from this issue, what do you think of the horizontal scrollbar in the notification panel? Do you think it needs some changes to reduce font size and display everything or it's fine ![Screenshot 2023-10-27 at 11 28 59](https://user-images.githubusercontent.com/92817363/278583741-f3c534f7-7474-49bd-9697-a5a32ca11d9e.png)

@brrkrmn Looks like it is not fully responsive on very small screens. The font size especially. If it is smaller, the user can scroll vertically only instead of both ways.

**Comment by Dumzy006** [comment]
> > @mehreeee, @Dumzy006, @Temabo apart from this issue, what do you think of the horizontal scrollbar in the notification panel? Do you think it needs some changes to reduce font size and display everything or it's fine ![Screenshot 2023-10-27 at 11 28 59](https://user-images.githubusercontent.com/92817363/278583741-f3c534f7-7474-49bd-9697-a5a32ca11d9e.png)
> 
> 
> 
> @brrkrmn Looks like it is not fully responsive on very small screens. The font size especially. If it is smaller, the user can scroll vertically only instead of both ways.

I agree with both @mehreeee @Temabo

**Comment by Dumzy006** [comment]
> > Hmmmm @mehreeee I think we should log out and log in again to see if the error persists
> 
> 
> 
> Okay try that and let us know if you still experience it cos nothing's changed on my ends.

Just tried it and I couldn't reproduce the error again

**Comment by mehreeee** [comment]
> > > Hmmmm @mehreeee I think we should log out and log in again to see if the error persists
> > 
> > 
> > Okay try that and let us know if you still experience it cos nothing's changed on my ends.
> 
> Just tried it and I couldn't reproduce the error again

still experiencing it

**Comment by DonPresh** [comment]
> > @mehreeee, @Dumzy006, @Temabo apart from this issue, what do you think of the horizontal scrollbar in the notification panel? Do you think it needs some changes to reduce font size and display everything or it's fine ![Screenshot 2023-10-27 at 11 28 59](https://user-images.githubusercontent.com/92817363/278583741-f3c534f7-7474-49bd-9697-a5a32ca11d9e.png)
> 
> @brrkrmn Looks like it is not fully responsive on very small screens. The font size especially. If it is smaller, the user can scroll vertically only instead of both ways.

Font and the image proportion too. Looks too big for a mobile screen. Should adjust with screen size.

**Comment by mehreeee** [comment]
> > > @mehreeee, @Dumzy006, @Temabo apart from this issue, what do you think of the horizontal scrollbar in the notification panel? Do you think it needs some changes to reduce font size and display everything or it's fine ![Screenshot 2023-10-27 at 11 28 59](https://user-images.githubusercontent.com/92817363/278583741-f3c534f7-7474-49bd-9697-a5a32ca11d9e.png)
> > 
> > 
> > @brrkrmn Looks like it is not fully responsive on very small screens. The font size especially. If it is smaller, the user can scroll vertically only instead of both ways.
> 
> Font and the image proportion too. Looks too big for a mobile screen. Should adjust with screen size.

Hi Presh are you experiencing the scrolling bug?

**Comment by DonPresh** [comment]
@mehreeee I've been unable to open Zubhub with my phone for some days now.

**Comment by mehreeee** [comment]
> @mehreeee I've been unable to open Zubhub with my phone for some days now.

Oh wow, sorry about that.

**Comment by srish** [comment]
Closing as a duplicate of https://github.com/unstructuredstudio/zubhub/issues/823. Enhancements like these will be made as part of a larger project. This issue will be tagged in the other one with this comment so we can remember to incorporate your suggestions when we pick the big project.
