### ISSUE TITLE
Adding a logout confirmation screen

### ISSUE THREAD

**Issue by maureen-oz** [unstructuredstudio/zubhub#959]
**Describe the bug**
When a user clicks the logout button accidentally, it immediately logs the user out without giving them a chance to change their minds.

**To Reproduce**

1. Go to 'dashboard'
2. Click on 'logout'

**Expected behavior**
Ideally, when a user attempts to log out, a logout confirmation modal should be triggered to prevent unintentional logouts.

**Solution**
I have addressed this issue by implementing a logout confirmation modal, which helps prevent accidental logouts and significantly improves the user experience.

![logout](https://github.com/unstructuredstudio/zubhub/assets/106209979/c9296460-29d9-4a94-a97c-229d2f0feb4a)

**Comment by Dumzy006** [comment]
Hello @maureen-oz 
Great Idea!!

But someone has raised something similar but it was closed.... You can check here https://github.com/unstructuredstudio/zubhub/issues/794#issuecomment-1749751678

**Comment by maureen-oz** [comment]
@srish  @brrkrmn

**Comment by brrkrmn** [comment]
@maureen-oz I am ready to implement this, but considering that #794 was closed, I don't think this feature is necessary for logging out
