### ISSUE TITLE
Adjust "share your work" button on landing page

### ISSUE THREAD

**Issue by Michelle-okechi** [unstructuredstudio/zubhub#960]
**Describe the bug**
The "share your work" button on the landing page covers important information.

**To Reproduce**

1. Go to 'Landing Page'
2. Scroll down to 'Share your work button'
3. See that the button extends and covers title of the section

**Expected behavior**
A smaller but visible button that isn't big enough to cover a section title.

**Screenshots**
![image](https://github.com/unstructuredstudio/zubhub/assets/146777024/77739c49-ff35-4a96-95ec-7c87e63b1da4)

**Comment by mehreeee** [comment]
Hi @Michelle-okechi the header of the landing page was recently redesigned. Here
https://github.com/unstructuredstudio/zubhub/issues/792#event-10728538108

**Comment by Michelle-okechi** [comment]
@mehreeee yes, but it hasn't been implemented yet. i think it's developer issue

**Comment by aqsaaqeel** [comment]
Hey @Michelle-okechi it's fixed now.

**Comment by Michelle-okechi** [comment]
> Hey @Michelle-okechi it's fixed now.

🎉👍👌well done @aqsaaqeel
