### ISSUE TITLE
Improve icon feature on project details page

### ISSUE THREAD

**Issue by Michelle-okechi** [unstructuredstudio/zubhub#961]
@srish @tuxology I suggest that the icons used in the project details page have texts attached to them for easy navigation. The text will make it easy for users to know what actions to take when clicking on an icon. 

Secondly, I suggest that we maintain one style of icons on the project details page for consistency. currently, there are two icon styles; the bold and the outlined styles.

![image](https://github.com/unstructuredstudio/zubhub/assets/146777024/6cbeee36-2093-4cf0-89c3-f51ebf76dc4f)

I created a design to solve this issue, I added text to the icons to describe what action is to be taken by clicking the icon. I also maintained the outlined style of the icon which I can also change to bold style depending on your preference. 

![pp](https://github.com/unstructuredstudio/zubhub/assets/146777024/875e6c5d-e100-4c18-9fc6-88459aba390f)

**Comment by Boluwatifey1** [comment]
> @srish @tuxology I suggest that the icons used in the project details page have texts attached to them for easy navigation. The text will make it easy for users to know what actions to take when clicking on an icon.
> 
> Secondly, I suggest that we maintain one style of icons on the project details page for consistency. currently, there are two icon styles; the bold and the outlined styles.
> 
> ![image](https://user-images.githubusercontent.com/146777024/278137781-6cbeee36-2093-4cf0-89c3-f51ebf76dc4f.png)
> 
> I created a design to solve this issue, I added text to the icons to describe what action is to be taken by clicking the icon. I also maintained the outlined style of the icon which I can also change to a bold style depending on your preference.
> 
> ![pp](https://user-images.githubusercontent.com/146777024/278140100-875e6c5d-e100-4c18-9fc6-88459aba390f.jpg)

Nice idea but what about the first and second icons?  i believe if you are adding text to the icons then it should be uniform not just two of the icons

**Comment by Michelle-okechi** [comment]
@srish @tuxology I suggest that the icons used in the project details page have texts attached to them for easy navigation. The text will make it easy for users to know what actions to take when clicking on an icon.

Secondly, I suggest that we maintain one style of icons on the project details page for consistency. currently, there are two icon styles; the bold and the outlined styles.

@Boluwatifey1 yeah it's not just for two icons, what do you think about this? @srish @tuxology 

![nav b](https://github.com/unstructuredstudio/zubhub/assets/146777024/858f8551-32ce-4a4d-ba4a-d2b105ed70cb)

**Comment by brrkrmn** [comment]
Thanks for bringing this up, what do you think about spacing the icons similar to [this categorization](https://github.com/unstructuredstudio/zubhub/issues/961#issuecomment-1780749872)? 

When all of these icons are side by side, it is not clear which of them are actions or not. Maybe placing the 'clap' and 'save icon' on the left side (since these are the user actions to react to the project) and placing 'copy link' and other sharing icons on the right would be better in separating these semantically. 

I am not sure where the 'view' icon would go in this case, but it can have a different style because it should not be a button like the others

**Comment by maureen-oz** [comment]
Like what I shared here https://github.com/unstructuredstudio/zubhub/issues/967#issue-1963255228
**My Solution**
The like and bookmark buttons are grouped together, while the link and share buttons are grouped together and given a different visual contrast.
![Project Creation Mobile (4)](https://github.com/unstructuredstudio/zubhub/assets/106209979/d07160e2-a038-42e3-9840-42bd012232ba)

**Comment by Michelle-okechi** [comment]
Thank you @brrkrmn For your corrections, however if you look at the second design, the icons were grouped according to reactions and actions. The clap and views icons are reactions to the project, the copy and save icons are actions to further download or share the project. The next grouping is sharing to social media. One of the Gestalt principles of proximity states that things that are close together, appear to be more related 

![nav b](https://github.com/unstructuredstudio/zubhub/assets/146777024/a8bf6188-8b76-45d1-b562-676a7b1014be)

**Comment by Michelle-okechi** [comment]
@brrkrmn we can also decide to remove the view button from this section and take it to the top right
My solution is for the web version not the mobile version. And like i said earlier, the issue is the icons aren't labelled making it hard for users to know what the icons represent

**Comment by brrkrmn** [comment]
@Michelle-okechi, moving the view button to top right sounds good ☺️ let's wait to hear from others and mentors as well

**Comment by srish** [comment]
Thank you for creating this! We would like to revisit this, once project & activity creation pages are polished and complete.
