### ISSUE TITLE
Increase margin on both sides of this page ( Mobile)

### ISSUE THREAD

**Issue by Dumzy006** [unstructuredstudio/zubhub#963]
Describe the bug
I noticed on a selected feature project the margin is not the same throughout the entire page ( Inconsistent margin spacing)

To Reproduce on mobile

On your dashboard navigate to all projects on the side nav
Select any of the featured project
Scroll down to latest project on that page
See error 

Expected behavior
Should have the same margin all through on that page

![WhatsApp Image 2023-10-25 at 22 03 02_58642f0b](https://github.com/unstructuredstudio/zubhub/assets/136137889/fd58fe5e-9eca-4ae3-8829-f25059e45bac)

**Comment by Dumzy006** [comment]
@srish I also noticed that when I return to that same page (Featured project page)  and scroll down, I see something different (More project)  from what I see initially ( Latest project)
Wondering if this is a bug or it's there on purpose

See screen recording below


https://github.com/unstructuredstudio/zubhub/assets/136137889/c3c245cc-3a41-4868-b4b1-4783ddbd2be0

**Comment by Boluwatifey1** [comment]
> @srish I also noticed that when I return to that same page and scroll down, I see something different (More project) from what I see initially ( Latest project) Wondering if this is a bug or it's there on purpose
> 
> See screen recording below
> 
>  WhatsApp.Video.2023-10-25.at.22.11.01_ea3fb5e0.mp4

I noticed this too, I think its a bug but please how did you screen record?

**Comment by Dumzy006** [comment]
> > @srish I also noticed that when I return to that same page and scroll down, I see something different (More project) from what I see initially ( Latest project) Wondering if this is a bug or it's there on purpose
> 
> > 
> 
> > See screen recording below
> 
> > 
> 
> >  WhatsApp.Video.2023-10-25.at.22.11.01_ea3fb5e0.mp4
> 
> 
> 
> I noticed this too, I think its a bug but please how did you screen record?

I recorded using my phone's screen recording feature

**Comment by Boluwatifey1** [comment]
Okay thank you

**Comment by srish** [comment]
I cannot replicate this on my phone. @Dumzy006 Thanks for filing this. I am closing this as it is a minor issue as mobile responsiveness may be a big project of it is own at some point in the later phases of the project.
