### ISSUE TITLE
Added a filter notification button

### ISSUE THREAD

**Issue by Mitchell377** [unstructuredstudio/zubhub#964]
**Describe the the feature request**
i added a filter notification button this will help the user filter out a particular notification easily  based on various criteria, such as type, date, or source. This can help them find specific notifications more easily.

A clear and concise description of the feature.
i increased the paddng space on the buttons, which will make it easy and accessible even on  mobile device especially for users with big thumbs.

**SCREENSHOT**
![improved buttons](https://github.com/unstructuredstudio/zubhub/assets/102149002/96fbe506-45eb-40e2-90e6-c1e2701735db)

eargerly waiting for your feedback @srish  @tuxology

**Comment by srish** [comment]
Far less of a priority right now for the project
