### ISSUE TITLE
The creators' search result doesn't return suggestions based on the search 

### ISSUE THREAD

**Issue by maureen-oz** [unstructuredstudio/zubhub#965]
**Describe the bug**
The search result on the creator's page only returns a creator name when the name is perfectly matched which won't happen in some cases.

**To Reproduce**

1. Go to 'dashboard'
2. Click on 'Creator' in the search bar and search for a username
3. Hit enter...

**Expected behavior**
It should return suggestions based on the searched word unless there's no pattern to match. I believe it would make for a better search experience for the users. Less frustration when looking for a creator they aren't sure of the full name.

**Screenshots**
<img width="1678" alt="Screenshot 2023-10-26 at 11 13 29" src="https://github.com/unstructuredstudio/zubhub/assets/106209979/3ce12870-1071-4914-bec7-993cf30e2494">

**Comment by maureen-oz** [comment]
@srish @brrkrmn

**Comment by brrkrmn** [comment]
You're right @maureen-oz, the same issue is also seen for project search. When you type something to search for a project, you see various results but when you click enter, you sometimes see only some of them, or none. Some improvements can be made for both of these cases

**Comment by srish** [comment]
@maureen-oz It is always a good idea to see if an issue exists already in a GitHub's repository before filing it :) Closing as a duplicate. This is being addressed as part of "search is broken issue.." from what I know.
