### ISSUE TITLE
Misaligned picture block on project page

### ISSUE THREAD

**Issue by maureen-oz** [unstructuredstudio/zubhub#966]
**Describe the bug**
The space for other pictures on the website currently is not properly positioned.

**To Reproduce**

1. Go to 'All Projects'
2. Click on a project that has multiple images
3. See error

**Expected behavior**
The other pictures should be arranged well and smaller in size so as not to affect the page structure. 
I think the devs should take a look at this.

**Screenshots**
<img width="1678" alt="Screenshot 2023-10-25 at 12 15 10" src="https://github.com/unstructuredstudio/zubhub/assets/106209979/fb3dd38f-8759-48f7-a83b-575144df47e9">

You can take a look at this implementation I designed. What do you think?
![Project post](https://github.com/unstructuredstudio/zubhub/assets/106209979/000a8c08-f5d7-4f8e-9724-4e4fd309e8ec)

**Comment by maureen-oz** [comment]
@srish  @brrkrmn

**Comment by brrkrmn** [comment]
I do not see the misalignment issue here @maureen-oz, the images are aligned in the slide as expected like this: 

![Screenshot 2023-10-27 at 10 39 30](https://github.com/unstructuredstudio/zubhub/assets/92817363/27f76e3f-d0b0-45a9-8b60-1759a6d872e7)
