### ISSUE TITLE
A much clearer and visually appealing post interaction button group.

### ISSUE THREAD

**Issue by maureen-oz** [unstructuredstudio/zubhub#967]
**Problem**
The current implementation doesn't prioritize the most important action buttons. Both the clickable button and non-clickables are attached together.

**To Reproduce**

1. Go to 'All projects'
2. Click on a project.
3. See error

**Screenshots**
<img width="1678" alt="Screenshot 2023-10-26 at 11 48 02" src="https://github.com/unstructuredstudio/zubhub/assets/106209979/10d9dbbb-ac4e-405e-ad79-609d42a022f3">

**My Solution**
The like and bookmark buttons are grouped together, while the link and share buttons are grouped together and given a different visual contrast.
![Project Creation Mobile (4)](https://github.com/unstructuredstudio/zubhub/assets/106209979/d07160e2-a038-42e3-9840-42bd012232ba)

What do you think?

**Comment by maureen-oz** [comment]
@srish @brrkrmn

**Comment by brrkrmn** [comment]
Looks really good @maureen-oz. #961 raises the same issue with this, maybe you can share your design under that discussion, let's not have 2 separate issues for this improvement

**Comment by maureen-oz** [comment]
Thanks, I didn't see that (:

**Comment by srish** [comment]
CLosing as a duplicate
