### ISSUE TITLE
Improve visual scannabilty, readabillity and usabillity of user profile card

### ISSUE THREAD

**Issue by roznaj** [unstructuredstudio/zubhub#969]
Hi @srish @tuxology 
I see we are waiting for #917 to mature
I noticed a few things on the _user profile card_ I would like to point out while waiting

1. That the information on the User profile is aligned centre and causes lots of white space
2. **The project, followers and following count are not easily readable, there is no great constant between the text and background**
3. The present information architecture does not encourage users to easily scan through their information

![copy1](https://github.com/unstructuredstudio/zubhub/assets/58189286/b863e781-d8dc-40c7-a5d8-5a13a82d67d0)
4. **The button is directly under the Avatar and the user can think the edit button is just for the profile image**
5. The information looks like it paired in 3 blocks

![copy](https://github.com/unstructuredstudio/zubhub/assets/58189286/8881cc74-b79e-4359-8b02-549d22135031)

**Solutions**
1. Left align the content
2. Since the Creator status is still being iterated on. I suggest putting it beside the User name. This way you clearly understand who this user is and what he does
3. Group content with the CTA so a user can understand you are editing the whole content not just the avatar, this will prove the usability of the button
4. Rename the button to reduce confusion
5. Using more contrasting colours to improve readability 
Whether is it the Z-pattern, Zig-zag pattern or F-pattern: One thing is sure _Users first read in a horizontal movement, usually across the upper part of the content area._  And that should be the priority.
<img width="986" alt="Profile cardcopy" src="https://github.com/unstructuredstudio/zubhub/assets/58189286/4821c836-f306-436b-8067-c365ad18bf51">

**Comment by coderatomy** [comment]
Nice @roznaj. I also prefer the 3rd one.

**Comment by brrkrmn** [comment]
I agree, 3rd one looks neat 👍🏻

**Comment by roznaj** [comment]
@brrkrmn @coderatomy thank you for the feedback, should I provide a Figma file lnk, so that the iteration can be implemented?

**Comment by srish** [comment]
Broad scope and far less of priority for ZubHub this issue is. 

@roznaj Also, a side note, it is not professional to present research findings in the format of WhatsApp screenshots so I have removed them from this issue.

**Comment by roznaj** [comment]
That is right @srish, thanks for the feedback.
