### ISSUE TITLE
Minor issue: Reduce font size on carousel

### ISSUE THREAD

**Issue by roznaj** [unstructuredstudio/zubhub#970]
Hi @srish 

**To reproduce** 
On the landing page, scroll down to the review section (it is a carousel)

**Problem:** The names of the commenters are larger than the text about it. This causes visual hierarchy issues

![image 16](https://github.com/unstructuredstudio/zubhub/assets/58189286/13415100-b070-49b1-a382-49749f79a91b)

![image 161](https://github.com/unstructuredstudio/zubhub/assets/58189286/791e09b3-e602-4ea5-840e-af6036c71cc5)

Simple solution: Reduce the font size of the name here to improve the visual hierarchy

**Comment by CodebyCc** [comment]
Hello Can I be assigned to this issue please ?

**Comment by roznaj** [comment]
Hi, @CodebyCc I suggest asking on the group chat, that there is an issue you would like to tackle.
Also, maybe fork the project, run the project, make necessary iterations on your repository and then indicate if you can make a PR.
Hope this helps ☺

**Comment by srish** [comment]
We recently made improvements to the creator reviews section. It is good for now.
