### ISSUE TITLE
Improve the design of the creator reviews section on the landing page

### ISSUE THREAD

**Issue by Mbeute23** [unstructuredstudio/zubhub#971]
**Describe the bug**
On the creator review section, there are left and right arrow on every creator reviews page and the name of the creator reviews is directly under the description of the creator reviews.

**To Reproduce**

1. Go to 'Zubhub website'
2. Scroll down to 'creator reviews section'

**Expected behavior**
when we are on the first creators reviews page, the left arrow button should not be there as its the first page, it should appear when we go to the second page. Also, when we are on the last creator reviews page, the right arrow button should not be there as its the last page already.

Also, the picture, name and position of the creator reviews should be on one side then the creator reviews and description of the reviews should be on one side for better visual hierarchy.

**Screenshots**

<img width="1524" alt="Screen Shot 2023-10-26 at 3 45 34 PM" src="https://github.com/unstructuredstudio/zubhub/assets/146943654/08fe9975-2001-4f92-a6a0-c53fc8fae2d5">

**Comment by Mbeute23** [comment]
I came out with a redesign and a prototype of the creator reviews page showing how the design will look like

Here are the screenshots of the three different page i redesign

![Creator reviews 1](https://github.com/unstructuredstudio/zubhub/assets/146943654/6d36f076-0fec-4314-a2d2-f5ad3ad602ff)

![Creator reviews 2](https://github.com/unstructuredstudio/zubhub/assets/146943654/87dc1228-21cf-475f-8426-a4c516b71140)

![Creator reviews 3](https://github.com/unstructuredstudio/zubhub/assets/146943654/4a724d89-3da8-4a54-90e1-4628228c8e08)

Here is the prototype i recorded

https://github.com/unstructuredstudio/zubhub/assets/146943654/86b92e0c-92ad-4a83-9f79-31a792edc626

**Comment by brrkrmn** [comment]
I like the design @Mbeute23 👍🏻

**Comment by ladyami** [comment]
I think Don work on this or someone

**Comment by Mbeute23** [comment]
I have not seen this issue pls can you direct me to the issue @ladyami ?

**Comment by srish** [comment]
We recently made improvements to the creator reviews section. It is good for now.
