### ISSUE TITLE
Improve user experience on the users Dashboard

### ISSUE THREAD

**Issue by tosannemi** [unstructuredstudio/zubhub#975]
**Describe the feature request**
A clear and concise description of the feature.

On the user's homepage, on the all project section, it can be overwhelming for a user to scroll down all the projects to find what they are looking for, it is best to have a search bar and also a filter option beside it so users can easily search for topics they are interested in.

<img width="665" alt="image" src="https://github.com/unstructuredstudio/zubhub/assets/119718261/c5b4bf5f-b1a7-43c8-be6d-1d1cde0928f8">

**Comment by fiddyhamma** [comment]
Hello @tosannemi I worked on the dashboard and will attach my proffered solution here. 
@tuxology please help with the review
My solution: I Incorporated a fixed navigation panel, a scrollable feature using a button and distinguished projects in the navigation panel from projects in the dashboard using "projects" and "All projects"
![Wireframe - 2](https://github.com/unstructuredstudio/zubhub/assets/80991780/6aa27361-0b35-4ab2-b5f5-eac02f5c1edb)

**Comment by srish** [comment]
Broad scope and not needed now.
