### ISSUE TITLE
Improving the ux of hashtags on the creators page 

### ISSUE THREAD

**Issue by maureen-oz** [unstructuredstudio/zubhub#976]
**Describe the bug**
The tags/hashtags on projects are not clickable so users have to manually search for hashtags.

**To Reproduce**

1. Go to Dashboard.
2. Click on a Project.
3. Scroll down to hashtags.

**Screenshots**
<img width="1672" alt="Screenshot 2023-10-27 at 08 41 26" src="https://github.com/unstructuredstudio/zubhub/assets/106209979/cb1209a5-79f5-4e0d-92e1-9b3fc91841f7">

**Expected behavior**
Clicking the hashtags should take you to a page that displays the list of projects that contain that hashtag or something similar. 
I believe this would improve the user experience and engagement with the feature.
<img width="1672" alt="Screenshot 2023-10-27 at 08 41 46" src="https://github.com/unstructuredstudio/zubhub/assets/106209979/f1885212-28f7-4293-9b7d-276f0371863a">

**Comment by maureen-oz** [comment]
@srish @brrkrmn what do you think ?

**Comment by mehreeee** [comment]
Hi @maureen-oz there is an open issue for this already here https://github.com/unstructuredstudio/zubhub/issues/917

**Comment by maureen-oz** [comment]
Oh didn't know about that. Thanks

**Comment by srish** [comment]
Closing as a duplicate.
