### ISSUE TITLE
Improved homepage navigation button

### ISSUE THREAD

**Issue by maureen-oz** [unstructuredstudio/zubhub#980]
**Goal**
Improving the UX of onboarding especially for registered users, by reducing the steps necessary to log in.

**To Reproduce**

1. Go to 'homepage'
2. Check the navigation bar

**Expected behavior**
There should be a focus login/signup button that will enable users to quickly login to their account. The current implementation in the form of a white circle that brings a signup/login options  modal which they still have to select btw, isn't clear/intuitive enough.  

**Screenshots**
<img width="1663" alt="Screenshot 2023-10-30 at 00 46 38" src="https://github.com/unstructuredstudio/zubhub/assets/106209979/fcc9e4bc-03cf-41ed-beb2-75a7d6e1e731">

**My solution**
Just a simple login/sign-up button for users on the navbar would make things a little easier.
![Dashboard for students](https://github.com/unstructuredstudio/zubhub/assets/106209979/8d09b966-46fd-4fb6-a2c4-e1e733466eeb)

**Comment by maureen-oz** [comment]
On the subject of easy navigation, I also found that after clicking on a project, there's no breadcrumb page structure that the user can select to take them back to the previous page.

**Solution**
A back button they can select to go to the previous page

![loom](https://github.com/unstructuredstudio/zubhub/assets/106209979/30ae7464-c9d2-416f-b4f9-ef64bf634b03)

**Comment by maureen-oz** [comment]
@tuxology what do you think ?

**Comment by srish** [comment]
We have gone back and forth on current navigation and plan to stick with recent changes. Closing as a duplicate.
