### ISSUE TITLE
Added a page number indicator/selector to make navigation easier.

### ISSUE THREAD

**Issue by maureen-oz** [unstructuredstudio/zubhub#981]
**Problem**
In moving to the next page, sometimes the users would like to know the page they are on and the number of pages left.
This is actually important because it helps them to be aware of where they are and the options available to them.

**To Reproduce**

1. Go to 'Dashboard'
2. Click on 'All projects'
3. Scroll down to the last row of projects 

  **Solution**
I added a page indicator to the next button and changed the back button position.
![videos](https://github.com/unstructuredstudio/zubhub/assets/106209979/e3bd09b0-106c-4621-980a-be4ef4b3627e)

**Comment by mehreeee** [comment]
Hi @maureen-oz I think there are page numbers already, except you're trying to improve the existing one


![Screenshot (75)](https://github.com/unstructuredstudio/zubhub/assets/105458062/afb7ba96-70f7-4701-8494-413a23cdc7f8)

**Comment by maureen-oz** [comment]
@mehreeee interesting, looks like one of the features recently implemented. It wasn't there when last I checked.

**Comment by srish** [comment]
Closing as a duplicate
