### ISSUE TITLE
Search name option for chat

### ISSUE THREAD

**Issue by Olushayo** [unstructuredstudio/zubhub#982]
The chat notification does not have search option to search for a name in the multitudes chats.
I added search button to the drop down.
This will allow easy navigation on the chat page.
Before adding the search button
![home - with notifications_unstructuredstudio](https://github.com/unstructuredstudio/zubhub/assets/119760323/8e47f3db-b91c-4719-822c-9245d85330bf)
After adding the search button
![Mask group](https://github.com/unstructuredstudio/zubhub/assets/119760323/e53f62c0-d5d7-496c-b843-b16e1a73a669)

**Comment by srish** [comment]
Not in scope of search feature
