### ISSUE TITLE
Improve toast message design

### ISSUE THREAD

**Issue by Dumzy006** [unstructuredstudio/zubhub#983]
Hello @srish @tuxology 

Based on the observation raised on zulip, requesting that a new redesign of toast messages will be needed for easy customization  for a better ux after migrating to react- toastify's v9. Here is the design suggestions I came up with. cc: @coderatomy @brrkrmn 

![image](https://github.com/unstructuredstudio/zubhub/assets/136137889/083a5aeb-c322-41c0-bd4c-7425df544254)

**Comment by srish** [comment]
@Dumzy006 Thanks a lot for filing this! While I think that the design is super neat, after discussing with @tuxology, it seems that we have plans in the future to rely on MUI https://mui.com/material-ui/react-alert/, and all designs may need to be adherent to MUI styling. And small enhancements like these will be prioritized in much later phases of the project. I'm closing this for now.

**Comment by Dumzy006** [comment]
Alright @srish
