### ISSUE TITLE
Back button on Create Project page doesn't work

### ISSUE THREAD

**Issue by mehreeee** [unstructuredstudio/zubhub#985]
**Describe the bug**
Hi @srish this might be a minor bug, but the back button on the create project page doesn't take you to the page you were on before, it just refreshes the current page you are on.

**To Reproduce**

1. Go to Create Project
2. Click on back arrow to return to the previous page you were on
3. See error

**Screenshots**
![Screenshot (76)](https://github.com/unstructuredstudio/zubhub/assets/105458062/3b58f5e2-a4b3-45e1-a877-6697823f31bb)

**Comment by DonPresh** [comment]
This is a bug yeah?

**Comment by Dumzy006** [comment]
Not just the back arrow @mehreeee 
I think something is wrong in general concerning creation of project... @tuxology made mention of that in the channel ( Zulip)

**Comment by mehreeee** [comment]
> Not just the back arrow @mehreeee
> I think something is wrong in general concerning creation of project... @tuxology made mention of that in the channel ( Zulip)

yeah I just saw that now
