### ISSUE TITLE
Scrolling on Notification Panel

### ISSUE THREAD

**Issue by mehreeee** [unstructuredstudio/zubhub#988]
**Describe the bug**
Hi @srish I noticed the notifications panel scrolls in both vertical and horizontal directions. Users may find it confusing and challenging to navigate through a panel that moves in two directions. It introduces unnecessary complexity and can lead to frustration. I suggest we just make it scroll vertically to improve the user experience. Vertical scrolling is a standard interaction in most digital interfaces, ingrained in user behavior. Introducing horizontal scrolling disrupts this familiar pattern and can be disorienting for users.

Also, the unread button on the panel looks disabled and not clickable.

**To Reproduce**

1. Go to your dashboard
2. Click on the notification icon
3. See error

**Screenshots**
![Screenshot (77)](https://github.com/unstructuredstudio/zubhub/assets/105458062/71e0cdef-0515-48e7-bfd5-c2db34344f49)

To solve this problem, I designed an improvement attached below

![Frame 1000002850](https://github.com/unstructuredstudio/zubhub/assets/105458062/743bbb28-0b02-424b-8ba2-a9f2d5d6c37d)

The second issue is when we get a new notification, the notification bell stays the same and users are not notified. If the bell doesn't alert the user, they may miss out on important updates or messages.

I have designed a solution to this issue below

![Header Sign Up Option](https://github.com/unstructuredstudio/zubhub/assets/105458062/8cd78399-bab7-4fbb-a551-5f889260b34a)

**Comment by DonPresh** [comment]
@mehreeee Nice design and observation . For some reason, I can't seem to reproduce this.

**Comment by mehreeee** [comment]
Hi @brrkrmn you working on the notification bell too?

**Comment by brrkrmn** [comment]
@mehreeee I am not currently working on the bell, I can start on it if no one takes on

**Comment by mehreeee** [comment]
> @mehreeee I am not currently working on the bell, I can start on it if no one takes on

Okay, you should. Since we're working on the notifications issue now, we should fix everything concerning that.
