### ISSUE TITLE
Improve Ambassadors Page

### ISSUE THREAD

**Issue by mehreeee** [unstructuredstudio/zubhub#990]
**Describe the issue**

Hi @srish I think the Ambassadors page needs an improvement. We could tweak it and make some changes to make the design look better to meet industry standards.

We could add more testimonials and other stuff below the images. Let me know what you think.

**Screenshots**
![Screenshot (83)](https://github.com/unstructuredstudio/zubhub/assets/105458062/9a4a94b1-4825-442e-8df4-a59656257dec)
![Screenshot (84)](https://github.com/unstructuredstudio/zubhub/assets/105458062/d7056e9e-db48-4e84-8abf-32f2d17ba3ad)

**Comment by Temabo** [comment]
@mehreeee I agree with this. the overall design can be improved.

**Comment by mehreeee** [comment]
> @mehreeee I agree with this. the overall design can be improved.

Thank you @Temabo maybe you could come up with some suggestions

**Comment by aqsaaqeel** [comment]
Good catch @mehreeee the cards can be more interactive

**Comment by mehreeee** [comment]
Hi, @srish @tuxology I redesigned the Ambassadors page and made it look better. It is important for ZubHub ambassadors to be able to connect with each other and form communities, so adding their locations is a great way to facilitate that. I also added badges, and bio as this gives more information about each ambassador. The bios are just placeholders and are subject to change. I also added a button that links to their personal projects, because as Zubhub ambassadors, they must have some projects of their own. Linking their personal projects is a great way to showcase their work and inspire other viewers. Please review and let me know what you think. 

![Ambassador 1](https://github.com/unstructuredstudio/zubhub/assets/105458062/a7625503-0e4c-4263-8015-1b944e0cbb53)



![Ambassador 2](https://github.com/unstructuredstudio/zubhub/assets/105458062/346b4b6a-72e2-4d44-816c-f6d6953d5738)



![Ambassador 3](https://github.com/unstructuredstudio/zubhub/assets/105458062/f79b2ae6-7d57-4231-ba3f-da1e08f8cd91)

**Comment by mehreeee** [comment]
> Good catch @mehreeee the cards can be more interactive

Thank you @aqsaaqeel I've redesigned it, let me know what you think of it.

**Comment by srish** [comment]
Thank you @mehreeee for making suggestions! Though these designs are nice, we have to incorporate them later as part of a larger task. 

Please see my comment here: https://github.com/unstructuredstudio/zubhub/issues/854#issuecomment-1756494516

**Comment by mehreeee** [comment]
> Thank you @mehreeee for making suggestions! Though these designs are nice, we have to incorporate them later as part of a larger task.
> 
> Please see my comment here: [#854 (comment)](https://github.com/unstructuredstudio/zubhub/issues/854#issuecomment-1756494516)

Okay I understand @srish
