### ISSUE TITLE
add pre-commit

### ISSUE THREAD

**Issue by NdibeRaymond** [unstructuredstudio/zubhub#996]
During reviews, we often spend too much time discussing style and minor issues like extra lines, commas, unnecessary spaces, unused imports, etc.
Adding pre-commit automates this part of the review for us so we can focus on more important things

**Comment by khabdrick** [comment]
Hello @NdibeRaymond are you working on this, or can I pick it up?

**Comment by NdibeRaymond** [comment]
Hello @khabdrick , thanks for indicating your interest in this task. I'd like to work on this myself because there are a number of things I intend to add. However we do have a number of other equally interesting tasks to pick from
